### ISSUE TITLE
No animation using AE CC 2015 + OSX

### ISSUE THREAD

**Issue by louiesolomon** [bodymovin/bodymovin#1]
I've created a simple movement animation using After Effects CC 2015 on Mac Yosemite (10.10.3), and I am unable to get any animation to play.  I can see the first screen of the animation, but it never animates.  

I've also tried plugging in the exported data.js file directly into working examples without any luck.

**Comment by bodymovin** [comment]
This issue is fixed. It was a problem with non rounded framerates when prerendering animations. Thanks louie for your help to find it.
