### ISSUE TITLE
player controls

### ISSUE THREAD

**Issue by berendvaneerde** [bodymovin/bodymovin#10]
First of all: You're a hero. I think this is a great tool for animatiors/webdesigners that is very promising. 

I am struggling with getting the player to work for me. I like using the data-attributes for specifying the animationdata etc. But I would still like to control the playing of the animation in javascript/jquery

For instance. I would like to play the animation once when the element is hovered. How would you go about doing that. I cannot seem to get the bodymovin.play('[data name value]') to work. on for example:

```javascript
<div id="logo_reveal" class="bodymovin" data-animation-path="/library/animations/botoboto_reveal/" data-anim-type="svg" data-anim-loop="false" data-name="logoreveal"></div>

$('body').on('hover', '#logo_reveal', function(){
 bodymovin.play('logoreveal');
});
```

Am I forgetting something?

**Comment by bodymovin** [comment]
@berendvaneerde Hi. I think the loadAnimation method might work for you.
you pass an object with the necessary params (look on the readme file for all the possible configurations). You can set the autoplay and loop flags to false on your case.
It returns an animation instance you can control and call the play, stop, pause, gotoAndStop and other methods on it.
I will update the documentation to reflect this.

**Comment by berendvaneerde** [comment]
Thank you for your quick response.
I tried the loadAnimation method before, but no succes. I am not sure how to load the json file in animationData param: do I just route to it?
 like: {animationData: JSON.parse('../animatoins/logo_reveal/data.json')}

**Comment by bodymovin** [comment]
@berendvaneerde Instead of using animationData, use path and pass the json path.
something like:
bodymovin.loadAnimation({
  wrapper: element, // the dom element
  animType: 'svg',
  loop: true,
  autoplay: true,
  path: '../animatoins/logo_reveal/data.json'
});

It's not on the documentation either :/
I'll update it.

**Comment by berendvaneerde** [comment]
Thanks for your help. Getting further

Still no luck though: I get the following error

Uncaught TypeError: this.animationItem.wrapper.appendChild is not a function
SVGRenderer.configAnimation @ bodymovin.js?ver=4.2.5:2
AnimationItem.configAnimation @ bodymovin.js?ver=4.2.5:4
AnimationItem.setParams.r.onreadystatechange @ bodymovin.js?ver=4.2.5:4

**Comment by bodymovin** [comment]
@berendvaneerde what did you pass as wrapper? you need to pass a dom element.

**Comment by berendvaneerde** [comment]
as following
 
var logoReveal = $('#logoreveal'); //corresponding to a dom element in my html
    
    bodymovin.loadAnimation({
      wrapper: logoReveal, // the dom element
      animType: 'svg',
      loop: false,
      autoplay: true,
      path: 'wp-content/themes/botoboto/library/animations/anim/data.json'
    });

**Comment by berendvaneerde** [comment]
GOT IT! appears that my jquery doesn't work... Does it need to be pure javascript?

**Comment by bodymovin** [comment]
@berendvaneerde  nice!
yes, for the moment it only supports pure javascript.

**Comment by berendvaneerde** [comment]
aha! So how about calling bodymovin.play('name') inside a jquery function? 
Is that the reason why that is not working?

**Comment by bodymovin** [comment]
@berendvaneerde no, I think that might be another issue. If you have a working example, I'll take a look.

**Comment by berendvaneerde** [comment]
I'm on the right track now! Thanks to your hint on the goToandStop method. Logical to reset the animation to a starting point, before you can play it again, but I never saw that method before your post ;) I've got a mouseover working now. Is there also a method to give the animation another frame at load or so?  

Perhaps I just need to dive into the code more, but your plugin definitely deserves some more documentation on these methods as well! All in time of course :) Thanks very much for your help. I feel like I can go to bed now with this little victory!

**Comment by bodymovin** [comment]
@berendvaneerde what do you mean by giving another frame at load? to display another frame by default on load?
I'm glad it works :)

**Comment by berendvaneerde** [comment]
yes! That's what I mean

**Comment by bodymovin** [comment]
@berendvaneerde no it doesn't but it makes sense. I'll add it to my todo list

**Comment by berendvaneerde** [comment]
Great! Thanks again...
