### ISSUE TITLE
Windows 8.1 IE 11 Off By One Issue Causing Animation Errors

### ISSUE THREAD

**Issue by gmjoseph** [bodymovin/bodymovin#100]
In the function getDistancePerc(perc,bezierData), (line 148 player/js/utils/bez.js) there is an attempt to access an object in an array of segments that returns an undefined object. Accessing the object causes no problems. However there is then an attempt to read a property off of the undefined object in two instances: segments[initPos+1].l on line 160, and segments[initPos+1].p on 170. This seems to fail silently or never happen in all modern major browsers. In IE 11 however, it causes an error which results in the animation not playing.

**Comment by bodymovin** [comment]
Hi, I'll check it out.
Do you have an exported json where this is happening?
