### ISSUE TITLE
Implement a `.playFrom(num)` method

### ISSUE THREAD

**Issue by ZachSaucier** [bodymovin/bodymovin#103]
I'd like to have a `.playFrom` or `.goToAndPlay` method for bodymovin.

Right now this can be done using  `.goToAndStop(num, true)` and `.play()`, but it'd be handy to have it in one method, even if it's just a shortcut telling bodymovin to do just what it does now.

**Comment by bodymovin** [comment]
Sure, goToAndPlay will be available on the next release
