### ISSUE TITLE
Create an event to fire when a certain frame has been reached

### ISSUE THREAD

**Issue by ZachSaucier** [bodymovin/bodymovin#104]
Right now the only ways to detect when a certain frame has been played is by using either

1) The `enterFrame` event paired with a check of `e.currentTime > frameNum` 
2) Using `anim.playSegments([startFrameNum, frameNum], true)` and the `complete` event followed by optionally playing the next segment in the animation.

It would be very handy to have a `anim.addEventListener("frameReached", frameNum)` event or something similar to save writing it every time we want to do something at a particular frame.

**Comment by bodymovin** [comment]
This could be built on top of the enterFrame event.
I'd rather not add another event check on every frame if it can be calculated from an existing one.

**Comment by marcobyburo** [comment]
Hi, can you give an example how to do this with "enterFrame" event?
I have the same question as ZachSaucier.
Thanks.

**Comment by ZachSaucier** [comment]
Hey @marcobyburo. You can use `anim.addEventListener('enterFrame', changePage);` where `changePage` is a function like so:

```
var someFrame = 40; // For example, this will fire after the 40th frame
function changePage(deferred, e) {
      if(e.currentTime > someFrame) {
          anim.removeEventListener('enterFrame', changePage);
          // Do whatever you want at that frame
      }
```

**Comment by marcobyburo** [comment]
Yes, that's it! :D 
Thank you so much @ZachSaucier. I really appreciate that.
Cheers.
