### ISSUE TITLE
Canvas renderer not running

### ISSUE THREAD

**Issue by ZachSaucier** [bodymovin/bodymovin#105]
It seems that the Canvas renderer is not working for some animations I'm trying that work when rendered with SVG. I've attached the data from one as a txt file because GH doesn't allow JSON files.

[data.txt](https://github.com/bodymovin/bodymovin/files/319593/data.txt)

I noticed that [this example](http://codepen.io/airnan/pen/PqjwYM?editors=0010) has two formats of data - one for SVG and another for canvas. Am I missing something in exporting that is necessary for the canvas version?

P.S. It might be good to mention in the docs that `animType` and `renderer` can both be used to specify which renderer to use.

**Comment by bodymovin** [comment]
Some types of masks are not supported on canvas. Can you share the .ae so I can confirm?

**Comment by ZachSaucier** [comment]
I emailed you the file.

Is there a more full list of the features that don't work with canvas?

**Comment by bodymovin** [comment]
Subtract masks don't work on the canvas renderer yet.
Only svg for now.
