### ISSUE TITLE
Several animations in one page?

### ISSUE THREAD

**Issue by bruroar** [bodymovin/bodymovin#106]
Hi Hernan!

I'm [finishing my site](http://kakumagame.com/test26/), and I'm trying to use one animation in each of the images of the site.

Nevertheless, when I add the second one at the bottom of the page, it appears just after the initial one, no matter where on the page I add the code.

Is this something bodymovin allows doing, and if so, is there a quick fix or something I´m not seeing?

Thanks!

**Comment by bodymovin** [comment]
Hi, several animations in a page is possible
it seems you're targetting always the same DOM element.
document.getElementById('bodymovin')
you should give a unique id to each to make it work

**Comment by bruroar** [comment]
Thanks Hernan, I've changed the second code for this:

     ```
       <div style="width:100%;height:100%;" id="bodymovin2"></div>
            <script>
                var animData = {
                    wrapper: document.getElementById('bodymovin2'),
                    animType: 'svg',
                    loop: true,
                    prerender: true,
                    autoplay: true,
                    path: 'data2.json'
                };
                var anim = bodymovin.loadAnimation(animData);
                window.onresize = anim.resize.bind(anim);
            </script>
```

With that it should be working, right?

It is not, but at least if that code is alright I know is because of the CSS.

As always, thanks!

**Comment by bodymovin** [comment]
yes, but if you name the animation instance "anim" on both cases, one will override the other one.
Same will happen with window.onresize function.
