### ISSUE TITLE
Document the 'loaded' event

### ISSUE THREAD

**Issue by tremby** [bodymovin/bodymovin#107]
It took me a while of reading the source to find how to detect when the animation is loaded and ready. I found that I can listen for the `DOMLoaded` event on the player object. It would be good if this were documented.

**Comment by bodymovin** [comment]
yes, I will update the wiki pages with a page about events.

**Comment by blastframe** [comment]
Is listening for "DOMLoaded" on an animation instance the best way to detect when the Bodymovin .json has loaded?

**Comment by bodymovin** [comment]
yes, that should be the event to listen to to know the json has loaded and the animation is ready.

**Comment by tremby** [comment]
If this has been documented I can't find it. Am I missing something?
