### ISSUE TITLE
Animations not playing since 4.2.0

### ISSUE THREAD

**Issue by tremby** [bodymovin/bodymovin#108]
The data files I had which worked with version 4.1.8 do not play with 4.2.0 or 4.2.1.

Perhaps backwards-compatibility was not expected, but it would be nice if breaking changes had a major version number switch with them -- otherwise builds can break unexpectedly when we think all we're doing is updating for new bug fixes and performance improvements.

More specifically, the animations do play, but are invisible (at least with the SVG renderer). The colours are to blame, with rgba values way out of the 0,255 range. Animation example which has this problem: http://sprunge.us/RVgG

**Comment by bodymovin** [comment]
I thought I had taken care of backwards compatibility.
Colors were just what needed to update.
I'll check the file and upload a fix.
my bad.

**Comment by bodymovin** [comment]
Can you share the .ae file so I can check the difference? I think see the animation fine on my side.

**Comment by bodymovin** [comment]
ok found the issue.
Fixed and uploaded.
Thanks for the heads up!

**Comment by tremby** [comment]
I don't have it; only the json file. In case it wasn't clear, I see the
issue in the browser via the JavaScript player. I have the rendering mode
set to SVG and am loading the json file via the "path" option.

I can try to get you an ae file if it would be helpful.

**Comment by tremby** [comment]
Oh -- great! I'll check it out when I get home. Thanks.

**Comment by tremby** [comment]
This did the trick. Thanks.

**Comment by tremby** [comment]
Looks like github is missing a tag for this, though I do note that the tag exists in NPM.
