### ISSUE TITLE
Add the player bodymovin.js on a CDN

### ISSUE THREAD

**Issue by heavybeard** [bodymovin/bodymovin#109]
Maybe is useful for all, add the [main script](https://github.com/bodymovin/bodymovin/blob/master/build/player/bodymovin.js) on a CDN.

**Comment by bodymovin** [comment]
yes, it's on my todo list check how to do it on cloudfront and prices :)

**Comment by heavybeard** [comment]
Hi @bodymovin. Ok thanks, perfect!!

**Comment by jeroentradecast** [comment]
Why not add it to [cdnjs](https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library)?

**Comment by bodymovin** [comment]
library is on cndjs now
https://cdnjs.com/libraries/bodymovin

**Comment by elliottregan** [comment]
I think this issue needs to be reopened for the newer version. I see Bodymovin v4.x on cdnjs, but not lottie-web v5.x.

**Comment by DominikTo** [comment]
There is a pull request over at cdnjs/cdnjs#12815 already.
