### ISSUE TITLE
Stroke Animation Issues 

### ISSUE THREAD

**Issue by JackPollitt** [bodymovin/bodymovin#110]
I recently updated bodymovin to the latest version and since then i have been unable to render my animated logo that worked perfectly before.

The animation is made up from layers from illustrator, converted to shape layers and then trim paths to animate in the stroke. Worked fine before but parts of my animation isn't loading. Rest is working fine. Only 2 out of the 7 letters don't work. one partially doesn't work.

This is on the inside of H, the inside of A and the inside of O the insides animate, the outsides don't.

Thanks for any help.

**Comment by bodymovin** [comment]
could you send me the json and ae file so I can check it?

**Comment by JackPollitt** [comment]
One moment, let me check if i can send the file over or not as it’s for a client.


Thanks

Jack Rogers
Motion Designer
 
Pollitt & Partners
9–10 Floral Street
London WC2E 9HW  <http://maps.google.co.uk/maps/place?hl=en&georestrict=input_srcid%3A9be3085c7a6e454f>
T +44 (0)20 7379 6709 <tel:+442073796709>
pollittandpartners.com <http://www.pollittandpartners.com/?utm_source=email-sig-logo&utm_medium=Jack%20Rogers&utm_campaign=Email%20signature>
  <http://www.pollittandpartners.com/?utm_source=email-sig-logo&utm_medium=Jack%20Rogers&utm_campaign=Email%20signature>

**Comment by bodymovin** [comment]
ok, meanwhile, are you using the canvas or svg renderer?

**Comment by JackPollitt** [comment]
To be honest i’m not sure. I am opening bodymovin using window, extensions.

Clicking the cog, selecting all ( just because that seems to work ) then hitting render.. that always worked for me before.. am i missing a step or is this ok?

**Comment by bodymovin** [comment]
Hey! Did you get this working finally?

**Comment by JackPollitt** [comment]
Hi,

Yes all fixed, had to convert each shape layer and edit with the strokes… was a very lengthy process but all worked in the end , thanks

Jack Rogers
Motion Designer
 
Pollitt & Partners
9–10 Floral Street
London WC2E 9HW  <http://maps.google.co.uk/maps/place?hl=en&georestrict=input_srcid%3A9be3085c7a6e454f>
T +44 (0)20 7379 6709 <tel:+442073796709>
pollittandpartners.com <http://www.pollittandpartners.com/?utm_source=email-sig-logo&utm_medium=Jack%20Rogers&utm_campaign=Email%20signature>
  <http://www.pollittandpartners.com/?utm_source=email-sig-logo&utm_medium=Jack%20Rogers&utm_campaign=Email%20signature>
