### ISSUE TITLE
Rendering stuck on 3D layers

### ISSUE THREAD

**Issue by CNek** [bodymovin/bodymovin#111]
Using AE CC 2015.x with OS X 10.10.5

• Create blank project
• Add random shape layer
• Make it 3D
• Export with bodymovin (any options)

Rendering hangs...
When canceling the render, got an alert : "cannot execute script at line 92, undefined is not an object" (translated from french)

Am I missing something ?

Great great plugin BTW 👍

**Comment by bodymovin** [comment]
hi.
can you share the .ae project so I can check it?
I can't seem to reproduce the issue.
