### ISSUE TITLE
How to use the JSON file instead of the inline demo method.

### ISSUE THREAD

**Issue by esbowman** [bodymovin/bodymovin#112]
I'm admittedly not experienced with code. I know HTML and CSS enough to do simple things, but not much else. 

I've had great success thus far using the "demo" option in the Bodymovin' extension window (the version that exports it into one HTML file), but when I try to export a JSON file and include it in an HTML page I'm lost. 

I read through the documentation on the Github page but I have to be missing something.

**Here's a sample of the code I'm using for the HTML page:**

```
<html xmlns="http://www.w3.org/1999/xhtml">
<meta charset="UTF-8">
<head>
</head>
<body>
<div id="svgContainer" style="width:650px;height:400px;background-color:#000;display:inline-block"></div>
<script src="js/bodymovin.js" type="text/javascript"></script>
<script type="json" src='demo.json'></script>
<script src="js/index.js"></script>
</body>
</html>
```

**This is what I have in my index.js file:**

```
var svgContainer = document.getElementById('svgContainer');
var animItem = bodymovin.loadAnimation({
  wrapper: svgContainer,
  animType: 'svg',
  loop: false,
  animationData: JSON.parse(animationData)
});
```

I'd appreciate some guidance. Thank you!

**Comment by joeshock** [comment]
Don't embed the .json file in your page with <script> tags. Just put it here:

animationData: JSON.parse(demo.son)

and you should be good!

**Comment by esbowman** [comment]
I appreciate the reply and have changed my crappy code. :) 

However, I'm still stuck. I moved all of the js stuff into the index.js file. I have the bodymovin.js file in the folder as well as the data.json file. I feel as though the files and links are in the correct places, but obviously I've done something wrong.

If someone would be so kind as to take a peek at this test page I'd appreciate it. 

http://assemblycreative.com/clients/wfa/html5/0711/demo.html

**Comment by bodymovin** [comment]
if you are loading the data from the external json, don't use the "animationData" param, use the "path" param and pass it the relative path of your json file. In this case I guess it's "data.json"

`var svgContainer = document.getElementById('svgContainer');
var animItem = bodymovin.loadAnimation({
  wrapper: svgContainer,
  animType: 'svg',
  loop: false,
  path: 'data.json'
});`
