### ISSUE TITLE
I updated version to 4.3.1 and I am now getting JS errors 

### ISSUE THREAD

**Issue by hardy613** [bodymovin/bodymovin#113]
Uncaught TypeError: Cannot read property 'roundness' of undefined

Uncaught TypeError: Cannot read property 'size' of undefined

We removed the JS in AE

**Comment by hardy613** [comment]
also the link on the readme

https://creative.adobe.com/addons/products/12557

the AF version says 4.2.0, is that correct? Should it be 4.3.1?

Cheers, and thanks for your time

**Comment by bodymovin** [comment]
The version on the addons store is usually outdated because it needs to go through the approval process.
Are you having trouble with an older animation or a new one?
Can you share the json and player with me?

**Comment by hardy613** [comment]
This would be a new animation, basically the color is not rendering out properly

I could ask if our video team can attach the file and if you would like I can pass it to you to try an export. 

As it stands now, we are running player4.3.0 and are not creating assets or modifying assets until the proper updates are out for After Effects.

Cheers.

PS: whats the difference of bodyMovin.js and bodyMoving.light.js, what has been trimmed out?

Seems like playSegments and the Events are missing, is that true?

**Comment by bodymovin** [comment]
The bodymovin light version has only the svg renderer and expressions are not supported.
playSegments and events work fine on it.
Are you having issues with it?

**Comment by hardy613** [comment]
I tried it out while trying to debug the version miss-match and it couldn't render past the first few frames.

Adobe updates are killer.. I have player 4.3.0 and we had the 4.3.0 extension installed and something changed on Adobes end "updating" our extension to 4.2.0 (the one in the store) and we are trying to revert the extension to 4.3.0 again.

**Comment by hardy613** [comment]
Details attached above

**Comment by bodymovin** [comment]
I see the animation json is version 4.2.0 and the player version is 4.1.8, if you update the player to an older version than the animation it should work fine.
You can use the version from github or the one from the latest extension.

**Comment by hardy613** [comment]
How can we tell what version our animations our exported as, or what version the player is?

returning null Rectangle Path 1
VM26512:2 Uncaught TypeError: Cannot read property 'size' of undefinedfn @ VM26512:2execute @ bodyMovin.ver2.js:9t @ bodyMovin.ver2.js:2BaseElement.prepareFrame @ bodyMovin.ver2.js:4ICompElement.prepareFrame @ bodyMovin.ver2.js:5SVGRenderer.renderFrame @ bodyMovin.ver2.js:4AnimationItem.renderFrame @ bodyMovin.ver2.js:7AnimationItem.gotoFrame @ bodyMovin.ver2.js:7AnimationItem.checkLoaded @ bodyMovin.ver2.js:7t @ bodyMovin.ver2.js:7(anonymous function) @ bodyMovin.ver2.js:7AnimationItem.configAnimation @ bodyMovin.ver2.js:7i.onreadystatechange @ bodyMovin.ver2.js:7
bodyMovin.ver2.js:9 returning null Rectangle Path 1
VM26513:2 Uncaught TypeError: Cannot read property 'roundness' of undefinedfn @ VM26513:2execute @ bodyMovin.ver2.js:9t @ bodyMovin.ver2.js:2BaseElement.prepareFrame @ bodyMovin.ver2.js:4ICompElement.prepareFrame @ bodyMovin.ver2.js:5SVGRenderer.renderFrame @ bodyMovin.ver2.js:4AnimationItem.renderFrame @ bodyMovin.ver2.js:7AnimationItem.gotoFrame @ bodyMovin.ver2.js:7AnimationItem.setCurrentRawFrameValue @ bodyMovin.ver2.js:7AnimationItem.advanceTime @ bodyMovin.ver2.js:7o @ bodyMovin.ver2.js:7
bodyMovin.ver2.js:9 returning null Rectangle Path 1

**Comment by bodymovin** [comment]
for the player, check bodymovin.version.
for the animation, you can check of the json request. It's a "v" attribute in the root of the json.

**Comment by hardy613** [comment]
Issues resolved,

Miss matching versions, we couldn't of figured this out without your added efforts.

Please share a donate link (paypal?)
