### ISSUE TITLE
Compatibility Duik / Bodymovin ?

### ISSUE THREAD

**Issue by fabiteby** [bodymovin/bodymovin#114]
Bodymovin is really an awesome tool !
I made some tests with the great Duik, but unfortunately, the scripts generated by Duik are not correctly interpreted by bodymovin. 
Is there any chance that they would be in the futur ?

**Comment by bodymovin** [comment]
hi!
can you send me the .ae file or the exported .json so I can take a look?

**Comment by fabiteby** [comment]
Hi! :)
Here's the html file of a very simple exemple
[demo.txt](https://github.com/bodymovin/bodymovin/files/363536/demo.txt)

**Comment by fabiteby** [comment]
here's the .aep file (i can't send the zipped file... don't know why)
[duik.txt](https://github.com/bodymovin/bodymovin/files/363541/duik.txt)

**Comment by bodymovin** [comment]
There's a velocity property that is not supported yet, but I'll work on it these days and let you know

**Comment by fabiteby** [comment]
thanks a lot for this return !
this would be really great :)

**Comment by bodymovin** [comment]
Done and uploaded!
