### ISSUE TITLE
How do I donate to the project? 

### ISSUE THREAD

**Issue by hardy613** [bodymovin/bodymovin#115]
I would like to support the project and/or the author and contributors. 

Is there a donation location?

**Comment by rgrevatt** [comment]
yes I'd do the same - really appreciate how responsive you've been!

**Comment by therealsalih** [comment]
Me too

**Comment by bodymovin** [comment]
thanks all! not accepting donations right now.
but if you spread the word or share your work that would be awesome :)

**Comment by bodymovin** [comment]
http://aescripts.com/bodymovin/
