### ISSUE TITLE
Feature Request: Export SVG Sequence

### ISSUE THREAD

**Issue by shaneparsons** [bodymovin/bodymovin#116]
This might be out of the scope of this project, but it'd be awesome to have the functionality to export an svg sequence from AE, much like how you can export a png sequence.

Unfortunately for me, this is what I originally thought this plugin was made to do.

**Comment by bodymovin** [comment]
why would you prefer having an svg sequence? to avoid using javascript?

**Comment by shaneparsons** [comment]
Basically I'm trying to use After Effects for the animation in my Unity project. The way I've done it before is using a png sequence, but there's no place for that now that I'm using svgs in Unity.

A great deal of the functionality of this plugin would be ignored in my particular case, but it's the only thing remotely close to what I'm looking for anywhere.

**Comment by bodymovin** [comment]
I guess you could use the plugin and then write a script that gets the innerHTML of the svg element on every frame.
