### ISSUE TITLE
Now that..

### ISSUE THREAD

**Issue by l3omtz** [bodymovin/bodymovin#117]
now that I got my AE exported, how do I added to my local html page.

**Comment by l3omtz** [comment]
<img width="401" alt="screen shot 2016-07-14 at 4 35 15 pm" src="https://cloud.githubusercontent.com/assets/11321783/16856657/06895eb8-49e1-11e6-92f9-f13ea1743785.png">

'm getting this issue in the console log and my animation wont load

**Comment by l3omtz** [comment]
This is my code


`<title>Animated Background Gradient</title>
        <link rel="stylesheet" href="css/style.css">
    <script src="js/bodymovin.js"></script>
         
         

  </head>

  <body>

    <div style="width:100%;height:100%;" id="bodymovin"></div>

    <script>

      var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: true,
        path: 'data.json'
    };
    var anim = bodymovin.loadAnimation(animData);
      
    </script>

> `</body>``

**Comment by l3omtz** [comment]
This is my code

<title>Animated Background Gradient</title>
        <link rel="stylesheet" href="css/style.css">
    <script src="js/bodymovin.js"></script>
         
         

  </head>

  <body>

    <div style="width:100%;height:100%;" id="bodymovin"></div>

    <script>

      var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: true,
        path: 'data.json'
    };
    var anim = bodymovin.loadAnimation(animData);
      
    </script>

</body>

**Comment by l3omtz** [comment]
@bodymovin  this is my code


Animated Background Gradient
        <link rel="stylesheet" href="css/style.css">
    <script src="js/bodymovin.js"></script>



  <body>

    <div style="width:100%;height:100%;" id="bodymovin"></div>

    <script>

      var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: true,
        path: 'data.json'
    };
    var anim = bodymovin.loadAnimation(animData);
      
    </script>

</body>

**Comment by l3omtz** [comment]
@bodymovin  This is my code  
 script src="js/bodymovin.js"

    <div style="width:100%;height:100%;" id="bodymovin"></div>

    <script>

      var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: true,
        path: 'data.json'
    };
    var anim = bodymovin.loadAnimation(animData);
      
    </script>

</body>

**Comment by etx** [comment]
Chrome cannot load local files. That is what the console is telling you.

Run a quick HTTP server with Python and load it from local host. https://docs.python.org/2/library/simplehttpserver.html

**Comment by l3omtz** [comment]
@etx ah okay thank you... but does the code look right?

**Comment by bodymovin** [comment]
@l3omtz yes, that code should work running it through an http server.

**Comment by l3omtz** [comment]
@bodymovin Yeah I have a MAMP server running but with the demo files it seems to only run the .js demos and not the .json ones why is that?

**Comment by bodymovin** [comment]
are you getting the error you posted on the first message or another one?

**Comment by l3omtz** [comment]
var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: true,
        animationData: JSON.parse(data.json)
    };


error is 
<img width="368" alt="screen shot 2016-07-14 at 8 37 57 pm" src="https://cloud.githubusercontent.com/assets/11321783/16861054/e85a11c2-4a02-11e6-84eb-ff9744732473.png">

@bodymovin

**Comment by bodymovin** [comment]
when you're passing a json file, you need to use "path" instead of "animationData" and pass the path to the json file, like so:
`var animData = {
wrapper: document.getElementById('bodymovin'),
animType: 'html',
loop: true,
prerender: true,
autoplay: true,
path:'data.json'
};`

**Comment by l3omtz** [comment]
@bodymovin then i get the first error ... is there a way i can get the .js file of the .json instead? that seem easier to load

**Comment by l3omtz** [comment]
This is my full code
<img width="673" alt="screen shot 2016-07-14 at 8 44 15 pm" src="https://cloud.githubusercontent.com/assets/11321783/16861165/cb184768-4a03-11e6-96da-0563cf48f01d.png">

**Comment by bodymovin** [comment]
the first error is because you need to use a valid http url, it won't work accessing it from your local system.

yes, there is an easy way to convert the json file into a js object.
If you open the file "data.js" in the folder demo/grunt and compare it with the json file exported, you'll see they are very similar.
It just creates a variable "animData" and assigns it the json data.

**Comment by l3omtz** [comment]
so i just add a var animData =  
and that will make it a .js format?
@bodymovin

**Comment by bodymovin** [comment]
yes, but make sure you check the html in the grunt example.
first it loads both script tags:
<script src="../bodymovin.js"></script>
<script src="data.js"></script>
then it creates the animationParams to load the animation

**Comment by l3omtz** [comment]
when I copy and past the grunt .js code it works and i see the animation
but when i put my own i dont see anything.... could I be exporting it wrong? @bodymovin 
<img width="1240" alt="screen shot 2016-07-14 at 9 22 25 pm" src="https://cloud.githubusercontent.com/assets/11321783/16861733/20a544f6-4a09-11e6-8862-d29544ef0238.png">

**Comment by bodymovin** [comment]
are you using the latest player?

**Comment by l3omtz** [comment]
what do you mean latest player? @bodymovin

**Comment by bodymovin** [comment]
where are you loading the bodymovin.js file from? the demo folder or the one on the builds folder?

**Comment by l3omtz** [comment]
im using build/ player/ bodymovin.js @bodymovin

**Comment by bodymovin** [comment]
Can you send me the json file so I can check it out?

**Comment by l3omtz** [comment]
This is my whole code file

Thanks again!

**Comment by l3omtz** [comment]
[animated-background-gradient.zip](https://github.com/bodymovin/bodymovin/files/365957/animated-background-gradient.zip)

**Comment by l3omtz** [comment]
@bodymovin actually i got it to work,  I rendered the wrong AE file. So thats why it was blank... 
Another question tho, is there a way to have two  AE .json files to animate two separate animations in one screen

**Comment by bodymovin** [comment]
sure
you can load each on a different html element

**Comment by l3omtz** [comment]
@bodymovin So i updated the AE and I still dont see anything 

var animData = {"assets":[],"v":"4.1.7","ddd":0,"layers":[{"ddd":0.....

is it because the assets [] is empty? 

my other .json file is filled in and it works

**Comment by bodymovin** [comment]
not necessarily, it depends on the animation.
None of them are working or only one?

**Comment by l3omtz** [comment]
@bodymovin  the only one working is the gear animation which has 2 layers and the code starts like this 
var animData = {"assets":[{"id":"image_0","w":700,"h":700,"p":"images/img_0.png"},......

The gradient animation one doesn't work and iit only one layer and its like this 
var animData = {"assets":[],"v":"4.1.7","ddd":0,"layers":[{"ddd":0.....

**Comment by bodymovin** [comment]
not sure if that's the reason, but unfortunately, gradient fills are not supported because AE doesn't expose gradient values.

**Comment by l3omtz** [comment]
@bodymovin will there be a reason why my the image is coming out pixelated?
<img width="791" alt="screen shot 2016-07-19 at 7 28 28 am" src="https://cloud.githubusercontent.com/assets/11321783/16949845/91b7d9a2-4d82-11e6-9060-d0c2be463635.png">

**Comment by bodymovin** [comment]
what renderer are you using?
can you share a link with the animation?
