### ISSUE TITLE
Reverse Animation

### ISSUE THREAD

**Issue by gigantc** [bodymovin/bodymovin#118]
Just found this today and it's awesome!!  

I'd like to have my animation play through once and then loop back in reverse.  It seems like setDirection() should let me run the animation backwards but it doesn't seem to be working...or maybe I'm just doing it wrong.  Any ideas?

**Comment by bodymovin** [comment]
can you share the code on how you're doing it?

**Comment by gigantc** [comment]
Basically I'm getting the data and setting the animation parameters.  The second function fires when I hit a spot on the page and plays the animation.  Everything works fine to just play the animation forward using anim.setDirection(1), if I switch the direction to -1 nothing happens. 

--

var anim;

$.getJSON( "/splash/ani-logo.json", function( data ) {
  var params = {
    container: document.getElementById('brandCanvas'),
    renderer: 'svg',
    loop: false,
    autoplay: false,
    animationData: data
  };
  anim = bodymovin.loadAnimation(params);
});

//run animation when brand hits the screen
$('.brand').scrolledIntoView()
.on('scrolledin', function () { 
     anim.setDirection(-1);
     anim.play();
});

**Comment by QQizi** [comment]
Set direction shouldn't be on the anim but on the global bodymovin variable.

bodymovin.setDirection(-1)

I know it's weird :)

**Comment by bodymovin** [comment]
you can setDirection to the animation itself.
If you're at the first frame and set direction negative and loop is false it will stay on the first frame.
You should set goToAndStop(lastFrame) for example before playing.
