### ISSUE TITLE
json issues?

### ISSUE THREAD

**Issue by watziznehm** [bodymovin/bodymovin#119]
When I try to get an animation to work with a json file I can't for the life of me get it to work. Nothing will show up. Not sure if its related but nothing appears when I load the demos that use json to, just a grey background. Any help would be appreciated.

**Comment by bodymovin** [comment]
can you share a json file that doesn't work?

**Comment by watziznehm** [comment]
OMG! I'm just stupid and wasn't working on a local host. Sorry about that.

**Comment by bodymovin** [comment]
nice!
