### ISSUE TITLE
"Failed to install" message using ExManCmd

### ISSUE THREAD

**Issue by drw158** [bodymovin/bodymovin#12]
Adobe CC 2015
OS X Yosemite 10.10.5

I'm getting an error message whenever I follow the instructions to use the ExManCmd utility:

> Failed to install, status = -160!

It's not on their error message page.

I made sure to run the correct command from their instructions:

`./Contents/MacOS/ExManCmd --install .zxp`

Adobe instructions page: https://helpx.adobe.com/x-productkb/global/installingextensionsandaddons.html
Error page: https://helpx.adobe.com/extension-manager/using/extension-manager-error-code-reference.html

Any ideas?

**Comment by bodymovin** [comment]
that command is not specifying the name of the zxp file
change it to
./Contents/MacOS/ExManCmd --install bodymovin.zxp

let me know if it works

**Comment by drw158** [comment]
This seems to work, although their command for checking to see if it has been installed doesn't return anything: `./Contents/MacOS/ExManCmd -- list all`

Thanks! I see the extension panel.
