### ISSUE TITLE
Exports come out black, regardless of color

### ISSUE THREAD

**Issue by wwwzrd** [bodymovin/bodymovin#122]
My exports are coming out all black, even though the shapes have different colors in the AE file. For instance; if I have a red square bodymovin will export a black square.

Has anyone else experienced this?

**Comment by bodymovin** [comment]
Check if you are using the correct player

**Comment by alexkerber** [comment]
Yes, you need the latest player that was used when you did export the animation. So always make sure that you export the right plugin if you update the bodymovin plugin.

**Comment by wwwzrd** [comment]
Bodymovin is no longer in Adobe Add-ons. To update bodymovin, do I need to uninstall and re-install again?

**Comment by alexkerber** [comment]
Just follow the steps in the read me and you should be able to update to the latest version.

**Comment by wwwzrd** [comment]
"MAC:
open the file ~/Library/Preferences/com.adobe.CSXS.6.plist and add a row with key PlayerDebugMode, of type String, and value 1."

For this step, I am missing the file "com.adobe.CSXS.6.plist", I have "com.adobe.CSXS.3.plist" instead. Is there anything I can do to get the right file?

**Comment by alexkerber** [comment]
Try just copy it and rename it … 
<img width="912" alt="screen shot 2016-07-28 at 21 19 15" src="https://cloud.githubusercontent.com/assets/1282718/17226293/ffb60400-5508-11e6-9334-40396f93ab3a.png">

**Comment by wwwzrd** [comment]
I tried renaming the files; I didn't get any errors and I believe I updated bodymovin but my renders are still coming out all black.

If I downloaded and installed the latest files, that should include the player, yes?

**Comment by alexkerber** [comment]
You have an save plugin when in the bodymovin window. Use that one or take it from the zip file. Same thing (you need to re export the animation again with the new updated plugin)

**Comment by bodymovin** [comment]
I'm travelling right now. I'll be back in the weekend. Can you share the .ae Project so I can check it?

**Comment by wwwzrd** [comment]
Crisis averted. I don't think the player was setup properly, but the bodymovin.js that was being referenced on our local server setup needed to be updated.

Thanks again.

**Comment by bodymovin** [comment]
nice!
