### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by alexkerber** [bodymovin/bodymovin#123]
Updated to the latest version of the plugin and from the right animation we got the left version with missing assets. Same file, same settings but new plugin. Trying to downgrade the plugin but same issue. Any ideas?

https://www.dropbox.com/s/q1w4q7z7hk6tpoc/diffrent.mp4?dl=0

**Comment by bodymovin** [comment]
Hi. I'm away right now. Will be back this weekend. Can you send me the .ae project so I can check it out?

**Comment by alexkerber** [comment]
You are a star! Email sent with the file!

**Comment by alexkerber** [comment]
Did you have time and look at my file?

**Comment by bodymovin** [comment]
Yes! I arrived late yersterday and couldn't upload the fix.
I'll be uploading it tonight.

**Comment by alexkerber** [comment]
You are a star! Thanks!

—

Alex Kerber

Creative Technologist

+46 (0) 735 40 30 20 | 

http://alexkerber.com/

On Tue, 02 Aug 2016 at 00:55 hernan

<
mailto:hernan <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Yes! I arrived late yersterday and couldn't upload the fix.

I'll be uploading it tonight.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/bodymovin/bodymovin/issues/123#issuecomment-236732596
, or

**Comment by bodymovin** [comment]
done!

**Comment by alexkerber** [comment]
Woks perfect now with the lastest version.
