### ISSUE TITLE
not found via adobe

### ISSUE THREAD

**Issue by yesmetoo** [bodymovin/bodymovin#124]
the link https://creative.adobe.com/addons/products/12557 leads to a message "product nor found"
and the manual way of installation does not work for me. nay help i appreciated, thx!

**Comment by larpo1** [comment]
I had the same problem

**Comment by yesmetoo** [comment]
did u find any solution?

**Comment by larpo1** [comment]
The alternative installation instructions are in the github readme.

**Comment by bodymovin** [comment]
I'm trying to solve this issue with Adobe.
Will let you know when it's up again.

**Comment by bodymovin** [comment]
The plugin is up again in the adobe store
https://creative.adobe.com/addons/products/12557
