### ISSUE TITLE
4.3.3: Cannot read property 'effect' of undefined

### ISSUE THREAD

**Issue by thomas-dm** [bodymovin/bodymovin#125]
Hello,

This is the first time I've ever used Bodymovin, so I can’t say if this particular animation would’ve worked before. Basically, I’m getting this error:

`Uncaught TypeError: Cannot read property 'effect' of undefined`

This is the problematic line:
`$bm_rt = thisComp.layer('Adjustment Layer 1').effect('Tail_Opacity')('Slider');`

Both the plugin and the player are up to date (4.3.3).
Any idea of what I should look into?

Thank you!

**Comment by bodymovin** [comment]
Hi!
Adjustment layers are not exported by the plugin.
Can you move those effects to another layer or convert it to another type of layer?

**Comment by thomas-dm** [comment]
That was it indeed!
Thanks you for the quick reply.

By the way, is there still no way we could donate to the project?
I’d seriously consider donating. ;-)
