### ISSUE TITLE
Using Bodymovin Animations with Barba.js

### ISSUE THREAD

**Issue by St3Ko** [bodymovin/bodymovin#126]
Hi everyone!

I am trying to use bodymovin animations with barba.js for transitions between sites (fade-in animation - barba replaces the old barba-container with the new one - fade-out animation).

The problem is, that i am not able to tell barba, when the first fade-in animation is finished, so it can safely remove the old with the new content.

I know that you can add eventlisteners but barba.js works with Promises. For example like so:
```
var FadeTransition = Barba.BaseTransition.extend({
  start: function() {
    Promise
      .all([this.newContainerLoading, this.fadeIn()])
      .then(this.fadeOut.bind(this));
  },

  fadeIn: function() {
    // do stuff, like fade-in animation and return fulfilled when the animation is finished
  },

  fadeOut: function() {
    // do stuff after the new barba-container is loaded AND the fade-in animation is finished
  }
});

Barba.Pjax.getTransition = function() {
  return FadeTransition;
};
```

Is there a way to use Promise with bodymovin animations?

any help would be greatly appreciated, thx!

**Comment by bodymovin** [comment]
can you wrap the bodymovin event with a promise and resolve it when the event fires?

**Comment by St3Ko** [comment]
Nice! Thank you very much, this solved my problem :)

**Comment by Sandstedt** [comment]
@St3Ko Could you provide an example of you finished code? I'm stuck with the same problem.

**Comment by St3Ko** [comment]
sure! i don't have the exact code anymore but i think i went with something like this:

define your animation:
```
...
var anim = bodymovin.loadAnimation(animData);
...
```
wrap animation with a promise and return it - resolve on complete:
```
...
fadeIn: function() {
    return new Promise(function(resolve) {
        anim.start();
        anim.onComplete = function() {
            resolve(true);
        }
    });
},
...
```
i haven't tested this code, but i think it should work :)

**Comment by Sandstedt** [comment]
Worked perfectly, thanks a lot @St3Ko!

**Comment by sifford** [comment]
I'm on the same barba + lottie path.. @st3ko @sandstedt, would any of you be able to share your code in regards to successfully firing a fadein and fadeout animation? Any bits are greatly appreciated! I've been wanting to do custom page transitions for awhile, but have settled with the animsition jquery plugin. Hoping I can implement something similar to https://waaark.com

**Comment by johangiraud** [comment]
I am facing the same issue. Can't have bodymovin trigger after barba page loading. I am sure I understand where to place the `new Promise` function. Here is my barba init:
```
const TLMax = new TimelineMax()
  barba.init({
    sync: true,
    transitions: [{
      name: 'opacity-transition',
      leave(data) {
        gsap.to(data.current.container, 0.3, {
          opacity: 0,
          onComplete: this.async()
        })
      },
      enter(data) {
        data.current.container.parentNode.removeChild(data.current.container)
        gsap.from(data.next.container, 0.5, {
          opacity: 0,
          onComplete: this.async()
        })
        lottieInit()
      },
    }]
  })
```
And here is my animation init:
```
var anim;
var jsonOutput = example.json;
var elem = document.getElementById('#animation-container')
var animData = {
      container: elem,
      renderer: 'svg',
      loop: false,
      autoplay: true,
      rendererSettings: {
        progressiveLoad: false,
        preserveAspectRatio: 'xMidYMid slice'
      },
      path: jsonOutput
};
document.addEventListener("DOMContentLoaded", () => {
      anim = bodymovin.loadAnimation(animData);
})
```
Can anybody help me with that? @St3Ko @Sandstedt @bodymovin? Quite new to lottie and barba, sorry if my question might seem trivial or so.
Thanks a lot in advance 😄
