### ISSUE TITLE
Uncaught TypeError: Cannot read property 'effect' of undefined

### ISSUE THREAD

**Issue by digamber89** [bodymovin/bodymovin#127]
I've exported the animation into jso file and it also has required images with it but the animation won't play, I took the js from build folder and used the default bodymovin example to render the file.

I can't figure out the error and 
[test.zip](https://github.com/bodymovin/bodymovin/files/401084/test.zip)
what i need to get this going could you please look at it?

**Comment by bodymovin** [comment]
There is an expression trying to get an effect from layer Falloff.
Is it possible that that layer is hidden or guided?
If you send me the .ae project I can take a look
