### ISSUE TITLE
Dashed strokes support

### ISSUE THREAD

**Issue by fabienjuxrousseau** [bodymovin/bodymovin#128]
Hi,

First of all, your plugin is awesome!
I tried to export a dashed stroke but this seems not supported yet. Am I right ?

Thank you!

Edit : My strokes were renamed in AfterEffects. It seems to work now with default name for the strokes properties.

**Comment by bodymovin** [comment]
I'll have a look at stroke naming. I must have missed that.
Can I close the issue?
