### ISSUE TITLE
img_0.png being overwritten

### ISSUE THREAD

**Issue by blastframe** [bodymovin/bodymovin#129]
I am exporting several separate bodymovin animations to a folder. A couple of them have an images. Rather than write separate files, both use the image name "img_0.png" so only one image is created and then overwritten. In my animations, the same image appears instead of two images. Is there a way to control the image names or have new names generated when two animations are trying to write the same image name?

I could create separate folders for each animation .json, but I'd rather keep them all in one folder as there will be many.

Thank you!

**Comment by bodymovin** [comment]
can't you export them to two different folders?
that way they won't conflict.
