### ISSUE TITLE
Demos don't work

### ISSUE THREAD

**Issue by drw158** [bodymovin/bodymovin#13]
I downloaded the latest, and I can't seem to get the demos to play. I open the html files in my browser, but nothing happens. It's just a blank gray div.

I ask because I am having a hard time understanding how to set bodymovin up. It would be helpful to have some demos!

**Comment by bodymovin** [comment]
You're right, I will upload updated demos this weekend.
Where are you having trouble setting things up?

**Comment by drw158** [comment]
@bodymovin Thanks for the quick response! I'm not too familiar with JS, so getting it to work isn't very easy for me.

Here is what I have so far: http://codepen.io/drw158/pen/yYaqom

I uploaded the files to my own server and added them in Codepen. Not sure if that works.

**Comment by bodymovin** [comment]
@drw158 There are a couple of issues.
first of all, your server isn't returning the right headers, so codepen can't load the json file.
You can inline the exported json to see the animation.
I've forked your pen here http://codepen.io/airnan/pen/xwEJQq
If you try it on your own server, loading the json will work, so you can do one of both techniques you've tried.
I will upload later two examples one for each.

**Comment by bodymovin** [comment]
demos updated
