### ISSUE TITLE
Exporting issues from After effects 

### ISSUE THREAD

**Issue by elgamble** [bodymovin/bodymovin#130]
Hello there,

I'm new to the whole HMTL, coding thing, I've been set a project at work to get some SVG's for a site, so I've created a little test animation in After Effects, but upon rendering, it goes whacky.

Here are some images:

<img width="722" alt="screen shot 2016-08-16 at 13 31 21" src="https://cloud.githubusercontent.com/assets/21059272/17698796/f7e69284-63b4-11e6-9c7e-a4bfd81453b2.png">

This is how the imagery is meant to look, but when I click render on the bodymovin window, and preview the animation inside the console, I get this result: 

<img width="728" alt="screen shot 2016-08-16 at 13 32 48" src="https://cloud.githubusercontent.com/assets/21059272/17698820/26c80a42-63b5-11e6-809b-e838b92dd585.png">

The code is also out of whack, it looks crazy: 

[bodymovin.js.zip](https://github.com/bodymovin/bodymovin/files/420240/bodymovin.js.zip)

Hope somebody can help! 

Many thanks

**Comment by kencieszykowski** [comment]
I'm having a similar issue with the exporting; except that I'm not getting anything to show up in the 'Preview' window.  Do I need to be selecting the layers and all of the elements in the timeline?

**Comment by bodymovin** [comment]
I missed this issue.
@elgamble if you're still trying to solve this, can you send me the ae project?
@kencieszykowski you don't need to select the layers. Can you share your .ae project with me?

**Comment by ThePredators** [comment]
hello bodymovin,

First of all thank you for this great pluggin !

Well im getting the exact problem as described by @elgamble and @kencieszykowski with solid element. While rendering with the bodymovin plugin no animation showed up.

Thanks for help.
(I join the project so u can see what's going on !).
[AmazingAppAnim.aep.zip](https://github.com/bodymovin/bodymovin/files/987124/AmazingAppAnim.aep.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately the radio waves effect is not supported.
Only a few effects are right now.

**Comment by ThePredators** [comment]
Thank for your answer. Mean while i corrected the composition and then used Shape Layers, then every runs tight.

**Comment by sebbean** [comment]
@bodymovin which ones are supported?

**Comment by bodymovin** [comment]
@sebbean Here is the list
https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by sebbean** [comment]
Thanks you very much
