### ISSUE TITLE
Is there a way to add a class to elements in the svg through after effects?

### ISSUE THREAD

**Issue by amanda--** [bodymovin/bodymovin#131]
I am aware that I can add id's to layers in After effects; that works great!

It would be very useful to be able to add classes as well. 

For example: I've got a big infographic animation which has several buttons that will open popups. It would be great to be able to add a general class as well as an unique id to those elements/buttons.

**Comment by bodymovin** [comment]
you can add classes as well as ids.
add an initial dot to the name of the layer and it will add a class to it.

**Comment by amanda--** [comment]
Sorry! I tested it, but apparently I did something wrong, because now it is working. 
Also adding a class and id to the same layer works perfectly. Thanks!
