### ISSUE TITLE
Animation not looping after loopComplete

### ISSUE THREAD

**Issue by amanda--** [bodymovin/bodymovin#134]
Hello,

We init a bodymovin animation in a button that loops and has autoplay set to false.
On mouse enter of the button we play the animation (and it loops).
On mouse leave we listen to the loop complete and stop the animation. So when you leave the button the animation finishes one loop.

This all works perfectly.

But when I enter the button for a second time the animation just plays once and doesn't loop anymore. This is probably caused by listening to the loopComplete, but I don't know how to set the animation to looping again when entering the button.

Any suggestions would be very much appreciated!

Thank you

**Comment by bodymovin** [comment]
can you share the code?
It might be related to adding an event to loopComplete more than once

**Comment by amanda--** [comment]
Hello,

It's embedded in a big project, but I can share te relevant functions with you. 

`/**
     * Init button icons
     */
    initButtonIcons: function ()
    {
        Object.keys(this.state.buttons).map((id, i) =>
        {
            let buttonEl = document.querySelector('#' + id + ' .icon');
        let animationData = JSON.parse(this.props.json[this.state.buttons[id].json.icon]);

        this[id] = bodymovin.loadAnimation({
            wrapper: buttonEl,
            renderer: 'svg',
            loop: true,
            autoplay: false,
            prerender: true,
            animationData: animationData
        });
    }
        );
    },

    /**
     * Entering the button
     * @param event
     */
    enterButton: function (event)
    {
        let id = event.currentTarget.parentNode.id;
        this[id].goToAndStop(1);
        this[id].play();
    },

    /**
     * Leaving the button
     * @param event
     */
    leaveButton: function (event)
    {
        let id = event.currentTarget.parentNode.id;
        this[id].addEventListener('loopComplete', function ()
        {
            this[id].stop();
        }.bind(this));
    },`

**Comment by amanda--** [comment]
Do you have any idea how I can fix this!?

My backup plan was to destroy and init the animation every time you hover, but that's not very efficient.

**Comment by bodymovin** [comment]
Sorry, I didn't get the change to try it.
I'll take a look at it this afternoon

**Comment by bodymovin** [comment]
The issue is probably related to not removing the eventListener once the loop is complete or once the button is hovered again.
Instead of attaching an anonymous function to the loopComplete event, try to attach a function declared on your class.
And once the event triggers, remove the event listener. Also remove the event listener on the enterButton in case it never got to the loop complete event before entering again.
I did a version without ES6 and classes, but I think it's easy to translate.

```
var buttonEl= document.getElementById('bodymovin');
var animData = {
    wrapper: buttonEl,
    renderer: 'svg',
    loop: true,
    autoplay: false,
    prerender: true,
    animationData: animationData
};
var anim = bodymovin.loadAnimation(animData);
function loopCompleteHandler(){
    anim.removeEventListener('loopComplete', loopCompleteHandler);
    anim.stop();
}
buttonEl.addEventListener('mouseover', function(){
    anim.removeEventListener('loopComplete', loopCompleteHandler);
    anim.goToAndStop(1);
    anim.play();
})
buttonEl.addEventListener('mouseout', function(){
    anim.addEventListener('loopComplete', loopCompleteHandler);
})
```

Let me know if it makes sense

**Comment by amanda--** [comment]
Thank you for your example!

We tried to make it work without the anonymous functions, but the same issue was still there. 
The eventListener didn't seem to get removed with the code you posted.

We found a different solution: 
on the mouse leave we set the loop property to false and on the mouse enter we set it back to true again. A lot simpler and it works perfectly :)

**Comment by bodymovin** [comment]
Good solution. I'm glad you made it work.
I did a demo with the code I sent you. Is this the effect you were looking for?
http://codepen.io/airnan/pen/zBQaWR

**Comment by amanda--** [comment]
Yes, your example is what I was looking for indeed.

You seem to do exactly what we implemented, so I've got no idea why it didn't work in our case. It probably has something to do with any other part of code. It's a pretty big project made with React.

I'm happy we got it working too :D

**Comment by SeanRoberts** [comment]
@amanda-- How did you set the loop property on an existing animation?  I'm not seeing that in the docs anywhere.

**Comment by bodymovin** [comment]
@SeanRoberts yes, it's not official, but you can directly edit the loop property on the animation instance.

**Comment by SeanRoberts** [comment]
@bodymovin Aha, this works perfectly.

For anyone following along:

```
const anim = bodymovin.loadAnimation(animData);

anim.loop = true;
anim.loop = false;
```

I managed to make a nifty React loader component this way:

```
import React from 'react';
import ReactDOM from 'react-dom';
import bodymovin from 'bodymovin';
import logoLoading from 'animations/logo-loading.json';

export default class Toolbar extends React.Component {
  componentDidMount() {
    this.loadingAnimation = bodymovin.loadAnimation({
      container: ReactDOM.findDOMNode(this.refs.animationContainer),
      renderer: 'svg',
      loop: true,
      autoplay: false,
      animationData: logoLoading
    });
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.isLoading && !this.props.isLoading) {
      this.loadingAnimation.play();
      this.loadingAnimation.loop = true;
    } else if (!nextProps.isLoading && this.props.isLoading) {
      this.loadingAnimation.loop = false;
    }
  }

  render() {
    return (
      <div className="toolbar">
        <div ref="animationContainer" className="toolbar__logo" />
      </div>
    );
  }
}
```

**Comment by BestUSMAN** [comment]
Sean Roberts, that was so cool, thanks but how can I destroy the animation, so that I could move to the next page, I've used your code, cause I'm kind of new to the animation and stuff like that.

**Comment by SeanRoberts** [comment]
@BestUSMAN You'd probably need to tap into the `componentWillUnmount()` lifecycle method and destroy the animation there.
