### ISSUE TITLE
Not working on Edge/IE ?

### ISSUE THREAD

**Issue by Raphiki44** [bodymovin/bodymovin#136]
I have no problem on running my animation trough Chrome or Firefox, but nothing happen in Edge or Internet Explorer 11. Not even an error log.

Here are how I setup my anim :
 
test-anim.html : 

```
<div id="anim" class="bodymovin" data-bm-path="scripts/animation_mock/data.json" data-bm-renderer="svg" data-anim-loop="true" data-anim-autoplay="true" data-name="mock"></div>
<script src="scripts/bodymovin.js" type="text/javascript"></script>
```

That's pretty basic (I also tried via js)
There is absolutely NO content inserted in my div on Edge or IE.

I already tested with 2 different anim, same problem.

Here's my Json file : http://pastebin.com/bcyQTDyE

**Comment by bodymovin** [comment]
I'm trying your animation and it seems to work fine (although I don't have the exported images).
Can you share a link so I can take a look?

**Comment by Raphiki44** [comment]
Ew sorry I found my mistake., I work from my local hard drive with Chrome and Firefox with the flag "allow-file-access-from-files" that wasn't enable on Edge or IE. It couldn't  access to the data.json file locally.

**Comment by bodymovin** [comment]
nice
