### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by jakeleboeuf** [bodymovin/bodymovin#138]
You want to drop this sucker on Bower? Working on an Ember.js addon to wrap this magic up and would love to handle versioning via bower if possible?

**Comment by bodymovin** [comment]
I'm not well acquainted with bower, but it would be great.
I'll look into it.
Any info is welcome :)

**Comment by UniK** [comment]
OK, I'm working on this.

**Comment by UniK** [comment]
I have submitted a pull request #470.

**Comment by UniK** [comment]
All right, so the `bodymovin` package is now registered with Bower.
All semver tags will be available as versions.
You can install the package with `bower install bodymovin`, or list all the available versions with `bower list bodymovin`.

**Comment by UniK** [comment]
This issue can now be closed.
