### ISSUE TITLE
Scaling SVG

### ISSUE THREAD

**Issue by rlavoie** [bodymovin/bodymovin#14]
Is there a way to control the size after initialization. I want the SVG to scale full screen, but maintain the aspect ratio?

**Comment by bodymovin** [comment]
@rlavoie  If you scale the contaning div, the svg element will scale maintaining the aspect ratio.
Let me know if there is any issue with that.

**Comment by rlavoie** [comment]
It does I guess I was looking for a fill effect but still maintain aspect ratio. So either the right or bottom would be cut off depending on screen size.  preserveAspectRatio="xMinYMin slice" seems to do the trick

**Comment by bodymovin** [comment]
@rlavoie yes. you can do it manually after initializing the animation. I will add to to a config at some point.

**Comment by fabiofcferreira** [comment]
@rlavoie @bodymovin 
I took the time and dedication to develop a very small lib (for now) which has 1 function to scale SVG animations rendered by Lottie. Take a look [here](https://github.com/fabiofcferreira/lottie-scale). Would be cool to make a PR to include this in Lottie itself or people could just use it whatever way they wish to.
