### ISSUE TITLE
Mask not supported Edge/IE

### ISSUE THREAD

**Issue by John-MAr** [bodymovin/bodymovin#143]
Hello,

I have no problem on running my animation through Chrome or Firefox, but Layers located in a mask appears with an opacity of 50% with Edge and IE

Do you have any solution for my issue ?

**Comment by bodymovin** [comment]
Not for the moment. It's a issue on their side.
What kind of mask are you using?

**Comment by John-MAr** [comment]
A mask Alpha

**Comment by bodymovin** [comment]
inverted or normal?

**Comment by John-MAr** [comment]
Normal

**Comment by jorisvanr** [comment]
I also have this issue. I use an image that I mask in with a alpha matte. This way the parts of the image that are overlapped by the stokes are revealed. It works in chrome, firefox and safari but in Edge and IE it doesn't. 

Besides that there is another weird problem. I have a comp that is exactly the same as this one, with a shape and alpha matte, but this one does not show anything in Edge and IE. Could this be the same issue? 
 
![alpha_matte](https://cloud.githubusercontent.com/assets/16778969/19301721/204f0570-9061-11e6-9416-93cc2a955db8.png)

**Comment by bodymovin** [comment]
yes, IE and Edge don't support alpha masking so those kind of masks behave as luma masks

**Comment by jorisvanr** [comment]
That actually makes a lot of sense (one of the strokes was red, hence semi-transparent, and the other was white, so fully transparent). I'm going to use an inverted luma matte.

**Comment by bodymovin** [comment]
alpha masks are supported now in edge and ie

**Comment by foguetes** [comment]
IE and Edge support alpha masks but not alpha inverted masks. please keep that in mind.

**Comment by marcelbold** [comment]
Hi bodymovin, we experience a lot of strange (not displaying correctly) behaviour in alpha or inv. alpha masks in IE / Edge. It seems to me that you can't use masks in edge?

**Comment by bodymovin** [comment]
have you tried the Luma mask?
Can you share the aep or a link where it fails?

**Comment by marcelbold** [comment]
[170613_LOGO_Animations_v2.aep.zip](https://github.com/bodymovin/bodymovin/files/1084932/170613_LOGO_Animations_v2.aep.zip)

Luna mask does't work for my 'layer 15', 
alpha mask for layer 8 & 12 doesn't render for IE / edge

**Comment by marcelbold** [comment]
Hi Hernan,

Sorry for getting back so late… busy and vacation-time. Did we send you the AE file?
Luma mask wasn’t an option. Some other stuff went *fubar* ;)



Met vriendelijke groeten,
Marcel Bold



-------------------------------------------------------------------------------------------------
Holleweg 31A                                              
6131 AA Sittard, The Netherlands                  
Direct: +31-(0)46-4000 330                                   
Fax: +31-(0)46-4000 331                                   

Web: www.51north.nl <http://www.51north.nl/>
-------------------------------------------------------------------------------------------------

 http://www.linkedin.com/in/marcelbold <http://www.linkedin.com/in/marcelbold>

**Comment by bodymovin** [comment]
Hi sorry I didn't check it before.
IE and Edge have a lot of issues with masks.
I'm looking into it right now but I'm not sure I'm going to be able to solve it.
I'll let you know if I make any progress.

**Comment by marcelbold** [comment]
Hi Hernan,

Thank you for the commitment! We really appreciate it.
We think it’s actually an IE bug and can’t be resolved. :(

Met vriendelijke groeten,
Marcel Bold



-------------------------------------------------------------------------------------------------
Holleweg 31A                                              
6131 AA Sittard, The Netherlands                  
Direct: +31-(0)46-4000 330                                   
Fax: +31-(0)46-4000 331                                   

Web: www.51north.nl <http://www.51north.nl/>
-------------------------------------------------------------------------------------------------

 http://www.linkedin.com/in/marcelbold <http://www.linkedin.com/in/marcelbold>
