### ISSUE TITLE
ctrlEffect is not a function Error

### ISSUE THREAD

**Issue by nbashiri95** [bodymovin/bodymovin#145]
Hi!
first , amazing plugin!
I exported an animation and when I'm trying to load it "**ctrlEffect is not a function Error**" this error appears ,is there any way that i can fix it?

[Uploading data.zip…]()

**Comment by bodymovin** [comment]
it's probably related to some expression included in the animation.
I'll take a look and let you know.

**Comment by nbashiri95** [comment]
thanks a lot

**Comment by bodymovin** [comment]
yes please, can you share the .json or the .ae project?

**Comment by nbashiri95** [comment]
[ae project and json file](https://www.dropbox.com/sh/mbwv304ve7r89m7/AACbHoFBwZi3ihLHrKm1J932a?dl=0)

**Comment by bodymovin** [comment]
The puppet tool from AE is not supported unfortunately so the animation won't work.
Besides that, if you're using guided and hidden layers, you need to export them explicitly on the settings menu.

**Comment by nbashiri95** [comment]
ow! yeah

**Comment by bodymovin** [comment]
no, the rest should work fine.
