### ISSUE TITLE
Render canvas error 

### ISSUE THREAD

**Issue by onceclick** [bodymovin/bodymovin#146]
I created a simple animation with Text. Then exported without check Glyphs.

var params = {
        container: document.getElementById('bodymovin'),
        renderer: '**canvas**',
        loop: true,
        autoplay: true,
        animationData: animationData
    };

Output file work ok with render: 'svg' or 'html'. But I got problem with render: canvas.

If I check Glyphs when exporting, It work ok with canvas, but because I need to change the Text in html file, then check Glyphs is not a good solution because fonts is converted to shape.

Is this an error or I've used in the wrong way. I use version 4.4.11. Thank you for your support.

**Comment by bodymovin** [comment]
yes, canvas doesn't support the text as text.
If you need to edit text, you can export it as glyphs and have an extra layer hidden with all the letters you need on it, so they will get exported and be available to edit text.
Could that work for your case?

**Comment by onceclick** [comment]
Thank you very much for your clear explanation @bodymovin

**Comment by spider853** [comment]
> yes, canvas doesn't support the text as text. If you need to edit text, you can export it as glyphs and have an extra layer hidden with all the letters you need on it, so they will get exported and be available to edit text. Could that work for your case?

Hi, I'm not sure I understood the solution, when exporting as glyphs each letter get exported as an json object. How would a hidden layer with all letters will help in this case if I want to replace a full text? ex: Test_Text -> Longer_OUTPUT_Text
