### ISSUE TITLE
Render bodymovin with node canvas

### ISSUE THREAD

**Issue by onceclick** [bodymovin/bodymovin#147]
Hi,

Bodymovin works like a charm on browser with my exist canvas. Does it work with canvas in node? I love to render bodymovin animation to mov/gif in node environment. Thanks for any support.

**Comment by bodymovin** [comment]
I haven't tested much but using phantomjs seems to work fine

**Comment by WangShuXian6** [comment]
> I haven't tested much but using phantomjs seems to work fine

can you show some examples ? i tried it all day and i don`t konw how to write
