### ISSUE TITLE
Animation plays smoothly on Chrome but really lags on Firefox

### ISSUE THREAD

**Issue by Shirkit** [bodymovin/bodymovin#148]
Hello,

I just exported a small animation that we want to use. It plays smoothly on Chrome, IE and Edge (although it breaks because of masks), but it just LAGS on Firefox. Like under 10 FPS, while I get a 60FPS on Chrome. I do not know what I've done wrong over here.

[New folder.zip](https://github.com/bodymovin/bodymovin/files/495804/New.folder.zip)

**Comment by bodymovin** [comment]
I guess you're using alpha masks for the animations, right?
Are they inverted or straight masks?
Unfortunately, firefox has some issues with masking and specially inverted masks.
As far as I can tell, you could do the same animation with regular AE masks, and performance would be much better.
If you want to share your .ae project, I can take a better look.

**Comment by Shirkit** [comment]
But it still wouldn't work on IE/Edge, right? Even with normal masks?

I'm using inverted masks.

**Comment by bodymovin** [comment]
yes, normal masks will work fine in Edge and IE

**Comment by bodymovin** [comment]
Also, if the letters are illustrator layers, you should convert them to shapes so you don't get images exported.

**Comment by Shirkit** [comment]
Ok,

I repassed this conversation to the dude that actually does AE, he said he was using MATTE.

Tomorrow we'll try fixing this, since it's 9:30pm already over here. We'll convert to regular masks and see the result. I'll get back topmost Thursday to report the result.

**Comment by bodymovin** [comment]
Sure, let me know if I can help you with anything else

**Comment by Shirkit** [comment]
Here's the return:

We now tried a mix of all solutions for the reveal effect:
- Matte: Chrome plays fine, Firefox plays under 20FPS, breaks on IE/Edge
- Inverted Masks: Chrome and Firefox plays fine, IE/Edge plays under 30 fps
- Normal Masks: Plays fine on all 4 browsers

The animation had about 10 layers.

The usage of "pre-comps" seems to make things run more smoothly on that animation of ours (I think it's like grouping layers together).

I haven't tested on Safari or Opera.

I have no idea whatsoever how to use After Effects, I'm just the web designer.

Thanks for this awesome plugin!
