### ISSUE TITLE
Data.json file exported but the animation not playing

### ISSUE THREAD

**Issue by Turash** [bodymovin/bodymovin#149]
Hello,

Greetings. I am very excited to run this plugin. I exported or rendered an animated loop in .json format but the animation seem not to run. I am not sure what is the issue below I list all the options I choosed for the render.
![screen](https://cloud.githubusercontent.com/assets/5880099/18884742/fc4e1932-84e8-11e6-802e-5cddcc81c3a9.png)
Thanks in advance.
Best Regards
Turash

**Comment by bodymovin** [comment]
hi.
for a basic animation, having Glyphs checked should be enough.
Can you share the .ae project or the json so I can take a look?

**Comment by Turash** [comment]
Hi
this is my html file
<div style="width:100%;height:100%;background-color:#333;display:inline-block;" class="bodymovin" data-bm-path="dataAlt.json" data-bm-renderer="svg"></div>

And My json file 
[dataAlt.json.zip](https://github.com/bodymovin/bodymovin/files/496303/dataAlt.json.zip)

**Comment by Turash** [comment]
html code didnt show up
`<div style="width:100%;height:100%;background-color:#333;display:inline-block;" class="bodymovin" data-bm-path="data3.json" data-bm-renderer="svg"></div>
`

**Comment by bodymovin** [comment]
it was an issue with trim paths on offsetted shapes. :/
I've just uploaded a new build with the fix.
If you update the player, with this new one, it should work fine now.
Thanks!

**Comment by Turash** [comment]
Hi, Thanks for the updated version so fast. I was able to run along with these settings. 
![solved](https://cloud.githubusercontent.com/assets/5880099/18908254/2ee53bb0-856f-11e6-8df9-d61cd635541c.png)

But still extracting in Json format got me some errors. But for now exporting in js file resolves my issue.

**Comment by bodymovin** [comment]
I'm glad it works.
If you want to share the json version, I can take a look at it.

**Comment by Turash** [comment]
Yeah definately. HTML code inside body
`<div style="width:100%;height:100%;background-color:#333;" id="bodymovin"></div>

<script>
    var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: true,
        path: 'dataTime.json'
    };
    var anim = bodymovin.loadAnimation(animData);
</script>`


[dataTime.json.zip](https://github.com/bodymovin/bodymovin/files/497885/dataTime.json.zip)
Thanks in advance

**Comment by bodymovin** [comment]
that json seems corrupted.
can you export it again without setting the standalone checkbox?

**Comment by Turash** [comment]
ok. you mean now I export only in glyphs checked? here is the file
[data.json.zip](https://github.com/bodymovin/bodymovin/files/498146/data.json.zip)

**Comment by bodymovin** [comment]
Did you finally get it working?
That json works fine on my side

**Comment by Turash** [comment]
Hi, my after effects plugin expired :( I am using standard css to animate. http://demo-alphadns.rhcloud.com/#/view1
