### ISSUE TITLE
how to play the animation when the element is visible

### ISSUE THREAD

**Issue by mitkovalkov** [bodymovin/bodymovin#150]
Hi, fellows
It's my first steps in this great plugin. How can I start the animation when I scroll to it? 

animContainer = document.getElementById('bodymovin');

var animationData ="datajson";

var params = {
        container: animContainer,
        renderer: 'svg',
        loop: true,
        autoplay: false,
        animationData: animationData
    };

    var anim;

    anim = bodymovin.loadAnimation(params);
    animContainer.addEventListener("mouseover", myScript);

    function myScript(){
        anim.play();
    }

In this case the animation start only on hover.
Thanks for your time!

**Comment by bodymovin** [comment]
I guess what you need is to attach to the scroll event of the page and when the animation is visible, play it. But the plugin doesn't handle scroll events on it's own.

**Comment by mitkovalkov** [comment]
Many thanks for the support,
I find a easy way to solved my issue... 

$.fn.inView = function(){
    if(!this.length) return false;
    var rect = this.get(0).getBoundingClientRect();

    return (
        rect.top >= 0 &&
        rect.left >= 0 &&
        rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
        rect.right <= (window.innerWidth || document.documentElement.clientWidth)
    );

};

$(window).on('scroll',function(){

    if( $('#bodymovin').inView() ) {
        var animationData = "..."

        var params = {
            container: document.getElementById('bodymovin'),
            renderer: 'svg',
            loop: true,
            autoplay: true,
            animationData: animationData
        };

        var anim;

        anim = bodymovin.loadAnimation(params);
    }else {
        console.log('not visible');
    }

});

**Comment by mitkovalkov** [comment]
Many thanks for the support,
I find a easy way to solved my issue...
`$.fn.inView = function(){
    if(!this.length) return false;
    var rect = this.get(0).getBoundingClientRect();

    return (
        rect.top >= 0 &&
        rect.left >= 0 &&
        rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
        rect.right <= (window.innerWidth || document.documentElement.clientWidth)
    );

};`

`$(window).on('scroll',function(){

    if( $('#bodymovin').inView() ) {
        var animationData =  the animation data

        var params = {
            container: document.getElementById('bodymovin'),
            renderer: 'svg',
            loop: true,
            autoplay: true,
            animationData: animationData
        };

        var anim;

        anim = bodymovin.loadAnimation(params);
    }else {
        console.log('not visible');
    }

});`

**Comment by mitkovalkov** [comment]
Many thanks for the support,
I find a easy way to solved my issue...

$.fn.inView = function(){
        if(!this.length) return false;
        var rect = this.get(0).getBoundingClientRect();

        return (
            rect.top >= 0 &&
            rect.left >= 0 &&
            rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
            rect.right <= (window.innerWidth || document.documentElement.clientWidth)
        );

    };

    $(window).on('scroll',function(){

        if( $('#bodymovin').inView() ) {
            var animationData =  the animation data

            var params = {
                container: document.getElementById('bodymovin'),
                renderer: 'svg',
                loop: true,
                autoplay: true,
                animationData: animationData
            };

            var anim;

            anim = bodymovin.loadAnimation(params);
        }else {
            console.log('not visible');
        }

    });

**Comment by rezwanferdous** [comment]
In this code, there's no mention of the path?
