### ISSUE TITLE
BodyMovin Light is broken in 4.4.11+

### ISSUE THREAD

**Issue by mpeterson2** [bodymovin/bodymovin#151]
```
bodymovin_light.js:5 Uncaught ReferenceError: ProjectInterface is not defined
```

I'm getting this error when trying to use bodymovin_light.js. It looks like it works up until `4.4.11`. I'm not really sure how you build the light version, so debugging it is kind of difficult.

I pasted ProjectInterface from the regular `bodymovin.js` and it came up with another error, looking for `HybridRenderer`. So it seems like the light version is missing several components.

Thanks!

**Comment by bodymovin** [comment]
thanks! with the new effects, it broke.
Fixed and uploaded.

**Comment by mpeterson2** [comment]
Looks like I'm getting

```
Uncaught ReferenceError: EffectsManager is not defined
```

now.

**Comment by bodymovin** [comment]
can you share the json file?

**Comment by mpeterson2** [comment]
https://gist.github.com/mpeterson2/956deb157bda420e720313029b1a2fe3

**Comment by bodymovin** [comment]
Effects are not supported in the light version.
There seems to be a Tint effect in the pball1.png layer

**Comment by mpeterson2** [comment]
Looks like removing the `ef` property made it work again. Thanks! Is there a list of features that do/don't work for the light version anywhere?

**Comment by bodymovin** [comment]
I've included a wiki page to detail it.
It only supports the svg renderer and I excluded the whole expressions and effects module.

**Comment by mpeterson2** [comment]
Awesome, thanks! Gonna go ahead and close this then.
