### ISSUE TITLE
Unminified version of the library

### ISSUE THREAD

**Issue by glenndehaan** [bodymovin/bodymovin#153]
Do you have an unminified version of the library available?

**Comment by bodymovin** [comment]
I haven't included one. Didn't think it was necessary.
Is there a use for doing it?

**Comment by glenndehaan** [comment]
In a lot of our projects we minify everything together. Sometimes this means some already minified libraries break the process because you can't minify the files twice.

**Comment by L8D** [comment]
I'm having the same problem. When including bodymovin as a dependency in our webpack bundle, it means it go through a second minification pass with UglifyJS2 and something in the code gets broken along the way (all the transforms look like `matrix(NaN,NaN,NaN,NaN,NaN,NaN)`).

**Comment by bodymovin** [comment]
Makes sense. 
Uploaded minified and unminified versions of bodymovin and bodymovin_light.
Thanks for your suggestions!

**Comment by glenndehaan** [comment]
Tnx
