### ISSUE TITLE
JS Module support

### ISSUE THREAD

**Issue by MerlinBB** [bodymovin/bodymovin#154]
Hey, thanks for an awesome plugin!

Would be super cool if it supported a module pattern that would be compatible with browserify / webpack allowing it to be bundled into applications and required when necessary.

**Comment by bodymovin** [comment]
The plugin is bundled as an UMD, shouldn't that work fine with browserify and webpack?

**Comment by MerlinBB** [comment]
Ahhrgh sorry... I have no idea why but this wasn't working the other day and I assumed it was an issue with the plugin, seems to work fine now.

Thanks again and sorry to bother you!
