### ISSUE TITLE
trembling in scale property animation

### ISSUE THREAD

**Issue by juanigorota** [bodymovin/bodymovin#156]
I love your script, but when a play it in my browser, Firefox, there is always a tremble in the simple scale animation of the backround layer. Why? Could i do something to avoid it?

Thanks!

**Comment by bodymovin** [comment]
is it a large layer? Firefox has issues with too large layers.
can you share the .ae?

**Comment by juanigorota** [comment]
1000x1334 pixels
[Revista_num_11_3_Portada_folder.zip](https://github.com/bodymovin/bodymovin/files/521510/Revista_num_11_3_Portada_folder.zip)

**Comment by bodymovin** [comment]
I think it's related to scaling images.
Can you try the canvas renderer instead?

**Comment by juanigorota** [comment]
Sorry, I don´t know how to do it. I´am an After Effects user only. Expert one, but only of After Effects.
Could you try to explain to me how to use canvas render? in a easy way, please.

**Comment by bodymovin** [comment]
how are you trying the animation?
are you using the demo.html or using your own code?

**Comment by juanigorota** [comment]
demo.html

**Comment by bodymovin** [comment]
you can open the demo.html on a text editor and you'll find near the end of the document a renderer specified as 'svg', try changing it to 'canvas'

**Comment by juanigorota** [comment]
Thanks a lot! It works! Great!
