### ISSUE TITLE
TypeError: comp(...) is undefined

### ISSUE THREAD

**Issue by panda-madness** [bodymovin/bodymovin#159]
Hello!

I've updated the extension from the repository, and downloaded the latest player version.

When trying to run the following code I get a 'TypeError: comp(...) is undefined' message. What could be the reason?

```
var object = bodymovin.loadAnimation({
        container: document.getElementById('test'), // the dom element
        renderer: 'svg',
        loop: true,
        autoplay: true,
        name: 'test',
        animationData: digitalLogoAnimData // the animation data
    });
```

digitalLogoAnimData is equal to the contents of the exported data.json.

**Comment by bodymovin** [comment]
it seems you have an expression pointing to an external composition.
If that's the case, you need to include it as an extra asset on the "Extra Comp" settings of the composition in the plugin.

**Comment by panda-madness** [comment]
@bodymovin Wow, thanks for the fast reply! I'll try that.

**Comment by panda-madness** [comment]
@bodymovin Checked the extra comp settings in the plugin, still getting the error. I also get the error on the generated demo.html

**Comment by bodymovin** [comment]
can you share the .ae so I can take a look?

**Comment by panda-madness** [comment]
@bodymovin 
[Pencil.aep.zip](https://github.com/bodymovin/bodymovin/files/532860/Pencil.aep.zip)

**Comment by bodymovin** [comment]
The issue is because "Comp 1" is the main comp and it can't be referenced from other comps. I need to fix that.
In the meantime, you can precomp Comp 1 into another comp and export that one. It will work like that.

On another topic, you are using repeaters in your animation and they are not yet supported. They are first on my pipeline but it will take some time.

**Comment by panda-madness** [comment]
Ok, thank you very much for your help!
