### ISSUE TITLE
Include demos for most recent version of the player

### ISSUE THREAD

**Issue by snorpey** [bodymovin/bodymovin#16]
I noticed that all demos in the [demo](https://github.com/bodymovin/bodymovin/tree/master/demo) folder seem to be using an older version of the player.

It would be nice if the repo could include demos that are working with the most recent version of the player in [``build/player/bodymovin.js``](https://github.com/bodymovin/bodymovin/tree/master/build/player/bodymovin.js).

I also noticed that the ``path`` variable in [``player/index.html``](https://github.com/bodymovin/bodymovin/blob/master/player/index.html#L51) points to ``exports/render``, which isn't included in the repo. Is this on purpose?

**Comment by bodymovin** [comment]
@snorpey yes, all demos are outdated. I'll upload them again this weekend.
the player/index.html usually points to animations exported locally. You should add your own on that folder.
But I will upload a working example you can replace.

**Comment by bodymovin** [comment]
updated demos
