### ISSUE TITLE
Building Light Version

### ISSUE THREAD

**Issue by mpeterson2** [bodymovin/bodymovin#160]
How do you build bodymovin_light? I've messed around for a while now and haven't been able to figure it out. Would be nice to document this for contributors.

**Comment by bodymovin** [comment]
Hi
On the latest version I've cleaned a little the build process that was a mess.
There is a gulp task that builds all versions, light, normal minified and non minified.
the task is "buildAll".

**Comment by mpeterson2** [comment]
Oh sweet, didn't see that. Thanks.

**Comment by zhengs** [comment]
Hi @bodymovin , is it possible to prune the build tree even further to reduce the light version size? 

Asking because in our use case, JS library binary size is critical so we want to minimize JS size as much as possible.

**Comment by bodymovin** [comment]
@zhengs sure, if you know what features you're not using, you could remove some extra classes too.
