### ISSUE TITLE
Can't get gradient fills to export

### ISSUE THREAD

**Issue by zenworm** [bodymovin/bodymovin#161]
I've imported an Illustrator file, "created shapes from vector layer," and added a gradient fill to a few shapes, but when I export it none of the gradient shapes show up at all.

Are gradients supported? If so is there any special trick to get them working?

Here's my test file: https://drive.google.com/open?id=0B9XHSLZbjgN-MEo2b19vMERnVWs

The two bottom left sparkles have gradients, the rest are white. The white ones come out fine, the two blue ones disappear.

Thanks in advance!

**Comment by bodymovin** [comment]
Hi. I can't access that link. I need permissions.

**Comment by zenworm** [comment]
Sorry, fixed that up!

**Comment by bodymovin** [comment]
Hi, I exported the gradients and they work fine.
Make sure you save the project when you edit your gradients. The plugin needs the project to be saved to get the latest changes to gradients.
I see you figured out you need to hide merged paths when converting AI layers, so I guess that is not the issue.
If you still can't get to export them correctly let me know or write me an email.

**Comment by zenworm** [comment]
@bodymovin Thanks for the support, it was indeed because I was using the "canvas" renderer instead of the SVG renderer. Cheers!

**Comment by mrkhan3** [comment]
Hi @bodymovin i am using bodymovin extension in after effects 2018.
The issue that is my file has shapes with Gradient Ramp effect but  when i export the composition from modymovin into json file it dosent show the gradients on "data.json" or on "demo.html" file.
please guide men how to export json file with bodymovin extension having the gradient effect
.

**Comment by bodymovin** [comment]
@mrkhan3 the gradient ramp effect is not supported unfortunately.
The gradient property on shapes is, though.
