### ISSUE TITLE
Stroke effect doesn't work in Edge/IE

### ISSUE THREAD

**Issue by Adeptuce** [bodymovin/bodymovin#162]
Hi,

I love your plugin but I have a problem with Stroke effect.
I have a shape that appears with the Stroke effect with a path and animated radius.

What parameter of the Stroke effect did not supported by the plugin?

Thank you.
[animation-ae-bodymovin.zip](https://github.com/bodymovin/bodymovin/files/541828/animation-ae-bodymovin.zip)

**Comment by bodymovin** [comment]
You are using version 4.4.12
version 4.4.13 is the version that supports stroke effect.

**Comment by Adeptuce** [comment]
Perfect !

**Comment by Adeptuce** [comment]
I have got another problem with stroke effect.
It's not working in Edge/IE.
All animation works, except stroke effect.

Can you help me please ?

**Comment by bodymovin** [comment]
I can't check it right now. 
But can you try setting the stroke color to white?
it's probably related to Edge not supporting alpha masks.

**Comment by Adeptuce** [comment]
Thank you for your fast answer but the stroke color is already white.

**Comment by bodymovin** [comment]
I've tried the animation you shared in Edge and IE and it seems to work fine.
Can you share a link where it isn't working correctly?

**Comment by Adeptuce** [comment]
http://www.igtechprivilege.fr/test/

Stroke near "IGTECH Privilège" doesn't show.

**Comment by bodymovin** [comment]
It looks like a bug from Edge when the element is scaled.
The animation you sent the first time works, but this one that has a scale of around 200% on that element breaks.
I'll try to find a workaround for that but I don't think I'll succeed.
Can you roll back those elements to not being scaled as they were at first?

**Comment by Adeptuce** [comment]
I changed the size of the animation but it doesn't change anything.
The first animation I sent was export with 4.4.12 version so the stroke effect doesn't show.

**Comment by bodymovin** [comment]
You sent me the .ae on that zip. When I exported it, it worked fine on all browsers.

**Comment by Adeptuce** [comment]
Can you try another export with the new zip please ?
[animation-logo-clean.zip](https://github.com/bodymovin/bodymovin/files/557813/animation-logo-clean.zip)
Maybe I export the animation not correctly.

**Comment by bodymovin** [comment]
This version doesn't work.
The older one did.
It seems to be an issue with translation of masks in Edge.
I need to look further into it.
