### ISSUE TITLE
encoding issue - "Â" character showing up

### ISSUE THREAD

**Issue by NatalyaPowers** [bodymovin/bodymovin#163]
Any ideas how to fix this issue? I need to keep text editable and do not convert font to shapes. 
Â-Â little help, please.
![bodymovin issue](https://cloud.githubusercontent.com/assets/22962879/19569303/42134316-96c3-11e6-8469-a4543c294ac9.jpg)

**Comment by bodymovin** [comment]
can you share the .ae project?
are you using non ascii characters?

**Comment by NatalyaPowers** [comment]
Using Roboto font. https://fonts.google.com/specimen/Roboto
No "weird" characters. This happens with any font. I have tried from Arial to the most crazy ones.
sharing all associated files:
https://drive.google.com/open?id=0B2HgFKafSY0vdVg1aEdrY2ZPUlU

**Comment by bodymovin** [comment]
what language is your OS or AE in?
The export works fine on my side.

**Comment by NatalyaPowers** [comment]
English. I have tried on 2 different  machines (Windows 7).  
Installed directly from the store https://creative.adobe.com/addons/products/12557.
Uninstalled-reinstalled. Restart. No luck.

**Comment by bodymovin** [comment]
I see indeed that error on the demo.html file
but when I check the data.js file it works fine.
Have you tried using the data.js or data.json?

**Comment by NatalyaPowers** [comment]
We have to force the charset to ANSI to make it work. Otherwise, it will not.

**Comment by bodymovin** [comment]
on the json file?

**Comment by NatalyaPowers** [comment]
on js

**Comment by NatalyaPowers** [comment]
This is what we had to do to make it work:
1. convert the js file to ANSI encoding.
2. Convert the js file back to utf-8.
Then it works.
Here is the converted file:
[data.zip](https://github.com/bodymovin/bodymovin/files/544786/data.zip)

**Comment by bodymovin** [comment]
thanks for the heads up!
I'll try to find a way to fix it.
