### ISSUE TITLE
Matchnames for expression properties

### ISSUE THREAD

**Issue by MikeOverbeck** [bodymovin/bodymovin#166]
Loving this tool!
I'm experimenting with expressions and have found that properties referenced by MatchName and stored in a variable will break when rendering. Pick-whipping seems to work fine though. I've attached a simple .aep testing this out.
[BodyMovMatchNm.zip](https://github.com/bodymovin/bodymovin/files/548085/BodyMovMatchNm.zip)

**Comment by bodymovin** [comment]
Thanks for reporting!
I've just uploaded a version working with your example.
I try to support as many expressions as I can but it's an endless job. :)

**Comment by MikeOverbeck** [comment]
Brilliant! Matchname support will be huge for us script writers. It allows our expressions to be readable on all language versions of AE. Thank you!
