### ISSUE TITLE
Can't install from adobe extension manager cc

### ISSUE THREAD

**Issue by supasitsst** [bodymovin/bodymovin#169]
Hello

I just dowloaded the latest version of Bodymovin(V 4.4.18)
then i cant install Bodymovin manually from adobe extension manager cc **on my iMac**

here its msg from adobe extension manager cc

> `Failed to install the extension 'com.bodymovin.bodymovin'. Please make sure the manifest.xml of this extension is valid and the Extension Manager recognizes at least one product which the extension supports. `

however i'm install directly from the store but extension still not found in Window>Extension
can someone help me.

Thank you.

**Comment by bodymovin** [comment]
The extension manager doesn't support Adobe 2014/2015 extensions.
What version of AE are you using?

**Comment by supasitsst** [comment]
Adobe After Effects CC 
2015.3 Release 
Version 13.8.1.38

**Comment by bodymovin** [comment]
can you try with this installer?
it usually seems to work well
http://aescripts.com/learn/zxp-installer/

**Comment by supasitsst** [comment]
Oh! yes its  work well
Thank you so much.

**Comment by dinamicostudio** [comment]
![capture](https://cloud.githubusercontent.com/assets/25509061/26686131/ec3b96ee-46a0-11e7-9db1-bbb036af670a.PNG)
Please have a look my screenshot I can't install also my velositey extension also please help me.

**Comment by bodymovin** [comment]
Hi, what is Velositey?
I think the Extension Manager doesn't work with CC 14 and up
