### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by wanbinkimoon** [bodymovin/bodymovin#17]
Hi everyone, 
I'm trying to install this plugin (I really wanna do this) but I can't find the CEP folder you are talking about, searching on internet I understood that is some sort of adobe sdk but I still can't understand how the folder should be created. 

thanks for the help

**Comment by bodymovin** [comment]
@wanbinkimoon Hi! Are you using CC 2015? and what OS?

**Comment by wanbinkimoon** [comment]
I'm using cc 2015 and Mac OS X El Capitan 

--
Nicola Bertelloni
Mobile: +39 328 4559247

**Comment by bodymovin** [comment]
@wanbinkimoon did you try instructions on this page? they seem to work fine.
https://helpx.adobe.com/x-productkb/global/installingextensionsandaddons.html
go to "Install third-party extensions".
where it says:
Run the command ./Contents/Mac OS/ExManCmd --install .zxp to install the extension.
change it to
./Contents/MacOS/ExManCmd --install bodymovin.zxp

**Comment by wanbinkimoon** [comment]
Yes, i get a dialog box which says that the xml file has been corrupted. 


On 8 October 2015 at 21:49:52, hernan (notifications@github.com) wrote:

@wanbinkimoon did you try instructions on this page? they seem to work fine.
https://helpx.adobe.com/x-productkb/global/installingextensionsandaddons.html
go to "Install third-party extensions".
where it says:
Run the command ./Contents/Mac OS/ExManCmd --install .zxp to install the extension.
change it to
./Contents/MacOS/ExManCmd --install bodymovin.zxp

**Comment by bodymovin** [comment]
@wanbinkimoon can you attach a screenshot of the dialog box?

**Comment by cjgammon** [comment]
May want to consider submitting this to the adobe add-ons portal 
https://creative.adobe.com/addons 

This way users can install it automatically through the creative cloud, extension manager is EOL (https://www.adobeexchange.com/resources/27).

**Comment by bodymovin** [comment]
@cjgammon I tried to do it twice. but I got an email informing me that zxp extensions are not accepted for AE plugins and I should create another type of installer. I haven't figured out what installer is acceptable. I guess they mean native installers.

**Comment by wanbinkimoon** [comment]
Hi, 
I tryied againg and again and again. 
I made some progresses but, still not working, at the moment I'm dealing with an error 403 given by the ExManCmd, I did find any documentation on the web regarding ExManCmd errors, can you help me?

**Comment by bodymovin** [comment]
@wanbinkimoon Hi.
Another user told me it happened the same to him. But he tried again and it worked. Here is a list of error codes.
http://www.adobeexchange.com/resources/19#errors
Have you tried editing the registry key?

**Comment by wanbinkimoon** [comment]
Hi,
I tried a lot of times but the error still come up, what do you mean editing the registry key?

**Comment by cjgammon** [comment]
@bodymovin sent you an e-mail

**Comment by wanbinkimoon** [comment]
Can you send it again, I never receive it :)


On 14 October 2015 at 17:30:48, CJ Gammon (notifications@github.com) wrote:

@bodymovin sent you an e-mail

**Comment by cjgammon** [comment]
I sent an e-mail to bodymovin, regarding submitting the plug-in to the adobe add-ons portal. sorry for the confusion.

**Comment by KyleDEV** [comment]
I'm using cc 2015 and Mac OS X El Capitan

it doesn not show up on window>extentions

**Comment by bodymovin** [comment]
@KyleDEV how did you install it?
Instructions here usually work well.
https://helpx.adobe.com/x-productkb/global/installingextensionsandaddons.html
ignore first part and go directly to "Install third pary extensions"

**Comment by KyleDEV** [comment]
@bodymovin  
just before your answer, I succeeded. 
I find out this link: https://www.adobeexchange.com/resources/27
and that takes me to: https://www.adobeexchange.com/resources/28
I followed the instructions

Although  the command accually was.. 
cd THEPATHofMY_ExMan_root
./Contents/MacOS/ExManCmd --install bodymovin.zxp
./Contents/MacOS/ExManCmd --list all

I think it basically the same as your answer.

Thank you for your help

**Comment by ratchetdrums** [comment]
@bodymovin 

I've tried installing the plugin using the above instructions as well as trying to install it manually, but when I copy the code into terminal, I get an error:

Failed to install, status = -156!

I've tried the troubleshooting area of the Adobe website but can't seem to find this error anywhere. 
I've edited the registry key.

Can you please explain the installation process as if I am 5 years old!

I'm using AE2015 on OSX Yosemite.

**Comment by bodymovin** [comment]
@ratchetdrums that error usually means the zxp file is missing or corrupted.
can you copy the command you are running to install it?

If you want to try it manually, you can follow instructions on this video:
https://vimeo.com/144533677
they are in spanish but you can follow them visually :)

**Comment by ratchetdrums** [comment]
Ahh I've got it working now, thank you for that video link :)

I hadn't renamed the extension folder in the CEP extensions to 'bodymovin'

**Comment by Klustre** [comment]
You can have a look at this [ZXP Installer](zxpinstaller.com). And the extension seems to load perfectly fine without debug mode on (CC14 & 15), since it's signed. I was wondering why you ask the user to turn on debug mode?

**Comment by bodymovin** [comment]
@Klustre nice! I didn't know about it. I'll try it out.
I ask to set debug mode to tru because if you install it manually, you need debug mode for it to work.

**Comment by Klustre** [comment]
@bodymovin Actually as long as it's signed and none of the files are changed by the user, you can simply copy an extension's root folder to the extensions folder and it works, without setting debug mode to true.

**Comment by bodymovin** [comment]
@Klustre I'm not sure that is enough. I've received many mails telling me the extension was visible on the menu but wouldn't open. When they added the debug mode, it started working.
But I'll look further into it.

**Comment by Klustre** [comment]
@bodymovin What I've found is that it depends on how the ZXP is being extracted. On OSX when extracting the ZXP using The Unarchiver, everything runs just fine. But when changing .zxp to .zip and extracting it with the native unzipper corrupts the package and therefore it shows up in the menu, but doesn't work. I'd be happy to hear your findings!

**Comment by mcpdob** [comment]
Confirmed had the same ting on OSX ElCaptain you need to use a 3rd party extractor.

**Comment by bgkillertavu** [comment]
Hey there,

I followed the tutorial you shared : https://vimeo.com/144533677
Everything looks fine except that the "Extensions" Tab doesnt show up in "Window". Anyone ?...

Thx a lot,

**Comment by Klustre** [comment]
@bgkillertavu Which After Effects version are you using?

**Comment by bgkillertavu** [comment]
CS6 and CC v.12.2.1.5
I've changed both plist and checked them.

Should i try with CC2015 ?

**Comment by bgkillertavu** [comment]
It works just fine with CC15...

**Comment by Klustre** [comment]
@bgkillertavu Extensions have been supported only since AE CC14, so that's why. And Extension Manager has been killed, also never supported AE. Use the ZXP Installer as noted a few posts up.

**Comment by etx** [comment]
I was getting the -403! error with ExManCmd also. 

I unzipped the ZXP file and moved the resulting folder into /Library/Application Support/Adobe/CEP/extensions/ and then the plugin worked for me. 

I'm on OSX 10.9 w/ AE CC 2014

**Comment by wanbinkimoon** [comment]
still open? nobody fixed this?

**Comment by Klustre** [comment]
@wanbinkimoon Do you mean none of the above options worked for you?

**Comment by bodymovin** [comment]
@wanbinkimoon it's available on the adobe addons store.  
[https://creative.adobe.com/addons/products/12557](https://creative.adobe.com/addons/products/12557)  
If that doesn't work for you and need to do it manually I'd suggest using instructions on this video.  
[https://creative.adobe.com/addons/products/12557](https://vimeo.com/144533677)  
They are in spanish but you can follow them visually.

**Comment by LucianParaian** [comment]
Hello. 
I've got a similar problem. It doesn't show in AE. (Window>Extensions)
Extension is installed, shows in extension manager. I retried manually as well following the options suggested here. Still no results. (AE CC 2015.2 - on Win 10)

Thank you.

**Comment by ZachSaucier** [comment]
It lets me add bodymovin through the addons store but doesn't seem to be syncing with AE.

When I try install it manually, it gives me this error when I try to open the .zxp file:

<img src="http://i.imgur.com/Qm5pWQK.png"/>

**Comment by shaneparsons** [comment]
> it's available on the adobe add ons store
> 
> https://creative.adobe.com/addons/products/12557.

This link was working recently, now i'm getting an error message, and am unable to find bodymovin anywhere.

**Comment by bodymovin** [comment]
Yes, no idea what happened, it disappeared completely from the addons store.
I'm trying to find out what is going on.

**Comment by shaneparsons** [comment]
I don't know if it helps, but I'm able to find it at `https://creative.adobe.com/addons/patches/29687` when i'm logged in. The fact that it's at *patches* rather than *products* make me think something may have gone wrong with an update or something.

**Comment by l3omtz** [comment]
so if i install it manually successfully and still don't see extension in the window drop down what do I do????

**Comment by bodymovin** [comment]
@l3omtz can you check in Windows > Extensions ?

**Comment by l3omtz** [comment]
Yeah I'm in AE and at the top I see  Windows but when I click on it there is no Extensions section

**Comment by bodymovin** [comment]
what AE version are you using?

**Comment by l3omtz** [comment]
CC 2015

**Comment by bodymovin** [comment]
@l3omtz os version?

**Comment by l3omtz** [comment]
El Capitan

**Comment by bodymovin** [comment]
someone made a video on how to install it in Mac.
They're in spanish but you can follow them visually.
https://vimeo.com/144533677
let me know if the help.

**Comment by l3omtz** [comment]
lol well good thing I understand spanish, I'll let you know thank you!

**Comment by l3omtz** [comment]
AH! I had to update AE, I SEE IT NOW!!!

**Comment by jvvnsk** [comment]
Hi there,

I.m looking forward to use this incredible extension but unfortunatelly I've encountered some problems. Here is what I did so far:

1. I've tried to install addons via adobe site (totally not working).
2. Extension manager doesnt work at all for AE CC15 it doesn't even show after effects on the left panel and it gives me an error.
3. Exman gives me an -160 error aswell.

Finally I got to the point where manual installation (copying files into CEP folder) caused that "Bodymovin" button finally showed in the after effects menu (screen attached). However clicking the button doesnt do anything and I've edit the regedit (however I'm not sure if I did it properly thats why I'm attaching a screen). I've also check the box "allow scripts to write files and acces network".

I am running AE CC2015 on win7

Thanks for your help.

[url=https://postimg.org/image/hmt66klel/][img]https://s22.postimg.org/hmt66klel/EM_error.jpg[/img][/url]

[url=https://postimg.org/image/mmqmeir19/][img]https://s22.postimg.org/mmqmeir19/inside_AE.jpg[/img][/url]

[url=https://postimg.org/image/5nhnz9ftp/][img]https://s22.postimg.org/5nhnz9ftp/path.jpg[/img][/url]

[url=https://postimg.org/image/8izcjv97h/][img]https://s22.postimg.org/8izcjv97h/regedit.jpg[/img][/url]

**Comment by bodymovin** [comment]
@jvvnsk Hi I'm attaching a screenshot of my reg editor.On the left panel, click on the CSXS.6 folder and on the right panel right click and select new > String value
Also make sure you don't have extra spaces on the name.
Then close AE and restart it.
![regex](https://cloud.githubusercontent.com/assets/11096607/18470693/2c5bd63e-7984-11e6-96a4-cacfcced36ab.jpg)

**Comment by jvvnsk** [comment]
Worked! Thank you very much :)

**Comment by jaramos99** [comment]
Hey All,

First off, incredible plugin! I'm on MacOS El Capitan 10.11.6 running After FX 2015.3, and was able to get the plugin installed manually following the Vimeo link above. Clicking on the extension in Windows > Extension produced no plugin window however. Renaming the plugin folder seemed to do the trick:

~~~/Library/Application Support/Adobe/CEP/extensions/bodymovin~~
~/Library/Application Support/Adobe/CEP/extensions/com.bodymovin.bodymovin

Hope this helps anyone that was having the same issue I was. Cheers and keep animating!

**Comment by Klustre** [comment]
To anyone still having problems with the ZXP: have a look at the [aescripts ZXP installer](http://aescripts.com/learn/zxp-installer/). It has matured and is available to the public. There should be no problems installing any ZXP with it.

@bodymovin Perhaps you want to mention this in readme.md instead of the manual installation description?

**Comment by Ibadnf** [comment]
whether this plugin can work in adobe after effect cs6 ?

**Comment by kiroskirin** [comment]
@Ibadnf Yeah, I agree

**Comment by atherkhan** [comment]
Hi guys,
I have tried everything and still cannot get the extension menu to show up. I'm using Adobe After Effects CS6 on Windows 10. I have tried ZPX installer, aescripts + aeplugins zpx installer, and exman, all of them seem to fail. I have also done manual installation, please look at the attached images. Any help would be highly appreciated.

![Menu](https://cloud.githubusercontent.com/assets/1720271/25987904/b4f0a81a-36aa-11e7-8633-4bc755d3486f.png)
![bodymovin](https://cloud.githubusercontent.com/assets/1720271/25988017/3940c23a-36ab-11e7-8017-102db88b6299.png)
![regedit_1](https://cloud.githubusercontent.com/assets/1720271/25988082/812351a8-36ab-11e7-912a-1054cd003d79.PNG)
![regedit_2](https://cloud.githubusercontent.com/assets/1720271/25988087/8681f4d8-36ab-11e7-9c80-10086116e2f7.PNG)

**Comment by bodymovin** [comment]
Hi, CS6 is not supported. CC2014 and up.

**Comment by clemencegermain** [comment]
Hello everyone,
I have CC, and I can't download the plugin. I tried through Extension Manager : 
<img width="491" alt="screenshot 2017-06-26 17 13 28" src="https://user-images.githubusercontent.com/13901230/27546345-ce522e9e-5a92-11e7-88c9-a83f927932ba.png">

What can i do ?

**Comment by Klustre** [comment]
@clemencegermain 
> **CC2014** and up

You should use the [aescripts installer](http://aescripts.com/learn/zxp-installer/) to install Bodymovin.

**Comment by velask** [comment]
Hello everyone,
After getting -160 and -403 errors using terminal, I used aescripts installer to install bodymovin and succeeded. Now I go to AE window tab and I cannot see extensions tab.
I really want to install this plugin could anyone help?
thx

**Comment by Klustre** [comment]
@velask Bodymovin supports CC2014 and up
