### ISSUE TITLE
Expression support for pickwhipping animated path shapes

### ISSUE THREAD

**Issue by MikeOverbeck** [bodymovin/bodymovin#170]
Hi!
I've noticed that bezier path shapes connected via expressions don't export fully when rendered. The initial shapes are correctly connected at frame 1, but they don't animate together appropriately. This would be really handy when using identical mattes to mask multiple objects. Simple example attached.
Thanks!
[BManimatedPathShape.zip](https://github.com/bodymovin/bodymovin/files/554950/BManimatedPathShape.zip)

**Comment by bodymovin** [comment]
Yes, I'm working on it.
it will be ready by the end of the weekend.

**Comment by bodymovin** [comment]
done!

**Comment by MikeOverbeck** [comment]
Thank you! Sorry for not checking back in on it.
