### ISSUE TITLE
can´t install body movin a effect cc 2014

### ISSUE THREAD

**Issue by nastyrave** [bodymovin/bodymovin#171]
Hi, i have several problems to install bodymovine xtension:

I try with EXmanCmd it gives me the issue : failed to install : -403, 
i don´t find specifically this number on the errors guide.

Then i try with regedit but i don have the folder "CSXS.6" I have .3, .4, .7 but not   .6
I put on CSXS.7 input the player debug mode but nothings happened.

Can anybody help me?
Thanks.

**Comment by bodymovin** [comment]
Hi, can you try with this installer?
it usually works fine.
http://aescripts.com/learn/zxp-installer/

**Comment by nastyrave** [comment]
Ok, ill check it out!

Thanks!!
