### ISSUE TITLE
Can't export font.

### ISSUE THREAD

**Issue by cpmbarcelona** [bodymovin/bodymovin#174]
I can't seem to export a composition when it has fonts.
I tried the different options, with both Glyphs checked and unchecked and in all cases It generates some compositions "bm_charHelper" and "bm_fontHelper" but the export is never complete.
Any idea of what might be happening?
Thanks so much.

Here is a screenshot
![a](https://cloud.githubusercontent.com/assets/3339855/20004510/0b42149a-a28d-11e6-98f9-6ef440db35ee.png)

**Comment by bodymovin** [comment]
can you share the .ae?
it might be some special character it can't export.
also, what version of AE are you using?

**Comment by cpmbarcelona** [comment]
I am using AE CC 2014 on mac.
The file is attached.
[test.zip](https://github.com/bodymovin/bodymovin/files/571415/test.zip)

Thanks no much for the quick answer : )

**Comment by bodymovin** [comment]
I've tried it with cc 2015 and it seems to work.
I'll try to install CC 2014 this afternoon and check it

**Comment by cpmbarcelona** [comment]
That would be much appreciated!
Thanks big time

**Comment by bodymovin** [comment]
Hi, I tried it with a CC 2014 version and it seems to work fine
do you have enabled "Allow Scripts to Write Files and Access Network"?

**Comment by cpmbarcelona** [comment]
Hmmm, that is strange because I do have that option enabled.
Any other idea of what may be causing this bug?

**Comment by bodymovin** [comment]
I can't think of anything in particular
do you get any error at all?

**Comment by cpmbarcelona** [comment]
I don't get any errors, but I never get the message "render finished" as I do when the composition has no fonts. I am sharing with you 3 screenshots of the steps. As you can see, on the screenshot C, two compositions are generated "bm_charthelper" and "bm_fontHelper". Is this normal? I also get the message " Select font families and font paths if necessary". Then I click on the red folder to try to select the font but it doesn't allow me to select any font.
On screenshot B I tried several options ( google font, typekit, url, none) but I get the same result for all of them...

![a](https://cloud.githubusercontent.com/assets/3339855/20211422/c23b690a-a7fe-11e6-9ee6-382078a8dd5d.png)
![b](https://cloud.githubusercontent.com/assets/3339855/20211423/c244967e-a7fe-11e6-87c1-2e03b8dec914.png)
![c](https://cloud.githubusercontent.com/assets/3339855/20211424/c24e6b86-a7fe-11e6-8044-f4e291a94a71.png)

**Comment by cpmbarcelona** [comment]
Hi again, any feedback on this?
Thanks so much.

**Comment by bodymovin** [comment]
Not yet. I don't have a Mac to try it though.
I'd guess it might be related to the CC version and OSX, but I'm not sure.
How did you install the plugin?

**Comment by cpmbarcelona** [comment]
I followed this tutorial:
https://vimeo.com/144533677

**Comment by cpmbarcelona** [comment]
Hi there.
I have updated to the latest AE version (cc 2017) and now it works.
Thanks so much for your time and effort, your plugin it a huge life saver for my work.
Best regards.

**Comment by bodymovin** [comment]
Nice
sorry I haven't been able to help you

**Comment by cpmbarcelona** [comment]
You helped a lot already : )
