### ISSUE TITLE
Frame by Frame animation detail in JSON

### ISSUE THREAD

**Issue by mdagostino** [bodymovin/bodymovin#175]
Hi, 

I'm just start working in a iOS & Android player library in an open source project. 

My question is: 

* Can I export the animation Frame by Frame? This is resolve many problems with the easing reader.

Thanks.
Dago.

**Comment by bodymovin** [comment]
hi
the exporter doesn't export the animation frame by frame, but you could eventually build an additional tool to get the exported data and save the html on each frame as part of a large svg spritesheet, ofr example.
