### ISSUE TITLE
Can't see the desired result. :(

### ISSUE THREAD

**Issue by vj1557** [bodymovin/bodymovin#176]
I rendered out a composition which had a shape layer and a layer with Trapcode 3D stroke and Trapcode shine.  The output only shows me the shape layer, the 3D stroke layer is completely ignored? Is there a walk-around this?

**Comment by bodymovin** [comment]
Hi, those effects are not supported.
For now only fill, stroke and tint are partially supported.
Trapcode 3d is too complex to implement and also to render on real time data.
sorry :/
