### ISSUE TITLE
Chrome Issue?

### ISSUE THREAD

**Issue by mrsamse** [bodymovin/bodymovin#177]
Hi there

I have a problem with this [data.json](https://github.com/bodymovin/bodymovin/files/589516/data.json.zip
)  but only in chrome. At the end of the animation a rectangle "jumps" around. In Safari and Firefox everything works perfectly.

Here my initialization code:
```javascript
$(function() {
	var animData = {
		container: document.getElementById('logo'),
		renderer: 'svg',
		loop: false,
		autoplay: true,
		path: 'js/data.json'
	}
	var anim = bodymovin.loadAnimation(animData);

	$('#logo').hover(function(){
		bodymovin.setDirection(-1);
		anim.play();
	}, function(){
		bodymovin.setDirection(1);
		anim.play();
	});
});
```

Can you help me?

Greetings
Sam

**Comment by bodymovin** [comment]
Can you share a link with the issue?
I'm trying your code and it seems to work fine on Chrome.

**Comment by mrsamse** [comment]
Here the link: http://dev.heidis-english.ch/

**Comment by bodymovin** [comment]
I see the animation working fine on that link as well.
Is there any particular configuration I might be missing?
are you trying it on a mac, windows?

**Comment by mrsamse** [comment]
Hmmm well at home where I use windows and chrome it works fine.
At my workplace I use a mac and the newest chrome and there I see the issue.

**Comment by bodymovin** [comment]
I'll try to check it on a mac and see if I can reproduce it

**Comment by bodymovin** [comment]
I haven't been able to reproduce the issue even on a Mac, but I've found today that chrome is having issues with resized svgs on the latest version.  
Can you try this player to see if it fixes it?  
[bodymovin.zip](https://github.com/bodymovin/bodymovin/files/593406/bodymovin.zip)

**Comment by mrsamse** [comment]
I tried your new js file, but I still got the error.
I have recorded my desktop to show you how it looks like:  [error.mov.zip](https://github.com/bodymovin/bodymovin/files/594763/error.mov.zip)
I hope it will help you to understand the problem.

**Comment by bodymovin** [comment]
I'm not sure I can see the issue clearly. Is it that blinking line next to the last "h"?
If it is, can you try pausing the animation and inspecting the svg with chrome dev tools?

**Comment by mrsamse** [comment]
Yes it is that blinking line next to the last "h". I've tried inspecting it, but everything looks normal to me, but I am not a SVG specialist...

**Comment by bodymovin** [comment]
That looks like a chrome rendering issue.
I see you have a media query that looks like this
@media screen and (min-width: 768px)
.logo-wrapper .logo {
    height: 123px;
    width: 400px;
    overflow: hidden;
}
so the container div doesn't have the same ratio as the svg.
Can you try giving the container the same ratio as the svg?
something like height:123px; width:474px;

**Comment by mrsamse** [comment]
Sorry for the late reply, but I wasn't at my workplace at the end of the last week.

It didn't work... I still have the same problem...
