### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by omphteliba** [bodymovin/bodymovin#178]
Thanks for your great work! I got the demos working, but my own file isn't. 
This is what the Webdev-Tools in Chrome tell me:

`Uncaught TypeError: Cannot read property 'length' of undefined(…)
completeText @ bodymovin.js:1973
completeLayers @ bodymovin.js:1390
completeLayers @ bodymovin.js:1386
completeData @ bodymovin.js:1809
checkFontsLoaded @ bodymovin.js:7667
(anonymous function) @ bodymovin.js:7676
AnimationItem.configAnimation @ bodymovin.js:7657
xhr.onreadystatechange @ bodymovin.js:7500`

Here the link to the animation
http://dev.fact-finder.de/test/bodymovin.html

**Comment by bodymovin** [comment]
hi
could you share the .ae with me?
there seems to be a property missing and I'm not sure why.

**Comment by omphteliba** [comment]
I will share it gladly. 
[Composition_v2.zip](https://github.com/bodymovin/bodymovin/files/591913/Composition_v2.zip)

**Comment by bodymovin** [comment]
Is the composition name Composition_Phone? 
there seems to be many files missing.

**Comment by omphteliba** [comment]
Yes there is. I can provide the missing files. But even with the files present the same error occures and the animation won't play.

**Comment by cyraxx** [comment]
I'm having the same issue as soon as there are any text layers. If I change those layers to invisible it works fine. I can share the .ae as well if needed.

**Comment by bodymovin** [comment]
yes, can you send me the ae file?

**Comment by cyraxx** [comment]
Here's a minimal example that causes the error.
https://dl.dropboxusercontent.com/u/12129812/bm-texttest.aep

**Comment by bodymovin** [comment]
I can't reproduce the issue with those projects.  
What OS and AE version are you using?

**Comment by cyraxx** [comment]
I'm using the latest AE (CC 2017) on macOS Sierra with the Bodymovin extension downloaded from GitHub a few days ago.
Would you like me to upload the generated JSON file as well?

**Comment by bodymovin** [comment]
yes, please, so I can check if it is the same issue than @omphteliba

**Comment by cyraxx** [comment]
Here you go. https://dl.dropboxusercontent.com/u/12129812/bm-texttest.json

Thanks for taking the time to look into this!

**Comment by bodymovin** [comment]
I'm pretty sure I know what's the issue.
Do you have AE installed in a language that is not English?

**Comment by cyraxx** [comment]
Yes, my AE is in German (and @omphteliba's probably is too since he's also German).

**Comment by bodymovin** [comment]
yes. That's probably it. I'll upload a fix in a minute and let you know.

**Comment by bodymovin** [comment]
done! can you try and see if it works?
you need to update the extension

**Comment by cyraxx** [comment]
That did it! Works for me now 👍

**Comment by bodymovin** [comment]
nice! thanks for your help!

**Comment by omphteliba** [comment]
Thanks, works for me too :)
