### ISSUE TITLE
Safari 3D transform causing SVG to render blurry

### ISSUE THREAD

**Issue by JackMoGraphics** [bodymovin/bodymovin#179]
Rendered SVG ok from After Effects, works ok as a stand alone HTML. 

When added to the website it causes the SVG to become a large blurred out block. When 3D transform is removed it removes the blurriness and restores it completely to normal.

Works fine in Firefox, Chrome etc just Safari doesn't like 3D transform. Any ideas as to why? What is 3D transform doing?

Thanks
Jack

**Comment by JackMoGraphics** [comment]
width: 100%; height: 100%; transform: translate3d(0px, 0px, 0px); transform-origin: 0px 0px 0px;

**Comment by bodymovin** [comment]
I use translate3d to create a new layer independent from the rest of the page so it can be hardware accelerated and hopefully doesn't trigger relayout of the rest of the page.
I never noticed it caused blurriness in safari.
Do you have a link I can check?

**Comment by JackMoGraphics** [comment]
Makes sense just not sure why it's only messing with Safari..

Bare with me on that one, will get back to you about a link.

As always thanks for the speedy reply!
