### ISSUE TITLE
Play/preview the animation after render?

### ISSUE THREAD

**Issue by Kentained** [bodymovin/bodymovin#181]
Pretty juiced about the possibilities with bodymovin on AE. I installed this morning without a problem. Ran it with a small .AEP and rendered out a.JSON, also seemingly error-free. However, I'm unable to  view or preview the animation. When I try to preview I just get a blank gray box. When I try to run the player I keep getting prompted to "Get the player" I did quit and restart AE after install and tried opening the .JSON in 3 browsers, but just get code. These ".SVG/.JSON/etc...)waters are new to me so if I'm missing something fundamental, any light you can shed is good light. Thanks.

![bodymovin1](https://cloud.githubusercontent.com/assets/23527541/20396293/54948e5c-acab-11e6-99be-f5aa2d4b73b7.png)
![bodymovin3](https://cloud.githubusercontent.com/assets/23527541/20396292/5491f764-acab-11e6-9adf-89553477a772.png)
![bodymovin2](https://cloud.githubusercontent.com/assets/23527541/20396291/5491fb92-acab-11e6-84f4-b988d4002610.png)
![bodymovin4](https://cloud.githubusercontent.com/assets/23527541/20396336/76f9127e-acab-11e6-8324-a44904b99b7b.png)

**Comment by bodymovin** [comment]
Hi, a json file is only the exported data.
You need the javascript player (bodymovin.js) to reproduce it on your browser. 
I recommend that you check the examples on the main page.

For a quick preview of your animation, click the gear button next to your comp and check the Demo box and you'll get a demo.html file together with the json file that you can double click to see it on your browser.

let me know if this helps.

**Comment by TomHoenderdos** [comment]
I was wondering the same thing as @Kentained. Can i assume the Preview functionality is broken? 
And is the 'snapshot' functionality you speak of in the Readme still available?

**Comment by alex-van-zijl** [comment]
Hey guys, as far as I noticed, the Preview button will not actually play a preview, but you can use the timeline to scrub through it.

1. Click on 'Current Render' to get your latest render.
2. Drag the circle to actually preview the animation.

![preview](https://cloud.githubusercontent.com/assets/16916321/22841537/000f89ee-efa0-11e6-8341-7259b89a11b5.png)

And mentioned by @bodymovin, if you want to preview the animation in your browser, first click on the gear icon, then scroll to the bottom and select 'Demo'. The html files that's been generated should show you the final animation, looping.

![demo1](https://cloud.githubusercontent.com/assets/16916321/22841625/4e825a3e-efa0-11e6-807f-f0434e8d2315.png)

![demo2](https://cloud.githubusercontent.com/assets/16916321/22841627/5250e54a-efa0-11e6-9259-c570f9e74de8.png)

Good luch!
