### ISSUE TITLE
Corner Pin not working

### ISSUE THREAD

**Issue by omphteliba** [bodymovin/bodymovin#182]
Hej,

I am not sure if this isn't supported or if it is a bug: 

http://dev.fact-finder.de/test/bodymovin.html

On top you see the export form bodymovin and below the animation as it should be. The map to the right and the text on top of the iPhone have both the "Corner Pin" effect.

**Comment by bodymovin** [comment]
Unfortunately, the corner pin effect is not supported.
sorry :/

**Comment by omphteliba** [comment]
That's too bad. Thanks for the info!
