### ISSUE TITLE
Change path and filenames

### ISSUE THREAD

**Issue by omphteliba** [bodymovin/bodymovin#183]
Hej,
could you please add a possibility to change the filenames and relative of the images? 
At the moment I change both in the JSON file and rename the images by hand.

Thx!

**Comment by bodymovin** [comment]
you can change the relative path of images if you pass a property "assetsPath" to the animation params.
Regarding changing image filenames, is more complicated because I need to build a new ui.
What I'm thinking of doing is using the layers names as filenames.
would that work for you?

**Comment by omphteliba** [comment]
> What I'm thinking of doing is using the layers names as filenames. would that work for you?

Sounds good, as long as I can change it.

Or take the name of the comp and add 0, 1, 2... That would be enough already. 

My CMS uses one folder to keep all the images etc. in it, so I need a way to have unique filenames for the animations.

**Comment by omphteliba** [comment]
Regarding "assetsPath": how do I use this param in a div? 

`<div class="bodymovin" data-bm-path="/files/milch-shop.json" data-bm-renderer="svg" data-bm-assetsPath="./"></div>`

This didn't work.
