### ISSUE TITLE
Subcomp size not respected in iOS Mobile Safari

### ISSUE THREAD

**Issue by omphteliba** [bodymovin/bodymovin#186]
Hej,

I have a comp over an image. iOS Mobile Safari shows the content outside the boders of the comp:

http://dev.fact-finder.de/test/bodymovin-milk.html

In Chrome everything os fine.

I already tried pre-composing the composition, but still the same problem.

**Comment by bodymovin** [comment]
I'm not sure I follow how it should behave. As far as I can see, it seems to exceed the borders on chrome as well. Could you send a screenshot comparing both cases?
Nevertheless, have you tried adding a mask in AE to the precomp?

**Comment by omphteliba** [comment]
Here how it should look like (and how it looks for me in Chrome on the desktop):
![milk_right](https://cloud.githubusercontent.com/assets/196336/20618271/63e7902c-b2ee-11e6-8474-0a5e3c9a8171.PNG)

And here how it looks like on the iPhone (yes, thats nearly the same frame, even the background is wrong):
![img_0711](https://cloud.githubusercontent.com/assets/196336/20618358/d4f190a6-b2ee-11e6-8e76-2e40161daa83.PNG)
