### ISSUE TITLE
Support for Hue/Saturation

### ISSUE THREAD

**Issue by celliGit** [bodymovin/bodymovin#187]
Does BodyMovin support color effects from within AE ? I have some comps that are using Hue/Saturation effect and only using the Hue controls, and when they are output, it looks like the Hue/Saturation is not rendered. I tried SVG and Canvas rendering.

Also I am using a shape effect 'Wiggle' but it doesn't look like that is rendering.

Is there a way to 'break apart' some of the effects in after effects to allow them to render with BodyMovin in HTML5 in Canvas or SVG ?

**Comment by bodymovin** [comment]
Hi, no, it doesn't suport them yet.
I'll look into it to see how hard it would be.
Wiggle is also not supported. Because of the nature of it's randomness, I don't think it will ever be supported.

**Comment by mmwotion** [comment]
For the wiggle you can convert expression to keyframes which works a treat. Animation > Keyframe Assistant > Convert Expression to Keyframes

**Comment by zhengs** [comment]
Is the decision not to support hue/saturation changes in the short term? If so, would it be possible to let bodymovin take transformed images through CSS (basically, let CSS do all the image transformations and let bodymovin do the animation).

**Comment by bodymovin** [comment]
@zhengs There are several ways you can approach this.
You can name image layers in AE with a "." (dot) and they will get exported as classes so you can manipulate them with css.
Or you can name them with a "#" and target them with svg filters for example.
Another option, would be to provide a different source folder in case you want to render different images server side.
Another hacky way would be to replace image sources in the rendered svg dom and provide your own.

**Comment by zhengs** [comment]
Hey @bodymovin, thanks a lot for your suggestions.

I've managed to implement this by using the first approach you mentioned (i.e. manipulate AE layers with a "." dot using SVG filters). Below is an example of implementing blur and brightness changes, FWIW.

Note that, my approach has to happen after the DOM is loaded, and I rename each layer using alias to help me figure out the original effect parameters in AE, e.g. sat_n100 means saturation set to -100.

So far, the approach works fairly well. I am thinking, could this be viable solution to make Bodymovin able to support AE effects (at least the ones for which we can find a SVG equivalent implementation)? 
```

    var anim;

    anim = bodymovin.loadAnimation(params);
    anim.addEventListener('DOMLoaded', function() { 
      var defs = document.querySelector('#bodymovin svg defs');
      var jpeg;
      var img;
      jpeg = document.querySelector('.sat_n100 .jpeg');
      jpeg.innerHTML = jpeg.innerHTML + '<filter id="sat_n100"><feColorMatrix type="saturate" values="0"></feColorMatrix></filter>';
      img = document.querySelector('.sat_n100 image');
      img.setAttribute('filter', 'url(#sat_n100)');

      jpeg = document.querySelector('.sat_n100_lt_31_blr_50 .jpeg'); 
      jpeg.innerHTML = jpeg.innerHTML + '<filter id="sat_n100_lt_31_blr_50"><feGaussianBlur in="SourceGraphic" stdDeviation="50"/><feColorMatrix type="saturate" values="0"></feColorMatrix><feComponentTransfer><feFuncR type="linear" slope="1.31"/><feFuncG type="linear" slope="1.31"/><feFuncB type="linear" slope="1.31"/></feComponentTransfer></filter>';
      img = document.querySelector('.sat_n100_lt_31_blr_50 image');
      img.setAttribute('filter', 'url(#sat_n100_lt_31_blr_50)');
    });
```

**Comment by bodymovin** [comment]
Hi, yes, some effects are already supported using svg filters.
But since filters affect performance significantly, it doesn't make much sense to mix animation and filters in a single svg element for now.
