### ISSUE TITLE
Expression Examples

### ISSUE THREAD

**Issue by perky** [bodymovin/bodymovin#188]
Is there an example of using expressions to drive properties from the browser? I've seen one that uses CSS classes to drive color, but I'm not sure if it's possible to drive other properties from browser-side javascript.

**Comment by bodymovin** [comment]
I'm not sure I follow what you want to achieve. Do you want to be able to target specific elements to add style or behavior to them?
Or is it related to After Effects properties expressions

**Comment by perky** [comment]
I want to know if it's possible to affect variables in AE expressions from javascript, for example changing to thickness of a stroke depending on where the mouse is.

**Comment by bodymovin** [comment]
you can't edit variables hard-coded inside an expression.
but if you have a variable linked to a slider control within an expression, you can edit the value of that slider control and it will update the expression.

**Comment by perky** [comment]
Ah ok, is there an example of editing the slider control? And is it possible using the canvas renderer?

**Comment by bodymovin** [comment]
yes, it will work using the canvas renderer.
For now, there is no official API for doing this.
You need to traverse the animation data object to find that slider and update the value manually.
If you have a link with a WIP I can help you figure out how to do it.
