### ISSUE TITLE
Skew on shapegroup

### ISSUE THREAD

**Issue by DaanDirk** [bodymovin/bodymovin#189]
Hi!
I'm exited about going to use bodymovin soon in a nice project.

I was wondering whether skewing of a shapegroup is going to happen soon?
I'm want some isometric shapes to appear and doing that with skewing is convenient 
(otherwise I would have to make paths of my rectangles and i'd rather not).
Or do you know a way to work around this problem?

Hope to hear from you.
Regards,
Daan

**Comment by DaanDirk** [comment]
Hmm, seems like some nesting of shapegroups was weirding up the skewing. Skewing everything below in the parent shapegroup. 
Unnesting and reworking the order. fixes it. 
I'm just so used to using too much shapegroups, dôh!

**Comment by bodymovin** [comment]
Could you send me an .ae with the issue?
skewing should be supported

**Comment by DaanDirk** [comment]
It happened when i used a stroke below several shapegroups which were skewed and nested in another shapegroup. Will mail you shortly.

**Comment by DaanDirk** [comment]
I see now that the 4.4.26 version has it fixed. :)
You're so quick, bugs are fixed before i can properly discover them.
I was still on 4.4.24. here. Sorry for that.

Would be nice to have a version number in the plugin itself!
