### ISSUE TITLE
Use bodymovin with rubberhose 1.06

### ISSUE THREAD

**Issue by jjhan1986** [bodymovin/bodymovin#190]
I created a minimal rubberhose using v1.06 and exported it via bodymovin. 
But I'm having trouble getting it rendered in browser.
Bodymovin returns "Uncaught TypeError: Cannot read property 'content' of undefined"
<img width="791" alt="bodymovin_error" src="https://cloud.githubusercontent.com/assets/4715740/20793110/8a7580c0-b819-11e6-8ace-fe8ea050b3bc.png">

The issue seems to be the exported data.json. The structure is different from the Codepen [example](https://codepen.io/airnan/pres/oLLvMw)

I attached my data.json and ae file. It would be really appreciated if you could shed some light on this.

[data.json.zip](https://github.com/bodymovin/bodymovin/files/624446/data.json.zip)
[test.aep.zip](https://github.com/bodymovin/bodymovin/files/624447/test.aep.zip)

**Comment by bodymovin** [comment]
Rubberhose 1.0 is not supporter because expressions are encrypted.
RH 2 will be supported and AFAIK is just around the corner.

**Comment by MB00design** [comment]
Hi . I created animated character in after effects (11/sec) .and  exported to json with bodymovin . But my json file is too heavy for my work ( 4 MG) . Why that happend and how can I fix it????
Please help me....

**Comment by bodymovin** [comment]
@MB00design There is a new version coming that reduces filesize significantly.
But regarding your case, keep in mind that gzipping the file on your server will reduce the animation size significantly.
