### ISSUE TITLE
Demo.html works, but data.json doesn't seem to work

### ISSUE THREAD

**Issue by celliGit** [bodymovin/bodymovin#192]
Hi BodyMovin,

I can see my bodymovin work here:
http://rarecutcreative.com/body/demo.html

But if I try and play my data.json file, it doesn't seem to work (see here)
http://codepen.io/celli/pen/aBJgoq

Am I using the correct  .js code to get the JSON file to work ? or is there something wrong with my JSON file ? I've tried some many different options, but none seem to work.

**Comment by bodymovin** [comment]
Hi, you're having Cross Origins issues.
You need to setup your server to accept requests from codepen.io domain.  
check the chrome console and you will see the error.
here is a link explainig the issue and how to solve it.
http://stackoverflow.com/questions/20035101/no-access-control-allow-origin-header-is-present-on-the-requested-resource

**Comment by celliGit** [comment]
Hi bodymovin, You are absolutely right, thanks! That is solved, but I have another strange problem. You see this doesn't seem to hold the color information http://codepen.io/celli/pen/aBJgoq but the html demo export does here: http://rarecutcreative.com/body/demo.html

What do you think the problem is ?

**Comment by bodymovin** [comment]
Your animation is version 4.4.24 and the player is version 4.1.3
the player should always be the same or older than the animation

**Comment by celliGit** [comment]
ahh, perfect. That solves it ! Thanks, Awesome tool !
