### ISSUE TITLE
Rendering Not Working (please help)

### ISSUE THREAD

**Issue by whrellieck** [bodymovin/bodymovin#193]

**Comment by whrellieck** [comment]
Good day Guys,

I'm just wondering why i'm stuck in rendering
![i427 cimgpsh_orig](https://cloud.githubusercontent.com/assets/24312138/20827011/d74a5d4a-b8a9-11e6-9a3b-0ce09fcb6905.png)
Please help,

Thanks!

**Comment by bodymovin** [comment]
Did you check on your Preferences "Allow scripts to write files and access Network"?
