### ISSUE TITLE
Uncaught TypeError: Cannot read property 'layer' of undefined

### ISSUE THREAD

**Issue by BigMacAttack** [bodymovin/bodymovin#194]
Really excited by the prospect of using this, however I'm encountering a couple of issues.

I'm able to preview my rendered compositions within the AE Bodymovin Extension, however when attempting to view the animation within Chrome, either via the embedded demo.html or with my own page, I get the following javascript error within the console:

`Uncaught TypeError: Cannot read property 'layer' of undefined`

Attached is the data.json for the composition.
[composition.zip](https://github.com/bodymovin/bodymovin/files/627345/composition.zip)

Note: The composition has other problems that eventually need to be solved (perhaps related to the current limitations of the Bodymovin extension, I don't know), but for now I'd at least like to understand why I can't view it in Chrome despite being able to preview it within the extension.

**Comment by bodymovin** [comment]
I think you're linking expressions to a composition that is not selected as part of the export: "_MainControlComposition"
To export extra compositions that are not in the Main comp render tree, you need to select the settings gear next to the comp, check Extra Comps and select the extra comps needed.

**Comment by BigMacAttack** [comment]
Yup, that's done it. However now I'm getting a different error, which I'll report as a separate issue.

**Comment by noor3** [comment]
Hello,

I am using duik plug in for rigging as well as 3d camera and whenever I try to export nothing
 pops up in the demo.html file, I was wondering are these features supported?

**Comment by bodymovin** [comment]
Hi, can you share the .aep so I can take a look?
