### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by BigMacAttack** [bodymovin/bodymovin#195]
Following the advice given in #194, the 'layer' error has gone away. However, now I'm getting a different error:

`Uncaught TypeError: Cannot read property 'length' of undefined`

Attached is the latest data.json and images for the composition:
[composition_v2.zip](https://github.com/bodymovin/bodymovin/files/628887/composition_v2.zip)

Unlike in #194, this time I can't see the preview within the BodyMovin extension once I link to the extra composition.

**Comment by bodymovin** [comment]
It seems you're importing an extra comp that has precomps nested in it.
Unfortunately that is not supported yet.
Is there a specific case where you need external comps to have nested precomps in it?

**Comment by RobinSiep** [comment]
Hi, 
I'm running into the same issue trying to export one of the icons from this pack: https://videohive.net/item/500-animated-icons/5586340.

I don't have a lot of AE experience but looking at my `data.json` it seems like the composition of the icon I want to export links to a different composition that controls the global color scheme in the project.

When I use the export extra compositions feature to include this composition it did solve the issue mentioned in https://github.com/bodymovin/bodymovin/issues/194 but follows up with this issue just like BigMacAttack mentioned.

Is this still not supported and therefore indeed the same issue? Is it somehow possible to prevent this issue in After Effects itself?

Thanks in advance.

**Comment by bodymovin** [comment]
Recursive compositions might break.
Can you share the .aep so I can take a look?

**Comment by RobinSiep** [comment]
I've sent you an email with the .aep. Because of the licensing of the pack I though it'd be best not to share it here.

Thanks for your help so far!
