### ISSUE TITLE
Deselecting the 'Extra Comps' radio option does not disable the external comps check

### ISSUE THREAD

**Issue by BigMacAttack** [bodymovin/bodymovin#196]
Whether intentional or not, deselecting the 'Extra Comps' radio option within the export options for a composition, does not disable the check if expressions point to external comps. It appears that any selected comps within the 'Extra Comps' drop down will still get checked.

**Comment by bodymovin** [comment]
I'll look into it. Thanks!

**Comment by bodymovin** [comment]
fixed
