### ISSUE TITLE
bodymovin.js:8002 Uncaught TypeError: Cannot read property 'u' of undefined

### ISSUE THREAD

**Issue by TomHoenderdos** [bodymovin/bodymovin#197]
So i have been playing for the last couple days with bodymovin. And I can't seem to get it working. 
And before you ask me, I have a After effects project I can't share unfortunately :( ... 

Here is my data.json and demo.html. I run this via a local Python SimpleHTTPServer ;)

Gist: https://gist.github.com/TomHoenderdos/86c0fcf5071dd0ae2dc48b908610857a

I have been digging through the code to find where the problem lies, and all I now know is that within the code beneath here is when I comment `this.renderer.searchExtraCompositions(animData.assets);` then everything works fine!
```javascript
AnimationItem.prototype.configAnimation = function (animData) {
    if(this.renderer && this.renderer.destroyed){
        return;
    }
    //console.log(JSON.parse(JSON.stringify(animData)));
    //animData.w = Math.round(animData.w/blitter);
    //animData.h = Math.round(animData.h/blitter);
    this.animationData = animData;
    this.totalFrames = Math.floor(this.animationData.op - this.animationData.ip);
    this.animationData.tf = this.totalFrames;
    this.renderer.configAnimation(animData);

    if(!animData.assets){
        animData.assets = [];
    }
    if(animData.comps) {
        animData.assets = animData.assets.concat(animData.comps);
        animData.comps = null;
    }
    this.renderer.searchExtraCompositions(animData.assets); // <!-- Comment this line!

    this.layers = this.animationData.layers;
    this.assets = this.animationData.assets;
    this.frameRate = this.animationData.fr;
    this.firstFrame = Math.round(this.animationData.ip);
    this.frameMult = this.animationData.fr / 1000;
    this.trigger('config_ready');
    this.imagePreloader = new ImagePreloader();
    this.imagePreloader.setAssetsPath(this.assetsPath);
    this.imagePreloader.setPath(this.path);
    this.imagePreloader.loadAssets(animData.assets);
    this.loadSegments();
    this.updaFrameModifier();
    if(this.renderer.globalData.fontManager){
        this.waitForFontsLoaded();
    }else{
        dataManager.completeData(this.animationData,this.renderer.globalData.fontManager);
        this.checkLoaded();
    }
};


```

Hopefully this can help you solve a bug or you can help me solve my 'export' problem ;)

**Comment by bodymovin** [comment]
have you selected some of your comps to be exported as Extra Comps?  
Those extra comps are only needed if they are not part of your render tree and are usually only needed if you have expressions referencing them.
Nevertheless, I'll look into the issue. It seems to be related to those comps having external images.
thanks!

**Comment by TomHoenderdos** [comment]
Yes i have selected some of my comps to be exported. I think i have selected all the comps that needs to be referenced.. Is the extra comps only necessary when i reference it from an expression? Not when the comp is used in the timeline?

**Comment by TomHoenderdos** [comment]
So i deselected a lot of comps that were not referenced with a expression and now without changes to your code it all works! Thanks for the tip!
I see some visual glitches with Trim paths, should I submit a bug report for that?

**Comment by bodymovin** [comment]
yes, please. If you can share an .ae also it would be great.
