### ISSUE TITLE
Compositions not showing in Bodymovin

### ISSUE THREAD

**Issue by itsthehamza** [bodymovin/bodymovin#198]
<img width="1039" alt="screen shot 2016-12-09 at 5 33 54 pm" src="https://cloud.githubusercontent.com/assets/24479172/21054293/b1dfcdc4-be35-11e6-827b-7bf7a43be31b.png">

I select the compositions to render but nothing show in the preview and nothing renders.
Any quick help for this? deadline for the project is tomorrow.

**Comment by bodymovin** [comment]
Preview works with animations already rendered.
Do you want to share the .ae file so I can take a look?

**Comment by itsthehamza** [comment]
Is there a way I can email it to you?
I'm 0 in coding, I don't know how to upload it to here.

**Comment by bodymovin** [comment]
sure
hernantorrisi@gmail.com
