### ISSUE TITLE
Made After Effects Unusable after installation

### ISSUE THREAD

**Issue by anitadavinci** [bodymovin/bodymovin#20]
After the installation of this plugin, After Effects started crashing and stopped recognizing the source files of the composition. I've been on this computer for the last two weeks, it's brand new and AE had never ever crashed before on this machine. I'm an experienced user of After Effects (6+ years), and I can tell this won't do any good to your machine or your OS. 

Do not install this. 

I also uninstalled and erased all the folders and files of the plugin, restarted the machine, and AE is so slow as it had never been before... I'm working on the same project of the previous week and it was running ok. I guess I'll have to either restore the system or uninstall/install After Effects again. Pfffffff.

**Comment by bodymovin** [comment]
@anitadavinci Hi, what OS are you working on?
Would you mind sharing the project you had problems with?
I've never experienced this behaviour.

**Comment by anitadavinci** [comment]
I'm on Windows 7 Pro, After Effects CC 2014. It's not only one project, it just turned the software almost unusable. It's slow, even on a new project, and although I have opened some other projects I had worked on before, it's the same behaviour. I'm sorry, I had high hopes for this plugin, but now I have wasted almost an entire afternoon, between installation, removal, restaring the software and the machine, and testing the projects. I'll have to do some extra hours tonight if I want to keep up with my work :(
And I'm not even counting yet the time I'll have to invest in the system restoration and the reinstallation of AE.

**Comment by bodymovin** [comment]
@anitadavinci  The plugin doesn't do anything out of the ordinary. Did you get to open it or run it once at least?
How did you install it? Did you edit the registry key?

**Comment by anitadavinci** [comment]
No, sir. I just checked that the panel was under "Window » Extensions", then I started working on the test file, and AE stopped recognizing the source files of my project... It crashed, then I reopened it, it crashed again and this time I was able to read something about "Premiere 2014 blah". I installed it manually, ExMan /install bodymovin.jzp, then checked through the command line, it showed me it had been installed under Premiere, although I never understood why... I'm very sorry I didn't take any print screens... So AE kept on crashing until I manually removed it (ExMan.exe /remove_for_all, then I erased all the files belonging to the plugin). 

No, I didn't edit the registry key because I wasn't able to find the file. 

I'm very sorry to bother you, and I also thank you very much for taking the time and effort to develop such a tool... only if it worked it would be awesome.

**Comment by bodymovin** [comment]
@anitadavinci If you didn't run it even once, it's even stranger, because all the ExMan.exe does is extract the content in a folder. 
As far as I know , the ExMan.exe is meant to work for CC2015 since they deprecated the extension manager, but I don't think it would mess up with older versions of AE.
I'm sorry I can't help you any further, if I get Adobe to help me with an official installer I'll let you know.

**Comment by anitadavinci** [comment]
Thank you very much, you are very kind, sir.
