### ISSUE TITLE
 this.addTo3dContainer is not a function(…)

### ISSUE THREAD

**Issue by milesholt** [bodymovin/bodymovin#201]
I get this error when setting renderer to 'html'.

**Comment by bodymovin** [comment]
do you have nested 3d elements inside precomps?
I guess it's probably that.
Could you send me the .ae so I can take a look?

**Comment by milesholt** [comment]
Hi,
yes they are. I've sent the file to your email.
thanks for taking a look.

**Comment by ariestav** [comment]
Did this get resolved?  I'm also seeing this on a comp with nested 3D comps.  I suppose they are not supported?
