### ISSUE TITLE
Canvas rendering issue - Cannot read property 'length' of null - google font

### ISSUE THREAD

**Issue by teebow** [bodymovin/bodymovin#202]
Hi, 

When i load this json, everythings works fine with the svg renderer, but when I switch to canvas, 
I've got this error : `Cannot read property 'length' of null`

` function getCharData(char, style, font){
        var i = 0, len = this.chars.length;
        while( i < len) {
            if(this.chars[i].ch === char && this.chars[i].style === style && this.chars[i].fFamily === font){
                return this.chars[i];
            }
            i+= 1;
        }
    }`

chars seems to be null. 

I've use export from AE without the Gliphs option checked 
and provide the url to google font when asked by the UI when rendering to json. 

You can find the json below.

Btw, thanks for the awesome work you've done !!

[cv.json.zip](https://github.com/bodymovin/bodymovin/files/652054/cv.json.zip)

**Comment by bodymovin** [comment]
Hi, yes the font export is not supported for the canvas renderer.
If you need to render it on canvas, you should select glyphs on the panel.
sorry :/

**Comment by teebow** [comment]
ok,
thanks for the quick reply
