### ISSUE TITLE
Moving text looks twitchy

### ISSUE THREAD

**Issue by DanySterkhov** [bodymovin/bodymovin#205]
Hi! First of all, thank you for your work on this plugin.

Here's the deal: I made text, which just floats around, problem is, it looks kinda twitchy, maybe it lacks some antialiasing, or I'm missing something on exporting?

You can check it here, on second slide: http://wolume.tv/bodymovin/

I can provide .js settings and ae file if needed.

**Comment by bodymovin** [comment]
It seems that texts got exported as pngs instead of vectors. What kind of layer are they on AE? are they illustrator layers?

**Comment by DanySterkhov** [comment]
Oh, sorry, I wasn't talking about header text, but rather animated one in the middle. They are text converted to shapes, and also, looking from lower res (pc in studio have full hd monitor, now I'm watching this  from my laptop, which is 1368x768), they leaving some kind of trail behind them [http://i.imgur.com/Nl5tIAr.gif](url)

**Comment by bodymovin** [comment]
In what browser and OS are you seeing that behavior?
I'm checking it here on chrome, edge, firefox and opera on windows and they look fine.
Chrome is a little more jumpy because of how it handles coordinates, but I don't see any trail

**Comment by DanySterkhov** [comment]
55.0.2883.87 m Chrome and Win 10, I'll test it on other browsers @ studio later, thank you for response

**Comment by DanySterkhov** [comment]
I looked into this, problem occurs only on Chrome. Is there a way to handle this jumpy behaviour? Maybe increase fps or blur or somehow?

**Comment by bodymovin** [comment]
have you tried the canvas renderer for this?

**Comment by DanySterkhov** [comment]
Yeah, it worked, but size of element are smaller than ae comp, and then I set row to "fullwidth content", it gets low-res ( http://i.imgur.com/VWNaD8y.png )

**Comment by bodymovin** [comment]
if you call resize on the animation instance it should scale properly.
It doesn't matter if ae comp is smaller or larger.

**Comment by DanySterkhov** [comment]
I'm not really sure how to do it, if you can point me in the right direction, that should help.

**Comment by DanySterkhov** [comment]
I tried resize, but in this case I get different sizes on slides
