### ISSUE TITLE
Shape Layer Fill and Strokes only rendering Black

### ISSUE THREAD

**Issue by mmwotion** [bodymovin/bodymovin#207]
I've been working on a logo animation and I'm trying to animate some simple text that changes colour as it animates. For some reason regardless of what fill or stoke colour I apply to the shape layers when I preview in the web the colour renders as black. I swear I've done this before and had no issues. Am I being stupid?

**Comment by mmwotion** [comment]
![capture](https://cloud.githubusercontent.com/assets/24705057/21406425/78bc3dc4-c7c3-11e6-8374-2fa23d7c6de1.PNG)

**Comment by mmwotion** [comment]
This is my shape layer set up. If anyone has an ideas I'd appreciate some feedback.

**Comment by bodymovin** [comment]
can you share the .ae?
I'm not sure what could be going on. Maybe an older version of the player with newer exported animations?

**Comment by mmwotion** [comment]
This was just me being an idiot. I just downloaded the player again and it works completely fine. So if anyone else encounters this issue, just make sure your player is up to date.

**Comment by bodymovin** [comment]
glad it's working
