### ISSUE TITLE
Performance is not defined

### ISSUE THREAD

**Issue by xaralis** [bodymovin/bodymovin#208]
On some older browsers, `Performance` object is not defined.

https://github.com/bodymovin/bodymovin/blob/master/build/player/bodymovin.js#L7409

You are checking it in wrong way and thus, it fails and raises exception.

Instead of:

```
if (Performance) {...}
```

it should be

```
if (typeof Performance !== 'undefined') {...}
```

**Comment by bodymovin** [comment]
thanks!
will be fixed in next version

**Comment by bodymovin** [comment]
fixed
