### ISSUE TITLE
Bodymovin ignore repetitions

### ISSUE THREAD

**Issue by reybufon** [bodymovin/bodymovin#209]
Hey, is there a way to export repetitions using Bodymovin? When I try to export the composition, repetitions are ignored. I attach my file, in case you need to see it.
Thanks!

[w.aep.zip](https://github.com/bodymovin/bodymovin/files/672980/w.aep.zip)

**Comment by bodymovin** [comment]
hi
if you refer to shape repeaters, no, they are not supported yet.
