### ISSUE TITLE
Puppet Tool Support

### ISSUE THREAD

**Issue by jkosoy** [bodymovin/bodymovin#21]
Are there any plans for bodymovin to support Puppet Tool animation? Looks like anything we render with that doesn't animate. Will post a demo shortly as soon as I can.

**Comment by bodymovin** [comment]
@jkosoy Hi, I don't think the Puppet Tool can be a real time rendering feature. 
Besides, I don't know the complexity of the implementation, but I'm guessing it would be very difficult to imitate it.
sorry :/

**Comment by jkosoy** [comment]
Ah!!! Bummer! I'll close the issue then. :frowning: 

Awesome repo though!. :+1:

**Comment by etx** [comment]
If you can somehow bake the puppet tool animation to keyframes this could work.

**Comment by bodymovin** [comment]
as far as I know, the puppet tool does some kind of mesh distortion to the elements.  
Keyframes wouldn't help if that is the case.

**Comment by tyuiii** [comment]
lol did anyone figure what other tools to use to mimick puppet tool

**Comment by pg-los** [comment]
Workaround:
1) export the puppet tool animation as a PNG sequence (crop the export to the focus area, so you don't need to export unuseful pixels)
2) import the puppet tool animation as a PNG sequence
3) tell bodymovin to include assets in the JSON and to allow for compression

hope this helps somebody
