### ISSUE TITLE
Offset path on shape

### ISSUE THREAD

**Issue by DanySterkhov** [bodymovin/bodymovin#210]
I have animated shape with offset path, but after rendering it in .json, it converts into simple line.

[Json](https://my.mixtape.moe/cwxrom.json) [aep](https://my.mixtape.moe/dmiuap.aep)

**Comment by bodymovin** [comment]
offset path is not yet supported
I'm working on it but it has a big performance impact

**Comment by DanySterkhov** [comment]
Got it, thanks.
