### ISSUE TITLE
Unable to execute at line 63. undefined is not an object.

### ISSUE THREAD

**Issue by LucasBgt** [bodymovin/bodymovin#211]
Hey !

I have some problems with the export with Bodymovin. 
I would like to animate a burger menu to a cross icon. I created my shapes layers in a unique comp, add a trim path on each, and some positions animations. All in 2D. So, I have 5 shapes layer.

When I render, the loading stops on one shape. When I cancel, it displays "**Unable to execute at line 63. undefined is not an object.**"

![screen shot 2017-01-02 at 14 31 26](https://cloud.githubusercontent.com/assets/9822810/21590020/36ff4afa-d0f8-11e6-804e-2bdc1976ce76.png)

If anyone already had this kind of problem, 
Please help me ! :)

Thanks !

**Comment by bodymovin** [comment]
hi
can you share the .ae so I can check it out?

**Comment by LucasBgt** [comment]
Hi !

Thanks for your quick answer ! Here we go : 
[cross.aep.zip](https://github.com/bodymovin/bodymovin/files/680824/cross.aep.zip)

**Comment by bodymovin** [comment]
Hi, there is a Gradient Fill included on Shape Layer 7 that's breaking the render because it is using default values and isn't being applied to anything.
I'm fixing it right now and will upload it later.
But for now, if you remove that Gradient Fill, everything should work fine.
Thanks for reporting!

**Comment by LucasBgt** [comment]
Oh great ! That would resolve some others problems that I have. 
Thank you so much ! The gradient was a mistake ;)

That works well!

**Comment by LucasBgt** [comment]
Please let me know when you fix the Gradient Fill problem :)

**Comment by bodymovin** [comment]
fixed and uploaded!

**Comment by LucasBgt** [comment]
Thanks ! You're the man !
