### ISSUE TITLE
Unable to use different weights of the same font family in one file.

### ISSUE THREAD

**Issue by brzyskibusiness** [bodymovin/bodymovin#214]
Hi- FANTASTIC EXTENSION, I LOVE IT, THANK YOU!

I get that you can't mix styles within a single text element, but I'm not able to use different styles of the same family in the same document. I was previously able to do this:

From 12/19/16 (Works):
http://humanface.com/clients/bbg/animation/build/player/tests/index.html

From 1/5/17 (today, using 4.4.30):
http://humanface.com/clients/bbg/animation/build/player/tests/index2.html

The fonts are loaded using the URL path option:
![screenshot 2017-01-05 11 34 49](https://cloud.githubusercontent.com/assets/1394982/21688505/163840d4-d33b-11e6-8ac9-a3f70bf2777b.png)

Am I missing a trick or doing something wrong? I've attached the example here. Thanks!

[font-issue.zip](https://github.com/bodymovin/bodymovin/files/687756/font-issue.zip)

**Comment by brzyskibusiness** [comment]
Alrighty then- User error I guess-- or semantic weirdness- Changing the above settings to:

![screenshot 2017-01-05 15 46 29](https://cloud.githubusercontent.com/assets/1394982/21696998/61fbcf36-d35e-11e6-91a9-a5a98f27feea.png)

...resolved the issue. The Font Family is auto-populated and mimics how the text panel lists fonts in the IDE. Changing that to the 'full name' made it display properly.

**Comment by bodymovin** [comment]
Hi, I'm glad you got it working.
Supporting fonts is somewhat tricky, and there are some issues.
I'll check anyway your first files and see if I find anything.
