### ISSUE TITLE
Glow effect and looping animation issue

### ISSUE THREAD

**Issue by jserra85** [bodymovin/bodymovin#215]
Foremost, this is a great solution, thanks for your development efforts and support!

I'm having an issue with portions of the animation not appearing or rendering properly, consistent behavior appears across all browsers.  Initially the ring will glow in and it slides to the right, but the loop appears to be a very long duration before the ring fades in again.  

Additionally, the colors in the animation aren't appearing either.

Ideally I'd like to include this in a cordova application, but I've stripped the demo down to a single .html file with the bare essentials in hopes that you may be able to tell me if the animations/transformations I'm attempting to animate aren't supported yet or if there is an issue in how the file is being exported.

Attached you will find the After Effects file, the data.json and the demo.html file.  Any guidance would be greatly appreciated.

[GlowTest.zip](https://github.com/bodymovin/bodymovin/files/688501/GlowTest.zip)

**Comment by bodymovin** [comment]
Hi,
unfortunately the glow effect is not yet supported.
Right now, the only supported effects are fill, tint, and stroke to some extent.
Tritone and Levels are coming
I'll check this weekend if I can get somewhere with glow or at least support a subset of it.

**Comment by jacksontaylor13** [comment]
@bodymovin Just checking in on this issue to see if any progress was made? We are working on a couple of projects over here that would make this an incredibly beneficial feature! Let me know if there is anything I can do to help 👍

**Comment by bodymovin** [comment]
Which glow are you using from AE?
The layer style or the Glow effect?
Also, which properties from them are you using?

**Comment by jacksontaylor13** [comment]
@bodymovin We are currently using `Layer Styles > Outer Glow`. The properties being edited are Spread, Size, Opacity, Range, and Color. Let me know if you need any other info

**Comment by bodymovin** [comment]
I can try to support it partially, but svg filters have a terrible performance on firefox, so it's probably not going to work if you're doing some expensive animation with it

**Comment by jacksontaylor13** [comment]
@bodymovin That would be excellent! Right now it is a very basic outlining animation so shouldn't be too expensive. Thanks so much!

**Comment by vikram-kumar** [comment]
@bodymovin Am trying to add outline stroke for my pre-comp animation using
**_Layer > Layer Styles > Stroke_** which I realized is not yet supported.
This feature would help me in my project. Thanks for this awesome tool.

**Comment by bodymovin** [comment]
@vikram-kumar stroke as a Layer Style is not supported. It has a huge performance impact to implement it and it doesn't make sense to include it.

**Comment by Alexandros-Paraschou** [comment]
Hi, many thanks for this extension. Is there any chance that the Outer Glow effect will be supported at some point?

**Comment by bodymovin** [comment]
@Alexandros-Paraschou hi, not for now. But maybe at some point it will
