### ISSUE TITLE
valueAtTime expression

### ISSUE THREAD

**Issue by njdunn1** [bodymovin/bodymovin#216]
First of all I just wanted to say great job on creating such a powerful tool.

The issue I'm having is with the "valueAtTime" expression. I find the expression only works if it's applied to it's own property and when used as so "valueAtTime(time-3)" 

If used like this "thisComp.layer("null layer").effect("Slider Control")("Slider").valueAtTime(time-3)"

It will either completely break the animation or delay it from appearing on screen.

Attached you will find the After Effects file. Any help would be greatly appreciated.

Cheers

[valueAtTime-test.aep.zip](https://github.com/bodymovin/bodymovin/files/692765/valueAtTime-test.aep.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately I'm not supporting that case yet because of how AE manages values.
Instead of using numbers I'd need to use Number objects in order to attach methods to them.
I'm afraid that in doing so it will affect performance.
I still need to evaluate how to proceed

**Comment by njdunn1** [comment]
I thought that might be the case.
Thanks for the quick reply and I look forward to seeing how bodymovin evolves!

Cheers!

**Comment by bodymovin** [comment]
done :)
