### ISSUE TITLE
Merge function?

### ISSUE THREAD

**Issue by pegeseus** [bodymovin/bodymovin#217]
First off, thanks you SO much for creating this.  Seriously a gamechanger!

It seems that the merge function in shapes is not yet supported.  Do you have plans to include that at some point?

Also I'm getting odd behavior on the latest release when using Levels with shape layers.  I have shape layers with strokes attached and it appears to be clipping the edges of the stroke.  I believe it's because the renderer needs to be set to html rather than svg in order to use Levels.  Is that correct?

example
![image](https://cloud.githubusercontent.com/assets/25020666/21790170/30c121f8-d68f-11e6-8d01-2a00d7adf8d1.png)

**Comment by bodymovin** [comment]
Hi, merge paths is really complicated. I've been working on it but it's far from done.
I'm not sure when I'll be able to suppor it.
Regarding the levels issue. It's related to strokes that are not taken into account when measuring the element, and browsers make a mess with them when applying filters.
If you add a transparent rectangle, or any shape that covers the size of the stroke underneath it, it should be fixed.
For the levels effect, it's better if you use the svg renderer.

**Comment by pegeseus** [comment]
I can imagine that merge would be pretty difficult indeed.  Just wanted to make sure I wasn't doing something wrong.

Great idea about the rectangle- will give that a shot.  Thanks for the response!

**Comment by Jeremy-Knudsen** [comment]
Merge seems to work on a simple square shape in my project, but it does not work on slightly more complicated shape, which is a square with concave sides. I can send the AEP with the two layers isolated if you want to test...

**Comment by bodymovin** [comment]
Merge paths is not supported yet. The square case might be working by chance.
