### ISSUE TITLE
how to install Bodymovin?

### ISSUE THREAD

**Issue by superhenning** [bodymovin/bodymovin#218]
I think I have tried anything to install this program, but it is not to be find in After effects.  I can easily install other  extensions  into After Effects, but not this one.... 

Anybody know what to do? 

Cheers Henrik

**Comment by areus** [comment]
- Download and install [ZXP Installer](http://zxpinstaller.com/)
- Clone this repo
- Browse to `bodymovin/build/extension/`
- Open ZXP Installer, and drag extension into ZXP installer window.

**Comment by superhenning** [comment]
Thank you very much.. It works!
