### ISSUE TITLE
README : 

### ISSUE THREAD

**Issue by villedieumorgan** [bodymovin/bodymovin#22]
Just to let you know for the installation process that you've got a problem on MAC there is a corrected version of your readme : 

Option 1:

1 - Extract the bodymin.zip folder 
2 - Open your terminal and copy past this line :  

cp -R YOURUNZIPEDFOLDERPATH/extension /Library/Application\ Support/Adobe/CEP/extensions/bodymovin

BE CAREFULL THIS FOLDER WITH THE ~ IS A DIFFERENT FOLDER : ~/Library/Application Support/ DON'T USE THE ~

and type copy past this line to double check if your folder has been created.

ls /Library/Application\ Support/Adobe/CEP/extensions/bodymovin

Close After Effects

Edit the registry key: On Mac, open the file ~/Library/Preferences/com.adobe.CSXS.6.plist and use xcode to add a row with the key PlayerDebugMode, of type String, and value 1.

**Comment by bodymovin** [comment]
thanks!
