### ISSUE TITLE
Export result 

### ISSUE THREAD

**Issue by bhrzk** [bodymovin/bodymovin#221]
Hi, 
First of all having bodymovin around is one of the best joy a web developer can have. Thanks. 

I guess there's a lack of feature in this nice plugin. After editing the JSON file in web or mobile it'll be good if we can export the result to gif, Webm or MOV file. I have no idea if it's possible but I'm just asking to see if anybody can help or even in future you are able to add this. 

For instance,  I have 60 sec animation created in after effect and exported to JSON now in my mobile application I change the name, title, and description but I want to export it in gif or any movie extension to merge on another video. 

Thanks again.

**Comment by bodymovin** [comment]
Hi, there are no plans to support this kind of conversions.
But it shouldn't be too difficult on the server side, to render a frame by frame copy of the animation, save each frame as an image, and use something like ffmpeg to export it to different formats.

**Comment by wst-shorty** [comment]
Very keen on the above too. How would we go about rendering frames? Would it be something like .toDataURL() to get each frame?

**Comment by bodymovin** [comment]
I think the best approach on the server is to use something like phantomJS or puppeteer

**Comment by friday** [comment]
I've just published my workaround / API-wrapper as https://github.com/friday/lottie-node (`lottie-node` on npm).

Make sure to read and follow the instructions since there are a lot of steps necessary for it to work. It hasn't been well tested.

**Comment by transitive-bullshit** [comment]
Just published a CLI and library for exporting `lottie-web` animations as images, GIFs, or MP4s via Puppeteer. 100% compatible with `lottie-web`.

- [puppeteer-lottie-cli](https://github.com/transitive-bullshit/puppeteer-lottie-cli) - CLI.
- [puppeteer-lottie](https://github.com/transitive-bullshit/puppeteer-lottie) - Underlying library.

@friday thanks a bunch for `lottie-node` -- it was a great source of inspiration 😄

**Comment by friday** [comment]
@transitive-bullshit Looks great! Lottie doesn't play perfectly with node-canvas, so I'm redirecting people your way. Seems like a better solution.
