### ISSUE TITLE
Using bodymovin in react native

### ISSUE THREAD

**Issue by bhrzk** [bodymovin/bodymovin#223]
Hi, 
I'm new to react and I was using bodymovin with ionic before. So is there any way I can this plugin in React Native?

Thanks

**Comment by bodymovin** [comment]
As far as I know, svg support in iOS and Android is scarce, so probably not.  
I guess you could add small web rendering views in the middle of your components, but I wouldn't recommend it.  
I know someone is working on a React Native implementation of bodymovin but I'm not sure if it will be release and when.

**Comment by petrbela** [comment]
https://github.com/airbnb/lottie-react-native 💥

**Comment by bodymovin** [comment]
yeah! 💥
