### ISSUE TITLE
Wrong opacity value is rendered when using an expression

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [bodymovin/bodymovin#225]
The opacity value is being divided by 100 when I use an expression. For instance, the value is set to 5% and when I use an expression with "value" opacity gets rendered as .0005 instead of .05. If I  put "value * 100" in the expression in After Effects layer, it doesn't look right in AE, but it will render correctly with bodymovin (I'm using the SVG option).

**Comment by bodymovin** [comment]
Hi, can you share the .ae project?

**Comment by bodymovin** [comment]
got it. I'll upload the fix later.
Thanks for reporting it.

**Comment by bodymovin** [comment]
fixed in version 4.5.3
