### ISSUE TITLE
Easing render bug

### ISSUE THREAD

**Issue by Sam116** [bodymovin/bodymovin#226]
Hello. I have one problem. Animation is exporting without curves i've created in Graph editor, everything is linearly interpolated. Should i change some settings?

**Comment by bodymovin** [comment]
hi
can you share your .ae file?

**Comment by Sam116** [comment]
[Iconus 10.zip](https://github.com/bodymovin/bodymovin/files/721430/Iconus.10.zip)

**Comment by bodymovin** [comment]
I see. When transitioning between 2 keyframes with the exactly same value is not well handled by the plugin yet.
I'm trying to find a way to support this. Sorry :/
But if you set your intermediate scale values to 99.9%, it should work fine.
