### ISSUE TITLE
Path after render fills

### ISSUE THREAD

**Issue by Sam116** [bodymovin/bodymovin#227]
I made a simple animation of icons, but after rendering instead of paths image flushed entirely. I tried several different icons from one pack, which gave me a designer, there is no difference in Illustrator. But even without any animation when rendering with plugin bodymovin it make a bug in the half of icons. As i think it can be a problem with my icons, but i do not understand what is wrong, in AE anything seems ok.  Project attached.
[wheel.zip](https://github.com/bodymovin/bodymovin/files/722118/wheel.zip)

**Comment by bodymovin** [comment]
This is because when AI layers are converted to AE shapes, AE adds an unnecesary merge path with a square layer.
Since merge paths are not yet supported by the plugin, it breaks the animation.
If you can erase them manually, it will work fine.

**Comment by Sam116** [comment]
Thanks for so fast support and nice plugin. 

Can you show me how to erase that square layers in AE without removing ico elements? I am not good in adobe products(

**Comment by bodymovin** [comment]
you need to traverse your shape layers by opening contents and search the Merge properties.
If you erase them together with the square shape, it will be enough.
