### ISSUE TITLE
.playSegments. Load 2 animations. Change object color in the .json file.

### ISSUE THREAD

**Issue by TaiRaise** [bodymovin/bodymovin#228]
Hi. I just wodering how to make playable the second part of animation buy click, like in your example here: https://codepen.io/airnan/pen/RawvLB

I've made 2 files of animation for my button:
a. The 1st animation is when we hover on button;
b. The 2nd animation is when we click on button.

# **Question 1:** (load 2 animations)

### **Scenario:** 
a. When we hover to button works 1st animation;
b. When we click to button:
    b.1. We're waiting for finish the first animation;
    b.2. We run the 2nd animation;
    b.3. After the finish of the 2nd, we return the 1st animation.

How can I make that after finishing the first animation (hover) runs the 2nd (when we clicked to button)? 

[motionbutton.zip](https://www.sendspace.com/file/rrf93r)

*click.js it's the 2nd animation;
*hover.js it's the 1st animation. 

*I copied a code from .json and pasted to .js with 'var btnhover=' and 'var btnclick='.  

# **Question 2:** (.playSegments)

I saw that you used playSegments. How can I find the right time from the generated .json file, if I want to run 2nd part of animation like in your example above. Can you explain, please, what does these numbers mean in your project (link above). 

#  **Question 3:**

How can I find the color of the object in the .json file? It's very interesting to me and for other users too, I guess, because re-render composition takes a lot of time :(

**Comment by bodymovin** [comment]
Hi, regarding question 1 and 2, is it possible in your case that you export a single animation with both states?
I think it will be easier for you to handle when states change.
segments in playSegments are frames in After Effects, so if you do playSegments([10,20]), you'll be playing frame 10 to 20 of your AE project.

regarding question 3, it depends what color you want to manipulate. If it is a shape color, you can find it in the shapes array on objects of "ty" "fl" and "st"

**Comment by TaiRaise** [comment]
Hey! Wow, thank you so much for your quick answer! You made the best plugin I've ever seen! 

1. Yes, I can export it in a single animation, but I'm a newbie in JavaScript, so could you help me to run my 'Scenario'? What should I do? 

2. Ok, thank you, but I have another question. (sorry, maybe it will stupid question, but anyway) How much frames in 1 second? If I want to run my animation from 3sec to 5sec? ...I think I got it. If my composition 60fps, so 1sec = 60 frames, is that right? 

3. Ok, thx. But I didn't see the code similar to #000dss (for example) near "ty", "fl", "st". What code should I put?

**Comment by bodymovin** [comment]
1- if you have a link to where you got to, I can help you from there
2- yes
3- it's an array with the three color components.
