### ISSUE TITLE
Rounded rectangle issue

### ISSUE THREAD

**Issue by iwo111** [bodymovin/bodymovin#23]
Hello there again. Like your plugin a lot. I have some issue with newest release. When I use parametric shape in AE, and I want to animate between circle to square using rounded rectangle, I end up with strange shape in between (circle part of animations. It looks like not complete rounding, more like some rectangle with soften edges) I didn't try with bezier path because takes some time to convert (i loose keyframes so I have to do it manually, frame by frame copying path).
One more thing what I wanted to ask is, When I use stroke and dash with offset, it does not recognize it. I don't know the background of that issue, but if not possible and there is workaround, please let me know how!
Also, I would like to contribute somehow, but I'm not a programmer, I'm designer. If you want me to design new UI for the plugin panel, just let me know ;) I would be glad to help :)

**Comment by bodymovin** [comment]
@iwo111 hi! do you have a simple ae example so I can take a look at your issues?

**Comment by iwo111** [comment]
Here's the .json file!

-- 

*Ivo Marinović*
Motion graphic & 3D animation


*NSoft d.o.o*
Bleiburških Žrtava bb,
88000 Mostar, BiH

*T/F:* +387 36 317 710
*M:* +387 63 304 071

*marinovic.ivo@nsoft.ba <marinovic.ivo@nsoft.ba>*
www.nsoft.ba

**Comment by bodymovin** [comment]
@iwo111 both issues fixed.
thanks!
