### ISSUE TITLE
Play / Pause with Multiple Elements on page

### ISSUE THREAD

**Issue by johnsweber** [bodymovin/bodymovin#230]
I have a project that has multiple SVG animations that play on hover, however, when I call the play function on respective elements, they all start.

`
	var anim = new Array();
	var params = new Array();
	var animIndex = 0;
	$('.ani-svg').each(function(i){
		var curCon = $(this).attr('id');
	    params[animIndex] = {
	        container: document.getElementById(curCon),
	        renderer: 'svg',
	        loop: true,
	        autoplay: false,
	        path: '/js/svgs/' + curCon,
	    };    

	    anim[animIndex] = bodymovin.loadAnimation(params[animIndex]);
	    animIndex++;
	});

        //Even when targeting the ID only, it still plays all animations
	$('.ani-svg').mouseenter(function(){
		var bodymovin_data = $(this).value;
		bodymovin.play(bodymovin_data);
	});

	$('.ani-svg').mouseleave(function(){
		var bodymovin_data = $(this).value;
		bodymovin.pause(bodymovin_data);
	});

`

Thank you, any help would be greatly appreciated!

**Comment by bodymovin** [comment]
I think the best way to pause your animations is using the instance references you're storing in your anim array.
so, if you can link each element with their corresponding animation, you can do
anim[animIndex].pause() to pause that particular animation when hovering.

**Comment by johnsweber** [comment]
bodymovin,

I could of sworn I had tried that, but I suppose my indexes were off, that fixed the issue.  Thank you so much!

**Comment by harshadsatra** [comment]
I have the same Issue, Can anyone share the demo for the Same.
