### ISSUE TITLE
Audio with bodymovin

### ISSUE THREAD

**Issue by gghhjj** [bodymovin/bodymovin#231]
Is there any way to embed or sync audio to bodymovin animation?
Thank you very much for your great work!

**Comment by bodymovin** [comment]
hi, not yet.
But if you have a single audio file to sync, you can control the player syncing it with the audio every frame.
I've used this for some projects.

**Comment by gghhjj** [comment]
Thank you! Are those projects that you mentioned publicly available?

**Comment by bodymovin** [comment]
no, not yet. And I'm not sure I can release it soon.
Probably in a couple of months.
But if you need any help, let me know.
I've used howler.js for one and it was easy to integrate.

**Comment by gghhjj** [comment]
Wonderful! I appreciate you help!

**Comment by mulka** [comment]
@bodymovin Was wondering if there was some sample code for how to implement this (with howler, or other). This seems like a pretty common need. I'm not sure how I would sync the bodymovin animation with the audio. Would just starting both at the same time work, or would you have to monitor the progress of the audio, and call goToAndPlay every once in a while to be sure they are synced?

**Comment by awingit** [comment]
+1 

I would also love to know how to do this. Even if its not truly synced, but to be able to trigger various samples at any given point. For my animation I would like an animated dog to bark at certain queues. I think it would be cool to have events at certain frames or seconds (time markers).

Is this currently possible?

Adrian

**Comment by danielwyb** [comment]
This library is so useful. Any news on this @bodymovin ?

**Comment by NashIlli** [comment]
Any updates? @bodymovin

**Comment by bodymovin** [comment]
Hi, not yet unfortunately.

**Comment by arsalan-assetvault** [comment]
@bodymovin  can u share sample with synced audio plz ?

**Comment by RacerDelux** [comment]
@bodymovin Its 2019! Is this a planned feature - or still unknown?

**Comment by gregbarry** [comment]
@bodymovin I was also wondering how you stitched together the audio/video using the Howler JS library.  I know this is an old thread, but any examples or a deeper explanation of your strategy would be really helpful.  Thanks for all of your hard work.  Incredible extension.

**Comment by AndreaMonzini** [comment]
Hello @bodymovin,
is it possible to sync an external audio file?
I am testing Glaxnimate and python-lottie with Blender addon that do not support audio in the .json

Otherwise could you plese give some info to add the audio in the .json code?

Thank you !

**Comment by bodymovin** [comment]
@AndreaMonzini I guess you can play the audio and the animation at the same time if that's enough for your case.
To keep them synced, you'd probably want to roll out your own ticker and make sure you update both in parallel (pausing them too when necessary)

**Comment by mrjgsantos** [comment]
Is there any documentation on how to implement audio directly with lottie and bodymovin?

**Comment by mrjgsantos** [comment]
> This should help
> https://github.com/airbnb/lottie-web/wiki/Audio

Because this is with an old version and an external library isn't it?

**Comment by RacerDelux** [comment]
> 
> 
> Is there any documentation on how to implement audio directly with lottie and bodymovin?



> 
> 
> This should help
> https://github.com/airbnb/lottie-web/wiki/Audio
