### ISSUE TITLE
Text rendering issue

### ISSUE THREAD

**Issue by TomHoenderdos** [bodymovin/bodymovin#232]
When rendering text inside an animation I encounter a weird issue with rendering spaces
example: 
![screen shot 2017-01-26 at 14 18 24](https://cloud.githubusercontent.com/assets/1308106/22332709/99e29cfc-e3d2-11e6-9048-349f49dfe7b4.png)

See attached zip with aep and bodymovin export :)!
[Animation text example.zip](https://github.com/bodymovin/bodymovin/files/732389/Animation.text.example.zip)

**Comment by bodymovin** [comment]
I think I found the issue but I'm not sure because I can't reproduce it.
Can you try installing this build?
[bodymovin.zip](https://github.com/bodymovin/bodymovin/files/736919/bodymovin.zip)
