### ISSUE TITLE
Cannot read property 'effect' of undefined

### ISSUE THREAD

**Issue by MADRAUL** [bodymovin/bodymovin#233]
Hello, 

I tried to use bodymovin for the 1rst time  but i have a problem : 

> Cannot read property 'effect' of undefined

Here the problem:
`var fn = function(){var $bm_rt;
$bm_rt = mul(comp('Scene Options').layer('Scene Options').effect('Light Leaks')('ADBE Checkbox Control-0001'), 100);;this.v = $bm_rt;}`

and my code:
`<div id="plop"></div>
<script type="text/javascript">

		var content = document.getElementById('plop');
		var anim = bodymovin.loadAnimation({
			container: content, 
			renderer: 'canvas',
			loop: true,
			autoplay: true,
			path: 'test-data.json',
		});
	</script>`
Bodymovin version 4.5.3

Can you help me to solved this problem please ?

Thank you.

**Comment by bodymovin** [comment]
can you check if the layer 'Scene Options' is hidden or guided?
if it is, you need to specify that you want to export hidden and guided layers, or simply unhide/unguide it.
Another possibility is that it is set as an Adjustment Layer, and it won't be exported. You need to set it as a normal layer.

**Comment by MADRAUL** [comment]
Thank you for your quick feedback.

I tried to check in bodymovin plugin Hidden (Check if you need HIDDEN layers to be exported.) and Guides (Check if you need GUIDED layers to be exported.)..
After export the problem still here !!!

Can u check my project if i send it to you because i'm novice with after effect ?

Thank you.

**Comment by bodymovin** [comment]
sure
i'll check it when I get home.

**Comment by bodymovin** [comment]
I confirmed in your project that the layer "Scene Options" in your project "Scene Options" is an Adjustment Layer, that's why it's not exporting. If you uncheck it, it should work.
Nevertheless, I see you're using many effects that are not supported by the plugin, so I don't think it will help you for this animation.

**Comment by MADRAUL** [comment]
Thank you for your helping and quick reply.

All the best :)
