### ISSUE TITLE
Needing an old version of the player

### ISSUE THREAD

**Issue by Tolmark12** [bodymovin/bodymovin#234]
I have a project that was created a year ago and need to grab a compatible player. When I'm looking at commits from a year ago, as far as I can tell, the player javascript is a binary file. Where can I grab an old player?

example : https://github.com/bodymovin/bodymovin/blob/5a0669929b4a7c1eb551531d063c031ce9bcf92c/build/player/bodymovin.js

Thank you! I know these type of requests are ultra annoying :-P

**Comment by bodymovin** [comment]
do you know the version of the player you need?
can you share a json file so I check the version of the export?

**Comment by Tolmark12** [comment]
You bet : 

https://gist.githubusercontent.com/Tolmark12/2849eac9014d757406c108fffeb103f4/raw/debf57d592aafdaf6938c4cd530035d54c06b50a/gistfile1.json

**Comment by bodymovin** [comment]
it's really old :)
can you try this player?
https://github.com/bodymovin/bodymovin/blob/5a0669929b4a7c1eb551531d063c031ce9bcf92c/extension/assets/player/bm.js

**Comment by Tolmark12** [comment]
:D, yeah. 

I think that's close, a few of the animations played, then I got an error :

`Cannot read property 's' of undefined`

**Comment by Tolmark12** [comment]
I ended up expanding the minified libs file and extracting modymovin from there. Thank you for your help!!
