### ISSUE TITLE
Dynamic text in animation

### ISSUE THREAD

**Issue by henriklied** [bodymovin/bodymovin#238]
Hi there! 

Is it possible to alter the text parts of an animation?

I'm planning to use Bodymovin together with the TV graphics rendering engine [CasparCG](https://github.com/CasparCG/Server/)  to make dynamic TV graphics (names of people in the broadcast etc..).

But then I would need to be able to dynamically alter the text in my animation. Does Bodymovin allow this in any way?

**Comment by bodymovin** [comment]
Hi, there is no proper API to do this, but it's simple to solve.
If you need to change it before instantiating the animation, you can change the text in the JSON object.
If you need to change it in the middle of the animation, it's more complicated, but also doable by updating the JSON and creating keyframes.
Keep in mind that you need all characters you need exported from After Effects, so you should set the text in AE with all the character set.
If you need more help, let me know

**Comment by Adam-Burke** [comment]
Hi @bodymovin, 

I'm a bit new to the bodymovin and after affects space to be honest. My technique for doing a similar thing to @henriklied described has been to build timelined animations by hand coding them and using the tween library GSAP to animate and modify svg data but the above technique seems far quicker and more performant potentially. 

> but also doable by updating the JSON and creating keyframes.

If you have the time would you be able to elaborate slightly on the following. Or point me towards some reading material that could illuminate this technique even if from a high level perspective. I guess I'm mainly interested in whether I can paramaterize a text field in after effects and get access to that paramater to dynamically change it in javascript somehow.

**Comment by bodymovin** [comment]
Hi, I made a demo on codepen than might help. 
Check the description and the editor.
http://codepen.io/airnan/pen/ZLVJmq?editors=0010
3d is not very stable and I wouldn't recommend yet to try it. SVG doesn't go well with 3d animations yet and the html renderer has some issues.

**Comment by IceMan391** [comment]
Today I played a bit and was able to get dynamic text working within my database. Sweet! 

I'm app-lovin' this.

**Comment by Darkhelmet0** [comment]
Only problem with this is if your trying to change animationData of an existing animation, you cant update the data. instead you create an entire new animation when you call anmi.loadAnimation(params with new data)

is there a way to "refresh the params" of an element without creating an entirely different object?

**Comment by bodymovin** [comment]
@Darkhelmet0 depending on the param you are trying to update.
Generally, any param with keyframes which are not "hold" keyframes, should be possible to update in the json data and they will be reflected in the animation.
For other static params, I don't have a solution yet.
For text, it might be tricky, but you could update the source of the layer.

**Comment by Darkhelmet0** [comment]
let me start by saying I love bodymovin, and have been working with it
diligently for the last 8 months. I was testing the values of a shapes fill
attributes at the time.

My current work around has been appending elements within the divs of
specific animation layers (rendered in html) then change those values
directly in the dom. But as I expand the scope of my project, I would love
to skip the hard coding of div elements based on the document tree, and
reduce my dom fetching.

By 'update source or the layer', do you mean in the animationData, or in
the dom?

I've read a few things from similar issues. please let me know if I am
misguided.

1. Not all features work in the HTML rendered (so its probably best to use
svg, and my current workaround doesn't work with svg)
2. I need to add key frames on values that I want to change...( and then
the animation data for that layer is dynamically fetched?)

Thank you for taking the time to respond and make this awesome tool!

**Comment by bodymovin** [comment]
by the source of the layer I mean the animationData.
1. yeah, specially some masking and strokes don't work well in the html renderer.
2. yes, exactly. What I usually do is add a keyframe in the first frame and a keyframe in the last one.
Then I update both in the animationData so they interpolate from the same value constantly.

**Comment by sohan99** [comment]
//This works with SVG
//and **uncheck** the 2nd option in setting
"**Glyphs - Checked converts fonts to shapes**"

var params = {
        container: document.getElementById('bodymovin'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData
    };

    var anim;

    anim = bodymovin.loadAnimation(params);
    
   //Adding event listners on ready
    anim.addEventListener("DOMLoaded",function (){
        Initialize_all()
    })
    all=[]
    arr=[]

    //Change all the Text
    function Initialize_all(){
       //first i get all the text from animation
        all = document.getElementsByClassName("rrt")
        arr = []
        console.log(all.length)
        for (var i=0;i<all.length;i++){
            console.log("pushes")
            arr.push(all[i].firstChild)
        }
        for (var i=0;i<all.length;i++){
            **all**[i].innerHTML="";  // remove all the current text
            **ar**r[i].innerHTML = ""+ i 
            all[i].appendChild(arr[i])
        }
      
    };

**Comment by ericmaicon** [comment]
Wondering if this is still working. I did a test where I try to change a text inside a layer and it doesn't load the animation again..but if I manually change on the json and reload the browser ,it works.

Is it some kind of cache ? I didn't find much on the issues here.

You can try in the following jsfiddle:
https://jsfiddle.net/ericmaicon/8Lcsx73p/2/

If you click on the button, it tries to change. I even tried to destroy before.

**Comment by bodymovin** [comment]
@ericmaicon there are several ways to change the text of a layer, but in your example, you need to change this property instead of the nm:
`json.layers[1].layers[0].t.d.k[0].s.t = 'oi.com';` on line 841

**Comment by samiam2020** [comment]
@bodymovin do you have the after effects file for that code pen example you shared. I'm trying to figure out how to build out a slot machine animation that could handle anywhere from 1 to 13 digits dynamically. Also your example couldn't take special characters is it possible to have commas, periods and dollar signs included or are those limitations with the dynamic characters.
