### ISSUE TITLE
gulp-cheerio is a runtime dependency?

### ISSUE THREAD

**Issue by ljharb** [bodymovin/bodymovin#240]
It appears v4.4.15 added `gulp-cheerio` as a runtime dependency, not a dev dependency (https://github.com/bodymovin/bodymovin/commit/44b02509ad0da27b161b9b12afd5640b7f148c2c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

This seems like it's a mistake. Could it be moved to a dev dependency?

**Comment by bodymovin** [comment]
my bad, missed that
thanks for pointing that out!
fixed

**Comment by ljharb** [comment]
Thanks! Looking forward to the release :-)
