### ISSUE TITLE
Trim Multiple Shapes Individually

### ISSUE THREAD

**Issue by yozef** [bodymovin/bodymovin#242]
Bodymovin **version: 4.5.0 and 4.5.3**

I've been trying out this aep: https://www.dropbox.com/s/p131s4evkclbn34/rocket.aep?dl=0
In After effects: 
![rocket_aep](https://cloud.githubusercontent.com/assets/287256/22597098/342037e6-e9fc-11e6-8eef-2798e33f5d19.gif)

The result is this json file: https://www.dropbox.com/s/8r807g1hcntrzt7/rocket.json?dl=0

The result:
![rocket_result](https://cloud.githubusercontent.com/assets/287256/22597360/46678b1a-e9fd-11e6-925d-c2a4d5e37198.gif)

Bodymovin Settings, if it helps:
<img width="300" alt="screen shot 2017-02-03 at 10 42 02 am" src="https://cloud.githubusercontent.com/assets/287256/22597402/7a4e9d10-e9fd-11e6-8710-329f0ab4de65.png">

**Comment by bodymovin** [comment]
The player is not yet supporting sequential trim paths, only simultaneous.
It's on the pipeline
Sorry :/

**Comment by yozef** [comment]
Hi @bodymovin just to confirm , instead of Trim Multiple Shapes (currently set to: Individually), only works with Simultaneously.. is this correct?

Also is there an ETA for Sequential/(Individually)?

**Comment by bodymovin** [comment]
Yes, Individually.
I don't have an ETA yet. I'll take a look at it this weekend and evaluate the difficulty.

**Comment by yozef** [comment]
much appreciated @bodymovin 

By the way, I have not given credit where credit is due... This Plugin/Player is amazing! The best one out there - hands down.

**Comment by bodymovin** [comment]
done and uploaded in v 4.5.4

**Comment by yozef** [comment]
Woohooo!! Works like a charm. Thanks @bodymovin
