### ISSUE TITLE
Shape paths missing 1/4 of their outlines

### ISSUE THREAD

**Issue by MrLizer** [bodymovin/bodymovin#243]
I dont know what I am doing wrong but when I add just a plain simple circle or square shape layer it renders out with 1/4 missing. Any idea what it is I am doing wrong? I thought it was something to do with Trim Paths but it happens when I add any shape... :(

<img width="232" alt="screen shot 2017-02-03 at 23 37 37" src="https://cloud.githubusercontent.com/assets/25539820/22612707/554ff10e-ea6a-11e6-8387-1bf600a7ba62.png">

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by MrLizer** [comment]
Sure thing, sorry I should have done that when I 1st posted. Zipped up the AE file and the json file too, thanks for your help

Liam


[shapeTest.zip](https://github.com/bodymovin/bodymovin/files/752172/shapeTest.zip)

**Comment by MrLizer** [comment]
Think I might have solved it myself! I was using an older version of the player.js file! Updated it to the latest version and its now working! Sorry to have bothered you!

**Comment by bodymovin** [comment]
Nice! Let me know if you need anything else.
