### ISSUE TITLE
Setting Attribute to Comp Size instead of Percentage

### ISSUE THREAD

**Issue by davismit000** [bodymovin/bodymovin#244]
Is there a way I'm not seeing to allow Bodymovin to set a canvas size to the exact dimensions of an AE comp by default? When I kick out HTML files from AE using Bodymovin, the frame height and width are set at 90% automatically. So, doing banner campaigns with upwards of 60+ banner versions requires me to edit the size for each manually. Also, setting other attributes like loop or autoplay to false would be amazing.

Thank you in advance!

**Comment by bodymovin** [comment]
The purpose of the Demo.html is just as a preview.
But you can create an empty html and load the animation exported as a standalone .js
How is your workflow for doing banners?

**Comment by davismit000** [comment]
Thanks for the response!

I pass off the .js and .html files to another agency. I believe they are using those html demo files on the back end. Changing the frame size and autoplay has been their only request. Other than that, using the demo files has always been fine. 

I'm an After Effects animator who's not well versed in development. So, I hope I'm not making you pull your hair out. This extension is incredible. Thanks again for your help.

**Comment by bodymovin** [comment]
I guess you can build an html template that loads the .json file and the bodymovin.js file.
So each animation would consist of 3 files.
You can use the same .html and .js every time and only replace the .json file with each animation.
If the agency can work with that, it's pretty simple to do.
