### ISSUE TITLE
what's the meaning of jsonkey

### ISSUE THREAD

**Issue by xuyisheng** [bodymovin/bodymovin#245]
can u provide a key-map of jsonkey's meaning, just like:

"ind"-->index
"nm"-->name 
.etc

thx a lot~

**Comment by bodymovin** [comment]
I've uploaded documentation for all the json properties
https://github.com/bodymovin/bodymovin/tree/master/docs/json
does this help?

**Comment by xuyisheng** [comment]
yes,my bad. I should read more carefully.thx very much.
