### ISSUE TITLE
Get current frame? 

### ISSUE THREAD

**Issue by SundancePioneer** [bodymovin/bodymovin#246]
Hi,

is there a way to get the current frame on a mouseover? 

I have an animation that is looping via playSegments() - on mouseover i want to get the current frame at the time of the mouseover and pass it to a goToAndPlay() 

Is there a way to do this? 

Thank you!!

**Comment by bodymovin** [comment]
yes, you can use anim.currentFrame, (and anim.currentRawFrame for more precision).
Does this help?

**Comment by SundancePioneer** [comment]
Yes, that should work - do you maybe have a codepen example showing how to use this? Also, can it be combined with the "enterFrame" event listener, to "exit" at a certain frame? Is there an example for it somewhere, how to code it?  Thank you!

**Comment by SundancePioneer** [comment]
I currently use "loopComplete", please see the codepen. 

Is this best practise or can it lead to problems? 

http://codepen.io/sundancepioneer/pen/xgzOKo

**Comment by bodymovin** [comment]
Yes, it should work with the loopComplete
just keep in mind that you need to remove the listener or it will be fired on every loopComplete event

**Comment by SundancePioneer** [comment]
Thanks for the heads up! :) 

Is there any documentation on how to use the enterFrame event? It could come in handy in this example - can i use it like to trigger an event upon entering a certain frame? 

Thank you for your kind help!

**Comment by bodymovin** [comment]
you should control it yourself.
You'll get an event every time the animation refreshes with a property "currentTime" with the time in frames. Whenever it reaches the frame you need, you can trigger the event and remove the event listener if needed.

**Comment by SundancePioneer** [comment]
Do you have an example on one of your codepens available?

**Comment by bodymovin** [comment]
I don't have a pen with that specific case. But if you want to share a link with what you've got, I can help you with it.

**Comment by SundancePioneer** [comment]
I tried to create it in this pen using enterFrame - but i don't know where or how to define the actual frame that triggers the event.. 

http://codepen.io/sundancepioneer/pen/xgzOKo

**Comment by SundancePioneer** [comment]
Did you have a chance to take a look at the pen yet? Your help is much appreciated!

**Comment by bodymovin** [comment]
let me know if you're trying to get to something like this

```javascript
//load animation data
var animation = {
  wrapper: document.getElementById('bodymovin'),
  renderer: 'svg',
  loop: true,
  autoplay: false,
  prerender: true,
  path: 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/1071426/data.json'
};

var anim = bodymovin.loadAnimation(animation);

// add events  
anim.addEventListener('DOMLoaded', function() {

      var elem = document.getElementById('shape');

      elem.addEventListener('mouseover', mouseElem)

      anim.playSegments([0, 50], true);

      function mouseElem() {
        var cur = anim.currentRawFrame;
        elem.removeEventListener('mouseover', mouseElem)
        elem.addEventListener('mouseout', playInitial)
        anim.playSegments([cur, 100], true);
        anim.addEventListener('loopComplete', pause)
      }
      
      function pause() {
        anim.removeEventListener('loopComplete', pause);
         anim.goToAndStop(anim.totalFrames - 1, true)
      }

      function playInitial() {
        elem.addEventListener('mouseover', mouseElem)
        elem.removeEventListener('mouseout', playInitial)
        anim.playSegments([0, 50], true)
      }
    })
```

**Comment by SundancePioneer** [comment]
Yes, thanks a lot - so anim.totalFrames - 1 does state what exactly?

**Comment by bodymovin** [comment]
to stop at the last frame of the current segment

**Comment by SundancePioneer** [comment]
Okay, i get it - so anim.totalFrames - 2 would mean that it is 2 frames before animation end, or "out point" to be more specific? Is that correct? Thank you

**Comment by bodymovin** [comment]
yes, correct
