### ISSUE TITLE
Circle render issue

### ISSUE THREAD

**Issue by engintekin** [bodymovin/bodymovin#247]
Hi,

My circles are not being rendered, I've been trying but couldn't find what I'm doing wrong. I appreciate any help.

[circle.zip](https://github.com/bodymovin/bodymovin/files/752712/circle.zip)

**Comment by bodymovin** [comment]
hi, the circle effects is not supported. Very few effects are.
ellipse shapes work for drawing circles.

**Comment by engintekin** [comment]
I'm having the same issue for ellipse, this is the default ellipse shape when I create a new one.
[ellipse.zip](https://github.com/bodymovin/bodymovin/files/753089/ellipse.zip)

**Comment by bodymovin** [comment]
Those generative effects are not supported yet.
It's the drawable ellipse from a shape that is supported.
sorry :/

**Comment by engintekin** [comment]
got it, thank you
