### ISSUE TITLE
Strange render effect of Mask Expansion

### ISSUE THREAD

**Issue by zmnv** [bodymovin/bodymovin#248]
Hello. 

Trying to use:
1. select shape -> right click -> Mask -> New Mask
2. right click -> Mask Shape -> set to ellipse
3. in timeline change Mask Expansion keylines by 0 to X pixels to fill shape.

**How it should be (last frame of animation)**
http://imgur.com/kO8vA18

**Render result**
http://imgur.com/YFOlLNy

**Sourse index.htm and data.json in .zip archive**
https://drive.google.com/open?id=0Bznf3Gtaeqq-bDVHS2xoRnBremM

------

Is that because of using pixels in Mask Expansion? Hmm, In first seconds it works fine and shape fills by mask expansion, but after solid mask is turning to ellipse line and displays not fine. 

I'm using Mask Expansion because it easily and quickly. Create LAYERS of mask-shape soo hard (I have more than 30 layers which and each require the mask. I dont want to create another 30 layers of masks).

Maybe there are other solutions?

**Comment by zmnv** [comment]
upd: There is mask expansion in the middle of animation (left side of rectangle should be filled, but its not)
http://imgur.com/xWpDIDu

**Comment by zmnv** [comment]
**HALF-SOLVED**

Just change Mask Path instead of Mask Expansion, or combine they.

----

But using only Mask Expansion is more comfortably, can you fix it?

**Comment by bodymovin** [comment]
Mask expansion is very complicated and with a very bad performance.
I haven't found a decent solution yet for this case.
But it is working to some extent.

**Comment by zmnv** [comment]
Still thank you:)
