### ISSUE TITLE
File Size Tips... 

### ISSUE THREAD

**Issue by JackMoGraphics** [bodymovin/bodymovin#249]
Tips on keeping file size to a minimum?

I have two shape layers revealing pre-comps of shape layers using alpha masks and trim paths

471 kb - no images in the folder just demo.html and the data.js they are 235kb and 236kb 

Not sure why they are so large, any idea how to reduce this? Would be amazing if you could release a tutorial start to finish Illustrator - Render and explain why you make it how you do in regards to bodymovin limitations, file size etc

Thanks

**Comment by bodymovin** [comment]
You don't need both files for playback, only one is enough.
demo.html actually has data.js embedded and includes a small markup.
Also, if you gzip the file, it should reduce to at least 1/5 of that size.

**Comment by JackMoGraphics** [comment]
Thanks! Greatly appreciated. 

I know this isn't an issue but didn't know where else to post it so close the issue whenever you like.
