### ISSUE TITLE
Documentation for text layer is same as documentation of solid layer

### ISSUE THREAD

**Issue by nashxena** [bodymovin/bodymovin#251]
In documentation of text layer _bodymovin/docs/json/layers/text.json_
"description": "Type of layer: Solid. Value 1.",
      "extendedName": "Type",
      "name": "ty",
      "type": "number"

this is same as solid layer.  Please help with documentation of text layer

**Comment by bodymovin** [comment]
thanks! Fixed in version 4.5.5
