### ISSUE TITLE
Support Even-Odd Fill Rule

### ISSUE THREAD

**Issue by therealsalih** [bodymovin/bodymovin#252]
I searched through all of the issues but didn't see anything related to this.
Have you ever tried implementing even-odd fill rule?

<img width="364" alt="screen shot 2017-02-07 at 6 47 00 am" src="https://cloud.githubusercontent.com/assets/5893643/22695958/651caab6-ed01-11e6-84d2-c7213f0a393e.png">

https://www.sitepoint.com/understanding-svg-fill-rule-property/

**Comment by therealsalih** [comment]
AE file attached

[Even-Odd Fill rule.aep.zip](https://github.com/bodymovin/bodymovin/files/758025/Even-Odd.Fill.rule.aep.zip)

**Comment by bodymovin** [comment]
I'll look into it. It will probably work with the svg renderer.
Not sure about the canvas renderer though

**Comment by bodymovin** [comment]
fill-rule added on version 4.5.8
