### ISSUE TITLE
Thank you for giving,this software is very user friendly

### ISSUE THREAD

**Issue by dashayuyoulaiyouqu** [bodymovin/bodymovin#253]
I am truly grateful to you for what you have done

**Comment by Jeremy-Knudsen** [comment]
Kudos! I just saw your work used in airbnb's design tool, called Lottie. Without your work, I'm not sure if Lottie much to offer.
Link:
http://airbnb.design/lottie

**Comment by therealsalih** [comment]
@Jeremy-Knudsen Lottie would NOT exist without Hernans fantastic work on Bodymovin ❤️
