### ISSUE TITLE
I found some Chinese word in the file,it's ok?

### ISSUE THREAD

**Issue by go2av** [bodymovin/bodymovin#254]
![:smile:](https://cloud.githubusercontent.com/assets/10859832/22728527/5cabdac8-ee19-11e6-8c55-728fe4f46886.png)

**Comment by bodymovin** [comment]
it's probably the layer name in AE. Is it possible?

**Comment by go2av** [comment]
I'm not found any Chinese word about `layer name` in the file at [test](https://raw.githubusercontent.com/facebookincubator/Keyframes/blob/master/scripts/sample/KeyframesLogo.aep) .
I think it's never mind if it's a desc of the word `nm` or if AE.'s language is Chinese.(I will be download Chinese of AE.😭)
let's test another file once again.
