### ISSUE TITLE
Possible to add classes/ids to sub-elements of layer?

### ISSUE THREAD

**Issue by SundancePioneer** [bodymovin/bodymovin#255]
Hi,

i'm currently using getElementByTagName to browse through the <g> elements and find paths - is it possible to name a path of a shape-layer to be able to find it directly using getElementById? 

Thanks in advance

Sundance

**Comment by bodymovin** [comment]
yes, you can name paths with classes and ids, and also you can name strokes and fills, depending on your needs

**Comment by SundancePioneer** [comment]
Okay, i named a path that is the sub-element of a group in a shape layer with an "#path1" id - but it is not displayed in the browser. I just renamed the path in AE, or do i need to add anything else?

**Comment by bodymovin** [comment]
you probably need to target it's fill or stroke.
one path can have many overlapping "path" tags drawing each style.

**Comment by SundancePioneer** [comment]
Ah, that solved it - i can now access it directly. Thank you! 👍 :)
