### ISSUE TITLE
masked video not showing in HTML render

### ISSUE THREAD

**Issue by Dpak83** [bodymovin/bodymovin#256]
Hi, i'm new to using bodymovin.

I've got a masked video in my comp, that when exported to HTML, it doesn't show. The rest of the animation works.

Is there something i am doing wrong?

Thank you

**Comment by bodymovin** [comment]
video layers are not supported, sorry :/

**Comment by Dpak83** [comment]
Ah ok, Just thought i'd ask. Maybe one for the future? :).

Great plugin none the less. Thanks for your work on this!

Are masks in general supported? I.e if i were to replace the video with an image?

Thank you

**Comment by bodymovin** [comment]
yes, most of mask types are supported.
maybe in the future videos will, but there's many issues around this.
depending on your case, you might export a placeholder from AE and replace it in your web with the corresponding video.

**Comment by Dpak83** [comment]
That's great. Thanks for your advice

**Comment by MehdiRaash** [comment]
Hey, Firstly thanks for this project, we are doing some serious TV stuff with it. 
Our designers are taught that they are not allowed to put video, and to overcome this issue we use some hacking and layers overlaying.
But actually we are suffering because of this lack( video support ).
Could you please explain this if it's gonna be available in BodyMovin? so I can assure my boss..

**Comment by bodymovin** [comment]
@MehdiRaash it's not on the pipeline right now. 
Not sure what your workaround is, but I've replaced a solid layer in AE with a video in web in the past and created a custom player to keep them synced.

**Comment by MehdiRaash** [comment]
Wow. such an interesting work.
Can you please share a link of that work?

**Comment by bodymovin** [comment]
I can't sorry, it's no longer available.
But there wasn't too much to it. Just a layer with an id and then replacing it with the video.

**Comment by NghiaTranTrongCao** [comment]
Hi @bodymovin , I'm not an expert of svg, so how can I replace layer with the video? If it wasn't too much, please make another demo to do replacing as you mentioned?

Thank you

**Comment by bodymovin** [comment]
@NghiaTranTrongCao you should explore using foreign objects with svgs, but I'm not sure all browsers support videos as FOs
