### ISSUE TITLE
Is there a min. animation length?

### ISSUE THREAD

**Issue by alex-van-zijl** [bodymovin/bodymovin#258]
Hi there,

I made an animation in After Effects with a total length of 3 seconds. It has an intro, loop, and outro part, so I split it up into 3 renders (it's one comp, but I changed the render area for the 3 different parts). The longest one is working just fine, but the other ones don't.
One of the animations seems to jump straight to the last from for some reason.

Attached you can find the .json.

Any ideas?

Thanks!
[buttonParts.zip](https://github.com/bodymovin/bodymovin/files/764125/buttonParts.zip)

**Comment by bodymovin** [comment]
I see them working fine, do you have a link I can check? Maybe I'm missing something.
Nevertheless, I'd suggest in this case that you export the whole animation in a single json, and use playSegments to render ranges of it as necessary.

**Comment by alex-van-zijl** [comment]
Thanks @bodymovin I'll check it out!
