### ISSUE TITLE
Animating the anchor causes flickering

### ISSUE THREAD

**Issue by MKGitHub** [bodymovin/bodymovin#259]
Please see attached, when the cube "walks" to the left it jumps/flickers for a short moment.

![untitled](https://cloud.githubusercontent.com/assets/535550/22806400/2c35700c-ef22-11e6-8527-c2d819eaee72.gif)

[Archive.zip](https://github.com/bodymovin/bodymovin/files/765181/Archive.zip)

**Comment by bodymovin** [comment]
You're using hold keyframes for the Anchor Point, and normal keyframes for the position.
Bodymovin interpolates  at a faster rate than After Effect's, so you're seeing those flickers inbetween keyframes.
If you use Hold keyframes on Positions as you did on Anchor points, it will work fine.
let me know if you need more help.

**Comment by MKGitHub** [comment]
Ohh thx!
