### ISSUE TITLE
3D Tracking camera

### ISSUE THREAD

**Issue by adamstanton** [bodymovin/bodymovin#260]
I've like to export shapes mapping to the 3D Tracking camera.   Is this something that will be available soon?

**Comment by bodymovin** [comment]
how does it work? do you have an .aep with an example?

**Comment by adamstanton** [comment]
attached an example

**Comment by adamstanton** [comment]
![tracking](https://cloud.githubusercontent.com/assets/16336316/22813977/7c079276-ef82-11e6-96a1-aa264e8192a0.jpg)


rename from .jpg to .aep

**Comment by adamstanton** [comment]
https://www.dropbox.com/s/km6ao719whuj699/tracking.zip?dl=0

try this link for a .aep example

**Comment by bodymovin** [comment]
there's an issue with the HTML renderer, I need to work on it.

**Comment by adamstanton** [comment]
OK keep me posted thanks

**Comment by adamstanton** [comment]
Do you know a time-frame when this bug can be looked at?

**Comment by adamstanton** [comment]
any update on this ,  are  you planning on fixing this bug in a later release ?

**Comment by bodymovin** [comment]
I'll take a look at this this week.

**Comment by KyleConnolly** [comment]
Hi, any update on html renderer?

**Comment by adamstanton** [comment]
Any update on this ?

**Comment by bodymovin** [comment]
this should be fixed with the latest version.
Restored to the same issues it had before it broke.
sorry for the delay :/

**Comment by adamstanton** [comment]
I have tested this and confirm the tracking is working.   I have use renderer: 'html'.   Unfortunately it seems to be too slow to re-draw so flashes on-screen.

**Comment by bodymovin** [comment]
Hi, can you share a link?
I haven't seen that behavior before.

**Comment by adamstanton** [comment]
here is the JSON

**Comment by adamstanton** [comment]
http://www.pintar.hk/data.json

**Comment by bodymovin** [comment]
Sorry, I meant a link with the animation running.
