### ISSUE TITLE
Glow  effects is not work 

### ISSUE THREAD

**Issue by OYsun** [bodymovin/bodymovin#262]

**Comment by OYsun** [comment]
- 
![default](https://cloud.githubusercontent.com/assets/21058462/22853935/5a0c970e-f09d-11e6-94e7-46a0ca90f894.PNG)
![02](https://cloud.githubusercontent.com/assets/21058462/22853943/7cc2197c-f09d-11e6-8dfd-fc72b877c7bf.PNG)

**Comment by bodymovin** [comment]
glow effects are not yet supported, sorry
