### ISSUE TITLE
The animation just don't move on my Phone(iOS 10.2.1)

### ISSUE THREAD

**Issue by zyxscientist** [bodymovin/bodymovin#263]
![wechatimg1397](https://cloud.githubusercontent.com/assets/16728209/22861301/9ae666e8-f150-11e6-80ea-9e540b290705.jpeg)

I render the comp and get the json,everything looks fine,but it just not works on my iPhone.But when i use the .json file download from the official blog,things work fine.So in one word,the json file rendered by my own After Effect doesn't work.

- After Effect CC 2015 & bodymovin 4.5.4

**Comment by bodymovin** [comment]
Are you using the Lottie player to render it?

**Comment by zyxscientist** [comment]
nope，I render it directly by using the bodymovin extension in After Effect.

**Comment by bodymovin** [comment]
You might be using features that are not supported yet. Can you share your .aep file?

**Comment by zyxscientist** [comment]
[DOWNLOAD HERE]( http://7xrjhy.com1.z0.glb.clouddn.com/BODYMOVIN_Github.aep)

This .ape file was also downloaded from the offical blog.If i output the .html file as demo and open the  .html with browser,everything works fine. Only doesn't work in iOS environment.

**Comment by therealsalih** [comment]
Hi @zyxscientist I can see that you're exporting the animation using the bodymovin extension in After Effects, but your screenshot and also this issue (https://github.com/airbnb/lottie-ios/issues/83)  shows that you're attempting to RENDER the animation using Lottie on iOS.

The AE file that you've attached of the bodymovin animation contains precomps, which Lottie does not yet support.

<img width="1321" alt="screen shot 2017-02-12 at 8 40 41 pm" src="https://cloud.githubusercontent.com/assets/5893643/22871210/8b7902de-f163-11e6-80b6-b11d7f960303.png">

If you want to track the progress of precomps on Lottie iOS please follow this issue

https://github.com/airbnb/lottie-ios/issues/57

Thanks!

**Comment by zyxscientist** [comment]
Really thanks for your answer.
And btw the jobs you have done just so great,thanks again!
