### ISSUE TITLE
Exporting images taking ages!

### ISSUE THREAD

**Issue by pprochnicki** [bodymovin/bodymovin#264]
Hi,
I've prepared simple AE animation for observing how bodymovin works. It has one object (AI rectangle with gradient fill) moving in straight line about 200px, lasts 10 sec. Exporting animation as for now last 34 min.
Is it normal?

**Comment by bodymovin** [comment]
no, it shouldn't last more than a second
have you enabled scripts to write to disk on your preferences?

**Comment by pprochnicki** [comment]
Already have. It works :-) Thanks for quick response.

**Comment by bodymovin** [comment]
:)

**Comment by Procs89** [comment]
I'm having a similar problem. I've set up small animations using a mask path over an image. In the past I would go into the BodyMovin settings and click on Assets - Enable Compression - Include in JSON, and it would work fine....but not anymore, it just sits at the rendering screen the whole time.

Any thoughts?

**Comment by bodymovin** [comment]
@Procs89 hi, can you share the project?

**Comment by Procs89** [comment]
I've re-opened the file, followed the same process and it worked this morning haha.

Thanks for getting back to me anyway ;)

**Comment by Moe-Apple** [comment]
I'm having the exact problem. my project has many png images and after i hit render the loading bar never moves. worked once before then it stopped again . I've tried every possible way to fix it and read almost every article i could find . this is getting ridiculous

**Comment by bodymovin** [comment]
@Moe-Apple is it going slow or not progressing at all?
Can you try emptying your render queue on AE?

**Comment by Moe-Apple** [comment]
@bodymovin  its not progressing and yes I've emptied the render queue , even cleared the cache just in case

**Comment by Nawazshareef** [comment]
Hello there,
I have a small (6 sec) project with a png in it. BodyMovin says "Exporting image: Logo.png" and rendering since yesterday night (it's been more that 10 hours now).

What to do?

**Comment by bodymovin** [comment]
@Nawazshareef what version of After Effects are you using?

**Comment by Nawazshareef** [comment]
Adobe After Effects CC 2018

**Comment by bodymovin** [comment]
@Nawazshareef can you share the project with the files? I'll try to check it later today

**Comment by Nawazshareef** [comment]
[Logo Reveal.zip](https://github.com/airbnb/lottie-web/files/4319305/Logo.Reveal.zip)
Yep. I have attached my project. Thanks for very quick response. 👍

**Comment by bodymovin** [comment]
@Nawazshareef it seems you only shared the .aep, the files are missing

**Comment by poloskk** [comment]
I have the same exact problem.. I am using jpg sequence for my animation..

**Comment by bodymovin** [comment]
@poloskk what version of AE do you have? And can you share the aep project with the linked files?

**Comment by poloskk** [comment]
@bodymovin I am using AE CC 2018 [https://drive.google.com/open?id=1cvo-U6ftftvXhYSXUi9-zEntl6khPuwh](url)

**Comment by mustafo2007** [comment]
hello everyone i use after effect 2020 and it bodymovin doesnt work! It just loading with text "Exporting images"

**Comment by mustafo2007** [comment]
hello every one! How can i convert text to shape?

**Comment by jarnomehj** [comment]
I have the same problem trying to render. I see the progress bar fill one time and then it keeps saying 

> Exporting image: Right highest signal

**Comment by jarnomehj** [comment]
> I have the same problem trying to render. I see the progress bar fill one time and then it keeps saying
> 
> > Exporting image: Right highest signal

**Quick update**
I got it working, I was using adobe Illustrator layers but you have to convert them to shapes and it will render!

**Comment by cyrex81** [comment]
same problem, 5 sec with png masked, not rendered at all: showing (Exporting Image.png). please help

**Comment by bodymovin** [comment]
@cyrex81 what version of AE are you using?

**Comment by cyrex81** [comment]
After Effects 2018. Only vector graphics are working.. Png are not working.
Any ideas?

Thank you,
Best,

**Comment by riccardosuardi** [comment]
I have the same problem. I have CC 15.1.1 (Build 12). Here the file: https://drive.google.com/drive/folders/1OD4slRMWtaU99faMR-IoLmrY1BkOJ8P8?usp=sharing

Thank you

**Comment by jarnomehj** [comment]
> I have the same problem. I have CC 15.1.1 (Build 12). Here the file: https://drive.google.com/drive/folders/1OD4slRMWtaU99faMR-IoLmrY1BkOJ8P8?usp=sharing
> 
> Thank you



> > I have the same problem trying to render. I see the progress bar fill one time and then it keeps saying
> > > Exporting image: Right highest signal
> 
> **Quick update**
> I got it working, I was using adobe Illustrator layers but you have to convert them to shapes and it will render!

@riccardosuardi, look at my answer i took a look at your file... they plugin can't handle an ai file as layer convert it to a shape.
[https://youtu.be/pPs9Ka9eDSI](url)

**Comment by jarnomehj** [comment]
Just do right mouse click on the layer then click "Create Shapes from vector layer" should do the trick...

**Comment by riccardosuardi** [comment]
> Just do right mouse click on the layer then click "Create Shapes from vector layer" should do the trick...

Amazing! It works perfectly! Thank you.

**Comment by aswathrnath** [comment]
Hello Guys,

I can't export images using bodymovin extension installed in my ae 2019
here is my [project file](http://www.mediafire.com/file/p9glez3f72fiho4/file)

project file is compressed using 7zip. download and extract it

please help me

@bodymovin @mnirm

**Comment by sourav-1983** [comment]
Hi i am using AE 2020 and while exporting my animation as a JSON file it taking ages to export all throughout the night. 
Here is the downloadable link to my AE file https://we.tl/t-KYduoBg12u

Your help would be very much appreciated.

Thanks

**Comment by bodymovin** [comment]
@sourav-1983 hi, version 5.7.6 should have fixed this
