### ISSUE TITLE
Particularly large rendering of the file

### ISSUE THREAD

**Issue by OYsun** [bodymovin/bodymovin#265]
Foremost, this is a great solution, thanks for your development efforts and support!

I met some problems in the process of use.When I make a simple animation, but more than 7M render by bodymovin
Why is this so？

Any guidance would be greatly appreciated.

[aep file](http://web-oysun.cn/about/A.ZIP)

**Comment by JackMoGraphics** [comment]
Just had a nosey as it helps me figure stuff out about bodymovin too.

My guess is that you have a LOT of keyframes and a LOT of masks. 

Simpler the better.

The less masks and keyframes you use the smaller the file. I try to keep it as basic as possible mine are usually 200-40kb

Usually use a lot of trim paths animations using alpha masks not mask paths. Less layers etc the better.

**Comment by bodymovin** [comment]
also, have you tried gzipping it? Filesize can be reduced up to 1/10th of the original size.

**Comment by bodymovin** [comment]
I've checked your animation and I found an issue I fixed.
It was reduced from 7Mb to 3.6Mb
and gzipped it was reduced from 2.5Mb to 500Kb
thanks for reporting it! :)

**Comment by OYsun** [comment]
@JackMoGraphics  I think this is the case,reduce the size can only be as much as possible to reduce the use of keyframes and masks。But for some complex animation to achieve the ideal situation does require extensive use of keyframes and masks。

**Comment by OYsun** [comment]
@bodymovin  That's wonderful.thanks a Ton. Very much looking forward to you to upload the fix file

**Comment by bodymovin** [comment]
done and uploaded :)
