### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by dharpo** [bodymovin/bodymovin#267]
After downloading the repo, I have been unable to use any of the demos that link to a JSON file. Subsequently, after trying to use my own exported JSON and importing the JS file to a HTML file I still can't get anything to show. I'm not sure what I'm missing but it seems fairly trivial :/

**Comment by savadodesigns** [comment]
Same issue here...

**Comment by bodymovin** [comment]
How are you trying to run the demos?
If you're double clicking the html, keep in mind that jsons need to be delivered from a web server.
Browsers, for security, don't allow loading a json file from an html that has been opened locally.
There is one of the demos that should work locally because the json file is converted to a js object.
Can you check if the file at demo/banner works?

best,
Hernan

**Comment by bodymovin** [comment]
which folder is missing?

**Comment by savadodesigns** [comment]
@bodymovin Thanks for the quick reply. The demo/banner works, but when I upload the demo's to my hosting server, they still don't work. I've found the problem: the path to the bodymovin.js in the index.html file (in demo/bodymovin) is wrong:

`<script src="../bodymovin.js"></script>`

should be

`<script src="../../build/player/bodymovin.js"></script>`

Thank you for this great plugin and the support, simply amazing!

**Comment by savadodesigns** [comment]
@bodymovin When I output my animation as json file and include it, nothing is animated. Could you tell me what's wrong? The demo is here: http://tc.teamcreative.nl/demo/savado/ and works just like the demo's in the ZIP. Probably something wrong in my .JSON file or export settings in AE?

**Comment by bodymovin** [comment]
@savadodesigns can you email me your .aep project so I can check it?

**Comment by dharpo** [comment]
Works now that I've uploaded to a web server. Thanks

**Comment by savadodesigns** [comment]
@bodymovin Thanks again for the quick reply. We've found the problem in the AE project and fixed it, so now everything works. Great!
