### ISSUE TITLE
Play one json file in segments?

### ISSUE THREAD

**Issue by areus** [bodymovin/bodymovin#27]
Is there any way I can output my timeline into 1 `.json`, then break it up into segments?

For example:
- Have a 6 second animation @ 180 frames (180f)
- Export entire animation to 1 `.json` file.
- Import and load player and generated `.json`
- Loop 0f-50f in `#element1`
- Loop 50f-100f in `#element2`
- Loop 100f-180f in `#element3`

Just trying to keep everything as lightweight as possible! Thanks in advance for any help you can provide. This extension is amazing. You're doing phenomenal work.

**Comment by bodymovin** [comment]
@areus  hi! do the three animations share layers?
If they don't, you can export all three separately and import them in a single js file as three vars.
If they do, you can use "playSegments" on each "anim" instance and set the segment for each.
something like:
anim1.playSegments([0,50],true);
anim2.playSegments([50,100],true);
anim3.playSegments([100,180],true); 
the second parameter "true" is to force the animation to jump to that segment immediately.
I'd suggest you to  load the json data as a string and pass it to each animation instance with JSON.parse.
If you need further assistance let me know and I'll send you an example.

**Comment by areus** [comment]
Yes! That worked perfectly! 

I'm extremely thankful for the work you're putting in on this. It's bringing a lot of my work to life, and something I'll probably use frequently going forward. If there's anything I can ever help out with (design? frontend?), please feel free to reach out to me.
