### ISSUE TITLE
Animation stops on some point

### ISSUE THREAD

**Issue by LucasBgt** [bodymovin/bodymovin#270]
Hello,

I have a problem with my animation. When I run it on my browser, she stops few frames later. When I check my console, I have this error : 

![16763815_10210423559658937_1165597644_o](https://cloud.githubusercontent.com/assets/9822810/22982590/e7d328b4-f39f-11e6-8602-87626e2688f4.png)

The only solution I have is to place the JS script in the DOM, but I want to separate it (in order to animate it with my preloader).
I'm not very clear, but do you know from where this error could come from ?

Thanks a lot!
Lucas

**Comment by bodymovin** [comment]
hi, can you email me the .aep project so I can check it?
There seems to be a problem with trim paths

**Comment by LucasBgt** [comment]
[loader.aep.zip](https://github.com/bodymovin/bodymovin/files/777549/loader.aep.zip)

I use trim path a lot for my animation. But in my website I have some other animations with Bodymovin where I use Trim path too, and it works great.. But not on this one.

Let me know,
Thanks!

**Comment by bodymovin** [comment]
There seems to be some pngs missing here
can you send them as well?

**Comment by LucasBgt** [comment]
Oh yes sorry ! I just uploaded the .ae
Here we are : 
[_numbers.zip](https://github.com/bodymovin/bodymovin/files/777859/_numbers.zip)

**Comment by bodymovin** [comment]
So, the animation seems to be working fine here.
Can you share a link where it's not working?

**Comment by LucasBgt** [comment]
Alright, it's online : http://preprod.remibonnet.com/

You can open the console and see the JS error. You need to reload the page, I don't know why, but the images are not loaded the first time.

**Comment by bodymovin** [comment]
can you try updating to the latest player?
there has been some fixes from that version regarding trim paths.
you can get all version urls from here
https://cdnjs.com/libraries/bodymovin

**Comment by LucasBgt** [comment]
Oh yes! It works great ! Thanks a lot, thanks for your availability, you rock!! :)

**Comment by bodymovin** [comment]
:)
