### ISSUE TITLE
Weird rendering issue

### ISSUE THREAD

**Issue by moultz** [bodymovin/bodymovin#272]
Hi :), Thanks for creating this awesome library, however I'm stuck! The animation I'm using isn't rendering properly, it should look like this:

![pip_logoanimation](https://cloud.githubusercontent.com/assets/2600623/23029549/d989a594-f462-11e6-8ad3-3ccd2503a34e.gif)

However, right now it looks like this (.mov file in the zip) :

![bizarre rendering](https://cloud.githubusercontent.com/assets/2600623/23029766/803dae62-f463-11e6-89b9-1a58a9843771.gif)

[bizarre rendering.zip](https://github.com/bodymovin/bodymovin/files/780733/bizarre.rendering.zip)

Here's the data.json file and After Effects file:
[data.json +. Logo Effects Animation.zip](https://github.com/bodymovin/bodymovin/files/780741/data.json.Logo.Effects.Animation.zip)

It's my first time using bodymovin, I downloaded it from https://creative.adobe.com/addons/products/12557 so I think it's version 4.5.0

**Comment by bodymovin** [comment]
Hi, that's an issue with filters on browsers.
To replicate the "Fill" effect from AE, I'm using an SVG filter.
and filters don't go well with strokes.
There are two options to solve this:
You can add a transparent rectangle on each layer that covers the whole area where the stroke is drawn.
or you can remove the fill effect and rely on the stroke color to change the color.
Second option should be much more performant by the way.

**Comment by moultz** [comment]
Is there any way to do this via After Effects rather than using SVG?

**Comment by bodymovin** [comment]
Yes, both options should be performed in AE, not in SVG, sorry if I wasn't clear.
You should add the transparent rectangle in AE on each layer.
Or use the shape stroke instead of the stroke effect.
I recommend doing the second option.

**Comment by moultz** [comment]
Thanks, passing onto the animators! 👍

**Comment by charlottekcb** [comment]
Hi, animator here. 

I have sorted all these problems but for some reason having a few issues rendering the entire length of the animation from AE. When rendering through bodymovin' it seems to cut it short by about half a second. Is this a quick fix?

Also, the coding section for looping doesn't seem to be responding to changes. Not sure why?

I would be very grateful for any advice!
Thanks so much,

Charlotte
