### ISSUE TITLE
get Cannot read property 'lastPath' of undefined

### ISSUE THREAD

**Issue by yotavm** [bodymovin/bodymovin#273]
hey,
it's my first time using this tool.
having this issue - after rendering from the AE I get this error in the html file:
**get Cannot read property 'lastPath' of undefined**
Here is the printscreen -
<img width="1096" alt="screen shot 2017-02-16 at 22 41 56" src="https://cloud.githubusercontent.com/assets/11390250/23040255/5e84a45c-f499-11e6-9e36-590961788fe2.png">

**Comment by bodymovin** [comment]
hi
can you share the .aep project so I can take a look?

**Comment by yotavm** [comment]
[icons.zip](https://github.com/bodymovin/bodymovin/files/781537/icons.zip)
the one I render is phone and radio

**Comment by yotavm** [comment]
hey,
I still have the problem I think it because I'm using stroke effect?
in the 2 big square 
help?

**Comment by yotavm** [comment]
after 5 days i find that the stroke effect work with player version 4.5.4 - 4.4.30
and not working with the new versions
@bodymovin

**Comment by bodymovin** [comment]
Sorry, I'm having a really busy week at work.
I'll try to check it as soon as possible.

**Comment by MarioDabrowski** [comment]
Getting the same issue.

**Comment by bodymovin** [comment]
Stroke effect should be working in the latest version 4.5.9 (with same limitations as before it broke)
