### ISSUE TITLE
the html/svg/canvas doesn't have RGB channels

### ISSUE THREAD

**Issue by yorkie** [bodymovin/bodymovin#274]
cc @bodymovin

**Comment by bodymovin** [comment]
Hi, sorry, I don't understand the issue

**Comment by yorkie** [comment]
Ah that means my AE project does have color, but in bodymovin player, the color has been converted to white.

**Comment by yorkie** [comment]
Hi @bodymovin May I ask one AE source file of example? So that I can let our animator to see what's differences between them :)

**Comment by bodymovin** [comment]
there is a project you can use as a reference here
https://github.com/bodymovin/bodymovin/tree/master/projects
