### ISSUE TITLE
Optimisation - rounding decimals?

### ISSUE THREAD

**Issue by tobystokes** [bodymovin/bodymovin#275]
I'm looking at ways of keeping the performance up in a few of my more complicated animations.
I noticed quite a few long decimal fractions in the .json, mostly in vector masks, maybe where points aren't quite aligned properly, i.e 5.99999999...

Would there be any performance value in rounding these to a smaller number of decimal places?

Obviously, whether it affects the exactness of the shape depends a lot on the existing scale.
It would help reduce the .json file size, but would it benefit performance in any substantial way?
Or should I be more interested in the number of decimal places in the svg matrix transforms?

For what it's worth, I used the following regex to limit a .json output to 5 decimal places:
`([\d]+)\.([\d]{5})[\d]+` and replace `$1.$2`
without any noticeable loss/increase of quality or performance, but my tests were hardly conclusive!

**Comment by bodymovin** [comment]
Hi, I fixed that issue in the latest version. 
For shapes and masks without the same amount of vertices between keyframes, their values were not being rounded.
If you update, it should work and filesize can be significantly reduced.
Regarding performance, when keyframes are interpolated in the html side, they have as many decimals as the calculation returns. I did some tests and I didn't see a significant difference rounding them. It seemed that doing some kind of rounding for every calculation might be worse. But I can try to check that again. 
Nevetheless, performance is much more affected by other things.
Can you share an .aep project so I can check it?

**Comment by tobystokes** [comment]
You're amazing. Bodymovin is amazing!
I think I have come to the conclusion that if shapes/masks are too complicated, there are lots of ways for the authors to optimise before export. (For instance, I have re-simplified paths, and snapped to pixel in illustrator before using in AE). 
I will hopefully share what I'm up to when it's complete, but I don't think it is suffering from any issue wth your code currently.

(I would be interested to know what you expect the the things that really are big performance hitters are though?)

**Comment by bodymovin** [comment]
For Firefox, anything that involves using filters, get a huge performance hit. That's any effect and Track masks specially.
In general, using very large elements, like solids can also affect. But it depends on each case.
Chrome does really amazing magic when it comes to performance. And apparently, they're bringing hardware acceleration to svg, that would be awesome.
