### ISSUE TITLE
Gradients not working correctly

### ISSUE THREAD

**Issue by stenuto** [bodymovin/bodymovin#276]
Hi, I'm having an issue getting shape with gradient fills working upon export. Some shapes don't render at all, while some render, but the gradient defaults to black and white. Any help?
![lend_ink_test4](https://cloud.githubusercontent.com/assets/24421110/23079905/146d4cca-f50c-11e6-9640-e8ebbc7c9a4b.png)

**Comment by bodymovin** [comment]
hi, can you share the .aep project?
also, remember that for gradients to get exported correctly, you need to save the .aep project previously

**Comment by stenuto** [comment]
Thank you. Saving the .aep solved my issue!

**Comment by kuoliangkwong** [comment]
Hi im saving my project with .aep. When i preview it, the gradient does not seem correct. The attached is my After Effect CC 2017 project
[Untitled Project.zip](https://github.com/bodymovin/bodymovin/files/801103/Untitled.Project.zip)

**Comment by bodymovin** [comment]
@kuoliangkwong Hi, what do you see that is not correct?
[demo.zip](https://github.com/bodymovin/bodymovin/files/801154/demo.zip)
This is the demo.html I exported from your project.

**Comment by kuoliangkwong** [comment]
I got this~ 
[demo.zip](https://github.com/bodymovin/bodymovin/files/801181/demo.zip)

Could it be the After Effect version issue?

**Comment by bodymovin** [comment]
@kuoliangkwong not sure. Is your AE version in english?

**Comment by kuoliangkwong** [comment]
@bodymovin yes it's in english~ AE 2017.0 release version 14.0.0.207. Or did i miss anything when render using bodymovin, e.g. some config or setup that causes the issue? What AE version are you using now?

**Comment by bodymovin** [comment]
@kuoliangkwong 14.1
but I don't think it's the AE version.
Can you send me the exported json file?

**Comment by kuoliangkwong** [comment]
Here you are 
[data.zip](https://github.com/bodymovin/bodymovin/files/801230/data.zip)

**Comment by bodymovin** [comment]
@kuoliangkwong Not sure what is going on. It seems your intermediate gradient values are not being correctly exported.
I don't think it's going to help, but could you update to the latest version of Bodymovin?

**Comment by kuoliangkwong** [comment]
hi @bodymovin, i downloaded and installed today. Still is 4.5.8. Is there new update?

**Comment by bodymovin** [comment]
@kuoliangkwong No, it's the latest indeed. 
I'm comparing your .aep with mine and I don't see any difference.
What is your OS version and language?

**Comment by kuoliangkwong** [comment]
@bodymovin mine is Windows 10 and English.

**Comment by bodymovin** [comment]
[test.zip](https://github.com/bodymovin/bodymovin/files/801265/test.zip)
@kuoliangkwong can you try exporting this project?

**Comment by kuoliangkwong** [comment]
@bodymovin having the same result.. 
[result.zip](https://github.com/bodymovin/bodymovin/files/801270/result.zip)

**Comment by bodymovin** [comment]
@kuoliangkwong I don't know what is going on. In order to get Gradient data, the plugin searches your .aep project in your file system and parses it, because that information is not available to scripting.
I guess it is not being correctly parsed, or there might be a permission issue that doesn't allow the script to load the file.
Can you think of something that is preventing the plugin to access your file?

**Comment by kuoliangkwong** [comment]
Hmm i tried run with admin for AE and still having same result. Or could u show me how to debug and i can try check on the code and see wat error it's throwing out?

**Comment by bodymovin** [comment]
these issues are hard to debug because you need to log info on the html side.
Do you know how to log events and see them in the console?
there is a method called "getGradientData" in a file called "ProjectParser.jsx" in the extension, where I'm guessing it's not finding the gradient tags

**Comment by PeterKim87** [comment]
@bodymovin did you solve the problem? I have same problem now.. If you did, please let me know.

**Comment by bfayangyang** [comment]
I got same problem.if youhave already solve this problem .please share .thk
