### ISSUE TITLE
Ease and Wizz expressions suported in bodymovin.min..js but not in bodymovin_light.min.js

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [bodymovin/bodymovin#278]
Hi there —

I used "Ease and Wizz" which creates expressions for easing my keyframes. I used an "expo-out" easing preset which renders correctly when I use bodymovin.js. However, when I use bodymovin_light.js, the expression is not used and the easing becomes linear.

From what I understand, this should work in both bodymovin and bodymovin_light. Is that true?

Thanks!
Jeremy

**Comment by bodymovin** [comment]
Hi, bodymovin_light doesn't support expressions, only bodymovin full does.
Do you need a lighter version for some reason?

**Comment by Jeremy-Knudsen** [comment]
Always the lighter the better. Faster page load time, which is why I tried bodymovin_light.

**Comment by bodymovin** [comment]
I can make a version with only the svg renderer supporting expressions if it works for your case
nevertheless, now that bodymovin is on cdn, I'd suggest that you use it from there if you're loading it externally

**Comment by Jeremy-Knudsen** [comment]
Yep, I am using the CDN now. I would love "light" to be an SVG only renderer that supports expressions.
