### ISSUE TITLE
Animation Screwing up at End

### ISSUE THREAD

**Issue by HowellDesigned** [bodymovin/bodymovin#279]
Hi All,

To preface, I am completely new to .bodymovin and for that matter svg animation. I recently exported my first animation, however at the end of the animation it backtracks a few frames and then ends at an incomplete state. Why is my animation glitching out at the end?

**Comment by bodymovin** [comment]
hi
can you share the .aep project so I can take a look?

**Comment by HowellDesigned** [comment]
There were some issues with the trim path effect. When I fixed the ending percentage it repaired the problem. Now for some reason when I render I'm not getting the json file, but instead just the .js file. I watched a tutorial on youtube by Matt Wilson and he says you need the file.

**Comment by bodymovin** [comment]
check the gear next to the comp. If "standalone" is selected, you'll get a js file, if it's not, you'll get a json.

**Comment by HowellDesigned** [comment]
Thanks, I will try this out on Monday.
