### ISSUE TITLE
Android implementation

### ISSUE THREAD

**Issue by jbruchanov** [bodymovin/bodymovin#28]
Just curious, if this generates SVG for web.
How hard would be to convert SVG generator into java/android and render it there by some SVG lib ?

**Comment by bodymovin** [comment]
@jbruchanov it actually exports a json with the animation data. You could create your own player and render it on svg, canvas or any native android / java api that supports some basic drawing functionality, like bezier curves, strokes, masking.

**Comment by jbruchanov** [comment]
@bodymovin 
thanks for quick response.
I actually exported svgs as frames and trying to animate them...
however seems it's not fast enough to have nice animation :/

**Comment by bodymovin** [comment]
@jbruchanov how did you export each frame? and what did you use to animate them?

**Comment by jbruchanov** [comment]
@bodymovin 
basically wrote simple JS to export SVG during animation...
currently http://bigbadaboom.github.io/androidsvg/ and wrapped into View to animate them...
it kinda works, but GC is too much obvious, seems that the svg lib needs optimization because memory usage constantly grows during animation and then GC "kill" the performance

**Comment by jcstfu** [comment]
Hi @bodymovin I have a big problem when it comes to padding in android studio, 1st i render it in after effects and may composition is about 500x500 or 700x700 etc but it's a square then, when we import it in Android studio it has a space in top and bottom of the animation.
![2](https://user-images.githubusercontent.com/30426646/28555656-d609876a-7133-11e7-9c3a-26127c5a736c.PNG)
![capture](https://user-images.githubusercontent.com/30426646/28555655-d6098d5a-7133-11e7-92a7-fe10c0e954c7.PNG)

**Comment by bodymovin** [comment]
@jcstfu are you using Lottie?
