### ISSUE TITLE
Are drop shadows (as layer style) supported?

### ISSUE THREAD

**Issue by stenuto** [bodymovin/bodymovin#281]
Is there a way to have drop shadows supported? Is there a work-around? I'm not concerned about performance.

Thank you!

**Comment by SundancePioneer** [comment]
One possible workaround could be to set an id for the object you want to have a drop-shadow, and use css to add the drop-shadow for that id in the browser.

**Comment by bodymovin** [comment]
as Sundande said, you can include it with css if you're not animating it's properties.
But a basic drop shadow is on the roadmap.

**Comment by Anthoni** [comment]
When will you want implement it?

**Comment by jpap** [comment]
👍 for drop-shadow support. :D (My project uses a static shadow, but it is associated with objects that are being animated. The animation is simple, animating position and rotation.)

**Comment by bodymovin** [comment]
I've got a first version of drop shadow supported. But I can't upload it yet to github.
If any of you want, I can send you a beta build with it.

**Comment by jpap** [comment]
I'd love to check it out! :D Perhaps use a feature branch for it? Otherwise happy to try it out-of-band. You move quickly, thank you!

**Comment by bodymovin** [comment]
here it is. New UI BTW :)
[bodymovin.zip](https://github.com/bodymovin/bodymovin/files/820079/bodymovin.zip)
rename it to bodymovin.zxp

**Comment by jpap** [comment]
Works [perfectly](http://www.sergee.com/)! Thanks for your legwork on this. :D

Will drop-shadow be supported in the `bodymovin_light` player?  I'm keen to link to the CDN version as soon it becomes available. Thanks again!

**Comment by bodymovin** [comment]
I don't think so. It needs the effects module to be supported.
I'm thinking of adding a new build with all features supported but only the svg renderer.
Not sure how much it will reduce filesize though.

**Comment by jpap** [comment]
A thin(ner) build just for SVG would be awesome. :D

I suppose that if I got desperate, I could use the light version and apply the drop-shadow via CSS?  Currently I'm only just a bit ahead of including the entire animation as an optimized animated GIF.

**Comment by bodymovin** [comment]
@jpap do you have a file size limit?
GIFs should be much larger than the full player + the animation.
Even more if the json and player are gzipped.

**Comment by jpap** [comment]
Not really; just obsessed with minimizing the transfer size. :D

Including the full bm player, my animation is currently ~255kB (uncompressed) or 66kB if the client accepts deflate.  The associated AGIF at acceptable quality is about 469kB. (OK, this is better than I alluded to earlier; my apologies.)

**Comment by uri3000** [comment]
Is drop shadow supported on the Canvas renderer for web?
Can't get it to work

**Comment by bodymovin** [comment]
@uri3000 unfortunately, they are not
