### ISSUE TITLE
Need Help Staging

### ISSUE THREAD

**Issue by HowellDesigned** [bodymovin/bodymovin#282]
Hello,

I am fairly new to coding and the bodymovin extension for After Effects. I have successfully rendered the animation into a demo file, however when I try to load it through a json file it won't show up on my page. If someone could please show me how to replace the svg icon in my file with the animated version, that would be awesome!

I've attached the AE file and demo files as well. I added a grey background to the demo so you could actually see it. If you need to re-render it, make sure its the composition named "Strategic_Consulting_Icon"

Any help would be greatly appreciated!
[Bodymovin_Files 2.zip](https://github.com/bodymovin/bodymovin/files/794367/Bodymovin_Files.2.zip)

**Comment by bancek** [comment]
There is a problem with your bodymovin.js file. Just replace it with this one https://raw.githubusercontent.com/bodymovin/bodymovin/master/build/player/bodymovin.js

**Comment by HowellDesigned** [comment]
I copy pasted the bodymovin.js code and replaced it, but still won't show up.

**Comment by HowellDesigned** [comment]
I am using MAMP to host the files if that helps.

**Comment by bancek** [comment]
I just needed to replace the javascript file and uncomment `<div id="bodymovin"></div>` in your html file.

**Comment by HowellDesigned** [comment]
Cool, can you send me the .js file in a separate folder or a zip?

**Comment by bancek** [comment]
Just download `https://raw.githubusercontent.com/bodymovin/bodymovin/master/build/player/bodymovin.js` and put in on the server. It's the same file that I've used.

Your network tab in Developer tools (right click -> Inspect on the page) should look something like this.

![screen shot 2017-02-22 at 21 58 58](https://cloud.githubusercontent.com/assets/367440/23232086/5157eff4-f94a-11e6-9eab-f805c493dcad.png)

**Comment by HowellDesigned** [comment]
Got it to work! Thanks for your help!

**Comment by bancek** [comment]
Great. You should close the issue.
