### ISSUE TITLE
Problem with stroke effect

### ISSUE THREAD

**Issue by margarhen** [bodymovin/bodymovin#285]
I'm using bodymoving for the first time and I'm having some issues with the exported file.

In after effects, my animation mainly use the stroke effect applied to masks. When I export the animation, I encounter this issues:

- The stroke gets bolder in some layers. In the others it seems to work fine.

- It's exporting a white background the same size of the composition that moves along with the layers (ex: if the object gets smaller and turns around, these "background" does the same with the same vaule). It's like the background was linked to the object.

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by margarhen** [comment]
Sure, here yo go. Thanks in advance! Hope you can see where the problem is.
[ANI-LIADER-v2-cc.aep.zip](https://github.com/bodymovin/bodymovin/files/796635/ANI-LIADER-v2-cc.aep.zip)

**Comment by margarhen** [comment]
I don't want to rush you but did you have a chance to take a look at the file? 

The only problem I'm having know is the stroke one, as I discovered that the white background was appearing because I had a solid layer with a mask that was not working, and so I changed all that layers to shape layers and I'm not having the second issue anymore.

**Comment by bodymovin** [comment]
Hi I haven't been able to fix the issue yet.
But for that kind of stroke animation you should use a shape stroke with a trim path.
It will be extremely more performant than the stroke effect.

**Comment by margarhen** [comment]
Don't worry. I'll use trim path in the next animation to avoid further problems.

For this one, I've "fake it" by making the stroke smaller in after effects so in the export, when it gets bolder, it has the original width.

Thanks for you kind and quick awnser.

**Comment by utkarshsaxena03** [comment]
Hi
I am having a similar issue with "WRITE-ON" effect from after effects library. I have created a logo animation which has to reveal the logo elements as if it's being drawn over. Have faced no issue other than with the layers on which this effect was implemented. Can you please help with this?

Dropping in the exported files

[Archive.zip](https://github.com/airbnb/lottie-web/files/2044855/Archive.zip)


Thanks in advance :) 👍

**Comment by bodymovin** [comment]
Hi, unfortunately the write-on effect is not supported by the plugin.
Not many AE effects are supported.
