### ISSUE TITLE
Other animation tools to create bodymovin json?

### ISSUE THREAD

**Issue by xinsight** [bodymovin/bodymovin#286]
Bodymovin is such a great project. Are there any tools (other than After Effects) that support exporting the bodymovin json format?

**Comment by bodymovin** [comment]
Hi, not that I've heard of.
But maybe in the future :)

**Comment by xinsight** [comment]
Thanks for the quick reply. Is the bodymovin format documented anywhere?

**Comment by bodymovin** [comment]
https://github.com/bodymovin/bodymovin/tree/master/docs/json
I started recently working on documenting it
still needs some work
