### ISSUE TITLE
Trimmed Path gets unexpected masking

### ISSUE THREAD

**Issue by thunderskull** [bodymovin/bodymovin#287]
When exporting, the animated trim paths layer gets masked or something at the beginning and end of the loop. Middle frames are fine, but when the path is nearly animated off, the issue occurs.

Any ideas on how to work around that?

![bodymovinmasking01](https://cloud.githubusercontent.com/assets/1615885/23269203/647e0c9c-f9b5-11e6-83e0-50ae9f258fd5.jpg)
![bodymovinmasking02](https://cloud.githubusercontent.com/assets/1615885/23269204/647e3cbc-f9b5-11e6-862f-fa954a682137.jpg)

 
[LoadingSpinner.zip](https://github.com/bodymovin/bodymovin/files/797085/LoadingSpinner.zip)

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by thunderskull** [comment]
It's included in the attached .zip

**Comment by bodymovin** [comment]
sorry, I missed it.
I{ll check it when I get home

**Comment by thunderskull** [comment]
No worries, thanks for the quick reply!

**Comment by bodymovin** [comment]
there is an issue on browsers with masked strokes
they don't measure correctly their size and this is the result.
If you include a Rectangle with a fill with opacity 0 underneath the Ellipse shape that covers the whole stroke element, it should work fine.
