### ISSUE TITLE
Bodymovin not installing

### ISSUE THREAD

**Issue by prabahars** [bodymovin/bodymovin#290]
Bodymovin is not able to intalling, I have tried to install the Bodymovin through https://creative.adobe.com/addons/products/12557, But in extension section it wont be appear

I am using , After effects cc2017 and Windows 7. Please help me out

**Comment by kayson** [comment]
Have you tried the other options?

## Option 1 (Recommended):
```
download the ZIP from the repo.
Extract content and get the .zxp file from '/build/extension'
Use the ZXP installer from aescripts.com.
```
