### ISSUE TITLE
Issue with a file

### ISSUE THREAD

**Issue by naumaan7** [bodymovin/bodymovin#293]
I get issue with some of the aep files that i bought from videohive these are animated icons. it says "Unable to execute script at line 109. undefined is not an object"

File attached

[Cinema_Video_Icons (converted).zip](https://github.com/bodymovin/bodymovin/files/806556/Cinema_Video_Icons.converted.zip)

**Comment by bodymovin** [comment]
Hi! It was a bug with expressions.
it's fixed and uploaded on the latest build.

**Comment by naumaan7** [comment]
awesome thanks
