### ISSUE TITLE
issue with load data.json

### ISSUE THREAD

**Issue by drhd** [bodymovin/bodymovin#294]
Hi 

I have issue with load data.json 
see this image
thank you.

![screenshot 253](https://cloud.githubusercontent.com/assets/13721894/23409534/2aec8dc0-fde1-11e6-822f-dfc003be04a0.png)

**Comment by bodymovin** [comment]
browsers don't allow loading json files from local served htmls.
Try uploading it to a web server or install something like xamp on your local machine and it will work fine.
