### ISSUE TITLE
Demo is fine. On my website it plays different.

### ISSUE THREAD

**Issue by shandonwayne** [bodymovin/bodymovin#296]
I have two character animations. When I play their demos they look fine. After putting them on my site the arms don't bend correctly. I'm using many other Bodymovin animations throughout my site and have not had this issue. What could be triggering the animation to play differently?

**Comment by bodymovin** [comment]
are you using the same player on your website than the one on the extension?

**Comment by shandonwayne** [comment]
I didn't realize that the changed. That was the issue. Thank you!

**Comment by bodymovin** [comment]
nice :)
