### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by crookookoo** [bodymovin/bodymovin#297]
Getting this error, my assumption is that an image is missing, but the project seems fine. 
Any ideas on what might be causing this?

```
HBaseElement.renderFrame	@	bodymovin.js:9868
IImageElement.renderFrame	@	bodymovin.js:6573
SVGRenderer.renderFrame	        @	bodymovin.js:4412
AnimationItem.renderFrame	@	bodymovin.js:7722
AnimationItem.gotoFrame	        @	bodymovin.js:7714
AnimationItem.setCurrentRawFrameValue	@	bodymovin.js:7950
AnimationItem.advanceTime	@	bodymovin.js:7801
resume	                        @	bodymovin.js:7284
```

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by crookookoo** [comment]
I found that the error goes away if I convert all AI layers into shape layers. Still strange because the image assets from Ai layers are being generated correctly.
