### ISSUE TITLE
google font used without gliph

### ISSUE THREAD

**Issue by dcfax** [bodymovin/bodymovin#298]
Hi

First, Thanks for all the great things in Bodymovin !

i currently have some difficult with fonts.
i am using 3 different google font in my ae project, and rendering without glyph ( i need to change the text value  at load time ).
when i display the page locally, everything is correct ( because i have the fonts installed on my computer ).
but on a computer where the fonts are not installed, bodymovin seems don't take the font from google.

did your script take care of downloading the fonts ?
should i download the fonts in the css of the web page ?

or did i made a mistake in this :
![capture_001_01032017_120142](https://cloud.githubusercontent.com/assets/23076981/23457310/a5d77338-fe77-11e6-84f4-b2fb09c94877.jpg)

**Comment by bodymovin** [comment]
Ideally, you should include it in your css so it's available to the animation.
But if not, you can specify the path of each google font on the Font path field and bodymovin will load them.

**Comment by dcfax** [comment]
it's working better with the css ( at least it's not the default font )

@import url('https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:300,500,700|Fira+Sans:300,500,700');
