### ISSUE TITLE
Alpha Matte masking doesn't clip

### ISSUE THREAD

**Issue by crookookoo** [bodymovin/bodymovin#299]
It looks like Track Matte is supported, though I'm having trouble getting it to work.

Here's aep: https://www.dropbox.com/s/z57nmmspvf6sna5/Gradient_shapes.aep?dl=0
data.json: https://www.dropbox.com/s/n54lchta05xt5h3/data.json?dl=0

bodymovin is up to date, renderer is svg, gradient fill / color fill does not affect the issue

**Comment by bodymovin** [comment]
Can you share a link?
I'm trying it and it seems to work fine.
One detail, it's better if you don't use such large compositions. It has a big hit on performance.
And since it's svg, original size doesn't really matter.

**Comment by crookookoo** [comment]
http://eugene.works/lnr/

```javascript
    var animData = {
        renderer: 'svg',
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: true,
        path: 'data.json'

    };
    var anim = bodymovin.loadAnimation(animData);
    window.onresize = anim.resize.bind(anim);
```

**Comment by bodymovin** [comment]
animType and renderer do the same. Can you remove the animType property and keep only the renderer as "svg" and see if it works?

**Comment by crookookoo** [comment]
This solved the problem, thanks!
