### ISSUE TITLE
Trying to open extension panel fails

### ISSUE THREAD

**Issue by tom2strobl** [bodymovin/bodymovin#3]
Hi, when I try to open the panel with Windows > Extensions > bodymovin, nothing really happens.
Because I see the extension in the menu (http://files.wild.as/sLVu/2U7815Uc) I've probably put it in the right place (Library/Application Support/Adobe/CEP/extensions) though.

Could it be the case that not having AE booted in english causes the panel to not show up? Are there some logs I can post?

I'm really keen on using this thing as it could enhance our workflow drastically! :-)

**Comment by bodymovin** [comment]
What version of AE are you using? CC 2015?

**Comment by tom2strobl** [comment]
Yeah, sorry forgot to mention.

**Comment by bodymovin** [comment]
Yes, I can see the issue on a different computer.
Since CC2015, Adobe seem to want all extensions to go through their store.
I'm waiting for the Creative Cloud add-ons team to approve the plugin so you can get it from their store.

Meanwhile, there are 2 options to get it to work.

you can edit the registry key:
On Mac, open the file ~/Library/Preferences/com.adobe.CSXS.4.plist and add a row with key PlayerDebugMode, of type String, and value 1.
On Windows, open the registry key HKEY_CURRENT_USER/Software/Adobe/CSXS.4 and add a key named PlayerDebugMode, of type String, and value 1.

Or install the zxp manually following the instructions here:
https://helpx.adobe.com/x-productkb/global/installingextensionsandaddons.html
I’ve uploaded the signed zxp to the folder.

**Comment by tom2strobl** [comment]
I'm afraid there's only a 5 & 6 plist files, didn't want to break anything in there, so I opted for the second approach, though it threw an error:

```
exmancmd/Contents/MacOS/ExManCmd --install bodymovin.zxp
Failed to install, status = -160!
```

Well getting it directly from their store would be a dream obviously, I'll keep my fingers crossed

**Comment by bodymovin** [comment]
I changed the paths, it should work if you edit the file on
~/Library/Preferences/com.adobe.CSXS.6.plist

Meanwhile, Adobe rejected my first attempt to upload the add on because there were some preview images missing.
I already sent a new version and I'm waiting for their response.

**Comment by LindyInc** [comment]
We've had the same issue. We'll be interested to see how this resolves. We only saw a 3.plist file in our library.

**Comment by bodymovin** [comment]
@LindyInc are you using CC 2015?

**Comment by LindyInc** [comment]
Yes we are, we found the correct file and followed your extra steps. But still can't get it to work. 

Enjoy Your Day,
The Lindy Team

**Comment by tom2strobl** [comment]
Any updates here? Could use it so bad right now :-)

**Comment by LindyInc** [comment]
We got the extension working, but the files that it created wouldn't work when implemented. When we use the example bodymovin files, the animation works flawlessly.

**Comment by bodymovin** [comment]
@tom2strobl The plugin has been rejected. They answered "After Effects doesn't support ZXP file installations", when actually it does, but for some reason they don't support it officially.
So they said I have to create another type of installer. But right now I'm looking into what kind of installer I can use and there's no info.
I'd suggest you to use the instructions on their page:
https://helpx.adobe.com/x-productkb/global/installingextensionsandaddons.html
I've gone through them with some users and it worked. 
there's a type on item 6:
Run the command ./Contents/Mac OS/ExManCmd --install .zxp to install the extension.
"Mac OS" should be "MacOS"
If you need any assistance, write me an email.
hernantorrisi@gmail.com

**Comment by bodymovin** [comment]
@LindyInc can you send me the exported file or the .ae project to check it out?
hernantorrisi@gmail.com

**Comment by tom2strobl** [comment]
@LindyInc What did you do to resolve the issue?

**Comment by Minigoer** [comment]
@tom2strobl, @LindyInc, I've got the same issue on mac os 10.10.3 / CC 2015 AE (13.5.0347).
Nothing happends when I try to open the panel with Windows > Extensions > bodymovin.

But I can successfully render comps to data.json file, opening the render panel opening body_movin_parser.jsx script, located in Bodymovin/build/parser.

**Comment by bodymovin** [comment]
@Minigoer The jsx is the old parser, some things won't work with the player. Have you tried following the instructions on adobe's help page to install the extension?

**Comment by Minigoer** [comment]
@bodymovin , no but I'll try soon. 
Thanks for your input, I'll tell you.

**Comment by tom2strobl** [comment]
@bodymovin Ridiculous that they have the MacOS typo, but even more ridiculous that I didn't notice that. Good god. Now the Exman-shizzle worked out. Thanks a bunch!

**Comment by RTakes** [comment]
@bodymovin I'm also having the same issue, with the panel not displaying.  I've tried both install methods.  Fixed Adobe's typo and ExManCmd still throws `Failed to install, status = -160!`.  
mac os 10.10.4, CS2015

**Comment by bodymovin** [comment]
Hi. I'm not sure what that error means. Maybe some user permits issue?
I found this link that apparently helped to fix it.
https://forums.adobe.com/thread/1906325

**Comment by bodymovin** [comment]
@RTakes I think I found your issue. When you run this command,
./Contents/MacOS/ExManCmd --install .zxp, make sure you put the name of the zxp file like so:
./Contents/MacOS/ExManCmd --install bodymovin.zxp
Let me know if this helps!

**Comment by tom2strobl** [comment]
Just found out this is still open, so closing it.

**Comment by lindasunkim** [comment]
I can't find "com.adobe.CSXS.6.plist" in my mac. Can you please help?
