### ISSUE TITLE
bodymovin player not working with new exports.

### ISSUE THREAD

**Issue by mientjan** [bodymovin/bodymovin#30]
All new exports we create do not work with the current player.

First we are seeing a discrepancy between the exports we are creating and shown in the examples.
 - demo/bodymovin/data.json has a different base structure than when we run the generated code. 
   *demo/bodymovin/data.json* {animation:{layers:[], ,"ip":0,"op":103,"fr":30,"w":1820,"h":275}}
   *our export* {animation:{layers:[], ,"totalFrames": 261,"frameRate": 25,"ff": 0,"compWidth": 1920,"compHeight": 1080}}

The player in the demo just breaks with our exports. Using the player from http://lab.nearpod.com/bodymovin/demo/bocas/bodymovin.js works fine.

Are we missing something?

**Comment by bodymovin** [comment]
@mientjan Hi!
Yes, the old player is not compatible with the new exported jsons.
Just get the one that comes with the AE plugin. ("Get Player" button in the top right corner).
Or use the player in the github folder:
[https://github.com/bodymovin/bodymovin/tree/master/build/player](https://github.com/bodymovin/bodymovin/tree/master/build/player)

If that doesn't work, write me an email with the json file and I'll take a look.
