### ISSUE TITLE
Problem displaying closed shapes imported from Illustrator

### ISSUE THREAD

**Issue by BloodyMovin** [bodymovin/bodymovin#301]
Hi there

I've got a problem when importing shapes from Illustrator and converting them into shapes in after effect. Every time I convert and export an enclosed shape (for example the thermometer
 in the picture) that I used in an animation, the enclosed shape gets filled out.

<img width="344" alt="pre-bodymovin" src="https://cloud.githubusercontent.com/assets/26142026/23509793/53531b2c-ff57-11e6-83fa-dbb146152a91.png"> 

I'm using the test apk-App to test the Json files and it's always displayed wrong. It works if I convert the whole thing into a real stroke in AE but this takes a lot of time.

<img width="464" alt="screen shot 2017-03-02 at 14 46 16" src="https://cloud.githubusercontent.com/assets/26142026/23509813/63fbdc7a-ff57-11e6-90b8-071a0205e966.png">

Is there a workaround?

Cheers!

**Comment by bodymovin** [comment]
I should check the .aep file, but sometimes when converting illustrator layers, they add an extra path and a merge path that are unnecessary.
If you delete the merge path and the extra path it should work.
If you want to send me the .aep I can check it out.
BTW: I hope your username is not for all the headaches bodymovin is giving you :)

**Comment by BloodyMovin** [comment]
Thank for you reply! Yes, I noticed that  AE converts shapes that don't have a fill color with two regular shapes: one path / shape for the outline and one path / shape for the inside. It then substracts the smaller shape from the bigger one and you end up with a seemingly empty shape that is displayed correctly inside AE. That's why deleting either one of the paths results in a wrong shape.

I also didn't notice that there was a settings option in your extractor. When i export the animation as a demo and open it in Chrome, it is displayed correctly, without any fill color!

IDK but the preview app might be buggy.

**Comment by bodymovin** [comment]
Can you share the .aep so I can check it?

**Comment by BloodyMovin** [comment]
Hi,

here's the .aep file. Jsut change .jpg into .aep.

![temperatur](https://cloud.githubusercontent.com/assets/26142026/23542982/533aefb8-fff0-11e6-98ee-9303bf0c170f.jpg)

Cheers!

**Comment by BloodyMovin** [comment]
I uploaded it as a ZIP again.

[temperatur.aep.zip](https://github.com/bodymovin/bodymovin/files/816141/temperatur.aep.zip)

**Comment by bodymovin** [comment]
The issue is probably related to some feature not implemented yet in Lottie.
I'd suggest that you share your file directly with the Lottie team that will have a better idea of what is going on.

**Comment by therealsalih** [comment]
We're still working on Lottie support for all the fill rule types which would allow your shapes to cut through. Follow that here
https://github.com/airbnb/lottie-ios/issues/43
