### ISSUE TITLE
Stroke appears as shape in iOS, but not in OS browsers. 

### ISSUE THREAD

**Issue by akendall0103** [bodymovin/bodymovin#302]
Hello! I'm having some problems with an animation I created. My developers tested the JSON file on browser and it looked great. When they tested it in iOS, there was a glitch with the stroke animation. I've attached screenshots of the problem, and the AEP file. Any solves for this? Thanks! 
[download_complete.aep.zip]
![final result](https://cloud.githubusercontent.com/assets/26144701/23514556/af1c6746-ff35-11e6-9808-eb6c7b95e78b.png)
![glitch_stroke](https://cloud.githubusercontent.com/assets/26144701/23514714/23499148-ff36-11e6-98c0-a938e154e63a.png)

(https://github.com/bodymovin/bodymovin/files/814302/download_complete.aep.zip)

**Comment by bodymovin** [comment]
Hi
can you share it with the Lottie team?
They'll have more info than me about it.
https://github.com/airbnb/lottie-ios

**Comment by akendall0103** [comment]
They helped me out. Thanks!
