### ISSUE TITLE
Odd Shapes - Different than in After Effects and Preview

### ISSUE THREAD

**Issue by n8allen** [bodymovin/bodymovin#303]
I am having troubles getting shapes to keep the shape of what was created. Looks great in AE and when previewed, but really odd shapes when actually rendered. Here is an example of the shapes in after effects (left), then what is seen when rendered and viewed (right). 

![bodymovin](https://cloud.githubusercontent.com/assets/5325608/23537539/058d5dc0-ff8a-11e6-969b-dfae092b82cd.jpg)

Can you let me know what I am doing wrong? 

File attached is it helps.

**Comment by bodymovin** [comment]
hi, I think you missed the file attachment. If you can share the .aep, I'll check it out.
Make sure you 're using the correct player version.

**Comment by n8allen** [comment]
Attached is the AE file along with the rendered animation files.
[logo-test.zip](https://github.com/bodymovin/bodymovin/files/817593/logo-test.zip)

**Comment by bodymovin** [comment]
I've checked the animation here and it seems to work fine.
Can you share a link where it is failing?
Could it be related to using an old version of the player?

**Comment by n8allen** [comment]
I only have locally so can't send you a link, but will try updating the player and see if that fixes the problem for me.

Thanks for the quick reply!

**Comment by n8allen** [comment]
That fixed it, thanks for the help!
