### ISSUE TITLE
Add class name for each path.

### ISSUE THREAD

**Issue by processprocess** [bodymovin/bodymovin#305]
Each path will generate with a class. 
The class value will be set to it's respective layer name from After Effects.

This will allow DOM selection of each path, opening up a huge potential to customize the SVG based on interaction.

(I'm loving bodymovin otherwise!)

**Comment by bodymovin** [comment]
That is already implemented :)
If you name your layers starting with a dot, they will get the layer's name as class name.
if you prepend the layer with a "#", it will be exported with an id instead of a class.

**Comment by processprocess** [comment]
I had no idea! Should this be added to the docs or did I miss it? 
I'm happy to write it in and submit a pull request if you want.

Thank you so much for this Hernan!

Now I'm wondering if there's other features I don't know of 🤔

**Comment by bodymovin** [comment]
You're right, it's not documented anywhere. I didn't notice it.
If you're up for it, it would be great :)
