### ISSUE TITLE
AE 2017 BUG / My exports is black 

### ISSUE THREAD

**Issue by drhd** [bodymovin/bodymovin#307]
Hi

After effect CC 2017 bug with BodyMovin
1.When i want render my scenes to .jason file, Bodymovin stucking in exporting images ...!

2.I was used PSD files in my project and my  exports is black
I was downloaded last verion of bodymovin and installed again yesterday.

And i replaced PNG converted files from bodymovin With PNG Exports in PS 
But this is my question every time i had to do this again ?
whats the problem?
Help me   

And thank you dude. :)

**Comment by bodymovin** [comment]
can you share your project so I can take a look?
