### ISSUE TITLE
SliderControl vs text.sourceText to pull a value

### ISSUE THREAD

**Issue by SJMcGee86** [bodymovin/bodymovin#308]
Hey Hernan,

So IT are setting the HTML up to work with Caspar, so I'm on my own with this at the moment. (We're really excited)

So we've managed to get the text to work to update itself using the expression below in the html and changed our .json file into a .js file.

**var anim = bodymovin.loadAnimation(animParams);
  animData.layers[0].t.d.k[0].s.t = "Text";
  anim = bodymovin.loadAnimation(animParams);**

This works nicely.

But I don't know how to get it to communicate back to the .js file to define the background layer properties.

I know you've included sourceRectAtTime to your enhancements for the future (Thank you for this), but is there anyway to get the layer below it to understand the changes made to the html above in a simple way.

At the moment I'm trying to do something as basic as

**if (thisComp.layer("Text").text.sourceText.length == 5) value else 0** 

Where if my character length is 5 this layers opacity will turn 100% other it's 0%

But it's can't define itself. It doesn't know it has to look at the changes to the html.

Is it something stupidly simple, or is this something that will have to be changed in your bodymovin.js that needs to include a var like the sourceRectAtTime? Or is there anywhere you could send me to that could help me learn this and I'll try and figure a way out myself (I don't mind this method as I learn at the same time)

I've said in a previous post I'm pretty good with after effects and not with html and javascript, so the less I have to do in this files the better, but I am learning and getting better. 

Any help would be deeply appreciated from anyone at the moment if anyone has played around with this.

**Comment by SJMcGee86** [comment]
Hey Hernan,

So after scrubbing through over a hundred pages (Only clicked on forums that may reference the information I wanted)

Only one other person enquired about it, that I can see.

https://github.com/bodymovin/bodymovin/issues/188

as you said to perky

**_you can't edit variables hard-coded inside an expression.
but if you have a variable linked to a slider control within an expression, you can edit the value of that slider control and it will update the expression._**

This is essentially what I want to do, but is there any other way to do this without the slider control so that the text layer is the variable that edits the value.

I can send you an after effects project that shows what I want to do. Unfortunately I do fear you are going to say no...Well no at the moment fingers crossed.

the expression is roughly as followed on each layer obviously defining each layer based off each station

**input = thisComp.layer("[Station]").text.sourceText;

if( (input == "bristol")  == 1 ) value else 0;**

When I type in Bristol in the text layer. This would then tell 3 layers to turn on and 18 layers to turn off. Really cool, when I am building 70 graphics, 10 for each station and I can switch between them by typing in the station in a text layer.

As I've said above...If you can change the value of the slider control to update the expression, is there no way to make this work?

I see that you can define items in CSS and use an array in javascript...Would it be easier to do it this way? My brain is mush, I've been staring at your .js file, the html and .json (now .js) for what feels like an eternity. I have surpassed what I know into a realm of what I fear I will never understand. No matter how many times I change the expression to cheat it and with you building a relatively new plugin that I can honestly say will revolutionise how graphics will be built for broadcast (This I can guarantee) no one has asked to do what I want it, which I so badly want it to do that, that I fear more you will say "NEVER". Please don't kill my dreams of getting rid of flash and animate for good and moving into the new world where I can cleanly build my graphics in after effects and pressing a button and adding a few bits of code have working graphics.

**Comment by bodymovin** [comment]
sourceText is currently not supported on expressions.
But it shouldn't be too hard to implement.
Let me take a look and I'll get back to you.

**Comment by bodymovin** [comment]
sourceRectAtTime is now supported only for text layers and the svg renderer
