### ISSUE TITLE
resetSegments

### ISSUE THREAD

**Issue by DaanDirk** [bodymovin/bodymovin#309]
Is resetSegments going to remain in bodymovin?
I only found it referenced here: https://github.com/bodymovin/bodymovin/issues/101
Could you put it down under usage in the readme.md? Because it can be really useful.

Maybe something like this, if it is correct:
**anim.playSegments(segments, forceFlag)** -- Will set and play these segments.
**anim.resetSegments(segments, forceFlag)** -- Will reset the segments, discarding previously set segments and replace them with the new segments
- set a single segment as such: [fromframe, toframe]
- set multiple segments as such:  [[fromframeSegment1, toframeSegment1], [fromframeSegment2, toframeSegment2], [fromframeSegment3, toframeSegment3]]
- forceFlag is a boolean for forcing the new segment right away, false is looping one segment, true is playing all multiple segments first to last

**Comment by bodymovin** [comment]
Hi, yes, the resetSegments is remaining in Bodymovin, I'll try to set some examples in the readme on the next upload.
What it actually does is set the inPoint and outPoint to the original values exported from AE.
It takes only one argument, which, when true, it will reset it right away. If it's false, it will wait to the end of the current playing segments.
