### ISSUE TITLE
Animation Events

### ISSUE THREAD

**Issue by Tolmark12** [bodymovin/bodymovin#31]
Curious if you had any plans on adding animations events. Maybe something like :

``` coffeescript

# (Coffeescript)
onAnimationComplete = (e)->
  console.log("animation complete")

onEnterFrame = (e)->
  position = e.currentFrame / e.totalFrames
  if position > 0.5
    console.log("animation is halfway complete")

animation.onComplete = onAnimationComplete
animation.onEnterFrame = onEnterFrame
```

**Comment by bodymovin** [comment]
@Tolmark12 yes, it's next on my list.
as soon as I finish this big refactoring. probably next week

**Comment by areus** [comment]
+1 for this feature!

**Comment by sanderson** [comment]
+1 for this feature!

**Comment by Tolmark12** [comment]
Sounds great, no rush :-)

Absolutely amazing project, great work!!

**Comment by bodymovin** [comment]
@Tolmark12, @areus , @sanderson 
events are ready!
let me know if they work this way or you need any other.

**Comment by areus** [comment]
:tada: :tada: :tada:

**Comment by sanderson** [comment]
Awesome! Thanks!

**Comment by Tolmark12** [comment]
Awesome, just tried it out, works great. Thanks!
