### ISSUE TITLE
[Question] Does the plugin support displacement maps? 

### ISSUE THREAD

**Issue by jkristoffer** [bodymovin/bodymovin#311]
I some text that I animate using displacement maps to make it 'wiggle' however upon exporting, the effect is lost.

**Comment by bodymovin** [comment]
Hi, no, the displacement map effect is not supported yet.
sorry :/
Is that the only effect you're using for your effect?

**Comment by jkristoffer** [comment]
it isn't the only effect, i believe everything else works. Any clues to what I can contribute to get displacement maps supported?

**Comment by bodymovin** [comment]
if you have any insight on how to translate AE Displacemente map to SVG displacement map, it would be great

**Comment by bigxixi** [comment]
maybe some webGL effects could help, just take a look at
https://tympanus.net/codrops/2016/05/03/animated-heat-distortion-effects-webgl/
