### ISSUE TITLE
font-weight listed as 'normal' instead of '900'

### ISSUE THREAD

**Issue by stenuto** [bodymovin/bodymovin#312]
Hi,

I'm replacing the rendered text paths, with `<text>` tags, allowing the font/text attributes on the `<g>` tag to apply the correct style. 

I've noticed fonts with weights of 400 and 700 work as expected, but the script is exporting `font-weight="normal"` instead of `font-weight="900"` on Open Sans Extra Bold type.

This is causing my fonts to render incorrectly with custom `<text>` tags.

Any help would be appreciated!

**Comment by bodymovin** [comment]
if you're using the Open Sans Extra Bold, it should be correct to export the font-weight as normal.
Can you share the .aep so I can take a look?
