### ISSUE TITLE
Feature Request: Track Matte Support

### ISSUE THREAD

**Issue by gl2748** [bodymovin/bodymovin#313]
Would love to have support for Track Matte support... Is this possible?

**Comment by SJMcGee86** [comment]
Not 100% sure, have you tried selecting Hidden layers in your export settings?
Track Mattes should work. I thought the same until I saw a few project examples

https://github.com/bodymovin/bodymovin/issues/206

**Comment by bodymovin** [comment]
track matte should work. Only inverted luma matte might not.
No need to check hidden layers in this case.

**Comment by gl2748** [comment]
Thanks, my bad  for not checking the JSON directly. I have been using Lottie so  suspect the issue might lie there.
