### ISSUE TITLE
Feature Request: Gradient support.

### ISSUE THREAD

**Issue by gl2748** [bodymovin/bodymovin#314]

**Comment by bodymovin** [comment]
gradient is supported :)

**Comment by podrivo** [comment]
@bodymovin And what's the correct way to apply gradients in after effects?
I'm using Layer Styles -> Gradient Overlay, but I can't seem to export the gradient.

**Comment by podrivo** [comment]
Tried using Gradient Ramp and no success as well.

**Comment by podrivo** [comment]
It turns out, you need to use Gradient Fill.
Problem solved! :D

Suggestion: make this clear somewhere in README file, as you have different gradients in After Effects.

**Comment by bodymovin** [comment]
thanks, I will
