### ISSUE TITLE
Trigger event on anim data load

### ISSUE THREAD

**Issue by processprocess** [bodymovin/bodymovin#315]
I want to trigger an event once bodymovin.loadAnimation() is complete.
I'm testing this with anim.isLoaded and it's returning false unless I put a setTimeout on it.

Is it possible to fire an event once my anim data is loaded?

Thank you!

**Comment by bodymovin** [comment]
you can use events 'data_ready', 'config_ready' or 'DOMLoaded' depending at which point you need to hook to them

**Comment by processprocess** [comment]
Fantastic, this works perfectly. Thank you Hernan!

**Comment by awingit** [comment]
@processprocess and @bodymovin, can you share an example of this? I am not sure how to specifically use DOMLoaded. Is the event listener added to the bodymovin object or the animation instance?

**Comment by bodymovin** [comment]
@awingit it's added to the animation instance.

**Comment by awingit** [comment]
thanks @bodymovin , would it be used like this:

`var _anim = bodymovin.loadAnimation(_options);
_anim.addEventListener('DOMLoaded ', function(e) {
      console.log('element loaded');
});`

**Comment by bodymovin** [comment]
yes, exactly.

**Comment by awingit** [comment]
Is there anything in the options that would prevent that event from firing? The animation loads but that event does not trigger...

**Comment by bodymovin** [comment]
you have an trailing space: 'DOMLoaded ', if you remove it, it should work.

**Comment by awingit** [comment]
Typical :P . Thanks bodymovin! Really enjoying the project I am working on using this plugin!

**Comment by lenghart** [comment]
Hello, i have similar problem with events, idk but i cant find solution. here is my code.

`var preLoad = bodymovin.loadAnimation({
                    container: document.getElementById('pre-animate'),
                    renderer: 'svg',
                    loop: 1,
                    autoplay: true,
                    path: 'assets/json/pre-anime.json'
                });

                preLoad.addEventListener('loopComplete', function (e) {

                    console.log('done');
                    //$('#pre-animate').fadeOut();
                    //preLoad.destroy();

                });`

I also try something like: 

`preLoad = bodymovin.loadAnimation({
                    container: document.getElementById('pre-animate'),
                    renderer: 'svg',
                    loop: 1,
                    autoplay: true,
                    path: 'assets/json/pre-anime.json',
onComplete: function(){ // code here}
                });`

also didnt work for me.

**Comment by bodymovin** [comment]
If you're setting loop to 1, it's better if you use the "complete" event instead of the "loopComplete".
If it doesn't work, can you share a link where I can check your implementation?

**Comment by lenghart** [comment]
Thanks, probably every solution worked but i have problem with json file because animation is completed but i must wait about 1min and after this my events start.

**Comment by OnlyBreak** [comment]
@bodymovin  The initial time is too long, Is there a solution to avoid it? I use react.

**Comment by bodymovin** [comment]
@OnlyBreak hi, can you explain some more?

**Comment by spider853** [comment]
I just want to add some more stuff on this matter. If you load animation from a static data (not a path url) it will fire all static events instantly and you'll not catch anything, except DOMLoaded which is called with a setTimeout but, if the data is badly formated it might return successfully with isLoaded = true but will never call DOMLoaded. 

Also sometimes when you deal with inline fonts or fonts in general, you might want both DOMLoaded and data_ready to trigger. In that case you need to be aware that might trigger in random order. I'm using a counter for this (ex: loaded = 2, onDomLoaded = loaded--, on data_read = loaded--, and call checkIfReady on each callback to see if loaded == 0)

So be aware of that. 

Probably need to set isLoaded to false in the try {} catch configuration part. Also will be nice if you could hook in the initialize struct (something like events...)
