### ISSUE TITLE
Uncaught ReferenceError: easeIn is not defined

### ISSUE THREAD

**Issue by Sebah** [bodymovin/bodymovin#319]
Hello,

First and foremost, thanks for this brilliant plugin!
I've managed to export my JSON file and followed the tutorial found [here](https://www.youtube.com/watch?v=FYOOucjdnkY), however I'm running into the following issue(s):

```JS
Uncaught ReferenceError: easeIn is not defined
at KeyframedMultidimensionalProperty.eval (eval at initiateExpression (ExpressionManager.js:308), <anonymous>:13:12)
at KeyframedMultidimensionalProperty.execute [as getValue] (ExpressionManager.js:647)
at TransformProperty.processKeys [as getValue] (PropertyFactory.js:391)
at IShapeElement.BaseElement.prepareFrame (BaseElement.js:44)
at SVGRenderer.renderFrame (SVGRenderer.js:175)
at AnimationItem.renderFrame (AnimationItem.js:329)
at AnimationItem.gotoFrame (AnimationItem.js:321)
at AnimationItem.checkLoaded (AnimationItem.js:295)
at AnimationItem.checkFontsLoaded (AnimationItem.js:265)
at AnimationItem.waitForFontsLoaded (AnimationItem.js:272)
```

I've tried embedding the SVG using the minified version, bodymovin.js, and using all the JS files provided with the player, but I get the same error either way.

I'm using the 4.5.9 version of the player (the same version being mentioned in the JSON file as well).

Any ideas why is this happening? 

Thanks.

**Comment by bodymovin** [comment]
hi
the easeIn expression is not supported yet.
I'll try to add it soon.

**Comment by Sebah** [comment]
Heya! 

Thanks for the quick reply. Any idea how could I avoid this easing bit? Is it something that should be done through AE? I gotta mention that I did not do the animation.

Thanks.

**Comment by bodymovin** [comment]
there must be an expression linked to a property in the animation that is using it.
If you want to send me the .aep, I can check it

**Comment by Sebah** [comment]
Dude, you're a star. They should name streets after you.
[Here](https://ufile.io/8795e) are the files which I've received from the designer. If you've got a few minutes and it's not too complicated please have a look.

Thanks!

**Comment by bodymovin** [comment]
Hi
the easeIn and easeOut functions are on the "Shape Layer 2" for what I can tell.
But the plugin doesn't support Adjustment Layers either, so I'm not sure if it can help you with that animation.

**Comment by Al-Imran420** [comment]
I am also got an error in my Angular 7 Project. Please anybody help me:

core.js:14597 ERROR ReferenceError: type is not defined
at _expression_function (eval at initiateExpression (lottie.js:12191), :2:31)
at KeyframedValueProperty.executeExpression (lottie.js:12465)
at KeyframedValueProperty.processEffectsSequence [as getValue] (lottie.js:2359)
at DashProperty.iterateDynamicProperties (lottie.js:316)
at DashProperty.getValue (lottie.js:4061)
at CVShapeElement.prepareProperties (lottie.js:7034)
at CVShapeElement.prepareFrame (lottie.js:8039)
at CanvasRenderer.renderFrame (lottie.js:6379)
at AnimationItem.renderFrame (lottie.js:11472)
at AnimationItem.gotoFrame (lottie.js:11465)

**Comment by bodymovin** [comment]
@Al-Imran420 hi, can you share your json or .aep?

**Comment by Al-Imran420** [comment]
@bodymovin O yes. It's will be really helpful for me if you can do any help me. Some json is working and some is not.

Please see it in google drive link below:
https://drive.google.com/open?id=1JgyKyTvwmZEwJ7tCepmoz0M3ksm9JD1U

There "testanim.json" file is working but "scene2bounce.json" is not working.

**Comment by bodymovin** [comment]
hi, you are declaring variables inside a method execution which is not supported for now in the exporter.
can you try changing this: `loopOutDuration(type = 'cycle', duration = 0)` to this `loopOutDuration('cycle', 0)`

**Comment by Al-Imran420** [comment]
@bodymovin Thanks bro. Finally it's working fine here

**Comment by Al-Imran420** [comment]
@bodymovin Hi Bro, I have another problem and need your help. In my website have an animation and next previous button. So i want when i will click the next or previous button then the animation will be reload just one time for every click. I was try it but not work and i am really very beginner with bodymovin and ng-lottie. Please see my function and code below:

**HTML**

    <fiv-lottie 
      [params]="lottieParams"
      (animationCreated)=onAnimationCreated($event)>
    </fiv-lottie>

**TS**

    lottieParams: LottieParams = {
        path: '../assets/animcom/welcome2.json',
        renderer: 'canvas',
        loop: false,
        autoplay: true 
    };
    onAnimationCreated(animation: LottieAnimation) {
        animation.play();
        animation.setSpeed(0.8);
    }

**And Click Function**

next(animation: LottieAnimation){
        animation.play();
}
prev(animation: LottieAnimation){
        animation.play();
}

By default the animation is working when site is loading but i want it's also re-animated when i click the next or previous button. Hope you can help me properly. 

Thank's

**Comment by bodymovin** [comment]
I don't know exactly where this isn't working and I haven't used ng-lottie
What happens when you call `animation.play()`?

**Comment by Al-Imran420** [comment]
@bodymovin Actually my real code and function is below. 

**HTML**

    <div class="section bounceInLeft" *ngIf="currentPage == 0">
      <fiv-lottie 
        [params]="lottieParams"
        [width]="600" 
        [height]="90"
        (animationCreated)=onAnimationCreated($event)>
      </fiv-lottie>

      <button class="get_start_button" (click)="changePage(1)"> Get Started </button>
      
      <img class="home_cr" src="../../../assets/images/home_cr.png" alt="">
    </div> 

**Function**

    public currentPage = 0;
    public pageBack = false;
    public pageNext = false;
    changePage(delta: number, animation: LottieAnimation): void {

        animation.play();
        
        this.currentPage += delta;
        if(this.currentPage > 1 ){
            this.pageBack = true
            this.pageNext = true
        }else{
            this.pageBack = false
            this.pageNext = false
        };
        if(this.currentPage > 9 || this.currentPage < 2){
            this.pageNext = false
        }else{
            this.pageNext = true
        }
    }

**Error**

HomeComponent.html:43 ERROR TypeError: Cannot read property 'play' of undefined
    at HomeComponent.push../src/app/components/home/home.component.ts.HomeComponent.play (home.component.ts:269)
    at Object.eval [as handleEvent] (HomeComponent.html:43)
    at handleEvent (core.js:21673)
    at callWithDebugContext (core.js:22767)
    at Object.debugHandleEvent [as handleEvent] (core.js:22470)
    at dispatchEvent (core.js:19122)
    at core.js:19569
    at HTMLButtonElement.<anonymous> (platform-browser.js:993)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:16147)

**Comment by bodymovin** [comment]
changePage is expecting as a second argument the animation instance, but on your button you are only calling it with one argument.
You should pass the reference and it will probably work.
