### ISSUE TITLE
HTML IDs/classes based on AE Layer Names?

### ISSUE THREAD

**Issue by sanderson** [bodymovin/bodymovin#32]
Is it possible to generate HTML IDs/classes, on SVG elements (`g`) based on AE layer names?

**Comment by bodymovin** [comment]
@sanderson It's not that easy right now because elements don't get nested into g tags unless necessary.
I do that to improve performance.
But that's definitely something I have considered and should look into it.

**Comment by bodymovin** [comment]
@sanderson how would you use it?

**Comment by sanderson** [comment]
Essentially what I'd like to do is target specific elements within the SVG and apply different states to them using CSS. For example, a dynamic color shift when hovering on a certain element within the animation without have to load an entirely new animation.

Quick example:

##### html
```html
<svg>
  <g id="little-man">...</g>
</svg>
```

##### sass
```sass
svg g#little-man:hover {
  polyline { stroke: blue; }
  path     { fill: green; }
}
```

**Comment by sanderson** [comment]
Something I've seen before in Illustrator SVG export scripts is assigning classes/IDs based on a naming convention in the layer name. Optimizing the SVG by removing groups is great and I totally understand why you do it. I wonder if users could "opt-in" to certain things being grouped with an ID based on the layer name.

For example, if a layer name was prepended with `>#`, it would get exported with an ID base on the name of the layer. So if this was my list of layers:

- Forehead  
- \>#Eye Brows  
- Nose  
- \>#Mustache  

The layers with prepended names would get output as groups with IDs, looking something like this:

```html
<svg>
  <polyline>...</polyline>
  <g id="eye-brows">...</g>
  <polyline>...</polyline>
  <g id="mustache">...</g>
</svg>
```

Thoughts?

Sorry, I know the preferred process for feature requests is a proposed code solution rather just a concept. I'm just not that familiar with the internals of the plugin. Love it though. Great work!

**Comment by bodymovin** [comment]
@sanderson yes it absolutely makes sense.
It's a good trade off.
I'll look into it soon.

**Comment by sanderson** [comment]
@bodymovin Awesome, thx!

**Comment by bodymovin** [comment]
@sanderson I've uploaded a first attempt at this.
I'm no longer setting svgs properties, I've moved them to css.
But they still are inlined, so in order to override them, you'll need to use !important on your stylesheets.
Another use for ids is adding interaction to specific elements.
Regarding naming, I'm not modifying the original name set on AE, so you should use the exact same name removing the "#".
Let me know how this works for you.
cheers and thanks for the suggestion!

**Comment by sanderson** [comment]
Great! I'll give it a go tomorrow and let you know how it goes.

**Comment by sanderson** [comment]
@bodymovin, I've downloaded the updated .zxp file and updated the extension, but in my tests, the IDs aren't being assigned to the outputted svg elements.

**Comment by bodymovin** [comment]
@sanderson That's strange, it works here.
Can you email me the .ae or the exported .json?

**Comment by sanderson** [comment]
I just created a repo with my test files: https://github.com/sanderson/bodymovin-id-test

**Comment by bodymovin** [comment]
@sanderson I see the issue now. I didn't clarify correctly.
It needs to be prepended by a '#', not a '>#'.
Sorry for the misunderstanding.
Nevertheless, is there a reason you thought adding two chars instead of only a '#'?

**Comment by sanderson** [comment]
I tried both, but neither worked. Initially the thought process behind two characters was a "barrier to opt-in", preventing unintentional output if users are already using naming conventions with hashes. But I actually prefer the single character. I know there may some looking for classes as well (`.`), but I'm happy with IDs.

**Comment by bodymovin** [comment]
@sanderson can you send me a json exported with only the '#' to check it out?

**Comment by sanderson** [comment]
Oh, sorry about that. Just pushed the updated json file and AE file to that repo.

**Comment by bodymovin** [comment]
@sanderson the exported json has the layer name correctly set.  
And I can see the g tag with the id correctly set. Did you update the player with the one from the latest plugin?

**Comment by sanderson** [comment]
I thought I did. Let me test again.

**Comment by sanderson** [comment]
:expressionless: Looks like I forgot to update the player. So sorry to bug you. It's working great.

**Comment by bodymovin** [comment]
@sanderson no problem!
I'm glad it's working.
I'm going to upload a small fix later related to transforms. With this modification they stopped working on older browsers and even the plugin has the animations corrupted.
I'm closing the issue. If anything turns up let me know!

**Comment by sanderson** [comment]
Sounds good. Thanks again!

**Comment by SamuelDialog** [comment]
@bodymovin where can i find this plugin? I have the same problem and your solution sounds like a fix for it!
