### ISSUE TITLE
best way to translateX multi assets

### ISSUE THREAD

**Issue by yotavm** [bodymovin/bodymovin#320]
hey guys,
having some issues with animations that are moving at the same time on the x axis.

for some reason the movement is not smooth and "stucky".

Could you suggest the best way of moving multiple animations (on the x axis)?

**Comment by bodymovin** [comment]
hi
can you share the .aep so I can take a look?
it might be invoking too many garbage collections.

**Comment by yotavm** [comment]
hi,
[assets.aep.zip](https://github.com/bodymovin/bodymovin/files/846307/assets.aep.zip)
this is the full project i work with:
window-small,window-big,radio,phone,horse
and all of them use lines 
what i trying to accomplish is to play 4 of them in the website and move the div in x axis

thanks in adv

**Comment by bodymovin** [comment]
do you have a working link with the example?

**Comment by yotavm** [comment]
http://beta.oklive.io/ 
need to wait 2 sec and the animation will came from left side
(4) and then you will see the lag in safari its faster

**Comment by yotavm** [comment]
hey,
i replace my json with json from lottiefiles and its way fast and idont know why 
thanks.
