### ISSUE TITLE
CSP Issues

### ISSUE THREAD

**Issue by syedjafri** [bodymovin/bodymovin#323]
Hello guys - As great as this is, this requires us to allow "unsafe-eval" for our content-security-policy (called by InitiateExpression function with use of new Function constructor, and eval statement). 
Is there a way you can provide some fallbacks for this, so if contect-security-policy is restricting unsafe-eval in script tags, we can still run this plugin.

**Comment by bodymovin** [comment]
Hi, unfortunately, for using expressions you need eval.
There is a light version that doesn't support expressions, that doesn't include eval.
Can you use that one instead?

**Comment by fpl1976** [comment]
Hi, all the light versions I have checked they contain eval.
Can you share a link please?

**Comment by bodymovin** [comment]
@fpl1976 all the light versions don't use eval.
for example this one
https://cdnjs.cloudflare.com/ajax/libs/lottie-web/5.7.5/lottie_light.min.js
here are all of them
https://cdnjs.com/libraries/lottie-web
