### ISSUE TITLE
Backwards compatibility issue

### ISSUE THREAD

**Issue by cristian-d** [bodymovin/bodymovin#324]
Hi,

Nice job with this project!

I'm having issues playing the exported animation for this [template](https://drive.google.com/file/d/0B0XgZ-gc-zz-Slk5amNBa0haRUk/view?usp=sharing)

This happens when I use a bodymovin AE extension >= 4.5.5. 
4.5.4 is the last one that exports it in a playable shape.
I'm using the svg renderer for playback and the latest (4.6.0) player.
The error is:

> Error: <g> attribute transform: Expected number, "matrix(NaN,NaN,NaN,NaN,…".
SVGBaseElement.renderFrame @ bodymovin.js:5272
SVGTextElement.renderFrame @ bodymovin.js:6061
SVGRenderer.renderFrame @ bodymovin.js:4471
AnimationItem.renderFrame @ bodymovin.js:7840
AnimationItem.gotoFrame @ bodymovin.js:7832
AnimationItem.checkLoaded @ bodymovin.js:7806
checkFontsLoaded @ bodymovin.js:7776

Thx

**Comment by bodymovin** [comment]
fixed and uploaded on version 4.6.1
thanks for reporting it!
