### ISSUE TITLE
Installed 4.6.0, and see a blank UI when bringing up the window

### ISSUE THREAD

**Issue by steven-luu** [bodymovin/bodymovin#325]
Adobe After Effects CC
Version 14.1.0.57
macOS Sierra 10.12.3

4.5.9 was working fine.  I just installed 4.6.0 using my usual option (#3 with ExManCmd from the README.md), and now the bodymovin window that I open in AE is a blank white canvas.

*Let me know if I need to move this to SO, thanks!*

**Comment by bodymovin** [comment]
is there any chance you have some ports blocked?
can you try going to this url on safari while the extension is open and see what the console logs?
http://localhost:3117

**Comment by steven-luu** [comment]
Hi bodymovin, thanks for your extension!  

Our UI designer ended up installing 4.6.1 and no longer is having this issue.  It might have been a user error, so I'll close this issue now.  Thanks
