### ISSUE TITLE
Start animation when div is visible

### ISSUE THREAD

**Issue by quentin35** [bodymovin/bodymovin#327]
Hi

Thanks for this incredible work !
I'm new in coding and I would like to know how can I just start the animation when the div which contain the animation is set on visible ( like with a javascript function ) ?

I think we can do this easily :) 

Thanks for your help !

**Comment by bodymovin** [comment]
hi
you can set autoplay to false and do animation.play with whatever event on the page you want to bind to.

**Comment by quentin35** [comment]
Hi
thanks !
I need to start my animation when user starts to scroll down : 
$(window).scroll(function() {
if ($(this).scrollTop() > 1){  
    $('header').addClass("sticky");
	$('#camaccessbeforescroll').fadeOut(400);
	bodymovin.loadAnimation(animDataAA35);
	 
}

  else{
    $('header').removeClass("sticky");
	
  }
});

But I have a loop issue... How can I fix this ?

**Comment by bodymovin** [comment]
what do you mean by loop issue? what's the issue?

**Comment by quentin35** [comment]
By loop I mean my animation appears several times instead of once. ( I dont mean the animation plays in loop )


Blue animation should appears once

**Comment by quentin35** [comment]
here is the images : 
![loop issue](https://cloud.githubusercontent.com/assets/26611520/24491886/965b82e6-1529-11e7-8d08-031ee3c30fb5.jpg)

**Comment by bodymovin** [comment]
The function you're binding to the scroll gets triggered every time the condition is met. You probably need to remove the scroll listener as soon as it triggers once.

**Comment by quentin35** [comment]
Okey ! hum... How do I do this ? 
Thx :)

**Comment by bodymovin** [comment]
I guess you can't remove the binding because you're adding and removing the sticky class to the header.
You can create a flag outside that function. Something like:
````javascript
var isActive = false;
$(window).scroll(function() {
if ($(this).scrollTop() > 1){
$('header').addClass("sticky");
$('#camaccessbeforescroll').fadeOut(400);
if(!isActive ){
    bodymovin.loadAnimation(animDataAA35);
    isActive = true;
}

}

else{
$('header').removeClass("sticky");

}
});
````

**Comment by quentin35** [comment]
Thank you for your help ! it worked great !!
I really appreciate this :)

**Comment by quentin35** [comment]
Is it normal that the animation doesn't start/work with chrome ? ( ok with safari and firefox )

**Comment by bodymovin** [comment]
it should work fine. can you share a link where it is failing?

**Comment by quentin35** [comment]
I can't really share my project online... 
What I can say is that there is no animation where it should be :/ But it's working fine with safari and firefox...
Thank you for your help

**Comment by bodymovin** [comment]
If you can share online a reduced version of the problem without using your project I can take a look.

**Comment by quentin35** [comment]
Ok,
I'll go back with this asap 
thanks for your support

**Comment by quentin35** [comment]
Hello again,
just an other question, 
I set my animation with : 
autoplay: false,
and i preload it with : 
var anim = bodymovin.loadAnimation(animDataAA7);

to avoid lag when displaying

But, when I set : 

bodymovin.play(MYANNIMATIONNAMEHERE);

Nothing happens...

Which animation name should I set here ?

Here is my code : 

var isActive = false;
$(window).scroll(function() {
if ($(this).scrollTop() > 1){
$('header').addClass("sticky");
$('#camaccessbeforescroll').fadeOut(400);
if(!isActive ){
	
	bodymovin.play();
  
	isActive = true;
}

}

else{
$('header').removeClass("sticky");

}
});

</script>
<script>
    AOS.init();
</script>
<script>
	
	var animDataAA7 = {
        container: document.getElementById('svgAA7'),
        renderer: 'svg',
        loop: false,
        autoplay: false,
        path: 'animation/AA7/svg7.json'
   
    };

var anim = bodymovin.loadAnimation(animDataAA7);

Thanks your for your help :)

**Comment by Jeremy-Knudsen** [comment]
There are two ways that I know of to play back your animation:

1. Since you loaded the animation into bodymovin using the variable `anim`, then you can use `anim` as the reference to the animation and call its `play()` method like this:
`anim.play()`

2. Or, you can add an animation data parameter called "name" that is stored in your "animDataAA7" variable. Then, pass the value of this `name` parameter to the `play()` method. Here's an example:

First, add the `name` parameter and give it a string value (for example, I used `_'myAnimation_'`):

`var animDataAA7 = {
    container: document.getElementById('svgAA7'),
    **name: '_myAnimation_',**
    renderer: 'svg',
    loop: false,
    autoplay: false,
    path: 'animation/AA7/svg7.json'

};`

Then, call `bodymovin.play('_myAnimation_')` and it will play only the animation with that has that name..

**Comment by cianmcintyre** [comment]
Hi, 
I'm new to most things js and just looking for some for help with Bodymovin. 

I have implemented 4 animations throughout my site and need them to start as they come into view and play once.

I tried to implement the above code but I couldn't get it to work. 
The animations play fine when I loop and autoplay so I know they're working.

My script is pretty much the default Bodymovin script

`<script>
							
                                var anim;
                                var elem = document.getElementById('svgtriangle')
                                var animData = {
                                    container: elem,
                                    renderer: 'svg',
                                    loop: false,
                                    autoplay: false,
                                    rendererSettings: {
                                        progressiveLoad: false
                                    },
                                    path: 'bodymovin/triangle/triangle.json'
                                };
                                anim = bodymovin.loadAnimation(animData);
																																					
									
                            </script>
                    `

Just wondering what I need to add to make them play when visible. 
Thanks!

**Comment by bodymovin** [comment]
@cianmcintyre Hi, you'll need to provide the coding yourself for making them play when visible.
You can attach to the scroll event of the window for example in order to know the scroll position and call anim.play() when the time is right.
