### ISSUE TITLE
Puppet tools problem

### ISSUE THREAD

**Issue by cynthia-ryu** [bodymovin/bodymovin#328]
Hello guys, i got a problem with the json+demo with the animation mady by puppet tools in AE. 
it doesn't move in demo and the shape will disappear in json. i made a sample for this issue,please take a look at the attachment,thanks!

AE 14.1.0.57
bodymovin 4.6.1
[sample.zip](https://github.com/bodymovin/bodymovin/files/864415/sample.zip)

**Comment by bodymovin** [comment]
hi
unfortunately, the puppet tool is not supported by the plugin.
It's difficult to implement and wouldn't be too performant for real time rendering.

**Comment by cynthia-ryu** [comment]
Ok,looking forward it can be supported some day,thanks!

**Comment by noor3** [comment]
is it supported now?

**Comment by bodymovin** [comment]
Unfortunately it is not.

**Comment by anwargul0x** [comment]
delete Lottie Plugin admin
