### ISSUE TITLE
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

### ISSUE THREAD

**Issue by ArkRide** [bodymovin/bodymovin#33]
Hello! First of all, thank you for the great plug-in. It's a great tool for the designers knowing little of coding (like myself) to finally be able to integrate their animation on the web.
I'm having an issue whenever i try to play back my animation in the browser. Browser console is returning me "Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource." error.
I am unfortunately getting the same error whenever trying to playback instance animations from the plug-in's demo folder so I can't really tell what is the error here. 
Could it be windows 10 compatibility issues or due to the wrong installation?
Please, give me a suggestion as I am getting lost finding another solution.

**Comment by bodymovin** [comment]
@ArkRide Hi, are you loading your html through a web server? If you are loading it via file:// it won't have the permissions to load a json file.

**Comment by ArkRide** [comment]
@bodymovin No, I don't, unfortunately. My assumption was that JSON file, simply containing animation data - wouldn't be needed having a web server. Which one would you recommend to use - is it XAMP or WAMP that you would recommend?

**Comment by bodymovin** [comment]
@ArkRide You can load the animation data as a js file and you won't need a webserver.
If you want write me an email and I will send you an example on how to do that.

**Comment by ArkRide** [comment]
@bodymovin Thank you, I appreciate your help. E-mail sent.

**Comment by janarthananrajan** [comment]
@bodymovin 

Hi,

Even we are facing the same issue, can you help us converting json file to js

**Comment by bodymovin** [comment]
@janarthananrajan do you have a link with the issue?

**Comment by janarthananrajan** [comment]
Please find the files

https://drive.google.com/file/d/1YG7y2QqX_NcJUnOxjlgFb-TThaBMn9r7/view?usp=sharing

**Comment by bodymovin** [comment]
Can you share a link online with the implementation so I can see what error you're getting?

**Comment by rohitmore1995** [comment]
Hello...I am also facing the same issue...please suggest me what to do

**Comment by rafpan** [comment]
Hello bodymovin, i am facing the same problem with Access-Control-Allow-Origin. This is the structure:

 var params = {
        container: document.getElementById('lottie'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData
    };

    var anim;
    anim = lottie.loadAnimation(params);

**Comment by contactjijo** [comment]
I am facing the same issue 

Access to XMLHttpRequest at 'localhost:3000/**/***/***' from origin 'http://localhost:4200' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

I have added cors in node server and restarted. Still it is not working

**Comment by IamRohitMittal** [comment]
@contactjijo Did you get solution to your problem?

**Comment by GlebBigma** [comment]
Where to find a solution?

**Comment by Syammed2429** [comment]
> @ArkRide Hi, are you loading your html through a web server? If you are loading it via file:// it won't have the permissions to load a json file.

Hey, I'm loading my file through the web server, do you know any solution for that?
