### ISSUE TITLE
is there a limit to layers that bodymovin will export?

### ISSUE THREAD

**Issue by jessicayoungdesign** [bodymovin/bodymovin#330]
Hi, first off, this extension is amazing!

Secondly, I am having trouble exporting to an html demo. It seems there is a layer threshold/file size that bodymovin can handle and it wont show any layers that go past that threshold. I will attach my file, I am specifically having problems with "blue background dots" layer on the "Building only" composition, I realize there are a lot of paths within that layer, what are your suggestions to simplifying it so that it will show up in the html demo animation? You will see that I have a second comp in there named "Car loop", and the same thing is happening there, accept it is not showing any animation, it is a second version of the first comp where I need to have the "Build only" art in there but add more layers for the secondary animation. When I export "Car loop" for an html demo, it doesn't show any animation at all. I need to eventually deliver json files but at this point I am having to delete layers for the sake of file size. What are your suggestions for lowering the layer size without sacrificing whole layers?

[Drive thru_building only.aep.zip](https://github.com/bodymovin/bodymovin/files/870003/Drive.thru_building.only.aep.zip)

**Comment by bodymovin** [comment]
Hi, I've checked the Composition "Building Only". 
The reason for the missing parts are the Merge Paths on some of your layers. Sometimes AE adds some unnecessary merge paths to shape layers when converted from AI.
And Merge Paths are not supported by the plugin yet.
If you remove those extra paths, it should work.
For what I've seen, you need to remove them at:
- white cloud backgrounds/Drive-Thru Illo Outlines > Contents > Group 1: remove Group 1 and Merge Paths 1
- white cloud backgrounds/Drive-Thru Illo Outlines > Contents > Group 2: remove Group 1 and Merge Paths 1
- CFA logo/Drive-Thru Illo Outlines > Contents > Group 1: remove Merge Paths 1, Group 1 and Merge Paths 2
- white building bg/Drive-Thru Illo Outlines > Contents > Group 1: remove Path 2 and Merge Paths 1

let me know if it helps

**Comment by jessicayoungdesign** [comment]
WOW. That works! Thank you so much, it saved me from a lot of extra
frustration!

**Comment by jessicayoungdesign** [comment]
Hi again,

I'm having the same problem again on the "Car loop" animation though I
can't see what paths/ or merge paths I need to remove. Could you please
review the attached file on the "Car loop" composition?

**Comment by bodymovin** [comment]
they seem to be the same
- CFA logo/Drive-Thru Illo Outlines > Contents > Group 1: remove Merge Paths 1, Group 1 and Merge Paths 2
- white cloud backgrounds/Drive-Thru Illo Outlines > Contents > Group 1: remove Group 1 and Merge Paths 1
- white cloud backgrounds/Drive-Thru Illo Outlines > Contents > Group 2: remove Group 1 and Merge Paths 1
- white building bg/Drive-Thru Illo Outlines > Contents > Group 1: remove Path2 and Merge Paths 1

**Comment by jessicayoungdesign** [comment]
Hmm that's not it. Did you open the new file I sent in the last reply (it's
an updated file)? I made the original changes you sent and the "Building
only" comp exported just fine. I then duplicated the same building art into
the second comp "Car loop" so there wouldn't be any merge paths. I then
added some car animation layers and did a test render demo, but the car
animations did not show up. Which made me think that I had merge paths in
the car layer, but I didn't see them there.

**Comment by bodymovin** [comment]
I don't see any new attachment on the last message.
Can you share it again?

**Comment by jessicayoungdesign** [comment]
Were you able to figure out what wasn't  working?

**Comment by bodymovin** [comment]
I didn't get the second file. Can you share it?

**Comment by jessicayoungdesign** [comment]
Here you go. I sent it earlier, I wondering why the zip file didn't show up.

**Comment by bodymovin** [comment]
still didn't work. I guess it's because you're attaching it to an email?

**Comment by jessicayoungdesign** [comment]
would it help if I posted it to github again?

**Comment by bodymovin** [comment]
if it isn't the same file than the first post, yes

**Comment by jessicayoungdesign** [comment]
try this

[Drive thru_building only.aep 2.zip](https://github.com/bodymovin/bodymovin/files/870489/Drive.thru_building.only.aep.2.zip)

**Comment by bodymovin** [comment]
got it. I see 2 compositions called Car Loop. Is it the 18s or the 7s duration one?

**Comment by jessicayoungdesign** [comment]
the 18 second one

**Comment by bodymovin** [comment]
it seems to be working fine. What do you see missing?

**Comment by jessicayoungdesign** [comment]
ahh you're right, I was exporting the other old "car loop" file. It works, thank you so much for your help!

**Comment by bodymovin** [comment]
nice!

**Comment by rutapoint** [comment]
Hi there,

The pulgin seems to be great, but I'm still having massive issues trying to export a json/html file of my animation. Once I've converted my AI layers into shapes it simply won't render the whole thing. I've double checked the merge paths issue that was mentioned above, but can't seem to find anything that would fix the issue. Feeling quite desperate at this stage and would really appreciate anyone's help. The AE file is attached.


[CK - Interactions Animations - Convert To Shapes.aep.zip](https://github.com/bodymovin/bodymovin/files/1408119/CK.-.Interactions.Animations.-.Convert.To.Shapes.aep.zip)

**Comment by bodymovin** [comment]
@rutapoint Hi, if you delete the stroke effect from the layers, it will work fine.
I'll try to find a solution on my side for this.

**Comment by LeoMatcham** [comment]
hello I am just starting to experiment with bodymovin with an aim to send animations to clients with lottie etc.. I created a quick test. It works, creates a json file but only half the animation works. Have attached the file, the position animation works but the rotation on the seat does not seem to work. Any ideas as to why only half the animation is created as json?
[Unicycle.zip](https://github.com/airbnb/lottie-web/files/1739906/Unicycle.zip)

**Comment by bodymovin** [comment]
@LeoMatcham Hi, there is an issue when interpolating between two keyframes that have the same value.
If you change the middle keyframe in the seat rotation to 0.1 instead of 0, it should work fine.

**Comment by khaled3adel** [comment]
Hello Guys, 

First of all i just wanted to thank @bodymovin  for the great job making this plugin and not only this but making it easier for every animator to help their clients. 

Secondly, i just wanted to know the solution for that issue " I'm working on a project that has layers of text and some shape layers that is done in AE, but whenever i render my composition i got the files i asked for HTML & JSON but when i play the HTML file using any browser it doesn't show anything that is made through my composition, and when i check the JSON file and i don't have any background about coding it gives me some data which i searched and found out that all the animations are documented there.. Lastly there's no animation shown using the exported renders from Bodymovin. 

Kindly help me with that... 

Thanks,

**Comment by khaled3adel** [comment]
here's my project file if you needed to check anything about the issue 
[Table Github.zip](https://github.com/airbnb/lottie-web/files/3662319/Table.Github.zip)

**Comment by bodymovin** [comment]
@khaled3adel hi, I tried your animation and it seems to work fine. Can you share a link where it is not working?

**Comment by khaled3adel** [comment]
Hello, can i share a link via Gmail? I’m just new to the platform

**Comment by bodymovin** [comment]
sure

**Comment by khaled3adel** [comment]
Down below you will find an attached file for the exported files "HTML &
JSON" file.

**Comment by bodymovin** [comment]
Hi, attachments don't work when answering github posts.
You can send me an email directly.
My email is in the Readme of this repo.

**Comment by khaled3adel** [comment]
i sent you the attachment to your email. i really appreciate your help.

**Comment by Ryan-Erickson** [comment]
Having problems with my adjustment layer showing, I keep seeing the original layer color. Any help would be great, Thanks.
