### ISSUE TITLE
Problem With DUIK

### ISSUE THREAD

**Issue by maboox** [bodymovin/bodymovin#331]
hi . I have a project. for example a dancing fox. I animate that with DUIK but when I Render it to Json and Run it's not working anymore. also Animating With Puppet tools not working for me. I don't know why. I only can animate with Rotation and Scaling and ...

**Comment by bodymovin** [comment]
Hi
puppet tool is not supported
buit DUIK should be
can you share the .aep so I can take a look?

**Comment by maboox** [comment]
@bodymovin 
Thank you. Here is my source code that including the differents type of animations method.
I try with RubberHorse Script too, but it's not workling either,
[fox.zip](adobefamily.com/maboox/fox.zip)

**Comment by bodymovin** [comment]
@maboox the link is broken. can you share it again?

**Comment by maboox** [comment]
@bodymovin 
sure.
http://adobefamily.com/maboox/fox.zip

**Comment by bodymovin** [comment]
they seem to work fine.
Make sure that for Duik you select "Guided" in the settings.
and for Rubberhose you select "Guided" and "Hidden".
Those layers are not exported by default because of filesize.

**Comment by maboox** [comment]
@bodymovin
Great. 
it fixed :) 
thanks a lot for helping and also fast responding.

**Comment by maboox** [comment]
@bodymovin 
Hi again 
I have another problem with DUIK
the head is not moving and IDK why.
could u help me again? 
here is .AE file
http://adobefamily.com/maboox/animal.rar

Thanks

**Comment by bodymovin** [comment]
I've found the issue.
It's an expression that is not supported in the current version.I'll upload a new version this days with the fix.

**Comment by maboox** [comment]
@bodymovin 
ow thanks. I'm waiting for it

**Comment by BedirT** [comment]
Hi, I have the same issue with Duik. I have really simple puppet. Couldn't get it work... @bodymovin

**Comment by bodymovin** [comment]
@BedirT are you using the puppet tool with Duik?

**Comment by BedirT** [comment]
@bodymovin No, I didn't. But the problem is fixed. Apparently you do have to use it in server, otherwise in local, it is not working.

**Comment by karanmintzip** [comment]
hi . I have a project. that I'm facing problem with DUIK plugin. I've made bones with DUIK but when I Render it to Json and Run it's not working anymore. also Time reverse layer is not working for me. I don't know why. I can only animate position and other values. 
[misa_login_aep.zip](https://github.com/airbnb/lottie-web/files/1907160/misa_login_aep.zip)

**Comment by bodymovin** [comment]
@karanmintzip Hi, the puppet pin effect is not supported unfortunately.

**Comment by karanmintzip** [comment]
@bodymovin But you've mentioned above in other thread that DUIK works with Lottie.

**Comment by bodymovin** [comment]
@karanmintzip Yes, duikdoes work, but not the puppet pin effect which is not part of duik

**Comment by karanmintzip** [comment]
@bodymovin I might be wrong but, we can only rig by using puppet point and then converting them into bones.

**Comment by karanmintzip** [comment]
What is the solution for this?

**Comment by bodymovin** [comment]
duik can be used for IK applied to separate layers. In that case there is no need for the Puppet Pin effect.

**Comment by kedaryn** [comment]
But to make bones first of all you have to use puppet tool.. I have the same problem.. first I use puppuet tool than convert it to bones everything is fine untill i export it do json and animation doesnt work.. but in other animation only part of it works, do you know what can I do?

**Comment by Yusuf2k** [comment]
@bodymovin 

I have used Character Animation Toolkit for the character animation
After Rendering the body doesnt seem to animate only head is animated i have also checked Hidden layers and Guide layers but it didnt work

here is the file
[Skeleton Walking.zip](https://github.com/airbnb/lottie-web/files/6636322/Skeleton.Walking.zip)

**Comment by Asim740** [comment]
I have created animation with Duik Auto Rig & IK, with wiggle expression, during some characters are working fine, but some characters hand makes glitches, I don't know how to fix those small glitches?

**Comment by HaykazKhroyan** [comment]
I have an animation where I used DUIK for animating a character (with the use of pin-add bones function), and also Bend It CC. And they both not working unfortunately. Is there. a solution for this issue?
