### ISSUE TITLE
Cannot read property split of undefined

### ISSUE THREAD

**Issue by joshterrill** [bodymovin/bodymovin#332]
I downloaded an after effects project from here: https://videohive.net/item/minimal-abstract-eye-logo/19546691

I downloaded the bodymovin plugin, installed it, loaded the project. There was a composition called "Render" that showed the animation I wanted. So I selected that one, chose a destination, and pressed "Render". It gave me the following JSON file: http://joshterrill.com/bodymovin/data-1.json

I tried to replace the URL on this demo http://codepen.io/airnan/pen/Yqmyod with my URL, and it's saying `Uncaught TypeError: Cannot read property 'split' of undefined`

Could someone tell me how to fix this?

Edit: here's a forked version of that repo with the error showing: http://codepen.io/anon/pen/PpdYqN

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by joshterrill** [comment]
Here's a good drive link with the zip file of everything I got: https://drive.google.com/open?id=0B1hbSSWIRimHZFFYdkl2TDlTM28

**Comment by bodymovin** [comment]
Sorry, that template is using features the plugin doesn't support yet.

**Comment by AbdelrhmanMohamed** [comment]
what features support ?
