### ISSUE TITLE
Demo excluding layers of animation

### ISSUE THREAD

**Issue by jessicayoungdesign** [bodymovin/bodymovin#338]
Hello, 

I was having similar problems last week where I would export a demo and some layer would not show up, the problem was fixed by removing the merge paths. Now I am having the same problem and I have made sure to remove all merge paths, I'm not sure why it is still excluding some layers in the demo. Could you please diagnose this problem.

[Drive thru_building only.aep 3.zip](https://github.com/bodymovin/bodymovin/files/880581/Drive.thru_building.only.aep.3.zip)

**Comment by bodymovin** [comment]
hi
what composition is not working?

**Comment by jessicayoungdesign** [comment]
The car loop composition, its 25 seconds long.

**Comment by bodymovin** [comment]
It seems to be working fine here.
What are the missing layers?

**Comment by jessicayoungdesign** [comment]
Nevermind, I got it thank out.
