### ISSUE TITLE
Problem with Duik

### ISSUE THREAD

**Issue by Jeroennouwen** [bodymovin/bodymovin#339]
Hello, Bodymovin is a really great product, but I'm experiencing a hickup when exporting a character rigged with Duik. The animation seems to work in browser, but not the kinematics (arms waving).
Am i doing something wrong or is this not featured in Bodymovin? I've got 'guides' and 'hidden' checked Thanks for the help!
After effects file: https://cdn.nimbu.io/s/pd726a0/assets/1490875982417/test.aep

**Comment by bodymovin** [comment]
Hi, DUIK is supported, but puppet pin is not.
sorry :/

**Comment by Jeroennouwen** [comment]
Hi, thanks for the quick answer. I'm going to replace the puppet pin arms with rubber hoses, that should do the trick. Keep up the good work!
