### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by Tolmark12** [bodymovin/bodymovin#34]
Do you know which browsers support the technology bodymovin uses to animate svgs? It would be nice to list that in the readme.

**Comment by nathansearles** [comment]
I'd check out http://caniuse.com/#search=svg

**Comment by bodymovin** [comment]
@Tolmark12 It's svg and javascript. Unless you're using the fancier features, it should work fine on modern browser and up to IE9.
Although all browsers have some bugs, usually they are not noticeable.
The caniuse link is helpful to find out support.

**Comment by mcpdob** [comment]
Any idea why performance in Mozilla Firefox 43 on Mac OS El Captain slightly slower as in Chrome newest version please?
Seems to be the V8 JS engine in Chrome?

**Comment by bodymovin** [comment]
@mcpdob are you using the svg or the canvas renderer?
do you have an .ae I can take a look?
