### ISSUE TITLE
File working in demo - excluding features in JSON file

### ISSUE THREAD

**Issue by mlmaloney** [bodymovin/bodymovin#340]
Hey there - We are working on an animation for an app and we have the animation working and rendering correctly. We have tested it in the demo and see it all loading, however when we pass it over to the developer it is cutting out a certain layer. The logo isn't fully loading and missing two features, an eye and a beak on the store front. I've attached the zip file of the After Effects file and the screenshot of what our developer sends back. 

We believe there is an issue with layer: CFA logo/Drive-Thru Illo Outlines 2

Can someone please take a look and let us know what issue we are having? Thank you! 

[CFA AEP and Screenshot.zip](https://github.com/bodymovin/bodymovin/files/882995/CFA.AEP.and.Screenshot.zip)

**Comment by mlmaloney** [comment]
Also, please take a look at “Car loop 01”composition 28 seconds long

**Comment by bodymovin** [comment]
@mlmaloney hi, I'm exporting the animation and it seems to work fine.
Can you share a link where it is failing?

**Comment by mlmaloney** [comment]
Hey yes, correct. From our side we are seeing it work great but when we send it to the development team it's getting cut off. Screenshot attached to show what they see. 
<img width="341" alt="screen shot 2017-03-30 at 7 54 28 pm" src="https://cloud.githubusercontent.com/assets/26796706/24532011/b67b8040-1582-11e7-9052-71ec7974b74b.png">

**Comment by bodymovin** [comment]
I see, if it's failing using Lottie, you should contact them directly and attach the .aep.
They'll have a better idea of what might be wrong.
https://github.com/airbnb/lottie-android

**Comment by jessicayoungdesign** [comment]
Hi again,
I am working with mlmaloney, this is the problem layer (json file attached) we are recieving back from the development team. Can you decipher what to change/ remove in the After Effects file I have attached?


[Drive thru_building only.aep 4.zip](https://github.com/bodymovin/bodymovin/files/891996/Drive.thru_building.only.aep.4.zip)

[problemLayer.json.zip](https://github.com/bodymovin/bodymovin/files/891994/problemLayer.json.zip)

**Comment by bodymovin** [comment]
Does it fail on ios or on the web?

**Comment by jessicayoungdesign** [comment]
it's failing on ios
