### ISSUE TITLE
Text not looping

### ISSUE THREAD

**Issue by kenreal** [bodymovin/bodymovin#341]
Hey there!
First of all, thank you for this awsome app and you support about it!
I've never experienced a problem with bodymovin but this time i got a strange one,
When exporting a text source keyframed, all goes good but this layer only is not looping.
Just playing one time meanwhile others layers are looping.
Any idea ? :)

**Comment by bodymovin** [comment]
hi
can you share an .aep so I can take a look?

**Comment by kenreal** [comment]
Yes sure, i've juste sended you an email to your gmail !

**Comment by bodymovin** [comment]
I exported the composition "Composition 1" and it seemed to loop correctly.
Do you have a link where it is failing?

**Comment by kenreal** [comment]
Hey hey,
Did you push it a html offline mode project ? 
I just tested it again (with your last bdm build) and it is strangly still not looping in my project. (the text part).

**Comment by kenreal** [comment]
SOLVED
Problem related to the player version.
My animations were version 4.6.0 and the player was 4.4.27
-> Update player fix the problem.

thank you hernan!
