### ISSUE TITLE
Repeaters sizes do not match AE

### ISSUE THREAD

**Issue by custa1200** [bodymovin/bodymovin#343]
Hi,
I have tried to create a little sun animation as a first test but am finding that the rendered results are not the same as it appear in After Effects. First time really playing with After Effect so I am a little unsure of what I am doing to even be doing it incorrectly :) Any help or ideas would be appreciated.

[demo.html.zip](https://github.com/bodymovin/bodymovin/files/892197/demo.html.zip)

**Comment by TomHoenderdos** [comment]
Hi Custa1200 😄 
Can you also upload your AEP file, that helps him debug your problem 😉 !

@bodymovin: I also have been playing around with the new repeater and it didn't work without problems aswell 😞 
My AEP + demo.html is here: [repeater test.zip](https://github.com/bodymovin/bodymovin/files/892434/repeater.test.zip)

Thanks again for your work hernan 👍 !

**Comment by bodymovin** [comment]
I need to still work on repeaters for groups. I'm looking into it.
If you move the repeater inside the group it should work in the meantime.

**Comment by custa1200** [comment]
Looks like the fact I was using transforms is what killed it rather than anything else. Fixed it up and it's working now.

I'm actually looking forward to Radial wipes more than anything :)

**Comment by bodymovin** [comment]
@TomHoenderdos 
http://codepen.io/airnan/pen/BWXLGo
Working now :)
I'll upload it soon.

**Comment by TomHoenderdos** [comment]
Nice!

**Comment by itaydressler** [comment]
Hi, repeaters for shapes aren't working for me. Can you upload the ae file for your codepen example? @bodymovin 

Thanks for this great plugin again!

**Comment by bodymovin** [comment]
repeaters supported in version 4.9.0
