### ISSUE TITLE
Unable to execute script at line 1. bm_compsManager is undefined.

### ISSUE THREAD

**Issue by ReneBrainstud** [bodymovin/bodymovin#344]
90% of the times i try to open bodymovin from the windows tab it gives an error message and wont open further than the half-loaded interface. 
''Unable to execute script at line 1. File or folder does not exist"
When clicking 'ok' it gives me another error:
''Unable to execute script at line 1. bm_compsManager is undefined.''
Clicking 'ok' on the message gives me the same error over and over again. The only solution is to force quit AE and try again. Restarting my machine seems to do the trick, but doesn't work all the time. I tried reinstalling and upgraded to the latest version, but i keep getting the error. Im working on a late-2014 iMac.  Am i the only one with this problem?

**Comment by bodymovin** [comment]
I've seen this reported by one person before. But I haven't been able to reproduce it.
A couple of questions:
How did you install the plugin?
Did it work before?

**Comment by ReneBrainstud** [comment]
Okay, good to hear it's not a common problem! I've had these problems from the moment i installed it (around february 12). I have been able to use it, but have to try a few times before it stops giving the error.
I've installed it with the provided adobe link ( https://creative.adobe.com/addons/products/12557 )
And downloaded the ZIP containing the ZXP file.  Which i've installed using ZXP-installer.

**Comment by mheesakkers** [comment]
I also ran into this issue. I removed bodymovin plugin via the ZXP-installer and re-installed it. I can open After Effects again.

**Comment by mheesakkers** [comment]
Just ran into this issue agian. I installed via the ZXP installer and when I try to run the Bodymovin extension I get this error:
![image](https://cloud.githubusercontent.com/assets/5702106/25375874/81474448-29a2-11e7-8642-29fb9492e501.png)

Previously Bodymovin was working fine.

**Comment by bodymovin** [comment]
I think this issue is solved now. Reopen if not.

**Comment by cmascal** [comment]
I am having this issue now. The exact same error.

**Comment by bodymovin** [comment]
@cmascal plugin version?

**Comment by cmascal** [comment]
I just downloaded it today from Adobe so I assume the latest.

**Comment by cmascal** [comment]
<img width="698" alt="screen shot 2017-11-21 at 3 26 22 pm" src="https://user-images.githubusercontent.com/33879894/33097623-613516e8-ced0-11e7-92b8-6eea4aadebe6.png">

**Comment by atomicmedia** [comment]
Is it a permissions issue? I have the exact same problem, in fact I completely messed up my entire Adobe installation (which they then spent approximately an hour sorting out via remote desktop)
I'm running a late 2014 iMac, mac OS Sierra, After Effects CC(2018) and bodymovin 5.0.5.
Bodymovin installed via AE Scripts ZXP installer.
Issue:
Opened a project the Bodymovin window loads (the version number isn't set in the bottom corner.  (might be a clue) I can drag the window to resize it, mouse anywhere outside the window too, but, as soon as I mouse over the window I get the ''Unable to execute script at line 1. File or folder does not exist"
When clicking 'ok' it gives me another error:
''Unable to execute script at line 1. bm_compsManager is undefined.''

No amount of restarts have helped.
Interestingly a colleague with an exact same setup has never had a problem getting it to run.

Does it attempt to write to a folder or file that I might not have setup on my machine? Is there a permission I'm missing which is causing Bodymovin to not be able to read/write from a specific directory? - Any ideas / suggestions gratefully received.

p.s. I don't have issues with RubberHose etc. (which I have already tried uninstalling all to get BM to work)
