### ISSUE TITLE
Adrock demo aludes to the face bodymovin can be created declaratively in HTML

### ISSUE THREAD

**Issue by custa1200** [bodymovin/bodymovin#348]
Hey,
Looks like in the Adrock demo that it can be set up to be run declaratively from HTML but the demo doesn't seem to work at all. Should this work? Is there a list of data items in documentation somewhere?

**Comment by bodymovin** [comment]
I haven't updated the demos folder. They might not work right now.
I'll take care of it soon.

**Comment by custa1200** [comment]
Sadly this is actually a pretty desirable feature for us due to CMS not liking inline scripts put onto a page. Was happy when I spotted it in the demos :(

**Comment by javierjulio** [comment]
Yes so was I! I just noticed this but it does not seem to be working. I've been trying to walk through the code to see if its even supported. Would be great to know what the extent of is there.

**Comment by javierjulio** [comment]
@custa1200 I've verified the data attributes approach does work so you can use it. The demos just have the wrong path set for loading the bodymovin.js file.

**Comment by bodymovin** [comment]
yes, the data attributes should work correctly but you have less control of the animation.
Can't you load an external js file loading the animation?

**Comment by custa1200** [comment]
Hey, I'd love to be able to use using JavaScript but the CMS setup currently in use strips script elements. 😖 Not my choice unfortunately.

**Comment by bodymovin** [comment]
If it doesn't support js tags, you won't be able to load the bodymovin.js file either, right?

**Comment by custa1200** [comment]
Would be able to get it to add a single core JS file like bodymovin.js, but would be hard to be able to add other frequently updated JS scripts like what is required to instantiate a SVG where we need it. Need to work out the best way to spec what is required to make this easier in the CMS, but big company means easier said than done.
