### ISSUE TITLE
Missing Paths

### ISSUE THREAD

**Issue by custa1200** [bodymovin/bodymovin#349]
I have a simple icon which includes a clock that I have imported from AI. I have created a trim path to show a morning time, but the Clock body is not being exported even though visible in AE. Have included the files for reference.
[Missing Clock.zip](https://github.com/bodymovin/bodymovin/files/895335/Missing.Clock.zip)

**Comment by bodymovin** [comment]
you need to delete on layer "Clock", in contents > Group 1 and Group 2
the merge path and the path 2
