### ISSUE TITLE
Not Opening

### ISSUE THREAD

**Issue by peteringram0** [bodymovin/bodymovin#35]
I have installed bodymovin and i can see bodymovin under windows and extentions however clicking on it does not open up any windows.

Im running After effects CC 2015 and have set the network pref's and the registry key.

Any ideas?

**Comment by bodymovin** [comment]
@peteringram0 That usually means the registry key is not correctly set.
Are you on a mac or windows?

**Comment by peteringram0** [comment]
Im on mac, 

I have the following:

<img width="411" alt="screen shot 2015-11-22 at 15 19 24" src="https://cloud.githubusercontent.com/assets/6588942/11324532/7830ffa8-912c-11e5-880a-404a33e47cac.png">

Thanks for your help :)

**Comment by bodymovin** [comment]
@peteringram0 it seems right.
For Mac users it seems that instructions on this page work fine:
https://helpx.adobe.com/x-productkb/global/installingextensionsandaddons.html
Ignore the first part and go directly to "Install third-party extensions".
And where it says:
./Contents/Mac OS/ExManCmd --install .zxp
change it to:
./Contents/MacOS/ExManCmd --install bodymovin.zxp

**Comment by peteringram0** [comment]
Ive also tried that way and i get the error: 

➜  Adobe Extension Manager CC.app   ./Contents/MacOS/ExManCmd --install /Users/peter.ingram/Desktop/bodymovin-master/build/extension/bodymovin.zxp 
Failed to install, status = -403!
2015-11-22 15:34:29 : INFO  get service manager executable name

Any idea? Thanks for the help by the way.

**Comment by peteringram0** [comment]
Its suddenly working now :P No idea why lol. 

thanks for the help
