### ISSUE TITLE
Fill color doesn't work

### ISSUE THREAD

**Issue by foguetes** [bodymovin/bodymovin#351]
Hi,
I'm trying to create a button on a bodymovin animation where when I hover over a shape it changes the fill color

`#square:hover{
  fill: pink;
  stroke: pink;
  opacity:.5;
  }`

I made an example on codepen with a simple square shape:
http://codepen.io/Gundersun/pen/MpRBzm

All the attributes work except the fill. 

Can anyone tell me what's wrong with my code?

**Comment by bodymovin** [comment]
The fill attribute to the g tag has less precendence than the presentation attribute in the path tag.
if you want to override it, you need to set your style selector to this:
#square:hover path{
  fill: pink;
  stroke: pink;
  opacity:.5;
}

another way around is naming your fill property in AE with the "#square" id. That way it will be directly pointing to the path element.

**Comment by foguetes** [comment]
Thank you! It works now. 
Another question: how can I add a clickable url link to the shape?
I assume I have to either use javascript or I have to export each of the buttons into a separate file and then place them on a div.
Is there a simpler way I am not seeing?

**Comment by bodymovin** [comment]
You can add a name to the layer starting with a "#" or with a'.'
that was it will get exported with an id or class and you can target it with javascript.

**Comment by foguetes** [comment]
Do you have any examples?

**Comment by foguetes** [comment]
I created a repo with the files from this project:
https://github.com/foguetes/navbar
