### ISSUE TITLE
After Effects Gradient

### ISSUE THREAD

**Issue by RuNpiXelruN** [bodymovin/bodymovin#352]
Hi :) I've added a 'gradient ramp' to one of my solids i've created in After Effects but i'm afraid it doesn't come across to the browser. Is there a way of being able to do this??

Thanks, appreciate your hard work!
[ae_gradient_test.aep.zip](https://github.com/bodymovin/bodymovin/files/904371/ae_gradient_test.aep.zip)

**Comment by bodymovin** [comment]
can you use a shape with a gradient fill?

**Comment by RuNpiXelruN** [comment]
Yeah that's a great idea, and worked perfectly. Thanks! :)

Did you want me to close this issue??

Also, let me know if there's anything you need help looking into. I'm a dev at a digitial agency here in sydney, australia. Currently building a custom Polymer Component that wraps your library, for use here in our projects! Almost finished and will open source it for everyone and give you credit for what you've created here. :)

**Comment by bodymovin** [comment]
That sounds great. Whenever you can, please share the link.
Thanks!

**Comment by sssandor** [comment]
Hi, I tried with a gradient fill shape but it stays black and white, it doesn't exports the colours, the opacity and the animation of the gradient. Do you have any idea what to do?
Thx!

**Comment by bodymovin** [comment]
@sssandor did you try saving the .aep before exporting?

**Comment by sssandor** [comment]
:D that was it. Thanx
