### ISSUE TITLE
Stepped animation 

### ISSUE THREAD

**Issue by watziznehm** [bodymovin/bodymovin#354]
Hey there!

Just wondering if there is a way to emulated stepped animation. Right now when you lower the frame rate to say 15 fps it just makes the animation slower and doesn't actually give it that jumpy look if you know what I mean. It always seems to render at 24fps in browsers.

Any insight would be appreciated!

Thanks!

**Comment by bodymovin** [comment]
if you set anim.setSubframe(false) it will render at the actual framerate of the AE composition.
Let me know if this is what you need.

**Comment by watziznehm** [comment]
YES! That's perfect!

Thanks for the quick reply!
