### ISSUE TITLE
Text layer font-style changes whenever I change a separate text layer

### ISSUE THREAD

**Issue by davidlowe** [bodymovin/bodymovin#355]
I have two text layers, one without any text styling and one italicized.  Both text layers seem to be linked when I change one of their font-styles between normal and italics. It looks correct in AE, but when previewing with demo.html, they always share styles.

I'm new to AE and BodyMovin. I created a codepen to showcase the two behaviors. Thanks!

http://codepen.io/collection/DLRKgo/

**Comment by bodymovin** [comment]
I'll try to check wht is going on, but I'm not sure that text style is exposed to scripting.

**Comment by bodymovin** [comment]
closing, reopen if necessary
