### ISSUE TITLE
Animation Freezes with Multiple Trim Paths

### ISSUE THREAD

**Issue by Joebc** [bodymovin/bodymovin#357]
Hi,

My animation freezes at a certain point. I've discovered that a group of strokes with trim paths applied are causing the issue.

My project file is attached. There is a comp called 'error isolated' which is a stripped down version of the error.

Any ideas why this could be happening? Amazing plugin btw.

Thanks,

Joe

[BC SVG Animation V7.zip](https://github.com/bodymovin/bodymovin/files/910591/BC.SVG.Animation.V7.zip)

**Comment by bodymovin** [comment]
Hi, it seems to be working here.
what version of the player are you using?
do you have a link where it fails?

**Comment by Joebc** [comment]
I was using an old version of the player. Apologies my bad...

One more thing if you don't mind. The animation ends on a play symbol. I would like to able to change the fill colour on a hover action.

The layers used for the play button within AE are 'Circle play' and 'Play Fill White'. 

Here is the live animation: http://boldcontentvideo.com/

**Comment by bodymovin** [comment]
if you name your layer in After Effects starting with a "." or a "#" the layer will get exported with a className or id respectively.
So you can target that specific layer with css or javascript.
