### ISSUE TITLE
Bounce expression works on 4.5.9, but on 4.6.x its very fast and erratic

### ISSUE THREAD

**Issue by javierjulio** [bodymovin/bodymovin#358]
We have an avatar SVG that we perform two bounce animations on and it works great on 4.5.9 and earlier but we noticed then when upgrading to the latest version (4.6.3 but also confirmed on 4.6.0) we noticed the animation bounce is much faster and goes much further. We aren't really sure what's wrong. There sounds like some great improvements on 4.6.x so naturally we wanted to be on the latest. I figured I'd share this case as you might be interested in knowing what could be wrong. We sure are as we are baffled as to what the issue is, whether its our bounce expression or the bodymovin library. I've attached a zip of the data.json file.

[data.json.zip](https://github.com/bodymovin/bodymovin/files/914513/data.json.zip)

**Comment by bodymovin** [comment]
hi
can you share the .aep? I'm not sure what could be going on.

**Comment by javierjulio** [comment]
Sure, I've attached it.
[avatar1.aep.zip](https://github.com/bodymovin/bodymovin/files/914815/avatar1.aep.zip)

**Comment by bodymovin** [comment]
Fixed in v4.6.4
it was an issue with velocityAtTime and the frame rate.
thanks for reporting it!

**Comment by javierjulio** [comment]
@bodymovin thanks so much for looking into this! ❤️ I updated to using v4.6.4 and the issue is resolved. The animations even feel a little smoother. Thanks again for the help!
