### ISSUE TITLE
unable , line 107 undefined

### ISSUE THREAD

**Issue by msongz** [bodymovin/bodymovin#359]
download from create cloud 
macos 10.12.4
ae 14.1.057

**Comment by bodymovin** [comment]
can you send a screenshot of the plugin when that error shows up?
Is it during export?

**Comment by msongz** [comment]
@bodymovin 
![Uploading 屏幕快照 2017-04-13 下午2.31.47.png…]()

**Comment by msongz** [comment]
@bodymovin 
![2017-04-13 2 31 47](https://cloud.githubusercontent.com/assets/2059694/24992863/2c0f10f0-2056-11e7-8d50-a991f129e8aa.png)

**Comment by bodymovin** [comment]
So is this as soo as you try to open it?

**Comment by msongz** [comment]
@bodymovin yes,on extension start up

**Comment by bodymovin** [comment]
this is probably solved now. Reopen if not.
