### ISSUE TITLE
.destroy() method issue 

### ISSUE THREAD

**Issue by peteringram0** [bodymovin/bodymovin#36]
There is an issue on the later versions of the javascript file. Im not really sure whats causing it but my animation works fine on the 3.0.8 version.

example:
http://peteringram0.github.io/ninjabot/
https://github.com/peteringram0/ninjabot

If you change bodymovin.js script to the latest version when running .destroy and then .loadAnimation you can see in the DOM that the animation is running however it appears tiny or no images are loading. I have been looking though the commit log from the 29th and cant work out what has caused this.

Any ideas? 

Thanks :+1:

**Comment by bodymovin** [comment]
@peteringram0 yes, there seems to be an error. I'll fix it tonight.
thanks!

**Comment by peteringram0** [comment]
Ive spent half the day on it lol, good luck :+1:

**Comment by bodymovin** [comment]
@peteringram0 temporarily, you can pass a new object with the animation each time like so:
JSON.parse(JSON.stringify(nodHead))
JSON.parse(JSON.stringify(shakeHead))

**Comment by peteringram0** [comment]
Did you have any luck on finding a longer term solution for this please?

Thanks

**Comment by bodymovin** [comment]
@peteringram0 I found the issue, and I will upload a quick fix tonight.  
I will deploy a final fix on the next big update.
