### ISSUE TITLE
Shapes don't show when seeking the animation

### ISSUE THREAD

**Issue by cristian-d** [bodymovin/bodymovin#361]
Demo app: https://jsfiddle.net/karuvhw5/10/

To reproduce:
 - go to frame 0
 - click the middle of the seek bar: the top line is gone
 - click the end of the seek bar
 - click the middle again: the bottom line is gone

https://drive.google.com/file/d/0B0XgZ-gc-zz-T3djRXN5WTZjNWM/view

**Comment by bodymovin** [comment]
hi, can you share the .aep so I can take a look?

**Comment by cristian-d** [comment]
Sent by email

**Comment by bodymovin** [comment]
fixed in v.4.6.5
thanks for your help :)

**Comment by cristian-d** [comment]
Excellent! Thank you ;)
