### ISSUE TITLE
Animation Composer

### ISSUE THREAD

**Issue by custa1200** [bodymovin/bodymovin#363]
Hi I am just trying a free plugin called Animation Composer (https://misterhorse.tv) and while the demos included seem to render fine in the plugin they do not work in a browser. Using the latest 4.6.6 Bodymovin. The error I get is:

![screen shot 2017-04-18 at 12 30 22 pm](https://cloud.githubusercontent.com/assets/161224/25112162/c19c8b7c-2432-11e7-8862-19d1c529c63e.png)

**Comment by bodymovin** [comment]
I'm guessing the plugin has the expressions obfuscated.
Can you share the .aep?

**Comment by custa1200** [comment]
The demo .aep is in the download from their website in a package with the installer. Prob be easier to see what's going on by grabbing it from there.

**Comment by custa1200** [comment]
Looks like it might be the use of sliders?? I just tried using the Animation plugin on one of my own files that was rendering previously and was getting the same issue :(

**Comment by bodymovin** [comment]
Expressions are indeed encrypted, so they won't  work when exported unfortunately.
Maybe you can contact them and ask them if they can provide a non encrypted version?
