### ISSUE TITLE
Can't export my animation properly?

### ISSUE THREAD

**Issue by audreymgr** [bodymovin/bodymovin#364]
Hey there, sorry to come up with such a dummy issue but my animation doesnt seem to export properly through bodymovin: I use ease & wizz for my animation, and the expressions don't seem to go through? I also have a polygon in my animation that doesnt go through whatsoever. I tried changing the layer, the opacity etc but nothing makes it go through. I know I'm doing something wrong but I can't find out what

Many thanks!
Audrey
[test_target_11.json.zip](https://github.com/bodymovin/bodymovin/files/930659/test_target_11.json.zip)

**Comment by bodymovin** [comment]
hi, can you share the .aep so I can take a look?

**Comment by audreymgr** [comment]
Yeah sure, sorry its got a few compos there but the one that would interest you is background_animation

[PARSEC.aep.zip](https://github.com/bodymovin/bodymovin/files/932723/PARSEC.aep.zip)

**Comment by bodymovin** [comment]
I'm trying the animation and it seems to work fine. Can you share a link where it is failing?

**Comment by audreymgr** [comment]
Sorry its in a React Native app so can't share a link to that but basically in there my eases don't export nor the losange in the middle. Would you be aware of a problem from Lottie or React Native? Thanks a lot for your answers!!

**Comment by bodymovin** [comment]
I know Lottie doesn't support expressions yet.
Regarding the polygon I'm not sure, I think it should work. Are you trying it on Android or iOS?

**Comment by audreymgr** [comment]
Oh cool for lottie, ill stop using ease & wizz then -- we're trying on iOS

**Comment by bodymovin** [comment]
not sure if polygons are implemented in iOS yet. I think they're not.

**Comment by audreymgr** [comment]
interesting, alright i'll find a way around it then! thanks a ton!

**Comment by MbF-Sathya** [comment]
my animation is also not coming properly, like there is light green is applying in bit on the image and also some image part missing
