### ISSUE TITLE
Export animation using AI Layers

### ISSUE THREAD

**Issue by omanzano** [bodymovin/bodymovin#365]
My animation didn't work, how can i use the images folder in order to the animation works properly?. Thanks!
[icono 1 prueba tamaño.zip](https://github.com/bodymovin/bodymovin/files/930828/icono.1.prueba.tamano.zip)

**Comment by bodymovin** [comment]
hi, I see it working fine. where is it failing? Can you share a link?

**Comment by omanzano** [comment]
I'm trying to render this on mobile with  http://airbnb.design/lottie/

**Comment by omanzano** [comment]
do you know if the stroke effect is supported?

![screen shot 2017-04-20 at 12 00 57 pm](https://cloud.githubusercontent.com/assets/27740238/25242990/26475338-25c1-11e7-936c-698779150e89.png)
