### ISSUE TITLE
Doesn't render trimmed path layers

### ISSUE THREAD

**Issue by ottodesignfabrik** [bodymovin/bodymovin#366]
Hello

Bodymovin will render my AI layers (which I've converted to shape from vector) but not the layers with a Trim Path effect added to them. 

I am attaching the AE file:
[bodymovin-experiment01.zip](https://github.com/bodymovin/bodymovin/files/930855/bodymovin-experiment01.zip)

Thanking you in advance

**Comment by bodymovin** [comment]
Hi, I see the animation working fine, can you share a link where it fails?

**Comment by ottodesignfabrik** [comment]
Here are the files I used to test on my localhost. As you may (or may not) see the head is animated but the surprise bursts are not visible.
[driver.zip](https://github.com/bodymovin/bodymovin/files/931578/driver.zip)

I'm also attaching an MOV of the result.
[driver.mov.zip](https://github.com/bodymovin/bodymovin/files/931579/driver.mov.zip)

Thanks!

**Comment by bodymovin** [comment]
I see, can you use the svg renderer instead of the html?
the html renderer has some issues with strokes I need to fix.

**Comment by ottodesignfabrik** [comment]
That fixed it. Thanks so much!
