### ISSUE TITLE
AE mask  and Gradient Overlay，is not support？helpppppp

### ISSUE THREAD

**Issue by shooo133** [bodymovin/bodymovin#367]
I use the  Gradient Overlay on a Shape Layer ，then render it，but it's not work

the shape layer just two color——white and black

and i use the mask，it's not work too。

I just want use Gradient color on a shape layer，please help me guys~~~~

**Comment by bodymovin** [comment]
save the .aep before exporting gradients, because the data is taken from the .aep file.
Regarding the mask I don't know what could be going on.
Can you share the project?

**Comment by shooo133** [comment]
@bodymovin yeah~~! thanks ,i will give you my project , please help me render it~~

**Comment by shooo133** [comment]
@bodymovin  project in your mail ~~

**Comment by cirnoc** [comment]
ohhh~~so do i ,i use the mask on a Shape Layer,it's not work too!

**Comment by bodymovin** [comment]
@shooo133 layer styles are not supported and the strok effect only to a certaing extent.
I suggest that you use stroke shapes and gradient strokes.
It should work as you need.

**Comment by bodymovin** [comment]
@cirnoc can you give me more information about it?

**Comment by cirnoc** [comment]
@bodymovin thank u for your reply
 i got it,it works now, because i use the "fill effect"

**Comment by shooo133** [comment]
@bodymovin thank you >....i will try....
