### ISSUE TITLE
'Destroy' weird behavior

### ISSUE THREAD

**Issue by cristian-d** [bodymovin/bodymovin#369]
Demo app: https://jsfiddle.net/Lb4o3g4b/10/

To reproduce: 
- seek to the end of the animation (more than frame 140)
- click 'destroy&recreate'
https://drive.google.com/open?id=0B0XgZ-gc-zz-XzdmS2F1bWR2OG8

Another weird behavior that I have experienced for the same animation (curved right block, misplaced stroke):  https://drive.google.com/open?id=0B0XgZ-gc-zz-MUdFWTVVZzBIdE0

**Comment by cristian-d** [comment]
For the curved block, at the same position I have 

> path fill="rgb(56,118,29)" fill-opacity="1" d="M0 0 M100,-30.1545 C100,-30.1545 100,30.1545 100,30.1545 C100,30.1545 -100,30.1545 -100,30.1545 C-100,30.1545 -100,-30.1545 -100,-30.1545 C-100,-30.1545 100,-30.1545 100,-30.1545z"></path>

without the bug, and

> path fill="rgb(56,118,29)" fill-opacity="1" d="M0 0 M-100,-30.1545 C-100,-30.1545 -100,30.1545 100,30.1545 C100,30.1545 -100,30.1545 -100,30.1545 C-100,30.1545 -100,-30.1545 -100,-30.1545 C-100,-30.1545 -100,-30.1545 -100,-30.1545z"></path>

with the bug

**Comment by bodymovin** [comment]
fixed in version 4.6.7
thanks!
