### ISSUE TITLE
Expressions in Rotation

### ISSUE THREAD

**Issue by themarten** [bodymovin/bodymovin#373]
Hi, it seems as if some expressions in Rotation don't work or render right. They work fine in After Effects but when rendered all images are static and placed in top left corner, instead of where they should be placed on screen.

This example doesn't Render right if used in Rotation: wiggle(3,10)

Nor this (using a Null layer's opacity to trigger rotation):
if (thisComp.layer("Running").transform.opacity > 1){
veloc = 10;
amp = 30;
freq = 3;
decay = 0//no decay
y = amp*Math.sin(veloc*time)/Math.exp(decay*time)
value + [y]
}else{
value + [0]
}

But if you reference another layers properties (except rotation) it uses those numbers, like: thisComp.layer("Wiggle").transform.scale[0]

But not if you reference their rotation, like:
thisComp.layer("Wiggle").transform.rotation

Any ideas?

**Comment by bodymovin** [comment]
hi, wiggle is not yet supported by the player.
It's not easy to replicate.

**Comment by bigxixi** [comment]
hi,
for animation with some complex expressions my solution is to 'bake' them into keyframes, see
https://helpx.adobe.com/after-effects/using/expression-basics.html#convert_an_expression_to_keyframes

but the problem is the json file exported would be heavier. You can try the smoother to reduce the keyframe number, then the json will be smaller.(note: the smooth result may not 100% match, replay the animation to check again)

**Comment by themarten** [comment]
Thanks for the quick replies.

Wiggle looks fine in the demo.html file, but only for Position and Scale. (I'm not a programmer so I haven't verified on an ios device).

But wiggle can be made to work for Rotation if you use another layers Position or Scale values, like: thisComp.layer("Wiggle").transform.scale[0]
Though obviously not as good as being able to add it directly to the Rotation of the layer itself.

Thanks for the tip about baking.

**Comment by bodymovin** [comment]
@themarten can you share the .aep so I can take a look?

**Comment by themarten** [comment]
Here's an aep.
[RotationExample_2.zip](https://github.com/bodymovin/bodymovin/files/950620/RotationExample_2.zip)

Uses Wiggle on the Running layer Scale, used by Leg1 for rotation.

If you add Wiggle directly to the rotation of a layer the file doesn't play in the demo.html.
I think this happens with any expression in Rotation (that doesn't reference another layer). Like oscillation for example. Also breaks the file.
amp = 20;
freq = 3;
y = amp*Math.sin(time*freq*Math.PI*2);
value + [y]

**Comment by bodymovin** [comment]
I found the issue, wiggle was not working with properties of one dimension.
Nevertheless, wiggle doesn't translate well from AE, it's just a placeholder so animations don't break.

**Comment by themarten** [comment]
Great that you found the bug.
Thanks for looking into this so quickly. Now I know that baking keyframes is the way to go for now (thanks for the tip bigxixi).

**Comment by mahsakhaje** [comment]
what did you do to solve the issue?

**Comment by themarten** [comment]
Haven't worked with it for years so the only solution I found was to bake keyframes. Can't help you any more. Good luck.
