### ISSUE TITLE
subtract merge mode not working

### ISSUE THREAD

**Issue by shSina** [bodymovin/bodymovin#375]
merge path not working correct , subtract or intersect not working at all
the output in adobe after effect:
![1](https://cloud.githubusercontent.com/assets/478063/25316157/d0368118-2876-11e7-93ce-bd4cb936516a.gif)
the output exported :
![2](https://cloud.githubusercontent.com/assets/478063/25316175/0c2ce6e4-2877-11e7-9bc1-9e8099529559.gif)

**Comment by bodymovin** [comment]
yes, merge path is not yet supported.

**Comment by vitpankin** [comment]
It's been 4 years, still unsupported?!
