### ISSUE TITLE
Ae Example

### ISSUE THREAD

**Issue by maboox** [bodymovin/bodymovin#376]
hello 
I'm working on a project, and I stuck in it.
I saw the examples in codepen.io , could you please Give me "Bacon Pancakes" or "Perri corn. a dog that was a unicorn" After Effect Source? I want to see how it works when some Shapes Are bending, Cause I can't bend things with puppet tools and I really don't have any other solution.
Thanks again :)

**Comment by bodymovin** [comment]
hi, puppet tool is not supported.
Those shapes have many keyframes in order to achieve that animation
You can see the bodymovin .aep example on the projects folder
https://github.com/bodymovin/bodymovin/tree/master/projects

**Comment by maboox** [comment]
thanks a lot :)
