### ISSUE TITLE
Animation JSON does not render correctly in iOS

### ISSUE THREAD

**Issue by mihaelaplesa** [bodymovin/bodymovin#377]
Hi, 
I'm having a issue with animation rendering in iOS.
I'm doing the following steps:
1. Export animation as JSON 
2.The animation is rendered correctly in web (see attached)
3. When try to load the animation in iOS with Airbnb Lottie the animation is not rendered correctly. (see attached image)

[test.zip](https://github.com/bodymovin/bodymovin/files/951401/test.zip)
![iosanimation](https://cloud.githubusercontent.com/assets/27953151/25333252/32712894-28f2-11e7-95f5-72e0f75fd7a6.png)

Can you please help me with that? Is it a bodymovin issue or Lottie?

**Comment by bodymovin** [comment]
it's probably a Lottie issue if you can see it correctly in web.
I suggest that you contact them directly.
