### ISSUE TITLE
LAGGING ANIMATION, SPLIT COMPOSITIONS & MISSING GLOW/BLUR ON EXPORT

### ISSUE THREAD

**Issue by fahudahmed** [bodymovin/bodymovin#378]
Hello Hernan/Team,

We are facing some difficult issues to crack when exporting the 2 compositions (attached), which use vector shapes and wiggle expressions.

Composition 'C' plays correctly in After Effects and even after a .MOV render, however when we export with bodymovin and is integrated in html, the animations seems to be split down the middle and creating a tiled effect which reveals a line break and overlap of what appears to be 2 compositions, not the one.

Composition 'T' uses a high velocity wiggle to create a vibrating effect of all these shapes and plays perfectly in AE aswell as in a video render, however it suffers extreme lag on playback when exported with bodymovin and viewed via HTML.

Could you kindly take a look at the attached AE files and even have a go at exporting yourself to see where we are going wrong!

We cannot tinker with the number of assets as we need the randomised movement on each one, hence the high number of vector shapes. We have exported a couple other animations similar to these with high volumes of shapes, and they have worked perfectly.

We look forward to your speedy response!

Regards,
Fahud

[01_SHAPE_ANIMATIONS_240417_FOR HERNAN.zip](https://github.com/bodymovin/bodymovin/files/951808/01_SHAPE_ANIMATIONS_240417_FOR.HERNAN.zip)

**Comment by fahudahmed** [comment]
Also, is there a reason why blurs and glows on vector shape layers do not appear or effect the output with Bodymovin. It renders it out as a vector shape with solid edges and doesnt include the glow or blur effect?

**Comment by bodymovin** [comment]
Wiggle has very bad performance and is not really reliable.
I added the function so animations don't break, but I would advice against using it.
On the T Master animation, I see you have around 2317 animated paths, it's probably too much to render in real time.
regarding the C animation can you share a link where it looks like that? I can't seem to reproduce it.

**Comment by zmax91** [comment]
Hello Hernan,

How about the blur/glow effects? Is there any way to make bodymovin to render them?

**Comment by fahudahmed** [comment]
Hello,

It seems bodymovin doesn’t play nicely with any CC effects in AE. The way I tackled the ‘glow’ issue was by applying an alpha matte with a blur to recreate the effect. Hope this helps!

Cheers,
F
