### ISSUE TITLE
Ae to SVG? 

### ISSUE THREAD

**Issue by jcksnptr441** [bodymovin/bodymovin#379]
Is it possible to export as .SVG instead of .JSON or .JS?

**Comment by Jeremy-Knudsen** [comment]
You could save out the SVG from what gets generated by the bodymovin player.

**Comment by foguetes** [comment]
Right, you could even do that by opening the json in the preview player and export the SVG, but you'd have to that manually, frame by frame. There should be an easy, quick way of exporting an svg sequence. Then we'd be able to create an svg sprite as an alternative to the bodymovin js.

**Comment by GitHubianin** [comment]
@foguetes and how to export the svg frame by frame manually? which player should I use and what should I do exactly?
