### ISSUE TITLE
Trim Multiple Shapes setting not respected

### ISSUE THREAD

**Issue by atyndall** [bodymovin/bodymovin#38]
When the "Trim Multiple Shapes" setting is set to "Individually" for a trim over a set of paths, bodymovin still behaves as if the setting is set to "Simultaneously".

Expected view (animated gif):
![working](https://cloud.githubusercontent.com/assets/1833303/11435360/c4151e7c-9514-11e5-8ffa-9cae6e1a6662.gif)

Actual view (animated gif):
![broken](https://cloud.githubusercontent.com/assets/1833303/11435371/d889dcd0-9514-11e5-8caf-8fae21bbf34c.gif)

Sample AE project file; https://www.dropbox.com/s/xltuzaqlj6g8bgv/38.aep?dl=0

Using build 25351995f4ad01e1b5194a5ba55787a3228e912f in After Effects CC 2014.0

**Comment by bodymovin** [comment]
@atyndall  yes, individual trim is not supported yet

**Comment by atyndall** [comment]
@bodymovin Thanks for letting me know. Is support for it planned in the near future? If not, I'll need to rework the comp to not use the effect.

**Comment by yozef** [comment]
This has been implemented in v 4.5.4
