### ISSUE TITLE
Mask not supported?

### ISSUE THREAD

**Issue by RuNpiXelruN** [bodymovin/bodymovin#383]
Hi, i've added a mask to one of my shapes but it doesn't seem to be coming accross in the render. I have the latest version of BodyMovin. Please see the ae file below. 

Oh and thanks for all your hard work!! Love what you've done here :)
[planets.aep.zip](https://github.com/bodymovin/bodymovin/files/957015/planets.aep.zip)

Justin

**Comment by bodymovin** [comment]
Hi, masks are supported, but masks' feather is not unfortunately.
