### ISSUE TITLE
3D layer is not supported？

### ISSUE THREAD

**Issue by suhehe** [bodymovin/bodymovin#384]
I use 3d layer in my AE project, beacuse I need some 3d transform. But when I rend it, It doesn't work and log an error: 
Unable to execute script at Line 297. Undefined is not an object
If I turn off the 3d layer it could work again. But I really need those 3d transform, what should I do?

**Comment by bodymovin** [comment]
hi
can you share the .aep so I can take a look?

**Comment by suhehe** [comment]
Thx for help!
I can't upload zip file here, so I sent a email to you.

**Comment by bodymovin** [comment]
Hi, the stroke effect is not supported on the html renderer, which you need for 3d transformations.

**Comment by suhehe** [comment]
It's stroke effect or 3d transformations not supported?

**Comment by bodymovin** [comment]
the bug will be fixed on the next release.
stroke effects is not supported, though.
