### ISSUE TITLE
Gradient Color overwritten by other animations

### ISSUE THREAD

**Issue by SundancePioneer** [bodymovin/bodymovin#385]
I am currently working in a project that works with duplicated comps where the animation gets slightly changed - the layers in the comps use the same gradients and names. 

When uploading the .json Animations to the page, some of the gradient colors were overwritten by other .json animations previously loaded - i had to rename the "Gradient Fill" group inside the shape layer content in order for it to work. 

Is there a way to circumvent this issue easier?

**Comment by bodymovin** [comment]
Can you share the .aep?
For gradient info, I have to use the .aep file and look for the gradient data with regular expressions. If I can't differentiate a gradient path to another, I have no way of getting theh right one.
If you share the .aep I'll see if I can improve the regexes.

**Comment by SundancePioneer** [comment]
Hi - sorry for forgetting to reply. Actually, assigning names to the gradients is helpful for other intents and purposes as well, so i changed the setup. I don't have the original file with the gradient problem anymore, sorry. If it ever turns up again, i will send it to you!
