### ISSUE TITLE
IDIOTS complete guide for blondes-and persons with no code know - how--- HELP!

### ISSUE THREAD

**Issue by christina-jade** [bodymovin/bodymovin#386]
IS there? Or could someone please point me...in the direction of a complete idiots guide from installing this little plugin/extension thingy. to getting it to work ....
My goal is to output to html 5  from after effects i have extension installed ,animation completed . select - windows--extension--Bodymovin-- and ..errmmmm   ..hmmm i fiddle around  select render and it renders out ....and.. eermm nothing.. do I need to do  something else ? add something.. I HAVE looked at the 'how to manual.. hhmmm ..I'm not a web /coding person.. i just make small fun animations..a nd i this case want it to be able to  put out as a html 5  thingy-wots it      LOL HA HA  i really am out of my depth, maybe a bullet point help... or a how me video on you ube ?

**Comment by ReneBrainstud** [comment]
Maybe this can be helpful? 
https://www.youtube.com/watch?v=FYOOucjdnkY
