### ISSUE TITLE
Uncaught ReferenceError: width is not defined

### ISSUE THREAD

**Issue by jahanzaibajmal** [bodymovin/bodymovin#389]
![screenshot 5](https://cloud.githubusercontent.com/assets/11048815/25568860/507b708c-2dc1-11e7-96f2-808f0a724c29.png)

**Comment by bodymovin** [comment]
hi, width on expressions is not supported yet.

**Comment by jahanzaibajmal** [comment]
So how is it possible to export 3d object with animation. Cause I really need that.

**Comment by jahanzaibajmal** [comment]
Trying to pull this pyramid spinning.

![image](https://cloud.githubusercontent.com/assets/11048815/25576704/b0e26544-2e15-11e7-808f-c6ae42b32ecd.png)

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by bodymovin** [comment]
hi, I've added "width" and "height" support for solids and I will upload it on the next release.
Nevertheless, 3d support is really basic for now. 3d lights won't work, so I don't think it will help you on your case.
I'd suggest that you try something like Three.js for this type of animations.

**Comment by jahanzaibajmal** [comment]
@bodymovin any guides how to use three.js with after effect?
