### ISSUE TITLE
Masks that do not affect AE composition affect bodymovin output

### ISSUE THREAD

**Issue by atyndall** [bodymovin/bodymovin#39]
Some compositions produces a blank bodymovin export when the "Masks" section of the shapes layer is present. It appears that bodymovin incorrectly interprets the non-effectiveness of these masks.

Expected output:
![working](https://cloud.githubusercontent.com/assets/1833303/11435530/6e3756c6-9516-11e5-96ff-bb9426dcac6d.png)

Actual output: Blank image

Sample AE project file; https://www.dropbox.com/s/jaie7kqj7pxafkl/39.aep?dl=0

Using build 25351995f4ad01e1b5194a5ba55787a3228e912f in After Effects CC 2014.0

**Comment by bodymovin** [comment]
@atyndall I'm getting those masks as difference masks when exporting them. I can see on the .ae project they don't have a mode. How did you do that?

**Comment by atyndall** [comment]
@bodymovin I was sent the .ae by a designer, and my AE upgraded it from CS6 to CC 2014 on open. I'm not entirely sure how it got to be this way unfortunately.

Perhaps it's a bug in AE?

**Comment by bodymovin** [comment]
@atyndall did you find a workaround for this?

**Comment by atyndall** [comment]
@bodymovin I did, the masks were empty so I just deleted them. Found it strange though.
