### ISSUE TITLE
Updating property values after loading animation?

### ISSUE THREAD

**Issue by ssanthos** [bodymovin/bodymovin#390]
Is there a way to update properties on layers (like the transform/opacity/fill) after loading the animation?

I saw this demo of an interactive "hand" - http://codepen.io/airnan/pen/pyMgzN

But when I forked this pen (http://codepen.io/ssanthos/pen/VbpwmY), and swapped out the bodymovin build to the latest one, and now the hand isn't interactive. Am unable to shake the hand anymore.

https://github.com/bodymovin/bodymovin/issues/291
^ Comments on this issue suggest that as long as the values are converted to keyframed values (with same values at the start and the end), they can be updated during playback.

Is the support for updating values after loading the animation not available anymore?

Have a feeling I'm missing something very basic here.

**Comment by bodymovin** [comment]
Hi, that workaround doesn't work anymore indeed.
Now you need to create two keyframes where the first and the last value are different from each other.
Just a detail, if the property is spatial, make sure the spatial interpolation is linear between them.

**Comment by ssanthos** [comment]
Superb! Just tested it out and was able to get for spatial properties as well as properties like stroke/fill etc during playback.

Thanks a ton. Love this library!

**Comment by maximus8891** [comment]
Does this approach not work any more?

**Comment by bodymovin** [comment]
@maximus8891 Yes, it should still work

**Comment by maximus8891** [comment]
@bodymovin I've made a pen: https://codepen.io/maximus8891/project/editor/DxGBkV where it doesn't work if I change the end position after the animation was created. The version is 5.1.4. The way I change it is as follows:

```javascript
// Chaning the property before applying works.
// anim.layers["0"].ks.p.k["0"].e = [100, 500, 0];

const animItem = bodymovin.loadAnimation({
    wrapper: document.querySelector('.container'),
    animType: 'svg',
    loop: true,
    autoplay: true,
    animationData: anim,
    rendererSettings: {
        preserveAspectRatio: 'xMidYMid slice'
    }
});

// This does not work
setTimeout(_ => {
    animItem.animationData.layers["0"].ks.p.k["0"].e = [100, 500, 0];
}, 3000);

```

The only place where the properties are read from the data is here https://github.com/airbnb/lottie-web/blob/master/player/js/elements/helpers/TransformElement.js#L6
I could not find where it re-reads the animation data.

**Comment by bodymovin** [comment]
@maximus8891 I see, the problem is that for position, if translation is not linear, the interpolated values get cached for performance.
In your case, translation is almost linear but it surpasses the "linearity" threshold.
I'll reduce it on the next build because it seems to be a floating point issue.

**Comment by alejost848** [comment]
@maximus8891 Did you find a way to solve it? I double checked that I was using linear spatial interpolation and having one keyframe at the start and other at the end with a slightly different value, but using `5.4.1` it does not work. If I try an old version like `4.6.9`, modifying animationData works as expected. Thanks.

**Comment by maximus8891** [comment]
@alejost848 I did not use this approach in the end. Fortunately, in my case I only had to change the animation json before I fed it into lottie and did not have to modify after.

**Comment by bodymovin** [comment]
@alejost848 you might want to take a look at https://github.com/bodymovin/lottie-api for manipulating values in runtime.
