### ISSUE TITLE
2.5D animation does not render correctly in IE

### ISSUE THREAD

**Issue by rolandzwaga** [bodymovin/bodymovin#391]
Hi there,

try running this animation in IE11 or Edge and then compare it to Chrome or Firefox:

var animationData = {"v":"4.6.3","fr":25,"ip":0,"op":101,"w":1000,"h":1000,"nm":"2.5D Test 01","ddd":1,"assets":[],"layers":[{"ddd":1,"ind":1,"ty":3,"nm":"Null 1","ks":{"o":{"a":0,"k":0},"rx":{"a":0,"k":0},"ry":{"a":0,"k":0},"rz":{"a":0,"k":0},"or":{"a":1,"k":[{"i":{"x":0.833,"y":1},"o":{"x":0.333,"y":0},"n":"0p833_1_0p333_0","t":0,"s":[0,0,0],"e":[0,180,0],"to":[0,0,0],"ti":[180,0,0]},{"i":{"x":0.833,"y":0.999},"o":{"x":0.167,"y":0},"n":"0p833_0p999_0p167_0","t":25,"s":[0,180,0],"e":[90,270,0],"to":[0,0,0],"ti":[270,0,0]},{"i":{"x":0.833,"y":0.999},"o":{"x":0.167,"y":0.001},"n":"0p833_0p999_0p167_0p001","t":50,"s":[90,270,0],"e":[270,0,0],"to":[0,0,0],"ti":[0,0,0]},{"i":{"x":0.833,"y":1},"o":{"x":0.167,"y":0.001},"n":"0p833_1_0p167_0p001","t":75,"s":[270,0,0],"e":[0,0,0],"to":[0,0,0],"ti":[0,0,0]},{"t":100}]},"p":{"a":1,"k":[{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":0,"s":[500,500,1591],"e":[500,500,3335],"to":[0,0,290.666656494141],"ti":[0,0,0]},{"i":{"x":0.667,"y":1},"o":{"x":0.333,"y":0},"n":"0p667_1_0p333_0","t":25,"s":[500,500,3335],"e":[500,500,1591],"to":[0,0,0],"ti":[0,0,290.666656494141]},{"t":100}]},"a":{"a":0,"k":[50,50,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"ip":0,"op":250,"st":0,"bm":0,"sr":1},{"ddd":1,"ind":2,"ty":1,"nm":"Red Solid 1","parent":1,"ks":{"o":{"a":0,"k":100},"rx":{"a":0,"k":0},"ry":{"a":0,"k":0},"rz":{"a":0,"k":0},"or":{"a":0,"k":[0,0,0]},"p":{"a":0,"k":[50,50,1000]},"a":{"a":0,"k":[960,540,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"sw":1920,"sh":1080,"sc":"#cb202c","ip":0,"op":250,"st":0,"bm":0,"sr":1},{"ddd":1,"ind":3,"ty":1,"nm":"Orange Solid 1","parent":1,"ks":{"o":{"a":0,"k":100},"rx":{"a":0,"k":0},"ry":{"a":0,"k":0},"rz":{"a":0,"k":0},"or":{"a":0,"k":[0,0,0]},"p":{"a":0,"k":[50,50,-1000]},"a":{"a":0,"k":[960,540,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"sw":1920,"sh":1080,"sc":"#ed7125","ip":0,"op":250,"st":0,"bm":0,"sr":1},{"ddd":1,"ind":4,"ty":1,"nm":"Orange Solid 2","parent":1,"ks":{"o":{"a":0,"k":100},"rx":{"a":0,"k":0},"ry":{"a":0,"k":0},"rz":{"a":0,"k":0},"or":{"a":0,"k":[0,270,0]},"p":{"a":0,"k":[-950,50,0]},"a":{"a":0,"k":[960,540,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"sw":1920,"sh":1080,"sc":"#f8ab1b","ip":0,"op":250,"st":0,"bm":0,"sr":1},{"ddd":1,"ind":5,"ty":1,"nm":"Red Solid 2","parent":1,"ks":{"o":{"a":0,"k":100},"rx":{"a":0,"k":0},"ry":{"a":0,"k":0},"rz":{"a":0,"k":0},"or":{"a":0,"k":[0,270,0]},"p":{"a":0,"k":[1050,50,0]},"a":{"a":0,"k":[960,540,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"sw":1920,"sh":1080,"sc":"#e54b27","ip":0,"op":250,"st":0,"bm":0,"sr":1}]};
    var params = {
        container: document.getElementById('bodymovin'),
        renderer: 'html',
        loop: true,
        autoplay: true,
        animationData: animationData
    };

    var anim;

    anim = bodymovin.loadAnimation(params);

You'll see that in Chrome and FF it'll look fine, but in IE/Edge it looks as if its zoomed in heavily.
When you change the renderer to svg or canvas, chrome and FF exhibit the same behavior.

Hope anyone can tell me if I'm doing anything wrong or if this might be a bug.

Thanks in advance,

cheers,

Roland

**Comment by bodymovin** [comment]
hi, can you share the .aep file?

**Comment by rolandzwaga** [comment]
Here you go, thanks a lot for your quick response!

[BODYMOVIN 2.5D TEST.zip](https://github.com/bodymovin/bodymovin/files/967962/BODYMOVIN.2.5D.TEST.zip)

**Comment by bodymovin** [comment]
I have to look further into it. But it seems edge is not handling perspective correctly.
Have you tried how it looks on safari?

**Comment by rolandzwaga** [comment]
No, I haven't, I don't have acces to a Mac right now, so its difficult for me to check...

**Comment by rolandzwaga** [comment]
By the way, Chrome and Firefox have the same behavior when setting the renderer to svg or canvas. Only renderer=html works correctly, in our experience.

**Comment by bodymovin** [comment]
yes, 2.5d is only supported by the html renderer.
But Edge's behavior is not exactly the same as using the other renderers.

**Comment by rolandzwaga** [comment]
Aha, I see, sorry for the confusion ;)
