### ISSUE TITLE
Reverse Animation only in Safari

### ISSUE THREAD

**Issue by DavidEscalante** [bodymovin/bodymovin#392]
Im running an animation made with Bodymovin for the **desktop** version of this site:
http://davidescalante.businesscatalyst.com/public_storage/franies/

If you watch it on Chrome, it looks fine, but if you watch in on Safari, it plays on reverse.

Here is the After Effects file:
https://www.dropbox.com/s/8mn24w9lfd4fvmx/phone3.aep?dl=0

And here is the .json file:
http://davidescalante.businesscatalyst.com/public_storage/franies/index.hyperesources/pixel.json

**Comment by bodymovin** [comment]
Apparently, Safari and Chrome manage dashoffsets differently when setting negative values.
I need to see if I can find a workaround for it.
Meanwhile, can you use positive values or trim paths for the same effect?
