### ISSUE TITLE
merge path

### ISSUE THREAD

**Issue by cirnoc** [bodymovin/bodymovin#395]
Hello, I have created shapes from ai file,it created many merge path layers,i know the merge paths are not supported，so what kind of path will not go wrong?
thank u~

**Comment by bodymovin** [comment]
You can delete the merge paths. They are usually unnecessary when converting from .ai

**Comment by binsprout05** [comment]
m

**Comment by binsprout05** [comment]
Hi, 

I saw this thread and i have a problem similar to this. I created the shapes from an ai file in after effects and there was a merge path. I deleted it and when i used the trim path option the path turns out wrong (it stretches out of the object itself)

**Comment by bodymovin** [comment]
@binsprout05 hi, can you share the project?

**Comment by binsprout05** [comment]
[CPDTutPart0.aep.zip](https://github.com/airbnb/lottie-web/files/2676300/CPDTutPart0.aep.zip)


The layer in question is called "Arm Outlines".

In the layer merge paths is left on and trim paths works properly but when i turn off merge paths the path becomes wrong. The reason why i wanted to turn off merge paths was that when i exported the clip to html and tested it, the trim paths offset direction is wrong (the path started from the middle of the arm and not the left end) so i suspect its the merge path option thats causing the issue.

Thank you so much for the help!

**Comment by bodymovin** [comment]
@binsprout05 merge paths are not supported by the player unfortunately. Not sure I understand the issue. If you remove MP, does it behave the same way in AE as with lottie?

**Comment by binsprout05** [comment]
ah, I think i solved my own problem because there was another group nested in the arm group. And if i turn that and merge path off everything works fine. Not sure why but...it works.

**Comment by bracketsberlin** [comment]
After hours of trying and having similar issues like described above, @binhao94's comment solved my problem: I was simply able to delete all the merge paths and tada, everything worked fine. Thanks!
