### ISSUE TITLE
Clipping/mis-rendering of SVG paths

### ISSUE THREAD

**Issue by sfoster** [bodymovin/bodymovin#396]
I'm trying to chase down an issue I'm seeing when using bodymovin on an AE composition with some vector shapes. The layer seems to be getting clipped and/or the stroke not properly rendered. Best described with a screenshot - notice the left-most line appears clipped as if the stroke width was not taken into account. The rounded end of the line is also squared off in the bodymovin export. The same thing is happening on the right of the graphic. 

![screenshot-library-icon-clipping](https://cloud.githubusercontent.com/assets/97747/25641562/a11b87aa-2f49-11e7-9a0f-da23f07db831.png)

As best as I can tell, this is happening in the export/conversion process, not the player? I can have a go at a pull request if you can point me at any likely locations in the code to start looking

**Comment by bodymovin** [comment]
are you using some type of matte masking?
can you share the .aep?

**Comment by sfoster** [comment]
A colleague has made the animations, so I'm not sure.. maybe?

[icon-animations.aep.zip](https://github.com/bodymovin/bodymovin/files/972113/icon-animations.aep.zip)

**Comment by bodymovin** [comment]
It's an issue with strokes and svg filters.
Browsers don't handle well that combination.
Instead of using a fill effect on the strokes, you should instead use a stroke color in the shape layer itself.
It will be much more performant also.

**Comment by sfoster** [comment]
Thank you for the fast response, I will relay the advice!
