### ISSUE TITLE
playSegments()

### ISSUE THREAD

**Issue by casizzi** [bodymovin/bodymovin#398]
@bodymovin even after locating the 'ip' & 'op' params i still can't get the playSegments functionality to work, my animation just plays the entire length of the animation when calling it, any tips?

![screen shot 2017-05-03 at 16 54 14](https://cloud.githubusercontent.com/assets/12881937/25666819/ea4a5b76-3021-11e7-9d2f-85f45e59b4f3.png)

**Comment by bodymovin** [comment]
@casizzi you need for the animation to be loaded before setting the segment.
you can do something like:
````javascript
anim.addEventListener('DOMReady',function(){
    anim.playSegments([30,82],true);
});

**Comment by casizzi** [comment]
@bodymovin, even after running a document.ready i still have the same issue where it plays the entire animation and does not play the segment that has been set, I also tried replacing the anim.PlaySegments([30,82], true); with anim.goToAndPlay(1500, true); just to test if I could maybe use time instead of frames and again I have the same issue where I just play from start to end of the animation

**Comment by bodymovin** [comment]
it's not the document ready event you need to wait for. It's the animation to be loaded.
Have you tried the code snippet I posted before?

**Comment by fariskas** [comment]
its supposed to be `DOMLoaded` right? was wondering that snippet didnt work for me until i tried `DOMLoaded` instead.

**Comment by bodymovin** [comment]
@fariskas yes, it's DOMLoaded

**Comment by ChrisCRMG** [comment]
This code worked for me, thanks @bodymovin ! 
![image](https://user-images.githubusercontent.com/43483059/46106508-867afa00-c19e-11e8-83e4-4b437dc38617.png)

**Comment by kmturley** [comment]
This doesn't work for me:
https://jsfiddle.net/kmturley/dz679q8k/10/

**Comment by bodymovin** [comment]
@kmturley you should also try with a newer version of Lottie, there were a lot of fixes since v5.2.x

**Comment by kmturley** [comment]
Upgraded to 5.4.4 it definitely plays part of an animation:
https://jsfiddle.net/kmturley/dz679q8k/22/

But I still have issues defining any frames below 15. and it reports the length of the animation as 33 frames, but anim.playSegments([1, 33], true); does not play the whole animation. Something seems to be out :) is it to do with the way files are exported? or the number of frames per second?

**Comment by bodymovin** [comment]
That animation originally has the first 22 frames empty in After Effects, that's why you see an empty segment.
You can check the json ip to see where the original segment starts.

**Comment by kmturley** [comment]
Ah amazing, it would be great to have a way to detect blank frames. or warn of blank frame in the future :)

**Comment by febriandhimass** [comment]
@bodymovin I am looking to unlimited loop the first part of the animation a couple of times, then continue to the rest of the animation and stop when it ends. Any suggestions on how I can do this?

For example, loop frames 0 to 64 unlimited and then continue from frame 64 to 100 and stop.

Thanks for your help!
