### ISSUE TITLE
no support for: "cc particle effect" ?

### ISSUE THREAD

**Issue by ChananG** [bodymovin/bodymovin#399]
Yo,

Created this star system using "CC Particle World" effect.
When I render I get a black blank screen.

Does this mean bodymovin doesn't support this kind of effect?

Please, your help - 
See attached AE file.
[02.aep.zip](https://github.com/bodymovin/bodymovin/files/973944/02.aep.zip)

**Comment by bodymovin** [comment]
yes, cc particle is not supported unfortunately.
Very few effects are for now.

**Comment by ChananG** [comment]
:(

**Comment by smpetrey** [comment]
Why was this closed? CC Particle World still not supported?
