### ISSUE TITLE
Trying to refresh the comps fails 

### ISSUE THREAD

**Issue by MickCoelho** [bodymovin/bodymovin#4]
After opening my aep project and opening the bodymovin extension, I can't seem to refresh the comps layer:
https://www.dropbox.com/s/3fy0s1e0ua0c3nq/Screenshot%202015-08-17%2012.01.16.png?dl=0

**Comment by bodymovin** [comment]
I added a JSON polyfill. Apparently it's not built-in in Extend .Script.
This should fix the issue.

**Comment by MickCoelho** [comment]
Thanks, seems to work fine now!

**Comment by bodymovin** [comment]
Nice!
Closing the issue.
