### ISSUE TITLE
Unable to execute script at line 90. undefined is not an object

### ISSUE THREAD

**Issue by griable** [bodymovin/bodymovin#40]
Hi all,

First thank you for this amazing plugin,

While trying to export my animation, I'm getting this error. Any hint?

<img width="1919" alt="screen shot 2015-11-30 at 17 44 10" src="https://cloud.githubusercontent.com/assets/193908/11477806/027e5ac6-978a-11e5-8fc0-71646d108758.png">

**Comment by griable** [comment]
Here is some complementary info about the problematic layer

<img width="1276" alt="screen shot 2015-11-30 at 17 45 25" src="https://cloud.githubusercontent.com/assets/193908/11477865/385595ba-978a-11e5-9193-0f164162e2ea.png">

**Comment by bodymovin** [comment]
@griable hi!
yes, it doesn't support 3d yet and I haven't handled that error yet.

**Comment by griable** [comment]
Thanks a lot for this quick feedback. I'll find a way to workaround :)

**Comment by digamber89** [comment]
i'm facing the same issue @griable did you find any workarounds?

**Comment by griable** [comment]
Nope @digamber89, I simply tried to reproduce the 3d effects using 2d animations or simplified the interpolations if not possible.

**Comment by bodymovin** [comment]
@digamber89 do you have 3d layers?

**Comment by digamber89** [comment]
@bodymovin Yes, the transformations are 3D transformations, i'm actually editing compositions sent by someone else, tried converting to 2D but without much success

**Comment by bodymovin** [comment]
@digamber89 3d is not ready yet. It will be available probably in february.
I will fix the error soon though.

**Comment by digamber89** [comment]
@bodymovin thanks for the info, waiting for the update
