### ISSUE TITLE
shadow under object with class

### ISSUE THREAD

**Issue by pprochnicki** [bodymovin/bodymovin#402]
I've creating shape layer in AE animation and give him a class. I need give box-shadow under this object. How can I do it. I've tried various methods, e.g. filter: drop-shadow( -5px -5px 5px #000 ), box-shadow: -5px -5px 5px #888;
Could anybody give me simple instruction about it?

**Comment by bodymovin** [comment]
Hi, did you check if the class is set in the element you're setting the shadow?

**Comment by pprochnicki** [comment]
Yes, I did. When I've been inspecting SVG in animation the proper element has assigned in AE class.

**Comment by bodymovin** [comment]
do you have a link so I can check?
