### ISSUE TITLE
SVG size gets bigger with time

### ISSUE THREAD

**Issue by stenuto** [bodymovin/bodymovin#403]
Hi Hernan, 

I see that you are dynamically adding svg elements as they are needed. As the animation continues, the `<svg>` element grows in size. From what I can tell, this is because your script is not removing elements that are no longer needed. Is this possible to add?

Thank you,

Steve

**Comment by bodymovin** [comment]
Hi, removing elements has a big impact on performance.
If your animation is in loop, I'd need to remove and include them on each iteration.
Instead of removing them, I set them to display: none so they don't get rendered which I've tested some time ago and seemed more performant.

**Comment by stenuto** [comment]
Thank you Hernan-- makes complete sense!
