### ISSUE TITLE
Cc page turn

### ISSUE THREAD

**Issue by orchardpost** [bodymovin/bodymovin#404]
Is page turn supported? Just have a brief from a client that would need page turn to be used, or anything similar?

**Comment by bodymovin** [comment]
no, it's not supported.
I don't know exactly what you need, but can you use masks and gradient fills?

**Comment by orchardpost** [comment]
How about image sequences? I could render out an image sequence of the page turn and put it in the comp? Would that work?

**Comment by bigxixi** [comment]
@orchardpost Hi, if your scene is **small and shot,** you can try [sprite animation](http://blog.teamtreehouse.com/css-sprite-sheet-animations-steps)
and I wrote a script for AE to export comps to that(asset and code), hope that can help
https://github.com/bigxixi/CSS-Sprite-Exporter
