### ISSUE TITLE
Text is not properly rendered in Microsoft Edge browser

### ISSUE THREAD

**Issue by cristian-d** [bodymovin/bodymovin#405]
Hi,
Looks like text isn't properly rendered on Edge. I tried with Edge 14.14393 and the latest 15.15063
Demo app: https://jsfiddle.net/zvj10q8d/2/
Bug preview: https://drive.google.com/open?id=0B0XgZ-gc-zz-X0dXZlVDWi1oWUU
Thx!

**Comment by bodymovin** [comment]
Yes, Edge has a lot of issues with clipping.
If you resize the window you'll see that it corrects itself.
I have filed a bug about this, but I don't know when they are going to address it.
I don't think there's anything I can do on my side.

**Comment by netjerikh** [comment]
Can you give me the bug link?

**Comment by cristian-d** [comment]
Can you give me the link to the edge bug?

**Comment by cristian-d** [comment]
is it this one: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4705340/ ?

**Comment by bodymovin** [comment]
No, I reported it to a microsoft dev and he told me they have an internal log.
