### ISSUE TITLE
Issue with JSON rendering 

### ISSUE THREAD

**Issue by geoffgerman** [bodymovin/bodymovin#406]
[02 Working animations.zip](https://github.com/bodymovin/bodymovin/files/979788/02.Working.animations.zip)
So, running into some issues with rendering art in the JSON file here. Our AE file is setup with Shape layers and trim paths and we're running into art on layers staying present even after they are completed on the timeline (explosions). Also, having an issue where the "THANKS" type has the counter (triangle in the middle of A) not knocking out. Any help you could provide would be great. : )

**Comment by bodymovin** [comment]
It seems to be working fine here.
Can you share a link where it fails?

**Comment by geoffgerman** [comment]
Hey Hernan, thanks for the response. Really appreciate it. See the attached movie file.

So, the difference is how it’s rendering in JSON for IOS. If you look at the .JS file it looks like it’s supposed to with the rocketship shooting the lasers and blowing up the food. But the JSON does this where the lasers don’t always show up and the ship flies through the disappearing food. Not sure why it’s working great in JS and not in JSON.

Geoffrey

Geoff German
Designer


RBMM
7007 Twin Hills
Suite 200
Dallas, Texas 75231

O  214 987 6539
C  214 435 1963

**Comment by bodymovin** [comment]
If it's an iOS rendering issue, I suggest that you contact the Lottie team directly. They'll have a better insight on what could be going on.

**Comment by geoffgerman** [comment]
Okay. I posted to that board on Friday. Appreciate your help. : )

Geoffrey


Geoff German
Designer


RBMM
7007 Twin Hills
Suite 200
Dallas, Texas 75231

O  214 987 6539
C  214 435 1963
