### ISSUE TITLE
What is html rendering?

### ISSUE THREAD

**Issue by machida-yosuke** [bodymovin/bodymovin#409]
I am not very good at English, so I apologize in advance.

I understand svg / canvas rendering.
but, I don`t understand html rendering.
I want to try 3D layer.
What kind of code should I write?

**Comment by bodymovin** [comment]
the 'html' renderer renders svg elements wrapped in div elements.
That way CSS 3d transformations can be applied to them.
Depending on your animation, it can help to render 3d.

**Comment by machida-yosuke** [comment]
I used a 3D layer &camera on AfterEffects cc 2017.
but, bodymovin(version 4.6.9) gives an error.
"Unable to execute script at line 311. undefined is not an object"

I use camera (position(z) anime) & plane(3d layer Y axis anime).

<img width="1432" alt="2017-05-18 20 03 32" src="https://cloud.githubusercontent.com/assets/26296501/26199606/9e2f70ec-3c05-11e7-8785-704538629c78.png">

**Comment by bodymovin** [comment]
I've found the issue.
I'll be uploading it by the end of this week.
thanks for reporting it.

**Comment by machida-yosuke** [comment]
I am looking forward to the weekend.
thank you.

**Comment by bodymovin** [comment]
fixed
