### ISSUE TITLE
Can I take only the animated SVG?

### ISSUE THREAD

**Issue by Leomaker** [bodymovin/bodymovin#41]
In some projects only the SVG is neccessary like make animated buttons. There are this possibility?

**Comment by bodymovin** [comment]
@Leomaker I'm not sure I understand correctly.
Do you mean animate the svg without javascript?

**Comment by Leomaker** [comment]
Like this guy did for Flash, but for After Effects: https://github.com/TomByrne/Flash2Svg

**Comment by bodymovin** [comment]
@Leomaker that library relies on SMIL to animate svg.
Unfortunately, SMIL is being deprecated on browsers, so I am not maitaining the SMIL export anymore.
