### ISSUE TITLE
Bodymovin Light is broken. `EffectsManager is not defined`

### ISSUE THREAD

**Issue by jmckinnell** [bodymovin/bodymovin#412]
https://github.com/bodymovin/bodymovin/blob/master/build/player/bodymovin_light.js#L5329

In the light player `EffectsManager` (camel case) is not defined anywhere

**Comment by bodymovin** [comment]
Yes, bodymovin light doesn't support effects or expressions.
You need to use the full version for them.

**Comment by jmckinnell** [comment]
Makes sense, could there be some better error messaging for the light version that says that?
