### ISSUE TITLE
Circle render cut off?

### ISSUE THREAD

**Issue by Ipaulsen** [bodymovin/bodymovin#414]
Not sure if this has to do with my ae file. But I have vector circles but they appear to be cut off see comparison screen shots. I dont see the effect in AE.
![screen shot 2017-05-10 at 9 52 18 am](https://cloud.githubusercontent.com/assets/1786263/25908242/e75d30c4-3566-11e7-963c-707df97a616f.png)
![screen shot 2017-05-10 at 9 52 04 am](https://cloud.githubusercontent.com/assets/1786263/25908247/ea577eb0-3566-11e7-9149-6cea85155998.png)
Really exited about the potential of this tool for our creative team. I am a developer and we always get this requests but can always get to "hand coding them". :)

**Comment by bodymovin** [comment]
that's probably related to some kind of matte mask in the project.
Strokes and masks don't work well together in browsers.
But if you add a rectangle with a transparent fill on those shape layers that cover the whole stroke's surface it should work fine.
Let me know if you need more clarification.

**Comment by Ipaulsen** [comment]
Here is the aep file as far as I know no masks are being used [https://ufile.io/a47k6](url)

**Comment by Ipaulsen** [comment]
I figured it out. I was changing the .json file into a js var. At it was rendering funny. After using the just the json method as you outlined it works like a charm amazing work.

**Comment by gregg-cbs** [comment]
@Ipaulsen  - Chaning animation type to SVG did it for me. I have been looking everywhere!!! That comment is gold. Thank you.
