### ISSUE TITLE
Uncaught TypeError: bodymovin.loadAnimation is not a function

### ISSUE THREAD

**Issue by Muthukrish92** [bodymovin/bodymovin#416]
Hi , 
I have animation Composition done in after effects then i used bodymovin to create json file. Then i tried to use that in a demo html you have given along with the zip files. and changed the script location to my newly created json.  but i get this error.

"Uncaught TypeError: bodymovin.loadAnimation is not a function." just let me know how to proceed. whether is there any alternative function? to use or we have define the function prior? or any other solution

I also tried to play a little with all the setting options of "bodymovin" in after effects in that there was an option to save as html. that one works but i am not getting the colors information as accurately. It actually took the solid color but i applied a gradient effect on the solid which didnt reflect in the html page, Just let me know what i would have missed.

Thanks,
Muthu

**Comment by tortilaman** [comment]
What is the environment you're using bodymovin in? It sounds like you haven't imported the plugin .js file. That would be my first guess as to why you're getting that error.
