### ISSUE TITLE
Unexpected End of Input

### ISSUE THREAD

**Issue by sanderson** [bodymovin/bodymovin#42]
With a somewhat complex animation (moving lots of bezier points), the animations render fine, but when trying to play them in browser, I get the following errors:

```
Uncaught SyntaxError: Unexpected end of input
i.onreadystatechange @ all.js:4

Uncaught TypeError: Cannot read property 's' of undefined
r @ all.js:1
(anonymous function) @ all.js:1
n @ all.js:1
BaseElement.init @ all.js:2
SVGBaseElement @ all.js:1
IShapeElement @ all.js:1
SVGRenderer.createShape @ all.js:1
SVGRenderer.createItem @ all.js:1
SVGRenderer.buildItems @ all.js:1
AnimationItem.configAnimation @ all.js:4
i.onreadystatechange @ all.js:4
```

The json file can be found [here](https://gist.github.com/sanderson/9b7cc0ac845a42750e06).

**Comment by bodymovin** [comment]
@sanderson can you upload the images?

**Comment by bodymovin** [comment]
@sanderson are you using separate dimensions por position? I think that's the issue.
I'll have it fixed tomorrow EOD.

**Comment by sanderson** [comment]
Sure, you can find them here:

https://github.com/sanderson/images-tmp

I didn't notice the images getting generated. I'm not sure why they are. They are shape layers inside of a nested composition.

**Comment by sanderson** [comment]
Ah, yes I am. Great! Thank you. I didn't realize that wasn't supported.

**Comment by bodymovin** [comment]
@sanderson yes, it should be.
bug :/

**Comment by sanderson** [comment]
No worries. They happen ;)

**Comment by bodymovin** [comment]
@sanderson hey! I've uploaded the fix.
let me know if everything works fine.

**Comment by sanderson** [comment]
Works perfectly! Thanks so much for the quick fix. Love this plugin.

**Comment by bodymovin** [comment]
@sanderson nice!
did you fix the layers exported as images?

**Comment by sanderson** [comment]
I didn't. Still looking into it.

**Comment by sanderson** [comment]
Nevermind. My mistake. Long day yesterday. It's fixed :)
