### ISSUE TITLE
Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by qasimalyas** [bodymovin/bodymovin#422]
Hi,

I'm trying to get s simple example working and am getting an error:

    Cannot read property 'length' of undefined

Below is a screenshot of the error in chrome.

![bodymovin-error](https://cloud.githubusercontent.com/assets/85598/26154133/2db0afc0-3b06-11e7-8389-c8d8eaf3dacf.png)

I'm guessing its something to do with an export setting as I tried the data.json file from http://codepen.io/airnan/pen/RawvLB which worked fine. 

The source files are here https://www.dropbox.com/s/vwlebcxwp0a6eix/test-example.zip?dl=0 with a ```.aep``` file and the generated json file.

Any guidance is appreciated.

**Comment by qasimalyas** [comment]
I tried the installation instructions again but followed option 1, rather than going directly from store. Version was bumped from 4.6.3 to 4.6.9 which kind of works now so I'll consider this issue as resolved. 

Perhaps the plugin link to the store should be removed or at the very least the store plugin should be updated with the current version.

Thanks

**Comment by bodymovin** [comment]
yes, I can't update the store version as often as I'd like to.
I try to do it once a month so sometimes it gets outdated.
I've just been accepted at aescripts, where it should be updated regularly.
http://aescripts.com/bodymovin/
