### ISSUE TITLE
Render from AE produces random playback artifacts in browser.

### ISSUE THREAD

**Issue by tommarquis** [bodymovin/bodymovin#424]
Hi guys, I have an issue where an after effects file is fine for awhile and renders out a flawless json animation. Then I may make a simple tweak to the art or keyframes and then bodymovin renders with an artifact or glitch in the playback. Im using a current version of Chrome. I dont think I'm doing anything crazy with after effects it (the render) just seems to break at random. Let me know how I can help.

[animation_with_artifact.zip](https://github.com/bodymovin/bodymovin/files/1011826/animation_with_artifact.zip)
[animation_no_artifact.zip](https://github.com/bodymovin/bodymovin/files/1011825/animation_no_artifact.zip)

[AE_FILE.zip](https://github.com/bodymovin/bodymovin/files/1011839/AE_FILE.zip)

**Comment by tommarquis** [comment]
So I went back to an older version of the same AE file and redid the changes. (just some small timing and art tweaks.) This time it renders fine. Weird, I don't know what causes the render to sometimes come out with an artifact. Let me know if I can provide any other assets/input. Thanks! Tom  (attached is the working AE file that produces a flawless render)
[Contact_Icon_Anim_11.aep.zip](https://github.com/bodymovin/bodymovin/files/1011893/Contact_Icon_Anim_11.aep.zip)

**Comment by bodymovin** [comment]
hi
in your layers "B line 02 Outlines" and "B line 01 Outlines", in Contents > Group 1
you have another Group 1 and a Merge Paths 1; since merge paths are not supported by the plugin, that group is getting trimmed and generates those artifacts.
if you delete the Group 1 and Merte Paths 1 on each, the artifact will disappear.
