### ISSUE TITLE
Rendering canvas to webm/gif

### ISSUE THREAD

**Issue by jvke** [bodymovin/bodymovin#425]
@bodymovin could you advise on the best strategy to render a bodymovin canvas or SVG animation to a gif/video? Potentially using CCapture.js or GIF.js

**Comment by stenuto** [comment]
You're going to need to create an image sequence from the DOM, and convert that to a video from there.

**Comment by bodymovin** [comment]
hi, do you want to do it client side or server side?
but basically, @stenuto 's suggestion should work.

**Comment by sudesh1456** [comment]
@bodymovin I would like to do it serverside, Is there any library available to convert bodymovin json to video on server side in nodejs or c#?

**Comment by transitive-bullshit** [comment]
I just published a project which you may find useful.

It allows you to export Lottie animations to **image**, **GIF**, or **MP4** via Puppeteer and is 100% compatible with `lottie-web`. 🔥 

- [puppeteer-lottie-cli](https://github.com/transitive-bullshit/puppeteer-lottie-cli) - CLI
- [puppeteer-lottie](https://github.com/transitive-bullshit/puppeteer-lottie) - Underlying library implementation
