### ISSUE TITLE
Extension not showing in after effects

### ISSUE THREAD

**Issue by MAGSON** [bodymovin/bodymovin#427]
I have followed the instructions, but the extension is not showing up in after effects. I have an old version of after effects: after effects 7.0. Does this extension also work for this version of after effects?

**Comment by bodymovin** [comment]
hi, it works starting from CC 2014 and up.

**Comment by MAGSON** [comment]
ok, thank you

2017-05-22 21:09 GMT+02:00 hernan <notifications@github.com>:

**Comment by jwjoeywalsh** [comment]
I upadted my macbook and now the extension is gone ive tried restarting, reinstallking and unistalling- no luck
