### ISSUE TITLE
Gradients issues

### ISSUE THREAD

**Issue by KhodorAmmar** [bodymovin/bodymovin#429]
hello!

We're having multiple issues with exporting an animation with gradient, some of the colors are not appearing correctly. would you mind taking a look?

**Comment by bodymovin** [comment]
sure, can you send me the .aep?
Make sure you save the .aep before exporting.
Gradient info is taken from the project file.

**Comment by KhodorAmmar** [comment]
here you go, with the exported files

[GradientsBug.zip](https://github.com/bodymovin/bodymovin/files/1021871/GradientsBug.zip)

**Comment by bodymovin** [comment]
I see, the 4-color-gradient effect is not supported.
Can you use a shape's gradient fill instead?
