### ISSUE TITLE
No compositions showing up

### ISSUE THREAD

**Issue by iamstevemckinney** [bodymovin/bodymovin#43]
Clicking refresh doesn't appear to do anything.

Using the new After Effects CC 2015

**Comment by bodymovin** [comment]
@iamstevemckinney that's strange.
does it happen with any project?

**Comment by lavruk** [comment]
Yeah, same for me. 
Just downloaded latest After Effects CC 2015, the refresh button in the plugin window does nothing.
OS: MacOS 10.10

**Comment by bodymovin** [comment]
@iamstevemckinney @lavruk fixed!
please download the latest build.

**Comment by lavruk** [comment]
Thank you,  @bodymovin! It works now, great job!

**Comment by iamstevemckinney** [comment]
Works for me as well!
