### ISSUE TITLE
full size solid background is not rendering in Bodymovin ! 

### ISSUE THREAD

**Issue by Onlypar2** [bodymovin/bodymovin#430]
I have made a small svg animation with a white background (after effects solid), extending to the full comp size. But it is not getting rendered, leaving the background black. As i tried rendering it with slightly smaller size than the comp, then it is rendering the white background also, but if i tried to make it a full comp size solid and render it, its rendering as black background ! Please let me know how to resolve this issue and render out white backgrounds in bodymovin !
Thank you.

**Comment by bodymovin** [comment]
hi, can you share the .aep so I can check it?

**Comment by Onlypar2** [comment]
Hi,
Thanks for the reply.
I am sending you the .aep file. Please check it out.
Thank you.

**Comment by bodymovin** [comment]
hi, email attachments don't come through in github. Can you attach it directly here?

**Comment by Onlypar2** [comment]
Hi, unfortunately, I am also unable to attach the .aep file through github,
as it accepts only a few formats. So, I am sending it through my google
drive. Please go through this link.

https://drive.google.com/file/d/0B9Y-loKvj6-MR1J2ZG40UmtTVmFPcDZXNG9OWmRSQkQ3ZlF3/view?usp=sharing

Thank you.

**Comment by bodymovin** [comment]
Hi, I'm trying it and it seems to work fine.
Do you have a link where I can see the error?

**Comment by Onlypar2** [comment]
Hi,
I tried it with many other projects, but i couldn't get the background
rendered. It is coming transparent. I am sending you the rendered file with
this mail. please check it out.
I am repeating my problem again:
When I am trying to create an svg animation render out of after effects
through bodymovin, I took full white/any color "solid" (not just a box
background) as background and added a small animation in the other
foreground layers. When i check the render in browser, I can only see my
foreground animations, but not the background solid. but if i change the
color of the background solid or its size, its rendering again.
Please help me with this problem.

*I am sending you the rendered file. check it.*

https://drive.google.com/file/d/0B9Y-loKvj6-MQWp6b3FwRVJUUDg/view?usp=sharing
*Above is the link to my render*

In it i have rendered with light red solid, which is smaller than the comp
size. so the solid got rendered, but the background (rest of the
transparent comp) remained black. what should i do to get full comp
rendered perfectly? is there any settings to be tweaked? please let me know.

Thank you.

**Comment by bodymovin** [comment]
What browser are you testing it on?
I tried the new version and it seems to work fine.
If you have an online link that I can check, it would be very helpful.

**Comment by Onlypar2** [comment]
Hi,
I checked in chrome and hopefully latest version only. I will check it once
again and send u an online link if possible. Thank you. and what about in
an older version browsers? cant they see the background as we see in the
latest versions?
Thank you.
