### ISSUE TITLE
Is 'corner pin' effect possible?

### ISSUE THREAD

**Issue by stenuto** [bodymovin/bodymovin#431]
Hi, would adding support for the corner pin effect be possible?

**Comment by bodymovin** [comment]
Hi, not for now.
I'm working on a three.js implementation.
Perhaps then I will be able to look into it.

**Comment by ranpeer** [comment]
Hi, have you made any progress with this? Corner pin would be a game changer

Thanks for all your great work

**Comment by nishanksisodiya** [comment]
Hi, 
I've got a workaround for this issue Export project as png sequence then create a new composition using that sequence images then render new comp using bodymovin  the only downside is the filesize in a large

https://lottiefiles.com/share/toOYyW

**Comment by simonfossom** [comment]
Yeah.. file size is so big it makes no sense to create the animation

**Comment by simonfossom** [comment]
@bodymovin are you considering this or is it closed for good?
(and thanks for all the work! really appreciate it.)

**Comment by Baegus** [comment]
I've been thinking about this effect and how it could be implemented. I wonder if it would be possible to use foreignObject (or HTML/canvas renderer) with a matrix3d CSS transformation computed from the Corner Pin effect coordinates. You can see the formula in here, for example: https://jsfiddle.net/szym/03s5mwjv/

I'm not exactly sure if it would work in the context of a Lottie animation, but maybe @bodymovin could have some insights... :)

**Comment by bodymovin** [comment]
That solution looks very promising, but unfortunately, 3d transforms are not supported on the svg format, so it would be hard to replicate.

**Comment by woozygoozy** [comment]
how about using javascript expressions to have make the 3d space transform of the pins – i can transform a path using that so why not? for example the lottifiles.com/games example of doom uses some sort of similar approach to map raster artwork to 3d positions so that you can create a doom level...
