### ISSUE TITLE
Animation render only as white screen

### ISSUE THREAD

**Issue by JoshFabian** [bodymovin/bodymovin#433]
Hey there, I have an animation that I'm attempting to render with Bodymovin but the output seems to end up as nothing more than a white screen, as seen here:

https://codepen.io/JoshFabian/project/editor/AaoNEm/

Any help would be greatly appreciated. AE file attached.

[kitsu-reveal.aep.zip](https://github.com/bodymovin/bodymovin/files/1023825/kitsu-reveal.aep.zip)

**Comment by bodymovin** [comment]
Hi, there are two issues going on:
- adjustment layers are not supported, so they are not getting exported. You should convert them to regular layers.
- there is an expression bug I need to fix on my side. I'll upload it this days. Meanwhile, as a workaround, if you add your "Reveal" comp inside a new comp and export that one, it should work fine.

**Comment by JoshFabian** [comment]
@bodymovin thanks, that's helpful! I'm pretty new to AfterEffects, I can see that disabling the adjustment layer gives me the white block I had seen with Bodymovin, but I'm not sure where to begin on converting them to regular layers. 

Any pointers or links your could send my way to get me started?

**Comment by Loreto17** [comment]
Tengo el problema con duik y bodimoving en after cc 2019.
los huesos de la pierna funcionan perfecto, pero si sumo un hueso de brazo o columna, en el html se ve todo blanco.

* todas las capas en svg, el brazo funciona perfectamente bien pero ninguno de los otros huesos funciona

**Comment by bodymovin** [comment]
@Loreto17 puedes compartir el .aep?

**Comment by Loreto17** [comment]
por supuesto!
[example_dontwork.zip](https://github.com/airbnb/lottie-web/files/3081167/example_dontwork.zip)
[example_works.zip](https://github.com/airbnb/lottie-web/files/3081168/example_works.zip)

**Comment by Loreto17** [comment]
:C

**Comment by bodymovin** [comment]
@Loreto17 Lo probé y parece funcionar bien.
Qué versión de bodymovin estás usando?

**Comment by Loreto17** [comment]
la ultima publicada en web: Version: 16.0.11

**Comment by bodymovin** [comment]
me refiero a la extensión Bodymovin en AE, la última versión es 5.5.1

**Comment by Loreto17** [comment]
bodymovin Version: 5.1.20

**Comment by bodymovin** [comment]
puedes intentar con una versión más reciente? Hubieron muchos cambios y correcciones desde esa versión.
