### ISSUE TITLE
Error: controller.effect is not a function

### ISSUE THREAD

**Issue by super-cache-money** [bodymovin/bodymovin#434]
We're unable to get this to work.

We're using the latest version of bodymovin.js, AE, and the AE plugin.

Here's a [forked codepen containing our broken attempt](https://codepen.io/super-cache-money/project/editor/ARwaMy/).

We get the following error:
```
Uncaught TypeError: controller.effect is not a function
    at MultiDimensionalProperty.eval (eval at initiateExpression (bodymovin.js:11733), <anonymous>:5:25)
...
```

**Comment by bodymovin** [comment]
hi, can you share the .aep file?

**Comment by super-cache-money** [comment]
Thanks for the quick support 😁 You have no idea how appreciated it is.
[Here's the .aep file](https://drive.google.com/open?id=0B_yd6q8QYct-a1U0TFRMNzZWcG8).

**Comment by bodymovin** [comment]
Can you try selecting to export Hidden layers in the comp's settings on the bodymovin panel?

**Comment by super-cache-money** [comment]
Trying it now...

**Comment by super-cache-money** [comment]
Almost there! I've [updated the codepen](https://codepen.io/super-cache-money/project/editor/ARwaMy/). It's still got some weird inconsistencies though compared to [what it should look like](https://drive.google.com/open?id=0B_yd6q8QYct-cjRqVWZKcDZEME0).

**Comment by bodymovin** [comment]
can you convert your .ai layers to shapes in AE?

**Comment by thecosss** [comment]
Got same error, using DUIK for animation, could it be the reason?

**Comment by thecosss** [comment]
[heroanim2-2018.aep.zip](https://github.com/airbnb/lottie-web/files/1895339/heroanim2-2018.aep.zip)

**Comment by bodymovin** [comment]
@thecosss Hi, make sure you include guided layers in the export settings of the composition. DUIK uses them for controls points.

**Comment by thecosss** [comment]
didn't help, same error
![image](https://user-images.githubusercontent.com/4847308/38600024-e8c864ec-3d62-11e8-86c1-2c3b9675d389.png)

**Comment by thecosss** [comment]
Got it working with demo.html thanks!

**Comment by mahtabbbkarimi** [comment]
I am using the latest version of bodymovin.js, AE, and the AE plugin.
I get the following error:

favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
VM1026:5 Uncaught TypeError: controller.effect is not a function
    at MultiDimensionalProperty.eval (eval at initiateExpression (bodymovin.min.js:12539), <anonymous>:5:25)
    at MultiDimensionalProperty.executeExpression [as getValue] (bodymovin.min.js:12761)
    at bodymovin.min.js:14052
    at Array.interfaceFunction (bodymovin.min.js:13995)
    at groupInterface (bodymovin.min.js:13964)
    at ValueProperty.eval (eval at initiateExpression (bodymovin.min.js:12539), <anonymous>:6:33)
    at ValueProperty.executeExpression [as getValue] (bodymovin.min.js:12761)
    at TransformProperty.processKeys [as getValue] (bodymovin.min.js:2494)
    at IImageElement.BaseElement.prepareFrame (bodymovin.min.js:6142)
    at ICompElement.prepareFrame (bodymovin.min.js:8141)

**Comment by mahtabbbkarimi** [comment]
@bodymovin 
could you help me?

**Comment by mahtabbbkarimi** [comment]
https://ufile.io/cuf8m
