### ISSUE TITLE
After effects animation

### ISSUE THREAD

**Issue by Jyoti10mane** [bodymovin/bodymovin#439]
I have created logo animation in aftereffects it works fine in aftereffects but when i convert it in bodymovin and use in html page its not showing ani animation pls tell me what is the problem why animation is not working in html page pls  give me any solution

**Comment by Jyoti10mane** [comment]
one more issue i hav i have created one page which display products and i hav done with my seard coding also but i stuck with currency we want that when i click on any currency all products price should converted to that paricular currency but its not working

**Comment by bodymovin** [comment]
hi, can you share the .aep so I can check it out?
