### ISSUE TITLE
Using frames to trigger other items on the page

### ISSUE THREAD

**Issue by orglennon** [bodymovin/bodymovin#44]
Hi there,
First off, this extension/library is amazing.

I'm rendering my animation as svgs and I want to be able to use the point in time in the animation to trigger other events (ex: fading in divs) on the page. I've been trying to use the currentFrame property of the animation to measure against, but it seems like I'm having inconsistent playback across computers (same browser, chrome on mac). Just wondering if currentFrame is the best way to measure in order to have other events trigger consistently at the same time across computers with different settings (ie: does playback speed/lag mess this up).

Thanks so much in advance!

**Comment by bodymovin** [comment]
@orglennon hi!
yes currentFrame should work for your case.
What kind of inconsistencies are you seeing?

**Comment by orglennon** [comment]
Thanks for the quick response!
It looks like I had a bit of old code and was setting a variable to the value of currentFrame onFrameEnter, but when there was lag it either wasn't always updating, or something else fishy was going on there.
Now I am measuring directly against animation.currentFrame and it seems to be working. So now even if there is lag, things still get fired, just choppily, instead of not firing at all. Hopefully this fixes the problem, but I will let you know if there are still inconsistencies across browsers/computers. Thanks!

**Comment by orglennon** [comment]
(Closing for now)

**Comment by bodymovin** [comment]
@orglennon I see. Do you know why is there lag? are animations too complex?

**Comment by orglennon** [comment]
@bodymovin I wanted to let you know that I ended up using bodymovin for the intro to a project that the firm I work for (@fathominfo) recently did for ge: ge.com/transformation

Thanks for your work on this project! It made getting our designer's animations web-ready so much easier!

**Comment by bodymovin** [comment]
@orglennon nice!
I'm glad it was useful.
any feedback is welcome :)
