### ISSUE TITLE
Opening AE with Bodymovin tab creates Untitled project

### ISSUE THREAD

**Issue by ffrutuoso** [bodymovin/bodymovin#443]
Well, this is not really a problem, just annoying. 

Each time I am opening AE in any workspace with the bodymovin tab open, it asks me to save an Untitled Project, before opening any other project.

![screen shot 2017-05-25 at 18 32 18](https://cloud.githubusercontent.com/assets/13594537/26550291/ea36a646-4474-11e7-94ad-94a04aa5a0a8.png)

Not something extra urgent, but now you know.

Thanks for all the hard work 👍

**Comment by bodymovin** [comment]
It should be fixed on the latest build
v4.6.11
