### ISSUE TITLE
Custom eases not rendered correctly

### ISSUE THREAD

**Issue by gpeal** [bodymovin/bodymovin#444]
@bodymovin Attached is a sample AEP with a custom ease on the scale of a triangle and a video of what it looks like After Effects vs Bodymovin. It looks the same as bodymovin in Lottie.

Originally reported here: https://github.com/airbnb/lottie-android/issues/308

**Comment by gpeal** [comment]
Forgot to attach the zip
[Ease.zip](https://github.com/bodymovin/bodymovin/files/1036945/Ease.zip)

**Comment by erikalutz** [comment]
@bodymovin this was originally a bug I filed on lottie-android, thinking it was only on Android. I'm also experiencing some errors with layer parenting on iOS that I'll email you about directly.

**Comment by bodymovin** [comment]
hi, it should be fixed on the latest build
v4.6.11
you'll need to install the latest extension and reexport the animation

**Comment by erikalutz** [comment]
@gpeal @bodymovin Looks good, thanks for the fix guys!
