### ISSUE TITLE
Exporting won't work (messed up)

### ISSUE THREAD

**Issue by gabrieltintarescu** [bodymovin/bodymovin#445]
@bodymovin 
Just bought a pack of animated icons pack, but when trying to export any of them I get a messed up red animation in json....
I attached a project with an example icon (atom) below... Please help 🥇 💯 

[AfterEffectsProject.zip](https://github.com/bodymovin/bodymovin/files/1036530/AfterEffectsProject.zip)

**Comment by bodymovin** [comment]
hi, Have you included the Effects & Color Control Comp as an Extra Comp in the settings of the animation?

**Comment by gabrieltintarescu** [comment]
Yep I tried including it but still no success....

**Comment by bodymovin** [comment]
do you have a link where it fails?

**Comment by gabrieltintarescu** [comment]
I have 0 experience with bodymovin&aftereffects so i guess I dont have any link (nor I know how to debug the process...)

**Comment by bodymovin** [comment]
where do you see the red animation?

**Comment by gabrieltintarescu** [comment]
Exporting it as a video, gif, or any other format works flawless.  However when trying to export with bodymovin it messes up. Here is a screenshot so you can understand better. 

![example](https://cloud.githubusercontent.com/assets/29048705/26762639/63b37552-494e-11e7-8c91-61d7c2b4bac6.png)

**Comment by bodymovin** [comment]
can you try choosing on the settings of that comp in the bodymovin panel to export the demo.html and open it in a browser or send it to me?

**Comment by gabrieltintarescu** [comment]
Here it is! 

[Atom Animation.zip](https://github.com/bodymovin/bodymovin/files/1050426/Atom.Animation.zip)

**Comment by gabrieltintarescu** [comment]
Any solution please?

**Comment by bodymovin** [comment]
Hi, I've been trying to debug this and it's getting really complicated.
Nevertheless, the animation works fine outside of the demo.html file.
Have you tried implementing it in your own project?

**Comment by gabrieltintarescu** [comment]
Yes i did and still won't work....

**Comment by bodymovin** [comment]
I've found the CEP panel from AE has an issue with the drop shadow effect on svgs.
Is there any link you can share where I can check the issue outside AE?

**Comment by abdualrhmanio** [comment]
same problem here

**Comment by gabrieltintarescu** [comment]
Maybe then the problem can be solved by removing the drop shadow effect? @bodymovin
