### ISSUE TITLE
Overlapping Animation

### ISSUE THREAD

**Issue by ellkell** [bodymovin/bodymovin#447]
New to bodymovin and trying to see if this is possible. 

My idea to have a looping walkcycle with a control that alters various properties (Position, Scale, Opacity, etc.) of elements within the walkcycle.  E.g. let's say I have a null object that animates the hip position.  I want the walkcycle animation to loop while I have the ability to control the playback of the null hip control with JS.  Is this type of overlapping animation possible?  If it is, how would I separate out these two sets of data?  

Let me know if any of this makes any sense, cheers!

**Comment by bodymovin** [comment]
Yes, there is not an official API for this, but if you edit the animation properties from the json object attached to the animation instance, you should be able to modify them in real time.
Here are some simple examples that do that.
https://codepen.io/airnan/pen/EmdXGo
https://codepen.io/airnan/pen/pyMgzN
If you need further help, let me know or write me an email.

**Comment by ellkell** [comment]
Awesome thanks!  I'll share the results when I get there, cheers!
