### ISSUE TITLE
I Create shapes Ai to Ae Already But Render is fail How to fix it.

### ISSUE THREAD

**Issue by honeyhorny** [bodymovin/bodymovin#448]
I Create shapes Ai to Ae Already But Render is fail How to fix it.
![dff137e2-4559-11e7-9713-d09c191200fa](https://cloud.githubusercontent.com/assets/12539087/26578585/a7740376-455a-11e7-960e-d989a3119cba.png)
![dff21fd6-4559-11e7-885d-f6eb68db58d8](https://cloud.githubusercontent.com/assets/12539087/26578586/a7c9a222-455a-11e7-927d-800ff38eced6.png)

**Comment by Kuzovlev-Sanya** [comment]
I have the same issue! After I create shapes from vector layers

**Comment by bodymovin** [comment]
sometimes when convrting layers from Illustrator, AE adds some unnecessary extra shapes with merge paths.
And bodymovin doesn't support merge paths
If you erase the merge paths and the extra squared layers, everything should work fine.
Let me know if you need further clarification.

**Comment by Kuzovlev-Sanya** [comment]
Ok, I found the problem, the fact is that after converting to shapes on one layer was unnecessary path, after removing it everything was displayed normally
