### ISSUE TITLE
Masking high width stroke

### ISSUE THREAD

**Issue by laygir** [bodymovin/bodymovin#449]
Hi!

I have a bit of an issue trying to figure out. I am trying to mask a stroke with a width of over 200px. Masking it with a rectangle but somehow I see only a few pixel height. Attached the aep file and few screenshots can anybody see what am i missing?

This is how it looks in AE
![screen shot 2017-05-30 at 14 56 20](https://cloud.githubusercontent.com/assets/772730/26584158/2b34cb40-4548-11e7-89b2-022dea371d47.png)

This is how it looks in the browser
<img width="469" alt="screen shot 2017-05-30 at 14 53 20" src="https://cloud.githubusercontent.com/assets/772730/26584109/f82ab444-4547-11e7-8679-ab216ff5850d.png">

[StrokeFail.aep.zip](https://github.com/bodymovin/bodymovin/files/1038314/StrokeFail.aep.zip)

**Comment by bodymovin** [comment]
how are you masking it? using a track matte?

**Comment by laygir** [comment]
Yes, just Alpha Matte

**Comment by bodymovin** [comment]
Browsers don't mask strokes correctly, so a workaround for this is creating a transparent rectangle in the contents of the masked shape layer that covers the whole surface of the stroke.
Let me know if it makes sense.

**Comment by laygir** [comment]
it makes sense theoretically, but couldn't make it work.
Tried these below

![screen shot 2017-05-30 at 15 09 58](https://cloud.githubusercontent.com/assets/772730/26584724/1607a36c-454a-11e7-8688-f30f3a80f95d.png)
![screen shot 2017-05-30 at 15 10 05](https://cloud.githubusercontent.com/assets/772730/26584723/15e8942c-454a-11e7-9022-77a20f79f178.png)

**Comment by bodymovin** [comment]
try including a transparent fill to it.
Tr going with option 1 so the trim path won't affect it and add it right below the Transparent Rect property.

**Comment by laygir** [comment]
yay! it worked. yeah by just adding the rect I thought I have added a transparent path. Obviously needs a fill with 0 percent opacity..
Thanks!

So one more question; does stroke paths supposed to work with zig zag and such things? Seems like it doesn't work or I need to figure out how it works

**Comment by bodymovin** [comment]
zig zag and those kind of modifiers are not supported yet.
I'm working on supporting them right now.
Only rounded corners and trim paths are supported for now.

**Comment by laygir** [comment]
that's perfect, thank you very much. Looking forward to it. if you ever need a beta tester, count me in.

Cheers!

**Comment by bodymovin** [comment]
thanks!

**Comment by jacobsorensen** [comment]
I'm stuck with the same problem. Tried adding transparrent rectangle, but it didn't work. Can you upload the file, that made it work for you @laygir ?

**Comment by bodymovin** [comment]
@jacobsorensen can you share the .aep project so I can take a look?

**Comment by jacobsorensen** [comment]
Of course! Thanks for helping. 
[Bodymovin_Issue.aep.zip](https://github.com/airbnb/lottie-web/files/1758587/Bodymovin_Issue.aep.zip)

**Comment by bodymovin** [comment]
Hi, the rectangle you added fixes the issue already.
Where are you seeing it incorrectly?

**Comment by jacobsorensen** [comment]
It "works", but it doesn't mask out the entire shape. I'm only seeing a think stroke, like Laygir, initially did in this post. (I'm using version 5.1.7). This is what I'm seeing: 
![screen shot 2018-02-26 at 13 45 09](https://user-images.githubusercontent.com/6444964/36671293-615e8024-1afb-11e8-9af2-014683593ee9.png)

**Comment by bodymovin** [comment]
what renderer are you using?

**Comment by jacobsorensen** [comment]
I'm using SVG

**Comment by bodymovin** [comment]
can you share a link? I see it fine here with the correct width

**Comment by jacobsorensen** [comment]
I'm running locally. But heres a link for the project: https://we.tl/2FohK7GdCh

**Comment by jacobsorensen** [comment]
I have no idea why. But I think it is working now.
