### ISSUE TITLE
Doesn't interpolate between different numbers of vertices

### ISSUE THREAD

**Issue by ConradIrwin** [bodymovin/bodymovin#45]
Right now the player re-uses the same number of vertices for each key-frame, however After Effects may have different numbers of vertices per key-frame.

Either the exporter or the player should be able to add extra vertices by splitting the bezier curves, as is done by After Effects itself.

See https://gist.github.com/1655e593b75402df88e4, it should be a circle -> star -> circle, but the star renders with only four vertices.

**Comment by bodymovin** [comment]
@ConradIrwin yes! it's a feature I'm not supporting yet.
Will be available soon after 3d support is ready.
sorry :/

**Comment by ConradIrwin** [comment]
hey! no worries :) I'd have implemented it myself, but it was easier to just add more vertices to the circle in After Effects :)

**Comment by bodymovin** [comment]
done

**Comment by ConradIrwin** [comment]
Awesome, thanks!
