### ISSUE TITLE
CanvasRenderer is undefined in bodymovin light player

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [bodymovin/bodymovin#452]
I'm getting the following error in the console when using the bodymovin light player. Any guesses as to why I might be seeing this error? I'm guessing it might be me ... but this error seems to be pointing to the player code.

SCRIPT5009: 'CanvasRenderer' is undefined
bodymovin_light.min.js (6,29083)

**Comment by bodymovin** [comment]
the light version only supports the svg renderer

**Comment by Jeremy-Knudsen** [comment]
Hi Hernan,

Thanks for your quick reply. I see this message in spite of specifying "SVG" as the renderer to use for the animation.

Thanks,
Jeremy

**Comment by bodymovin** [comment]
can you share a link with the error?

**Comment by Jeremy-Knudsen** [comment]
Here's the link (just have the Console open when you load the page):
http://jeremyknudsen.azurewebsites.net/mwf/

**Comment by bodymovin** [comment]
try adding the renderer type on the div element.
data-bm-renderer='svg'
it will default to canvas if you don't.
I should change that for the light version, though.

**Comment by Jeremy-Knudsen** [comment]
Yeah, I was thinking since this is the _light_ player it should only support the SVG renderer and not even have a case statement here. Removing it would make the "light" player even lighter :)

**Comment by AlexandraKlein** [comment]
Still getting this error with `renderer: 'svg'` in the js and `data-bm-renderer="svg"` added to the container.

**Comment by bodymovin** [comment]
@AlexandraKlein hi, can you share a link?

**Comment by AlexandraKlein** [comment]
@bodymovin error went away after I reexported from After Effects. Thanks!

**Comment by fnagel** [comment]
@bodymovin 

> I should change that for the light version, though.

Any chance this will be changed? Still getting the console error with the light version and renderer set to SVG.

**Comment by mccallofthewild** [comment]
My hacky solution:
```javascript
window.CanvasRenderer = class {
    setProjectInterface() {}
}
/* Inject Player Below */
```

**Comment by artrayd** [comment]
@mccallofthewild then I have this error:

```
lottie_light.js?a851:10337 Uncaught TypeError: Cannot read properties of undefined (reading 'defs')
    at AnimationItem.setParams (lottie_light.js?a851:10337:1)
```

**Comment by artrayd** [comment]
@mccallofthewild 

I found the problem.. it was caused by ".lottie" class name for the animation container...
