### ISSUE TITLE
please add support for track matte

### ISSUE THREAD

**Issue by vishnu0vh** [bodymovin/bodymovin#453]
track matte is a feature in after effects which lets you clip mask a layer to another layer 
this feature lets the artist tweak the mask in ways any normal layer can be
can this be incorporated anytime soon ?

**Comment by bodymovin** [comment]
it should be working with the svg renderer.
What kind of matte are you using?

**Comment by vishnu0vh** [comment]
i am using a vector shape, an elipse with stroke and trim path as matte so that i can make my drawing appear in a circular path mask.. i am attaching how it would look in a gif along with this
![shubam](https://cloud.githubusercontent.com/assets/29099314/26666338/06d0d426-46bd-11e7-9a17-8d8d9281e388.gif)

**Comment by bodymovin** [comment]
is it not working? can you share the .aep?

**Comment by jhughes000** [comment]
I believe what @vishnu0vh  is talking about is "Preserve Underlying Transparency" which is explained here:

https://helpx.adobe.com/after-effects/using/alpha-channels-masks-mattes.html#preserve_underlying_transparency_during_compositing
