### ISSUE TITLE
Rubberhose object is being rendered incorrectly on SVG

### ISSUE THREAD

**Issue by k0mrad** [bodymovin/bodymovin#454]
I have exported everything from AE, and the canvas rendering works just fine, however when working with SVG the rubberhose is attached to the top left of the scene. Any ideas? 

https://codepen.io/komrad/pen/0bcbfad0318eba90892680951af705ab

https://www.dropbox.com/s/h2bys22k89e9aup/digital-panda-home%20auto-save%2055.aep?dl=0

**Comment by bodymovin** [comment]
Hi, I've tried it and it seems to work fine.
Do you have a link where it fails?
the codepen link seems to display another animation.

**Comment by k0mrad** [comment]
I just changed it 2 minutes ago haha. please check again.

**Comment by bodymovin** [comment]
You seem to be using an old player. can you try with the latest one?

**Comment by k0mrad** [comment]
fixed. thank you
