### ISSUE TITLE
Two masks, two comps

### ISSUE THREAD

**Issue by jorgosh** [bodymovin/bodymovin#455]
I've a simple single animation with a trim path animator. This has been pre-comped and put on another comp. In this main comp I've duplicated the animation and added a mask to both on one part. The second comp doesn't show up when rendering. No .ai files, just shapes and paths. When I remove a mask from the second comp, it renders everything.

**Comment by bodymovin** [comment]
Hi, can you share the .aep so I can take a look?

**Comment by jorgosh** [comment]
Hey, I've sent an email.
