### ISSUE TITLE
I have a question about using the Chinese version of AE

### ISSUE THREAD

**Issue by wyfang** [bodymovin/bodymovin#456]
I was using bodymovin derived json, but the use of Chinese version of AE, derived json Lane will have Chinese characters, how to solve this?

**Comment by bodymovin** [comment]
Hi, do you have issues loading that json?
Also, can you share the json or the .aep project?

**Comment by bbzz7** [comment]
![image](https://cloud.githubusercontent.com/assets/5621067/26763395/ddcd62d6-4984-11e7-9d06-30707a4dee9a.png)
I have the same problem too

**Comment by bbzz7** [comment]
The script can not be executed at line 129，After effect error: can not get the font outline, do you want to try another font?

**Comment by bodymovin** [comment]
Hi, some fonts can't be converted to shapes in AE.
Can you share the .aep so I can take a look? (include the font if necessary)

**Comment by wyfang** [comment]
I am sorry, I test, even if the Chinese can still run. So, this is not a problem, or thank the street
