### ISSUE TITLE
AE Effects

### ISSUE THREAD

**Issue by tobgt** [bodymovin/bodymovin#457]
Hello i knew that AE2Unity script doesn't support AE effects like " Radial Wipe "
so is there any other way to make Radial Wipe effect in AE and can work with this script ??

Also i tried Trim Path at line but didn't work too, Also mask didn't work , So please if you know how can
i make this effect and can work with script it will be great , thanks

**Comment by bodymovin** [comment]
Hi, I think people use a circle with a wide stroke with trim path as a track matte.
