### ISSUE TITLE
Rendered canvas wouldn't play

### ISSUE THREAD

**Issue by daksamedia** [bodymovin/bodymovin#459]
Hi @bodymovin 

I'm new on using this plugin.
I already rendered my animation into 'canvas', but it wouldn't play.
here's my config 👍 

`var anim;
	var canvaso = document.getElementById('canvaso')
    var elem = document.getElementById('bodymovin')
    var animData = {
        container: elem,
        renderer: 'canvas',
        loop: true,
		prerender: false,
        autoplay: true,
        rendererSettings: {
            clearCanvas: true,
            context: canvaso.getContext('2d'),
            //scaleMode: 'fit'
			//progressiveLoad:false,
			preserveAspectRatio: 'xMidYMid slice'
        },
		//animationData: JSON.parse(canvasSwitchData)
        path: 'data.json'
    };
    anim = bodymovin.loadAnimation(animData);
	anim.frameRate = 220;
	anim.play();`

Hope you can help me.
Thank you.

**Comment by bodymovin** [comment]
Hi, can you share a link where it is failing?
I can't figure out what might be wrong.

**Comment by daksamedia** [comment]
Hi, I already sent the file for you..
I sent it to your email.

**Comment by bodymovin** [comment]
It seems I didn't get it. Can you resend it?

2017-06-06 4:25 GMT-03:00 Daksa Media.Inc <notifications@github.com>:
