### ISSUE TITLE
Masks no longer supported?  3.1.7

### ISSUE THREAD

**Issue by ratchetdrums** [bodymovin/bodymovin#46]
Since updating to V3.1.7 on CC2015 13.6, I'm having trouble with the outputs.

I seem to need to convert every shape path to bezier.

Also masks don't seem to be working - this is evident in the bodymovin example where the second O (the one that's vomiting) doesn't preview properly.

Rending out a project that worked previously, now seems to ignore all the mask data.

**Comment by bodymovin** [comment]
@ratchetdrums do you have an example of this issues?
I'll take a look at the O in the bodymovin example but everything was working correctly on my side.
What kind of shapes you need to convert to bezier?

**Comment by bodymovin** [comment]
@ratchetdrums hi! the bodymovin animation works fine. do you have an .ae I can take a look at?

**Comment by ratchetdrums** [comment]
Hmmm, that's really strange, I wonder why I'm seeing it differently. I'll email you a link to download the .aep I'm working on as well as a few of the json outputs that I've had.

**Comment by ratchetdrums** [comment]
Have just emailed you

**Comment by itwasmattgregg** [comment]
I am having this issue as well. It doesn't seem to treat masks as expected

**Comment by bodymovin** [comment]
@itwasmattgregg Can you share the .aep so I can take a look?

**Comment by sandydesigner** [comment]
I am also having the same issue as well.

**Comment by bodymovin** [comment]
@sandydesigner can you share an .aep?

**Comment by sandydesigner** [comment]
[aep.zip](https://github.com/airbnb/lottie-web/files/1613924/aep.zip)

**Comment by neilpaytm** [comment]
I'm having issues with using masks also, specifically using set matte and shapes layers as a mask
