### ISSUE TITLE
Calculate intermediate state of two path shapes?

### ISSUE THREAD

**Issue by DaanDirk** [bodymovin/bodymovin#463]
Hi Hernan,
Very happy to have an interactive version of JnS!! Lots of possibilities. :) 

Now that the JnS works on some parameters interactively, I would love for the paths to work as well.
I figured i can do a path transformation on each axis with time remapping: http://www.daandirk.com/drag-jns/
So I guess, it is possible to calculate the intermediate state of these two shapes with something like polymorph.js: https://github.com/popkinj/polymorph

I would love to work on this.
But, it is possible to do this?
How would I go about putting javascript in an AE layer to get to try and do that?
Or do you see another method that could do something like this with less use of resources?

If you want it; this shape rig: https://www.dropbox.com/s/8j3togzsmkwhnb4/shape%20rig.aep?dl=0

Also I keep putting this part into the json by hand:
`"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[-135,-10,0],"e":[0,1,0],"to":[0,0,0],"ti":[0,0,0]},{"t":9255}]},`
Is there a way to trigger bodymovin to do that for me?

Thanks!

**Comment by DaanDirk** [comment]
Hi,

Didn't need to put the paths in the right form as AE already does that. So no need for polymorph.

So with this you can get the intermediate state between two paths.
`function pathMix(){
	// set the paths of the layers to mix
	A = 'v';
	B = 'h';
	Mix = 'mix';
	var aPath = document.getElementById(A);
	var bPath = document.getElementById(B);
	var mixPath = document.getElementById(Mix);
	var theAPath = aPath.children[0].children[0];
	var theBPath = bPath.children[0].children[0];
	var theMixPath = mixPath.children[0];
	// get the values
	var valuesA = theAPath.getAttribute("d");
	var valuesB = theBPath.getAttribute("d");
	// place to put the values and empty the value
	var valuesMix =[];
	valuesMix = [];
	
	// make the SVG string ready to calculate on, separating spaces, letters, commas and numbers
	var shapeArrayA =[];
	shapeArrayA = valuesA.match(/[ ]+|[,]+|[a-zA-Z]+|(-?\d*(\.?\d)+)+|-?\d/g);
	var shapeArrayB =[];
	shapeArrayB = valuesB.match(/[ ]+|[,]+|[a-zA-Z]+|(-?\d*(\.?\d+))+|-?\d/g);
	
	// go through the values
	for (var i = 0; i < shapeArrayA.length; i++) {
	var val = shapeArrayA[i];
	if(val === ' ') {
		val = ' ';
	} else if(isNumber(val)) {
		val = (Number(shapeArrayA[i]) + Number(shapeArrayB[i]))/2;
	} else {
		val = shapeArrayA[i];
	}
	// put them back together
	valuesMix += val;
	}
	
	// set the values to the mix path
	theMixPath.setAttribute("d", ''+valuesMix+'');
}`

I guess it would be nicer to get the values that need to be mixed from the json directly and to put them back in there again.
Even better if it would get the JnS keyframe values from the json as well. 
And then the values would need to be given the proper weight .
Might be easier to put the javascript formula in the layers directly and export them with bodymovin into the json.
Hope to figure that out soon.

**Comment by bodymovin** [comment]
So where in the rendering do you want to hook to modify shapes?
Are you thinking of setting an initial and final value and let bodymovin interpolate or do you want to set arbitrary middle values?

**Comment by DaanDirk** [comment]
The time remapping is a distraction.

I only want to set the current shape.

With JnS the 5 keyframes to interpolate between are transcribed in the expression of the path that should get the new interpolated shape.
That is an interpolation between 3 shapes; 
  1) center, 
  2) horizontal (either left or right), 
  3) vertical (either up or down).

So I get those from for example: anim.animdata.layers[i].shapes[j].ks.x ?
That being a layer with the script active.
Do a calculation with the 5 keyframes and the set joystick position,
and then put the interpolated values back in:
anim.animdata.layers[i].shapes[j].ks.k.i
anim.animdata.layers[i].shapes[j].ks.k.o
anim.animdata.layers[i].shapes[j].ks.k.v ?

Do only values with expressions have the x value set?

**Comment by bodymovin** [comment]
Yes, exactly, only values with expressions have the x.
if you want it interpolated, try creating 2 keyframes for the shape, one on the first frame and one on the last.
For it to update, change both values in the animationData, and it should work fine.

**Comment by DaanDirk** [comment]
Yes. It works: http://www.daandirk.com/
So silly it's impossible to do adjust the paths vertices in AE.
Would still like to put the calculation into the json. Would that be possible?

Also I keep putting this part into the json by hand:
"p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[0,0,0],"e":[0,1,0],"to":[0,0,0],"ti":[0,0,0]},{"t":9255}]},
Is there a way to trigger bodymovin to do that for me?

**Comment by Jeremy-Knudsen** [comment]
@DaanDirk I love this! You don't happen to have a tutorial that I could follow, do you?? :) I understand the theory behind this all, but I have yet to succeed in getting this to work for my own projects. Would you be able to outline the basic steps and/or let me know what your export settings are set to? Do I need both "export hidden layers" and "export guide layers" turned on?

**Comment by DaanDirk** [comment]
Hey @Jeremy-Knudsen, 
I haven't done a tutorial, but I can walk you through it and then maybe write one afterwards.
So, you got your headrig or whatever in after effects with Joystick n Sliders using shape layers?
And you need to adjust path shapes to get it looking just right?
Or what is your starting point?

http://www.daandirk.com/headrig-jns/
http://daandirk.com/wp-content/uploads/bm-headrig-jns.js

**Comment by DaanDirk** [comment]
In short how to do this.

> Do I need both "export hidden layers" and "export guide layers" turned on?
I didn't need that because to make it work I did this:

1) Put the solid/null which controls JnS as first layer and give it a name like: #name
2) Put the box from JnS as a second layer and name it
    If need be put the transparency at 0.1, but not 0. These layers need to exist on the web page for the script to work.
3) 3-n. foreground layers
4) n-m. layers with the paths that get transformed by JnS
   For each layer n-m with a path, build it with a path and below that the fill and stroke (not in a group).
So the layers n-m are just shape layers with in the content a path at the top.
For each of those paths put a keyframe at the start and end of the composition.
5) m+. background layers

If you need a more complicated set up or mask something, you can link/pickwhip to a path.
Ideally you can adapt the script to do this all automatically and just find the paths that need to be adjusted. :-) I haven't taken the time to do that jet.

In the script change the value for w in the for loop to the n and m layer numbers.
> for (var w = 3; w < 15; w++) {
This for loop extracts the path information from the json and puts it in an array.

Finally you have to replace a bit in the json. I believe this is to make the position of the first layer work like a slider.
Instead of something like:
>"p":{"a":0,"k":[250,250,0]},

Put:
> "p":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":0,"s":[0,0,0],"e":[0,1,0],"to":[0,0,0],"ti":[0,0,0]},{"t":9255}]},

The [0,0,0] part determines the starting point of the joystick

I believe that that is about it.
Let me know if you run into trouble. 
Would love to see the result.
