### ISSUE TITLE
fast blur + simple choker

### ISSUE THREAD

**Issue by sudeshprathap** [bodymovin/bodymovin#464]
couldn't convert the "simple blur + simple choker" effect into Java script file. Is there any way or It isn't possible?

**Comment by bodymovin** [comment]
Hi, no sorry, those effects are not supported yet.
They are difficult to replicate and I don't think that for real time rendering they'll be performant enough.
sorry :/

**Comment by SundancePioneer** [comment]
@sudeshprathap - you can use css-blur effects on certain objects by assigning a class or id to them. You can get around using the simple choker by using masks in most cases!
