### ISSUE TITLE
Images are blurry only on some monitors

### ISSUE THREAD

**Issue by derfmilar** [bodymovin/bodymovin#469]
This seems to be an issue with all browsers, but each have different problems. I'm just looking for any kind of help on this. 

To see what I'm saying -
- go this URL http://guidedtours.devmoore.com/
- select "provider"
- click "next"
- click on "3" in the bottom right
- click "next" one time

The language dropdown animation is blurry on most screens (but not all), and most browsers (but not all).

Thank you for any help on this at all!

**Comment by bodymovin** [comment]
It's probably because you're using very large images as source files.
When text in an image gets scaled too much, image renderers can't handle it with a good antialiasing.
Have you tried using the assets in their final size?
