### ISSUE TITLE
Impossible de faire un rendu

### ISSUE THREAD

**Issue by fyneDC** [bodymovin/bodymovin#471]
Bonjour,

J'ai eu beau lire un peu partout sur git, les messages des autres qui ont eu le même problème, je n'arrive pas à résoudre le mien.
Mon animation n'est pas folle, rien de bien tordu, juste des rotations.
J'ai toujours l'erreur, impossible, erreur à la ligne 311...

Bref, j'ai besoin d'aide...

Merci d'avance

**Comment by bodymovin** [comment]
Salut, pouvez-vous partager le project .aep pour que j'y regarde?

**Comment by fyneDC** [comment]
Bonjour,

J’ai consolidé le document. C’est vraiment un tout petit truc. Si jamais on arrive à le faire fonctionner, ça peut être pas mal pour notre projet final.

Merci d’avance et encore félicitation pour le plugin et surtout la maj avec les petits effets sur les boutons !

A bientôt !


	
Jean-Bastien Calatayud

Creative Director & Co-founder

jbcalatayud@fynedc.com <mailto:jbcalatayud@fynedc.com>        

+33 6 37 30 91 19 |fynedc.com <http://www.fynedc.com/>

**Comment by bodymovin** [comment]
Les fichiers attachés a un email n'arrivent pas a github, pouvez vouz l'attacher ici?

**Comment by fyneDC** [comment]
[M dossier.zip](https://github.com/bodymovin/bodymovin/files/1063881/M.dossier.zip)

**Comment by bodymovin** [comment]
as tu After Effects en francais?
Quelle version de bodymovin as-tu installée?
Ca devrait etre corrigé dans la derniere.

D'autre part, les animations 3d sont seulement supportées dans la Comp principale pour le moment.

**Comment by fyneDC** [comment]
yes, en français, la version CC 2017.
la version de bodymovin, je n'arrive pas à la trouver mais je sais que le plugin s'est mis à jour tout seul, je l'avais téléchargé à partir du store adobe.

OK, ça doit être pour ça, du coup je ne sais pas trop comment faire pour faire tourner mon objet en plus des formes...

**Comment by bodymovin** [comment]
aujourd'hui la version du store s'est actualisée, tu peux essayer avec celle ci.
Peux tu utiliser des Null Objects en lieu de Précomposer?

**Comment by fyneDC** [comment]
malheureusement, je ne suis pas assez calé en after pour te répondre...
je vais essayer quand même aujourd'hui.
