### ISSUE TITLE
4.7  Unable to export text elements

### ISSUE THREAD

**Issue by V-Zhou** [bodymovin/bodymovin#472]
I'm using the latest version 4.7, why can't I export my own simple text elements?
What additional settings do you need to export text?
When you export any text element, there is a pop-up, about the font
Also, I've tried the Chinese version of version 4.6. You can export text elements, but you can't export any elements with 3D rotation effects

**Comment by bodymovin** [comment]
hi, can you share the .aep so I can take a look?

**Comment by V-Zhou** [comment]
Sorry, I can't provide screenshots now. It will need to wait until tomorrow
But I remember that the error tip probably means "unable to render the outline of the font."

**Comment by bodymovin** [comment]
That's usually related to the used fonts.
Some fonts can't be converted to shapes in AE.
But nothing has changed related to that in version 4.7

**Comment by V-Zhou** [comment]
Are there any default supported fonts?

**Comment by V-Zhou** [comment]
Thank you very much for your quick answer, and now I have a video to demonstrate my problems

As shown in the video, I wrote a simple text element and exported the JSON file with "bodymovin"
But I don't know how to set it up when it comes to a Font popup

I look forward to hearing from you very much. Thank you very much!
[https://youtu.be/QH9jWB6ExZ8](url)

**Comment by bodymovin** [comment]
hi, the video doesn't seem to be working.

**Comment by bodymovin** [comment]
working now, sorry

**Comment by bodymovin** [comment]
does it work when you export it as Glyphs?

**Comment by fentonbutcher** [comment]
@bodymovin I'm having some similar issues. Font's don't seem to export properly when outlined in bodymovin in after effects 
![image](https://user-images.githubusercontent.com/25327714/28591845-faa52f0c-717e-11e7-890a-c5b71b459e99.png)

**Comment by fentonbutcher** [comment]
@bodymovin any help would be appreciated. I am using the latest version of Bodymovin and After effects cc 2017 on a mac

**Comment by bodymovin** [comment]
@fentonbutcher can you share the .json so I can check it out?

**Comment by fentonbutcher** [comment]
@bodymovin [test_02.json.zip](https://github.com/bodymovin/bodymovin/files/1174811/test_02.json.zip)

It uses the after effects file ( https://www.lottiefiles.com/327-tagging )

Which i know works, just unsure as to why my export isn't working. I've been going around in circles with this for a week or so :(

**Comment by bodymovin** [comment]
Are you trying it with Lottie or with Bodymovin in the browser?

**Comment by RhysyG** [comment]
Can't export any text without getting:
Unable to execute script at lie 280. null is not an object.

My file is a new comp with just the text "Test". I have even tried to use some of the template files (like hashtag) with the same result.

I've also got the latest updates.
Adobe After Effects 15.1.0 (Build 166)
Bodymovin 5.1.1

It then opens the bm_charHelper tab with this:

<img width="1417" alt="screen shot 2018-04-12 at 3 32 48 pm" src="https://user-images.githubusercontent.com/5491092/38661659-fffea8a2-3e74-11e8-821e-b0c01527b159.png">

**Comment by nasdaq0408** [comment]
I also got this problem and I tried an alternative way to make it work by create outlines of the text in AI first and then import it into AE. It works but tricky.
