### ISSUE TITLE
html renderer

### ISSUE THREAD

**Issue by casillasluisn12** [bodymovin/bodymovin#473]
Great plugin btw, truly truly amazing. 

Just a little issue. 

I noticed that changing the renderer from svg to html, creates a div with height 0, checked in both chrome and safari. later changing that height from the console shows nothing. with svg works just great. I'm working with Bootstrap 

right now it doesn't really affect my workflow, but I saw that you can apply 3d transformations with css and would like to experiment with it in the future.

**Comment by bodymovin** [comment]
yes, when using the html and canvas renderers, you need to call the resize method on the instance whenever you need for it to resize.

**Comment by casillasluisn12** [comment]
Ok, yeah, that was it. Also, it didn't appear with height percentage values, it only worked when a numerical value was assigned. 

Thanks for the response. Again what an amazing plugin 🙌🏽

**Comment by kamman27** [comment]
Jus stumbled on this thread and I seem to be having a similar issue. I'm wondering what the resize method you're referring to is, and how to use it? Experiencing the same thing, switched renderer to 'html' from 'svg' and it no longer displays. Worked fine when rendering to svg

**Comment by bodymovin** [comment]
@kamman27 you can call `.resize()` on your animation instance
