### ISSUE TITLE
Single stage with multiple animated elements to be controlled individually

### ISSUE THREAD

**Issue by awingit** [bodymovin/bodymovin#478]
Hi, 

I am not sure of this is a feature request or can be done already. 

I am trying to improve the work flow from animator to developer. 

What comes to mind is allowing the animator to have a single stage which then has individual animated elements/characters which I can then control individually. Instead of having to export individual animations. This would allow the animator to position and animate as desired, then I could add the triggers for specific animations on the stage. 

If this is not yet possible, then I would like to suggest this feature. It would be cool if the animator could setup the stage and the elements within after effects and be able to give the animations unique IDs and even markers to determine specific loops within the animation. 

Any feedback is much appreciated. 

Many thanks for this awesome tool! 

Adrian

**Comment by bodymovin** [comment]
Good idea but it's not that simple because they all run in a single instance.
You could play around with in points and time remapping to achieve this, but not sure how flexible it will be.

**Comment by DaanDirk** [comment]
I just did a single stage with multiple elements controlled by time remapping, resetting in and outframes after a loopComplete:
http://rechthoekig.nl/rechthoekig-augustus/
Check the js here: http://rechthoekig.nl/wp-content/uploads/rh-augustus.js

Compare with: http://rechthoekig.nl/rechthoekig-maart/
the js: http://rechthoekig.nl/wp-content/uploads/rechthoekig/rh-maart.js
Where I stacked different animations on top of each other and added a invisible 'clicklayer' on top of all to register the right clicks.

Setting markers or whatever from within after effects would be nice.
I first tried to do that with sliders and expressions on the time remapping, but alas that isn't implemented yet. 
I tried something like this: 
>max = thisComp.layer("Null 1").effect("Slider Control")("Slider");
min = 0;
t1 = key(1).time;
t2 = key(2).time;
linear(time,t1,t2,min,max);

Are expressions on time remapping coming? Is something like this possible?
That would be nice tough!

Another option is to set classnames with frames/intervals and read those with a script which plays them accordingly, but you would be working 'blind' in after effects.

**Comment by bodymovin** [comment]
I've tried your expression on the time remap and it seems to work fine.
What are you getting as a result?

**Comment by DaanDirk** [comment]
Yeah, it is working! I will be using it in the future.
I deleted my original expression. Not sure what went wrong before.
The preview would only show 1 frame.
There aren't any size-constraints on the preview window, right?

Wanted to use it like this (which now works in the preview!) to get to a different part on the fly:
> input = framesToTime(thisComp.layer("Shape Layer 1").effect("t")("Slider"));
max = framesToTime(85) + 85*input;
min = 85*input;
t1 = key(1).time;
t2 = key(2).time;
linear(time,t1,t2,min,max);

So now I can have it both visible in AE and in the online interactive version.
Yes!
