### ISSUE TITLE
Animation loops within a single animation

### ISSUE THREAD

**Issue by awingit** [bodymovin/bodymovin#479]
Hi, 

Is there a way to use a single animation provided by an animator to be able to loop segments of the animations? 

The first idea that comes to mind is simply using time and detecting when an animation reaches a certain time then the animation either resets to the beginning of the loop or reversing. 

What this would allow is the animator to be able to determine varies loops within a single animation export and I can then control individual loops with a single animation. This helps with not having to export individual animations for each loop. 

Any feedback is much appreciated. 

Regards, 

Adrian

**Comment by bodymovin** [comment]
you can use playSegments() to achieve that. It takes an array with an initial and final frame, and a flag to force it right away.

**Comment by awingit** [comment]
Thank you. Does playSegments allow for infinite looping? For instance, if I play a segment, would it loop infinitely by default?

**Comment by bodymovin** [comment]
if the loop param is set to true, yes

**Comment by awingit** [comment]
Thats awesome. Thanks for an awesome plugin!
