### ISSUE TITLE
Control Framerate

### ISSUE THREAD

**Issue by Komsomol** [bodymovin/bodymovin#48]
Hi,

Awesome plugin. But I have question. I would like to control the frame rate of the playback.

Bit confused where to change this.

Editing anim directly doesn't seem to work as it's just the data itself.

I can see that I can change the 'speed ' by using bodymovin.setSpeed(1); but I would like granular control over the frame rate playback?

How is this possible? Thanks!

**Comment by bodymovin** [comment]
@Komsomol hi.
there's a property on the instance returned by the "loadAnimation" method that you can use to change the framerate.
something like this:
var anim = bodymovin.loadAnimation(params);
anim.frameRate = 25;

**Comment by Komsomol** [comment]
Hi thanks for you reply. This is my code and there is no effect on frameRate via anim.frameRate

This is my code... am I missing something basic?

      var animData = {
          wrapper: document.getElementById('bodymovin'),
          animType: 'svg',
          loop: true,
          prerender: true,
          autoplay: true,
          path: 'data.json',

    };
    var anim = bodymovin.loadAnimation(animData);

    anim.frameRate = 60;

**Comment by bodymovin** [comment]
@Komsomol yes, sorry I didn't clarify that.
If you're loading the animation data asynchronously, you need to wait for the "data_ready" event to fire, or it will overwrite your manual setting.
anim.addEventListener('data_ready', function(){anim.frameRate = 60});

**Comment by Komsomol** [comment]
Sorry to keep bothering you but I can't seem to get that working at all. This is my code.

Frame rate stays at 28. I see the data_ready function being called. I took the latest lib from 
https://raw.githubusercontent.com/bodymovin/bodymovin/master/build/player/bodymovin.js

I looked at the examples but can't seem one where FrameRate is controlled. Thank you so far for your help! 

    var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'svg',
        loop: true,
        prerender: true,
        autoplay: true,
        path: 'data.json',
    };

    var anim = bodymovin.loadAnimation(animData);

    anim.addEventListener('data_ready', function(){
        anim.frameRate = 60;
        // shows rate at 60 but playback is still at 28. I tried silly nums like 10 or 120.
        console.log('rate?', anim);
    });

**Comment by Komsomol** [comment]
I got it working by changing all 3 vars controlling the frameRate


    anim.addEventListener('data_ready', function(){
        anim.frameModifier = 0.120;
        anim.frameMult = 0.120;
        anim.frameRate = 120;
        console.log('rate?', anim);
    });

Is this how it's supposed to be?

**Comment by bodymovin** [comment]
@Komsomol sorry, I don't have the code here and couldn't test it right.
modify those values and then to get an update do anim.setSpeed(1);
out of curiosity, why wouldn't you use the setSpeed directly?
If you have the original frameRate it would be simply doing: setSpeed(newFrameRate/originalFrameRate);

**Comment by Komsomol** [comment]
@bodymovin 

I didn't know that you can do that with "setSpeed(newFrameRate/originalFrameRate);"

My animator was against using setSpeed as I and he thought it would just do a range from 0 to n.

Thank you for all your help. Great Lib!

**Comment by omasback** [comment]
> If you're loading the animation data asynchronously,

@bodymovin, is `bodymovin.loadAnimation` asynchronous?? sure doesnt seem like it

**Comment by bodymovin** [comment]
if you pass a path to loadAnimation, it does an xmlHttpRequest to load the json file.
If you pass animationData it will load it immediately.
Is that what you mean by asynchronous?

**Comment by vikomte** [comment]
Hi, i have tried all the solutions, but the only thing that appear to change my animation is when i change frameMult.
I would like to drop the frameRate, and im testing it with anim.frameRate = 2.
Is this solution still relevant @bodymovin ?

**Comment by ofmarconi** [comment]
@joeqj and noticed lower CPU consumption?
