### ISSUE TITLE
CliPath don't work in Microsoft Edge if is defined inside <defs>

### ISSUE THREAD

**Issue by 7iomka** [bodymovin/bodymovin#482]
Hello!
I noticed a strange bug that I could not fix with the help of answers on the Internet, however I randomly moved the <clippath> definitions from <defs> to the body <svg> and hurray - it worked!
The real question is how do I interact with the received json file to get the clippaths from the defs before the animation starts?
Of course, I can first render to the scene, then move with js, and then call the play method, but this is the extra resources and time spent (.
Thanks for any ideas!

**Comment by bodymovin** [comment]
Hi, can you explain a little more of the use case?
You'd like to modify masks before animation starts?

**Comment by 7iomka** [comment]
https://j.gifs.com/X64qml.gif
I want the clippath to be rendered out of defs because the edge does not support the clippath declaration inside the defs! How it works I showed on the animated screenshot.
There is no existing customization in api to do this at the export level from AE via bodymovin I did not find

**Comment by bodymovin** [comment]
I don't think the problem is having it inside the defs tag. Usually Edge works correctly once you modify something from the console.
Can you create a simple demo where it shows clip paths don't work?
It doesn't have to use bodymovin at all, just a basic demo.

**Comment by 7iomka** [comment]
You are right about something.
https://codepen.io/7iomka/pen/YQGwvG - without gsap & bodymovin animations 
https://codepen.io/7iomka/pen/YQGwdp - only bodymovin animations
https://codepen.io/7iomka/pen/OgRMqz - gsap & bodymovin animations 
All works
However, with site styles (moved as is)
This bug is observed:
https://codepen.io/7iomka/pen/EXgKyP?editors=0110 - not working correctly
I'm scratching my head, what could it be like...
Thanks for any ideas. The site is actually already ready for production, and here such a bug (thanks for a good plug-in!
