### ISSUE TITLE
Is it possible to use outside of RequireJS when RequireJS is loaded on the page?

### ISSUE THREAD

**Issue by cj-rogers** [bodymovin/bodymovin#483]
Hi,

I'm trying to get this to load onto a site where I only have partial control over whats loaded/how it loaded onto the page. The part I don't have control over uses RequireJS to add their own scripts. 

When I try to load this script the 'normal' way, this causes a conflict with RequireJS because of the define global variable. Then If i try loading it within a requireJS function, all other scripts fail on the page.

Is there a version of this plugin without any reference to requireJS, specifically the define variable?

Thanks

**Comment by bodymovin** [comment]
Hi, unfortunately there is no build without the define method checked.
If you use the unminified version you could do a quick fix changing the validation
typeof define === "function" && define.amd
to something else

**Comment by cj-rogers** [comment]
Hi, thank you for the quick response!

In the end, I had to remove the define and object creation conditionals to get this working!
This is very much so an extreme edge case.

Thanks again for your help! Closing ticket.
