### ISSUE TITLE
Key animation issue

### ISSUE THREAD

**Issue by tobgt** [bodymovin/bodymovin#484]
I'm really didn't understand what happened here , but when i run script it divided the animation , so it doesn't work smoothly as it is in after effects , in unity each loop it stops for a part of a second and it continues in the other loop .
![keyissue](https://user-images.githubusercontent.com/28784190/27036075-fb434768-4f83-11e7-8cc4-1eae3da4418d.jpg)

**Comment by bodymovin** [comment]
can you subtract one keyframe from the animation Work Area?

**Comment by tobgt** [comment]
iam sorry what do you mean ??!

**Comment by tobgt** [comment]
Please explain more , all what i did in after effects is a rotation key from 0 : 360 and i run the script . and when i opened it in unity i found it divided to 4 keys and it didn't work smoothly
