### ISSUE TITLE
Font Rendering not working in some cases

### ISSUE THREAD

**Issue by mountaindata** [bodymovin/bodymovin#485]
I am trying to export some text layers that use special characters using the "fonts to shapes"-feature. I had no issues while rendering other files with the same specifications but this time the script doesn't work:

![1](https://user-images.githubusercontent.com/29404675/27087069-4dcffcd0-5054-11e7-9755-4d2aac23e26d.jpg)
![2](https://user-images.githubusercontent.com/29404675/27087067-4dbecc4e-5054-11e7-9453-64b4667b76cb.jpg)

What am I missing this time?

The broken file and a working one can be found here:
[CT](http://afraz.de/CloudTemplates.zip)

**Comment by bodymovin** [comment]
there seems to be a character in some of your layers that can't be exported:
#65279 is the Unicode Character 'ZERO WIDTH NO-BREAK SPACE' 
for example in your layer 99: ﻿"Virtual Reality wird behandelt von Finanzen"
if you delete it, it should work fine.
I'll try to fix this on the extension side on the next update.

**Comment by mountaindata** [comment]
Thank you for looking into this. I appreciate your support very much.
