### ISSUE TITLE
Using Stroke Effects For Text Animation

### ISSUE THREAD

**Issue by RTDQ** [bodymovin/bodymovin#486]
I've been trying to do a simple handwriting animation test in after effects but when loading the export in chrome it only plays the last letter of it. I'm using the stroke effect for it and from reading the wiki the support for it is only partial. Would it just be a case of this not being compatible with the extension or am I missing something? This is what the output looks like in chrome:

![bodymovin](https://user-images.githubusercontent.com/9151123/27095704-853cb57a-5066-11e7-97df-5a65ce4846e7.gif)

Here's the export and after effects project:

https://drive.google.com/open?id=0BwmJXNLk6lQIRHZnQkFOV0FIUms

As an aside: would I be right in saying that text layers aren't supported? I had to convert it to a shape just to display it.

**Comment by bodymovin** [comment]
closing. Reopen if still facing this issue.

**Comment by guitar9** [comment]
What is the answer?
Why is it closed without any answer?

**Comment by bodymovin** [comment]
@guitar9 are you experiencing the same issue?

**Comment by guitar9** [comment]
hello. yes. should i upload my project files?

**Comment by guitar9** [comment]
in After Effects the Animation works correctly. if i export it with bodymovin each letter of the text was written at the same time. ( not from the beginning to the end)

**Comment by qbait** [comment]
I'm experiencing the same issue.

**Comment by bodymovin** [comment]
@qbait can you share your .aep?

**Comment by PivunovaAnna** [comment]
I also have the same problem and I would be grateful if you could help me. in After Effects the Animation works correctly. I've exported the first option and it worked just like in this comment: " each letter of the text was written at the same time. ( not from the beginning to the end) " .After that I tried various options, but none of them worked at all ( in after ef. everything was fine). I attach the link on  the files of the first variant 1. ae file + result and the last 2. ae file + result + preview on the site (does not work)  https://drive.google.com/drive/folders/1DbWlhd5SAuwEITpNGqkq-2A7rk-rx7b9?usp=sharing  http://spacey.hable-test.ru/

**Comment by bodymovin** [comment]
@PivunovaAnna hi, can you share the missing font Born Ready and .ai files?

**Comment by PivunovaAnna** [comment]
@bodymovin Done! please check the folder

**Comment by bodymovin** [comment]
@PivunovaAnna The stroke effect has very limited support, that's why it's animating simultaneously.
Perhaps using an alpha mask and trim path you can get the same effect.
