### ISSUE TITLE
QUERY: How are animations rendered?

### ISSUE THREAD

**Issue by awingit** [bodymovin/bodymovin#488]
When I debug the animated SVG with chrome dev tools, I notice there is a hide/show animation of individual frames. I am just curious to know if this is the only way it would render or if animated paths and shapes could be rendered, not as frames?

The reason I ask is because I would assume the file size would be much less if a single vector shape is loaded and then the actual vector points be modified.

I am not sure if this is available already.

**Comment by bodymovin** [comment]
The plugin actually updates a single vector if it comes from the same AE layer.
Hidden shapes are layers that are no longer in the composition's current frame.

**Comment by awingit** [comment]
Ok cool. I then assume it has to do with the animation itself. Thanks.
