### ISSUE TITLE
Animation doesn't export properly

### ISSUE THREAD

**Issue by OpherV** [bodymovin/bodymovin#490]
This is my animation in AE
![forest1](https://user-images.githubusercontent.com/3951311/27171966-1a212530-51bc-11e7-8e85-e0a8d7186797.gif)

When exported with Bodymovin:
![forest_rendered](https://user-images.githubusercontent.com/3951311/27171973-20aa0818-51bc-11e7-93ff-7ab30907c1ed.gif)

Looks like something weird is going on with masking.

Here's the composition
[forest.aep.zip](https://github.com/bodymovin/bodymovin/files/1076993/forest.aep.zip)

**Comment by samiam2017** [comment]
issue is with the inverted alpha on your tree comp. If you turn that off the project will render the green part. I think bodymovin doesn't support inverted alphas.

**Comment by OpherV** [comment]
Got it. Thanks @samiam2017!
