### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by matthijsotterloo** [bodymovin/bodymovin#493]
Hi!

I'm trying to install this on Adobe After Effects CC 2017, but I can't manage to install it.
ZXP Installer says: "Installation failed because the extension is not compatible with the installed applications" and installing it trough the command line with `./Contents/MacOS/ExManCmd --install bodymovin.zxp` gives `Failed to install, status = -403!`.

How can I solve this?

**Comment by bodymovin** [comment]
Have you tried installing it through aescripts?
http://aescripts.com/bodymovin/
