### ISSUE TITLE
Some layers look fine, but some look like they felt from mask, although no masks were applied

### ISSUE THREAD

**Issue by inessashillo** [bodymovin/bodymovin#494]
Hi! I have a strange issue. I have fully prepared and simple file from AI https://tppr.me/NixYo with super simple animation in AE. No extra dots in paths. Although, when I render it with bodymovin I've got this https://tppr.me/jkSy3.

Do you know something about that problem and how can I solve it?

**Comment by bodymovin** [comment]
hi, can you share the .aep so I can take a look?

**Comment by inessashillo** [comment]
[twist.zip](https://github.com/bodymovin/bodymovin/files/1088877/twist.zip)
Sure!

**Comment by bodymovin** [comment]
that zip doesn't seem to have the .aep file.
I only got the .ai and .json

**Comment by inessashillo** [comment]
Shoot! sorry!
[twist aep.zip](https://github.com/bodymovin/bodymovin/files/1090816/twist.aep.zip)

**Comment by bodymovin** [comment]
I see it working fine here. Is it possible that you're using an older version of the player?
Can you share a link where it fails?

**Comment by inessashillo** [comment]
https://svgsprite.com/demo/bm/player.php?render=svg&bg=333 here

**Comment by bodymovin** [comment]
That is an old version of the player, that must be the reason why it fails.
It's usually best to use the player equal or newer than the animation.

**Comment by inessashillo** [comment]
can you share a newer player?

**Comment by bodymovin** [comment]
on the bodymovin panel in After Effects, select Get the Player and you can get your current version.

**Comment by inessashillo** [comment]
Yeah, it works! I struggled it for so long and it was only the player issue 😅  Thank you!
