### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by elzanzibar** [bodymovin/bodymovin#499]
Hi! Loving the Bodymovin extension but having some real difficulties exporting... 

Sometimes they work and other times they render out static, out of position and out of scale! I can't seem to get any consistency out of it...

I've attached my most recent render and the .AEP file.

Please help me crack this!! Got deadlines...

[Lovemoney.zip](https://github.com/bodymovin/bodymovin/files/1095066/Lovemoney.zip)

**Comment by bodymovin** [comment]
Hi, there seem to be some files missing, can you share them too?

**Comment by elzanzibar** [comment]
Thanks for getting back to me!

I've attached the files with all the assets in.

[728x90 Leaderboard.zip](https://github.com/bodymovin/bodymovin/files/1101445/728x90.Leaderboard.zip)

**Comment by elzanzibar** [comment]
[728x90 Leaderboard.zip](https://github.com/bodymovin/bodymovin/files/1102159/728x90.Leaderboard.zip)

**Comment by elzanzibar** [comment]
Same with this, can't figure out the method to the madness!

**Comment by elzanzibar** [comment]
Please I just can't figure out the method to the madness! What am I doing wrong?
[TotalJobs.zip](https://github.com/bodymovin/bodymovin/files/1102483/TotalJobs.zip)

**Comment by elzanzibar** [comment]
No matter what variants I try 
[TotalJobs 2.zip](https://github.com/bodymovin/bodymovin/files/1102497/TotalJobs.2.zip)

**Comment by elzanzibar** [comment]
Hi Hernan,

Are you able to shed any light on the problems?

Thanks

**Comment by bodymovin** [comment]
Hi, there seems to be a problem mixing 3d layers and 2d layers, but I'm not sure yet.
I need to investigate some more.
