### ISSUE TITLE
looping

### ISSUE THREAD

**Issue by juancabrera** [bodymovin/bodymovin#50]
I don't think is possible to do it right now, but would be great to being able to loop just a part of the animation, not the whole thing. I currently have a flag animation that rises and them it waves. I think would be better to being able to loop just the "waving" part of the animation instead of having 2 different animations and loop just the second one.

Does it makes sense ?

**Comment by bodymovin** [comment]
@juancabrera yes, absolutely. That way you don't need to load information twice.
You can do it right now:  
set loop in true 
and then, once the animation is loaded, set
anim.playSegments([[0,20],[21,80]],true) 
where [0,20] would be the first segment and [21,80] the second, both in frames.
if you need any help, let me know.

**Comment by juancabrera** [comment]
@bodymovin that worked perfectly! Thanks!

**Comment by sbsomya** [comment]
Can we loop some segments and not loop some segments
Have a small functionality with http://www.lottiefiles.com/73-submit-confirmation
Want the middle animation stay till the task is complete and then fire the next segment
