### ISSUE TITLE
Does this awesome library works with Angular 1.x 

### ISSUE THREAD

**Issue by Khachatour** [bodymovin/bodymovin#500]
Hey there folks! 

I am now trying to make bodymovin work with angular 1.x, does anyone managed to do this ?

**Comment by Khachatour** [comment]
Nevermind folks, I've wrapped it in a service, but now I do have interesting error which says 
`Unexpected token < in JSON at position 0`

**Comment by bodymovin** [comment]
that looks like the json was not found in that specified url.
Can you share a link where it fails?

**Comment by Khachatour** [comment]
I am using minfied CDN

**Comment by bodymovin** [comment]
yes

**Comment by Khachatour** [comment]
![screen shot 2017-06-22 at 9 31 05 pm](https://user-images.githubusercontent.com/8447007/27447502-39a019bc-5792-11e7-8ac2-ce254ccf010f.png)

In the left you can see, landing folder, in which is data.json, and in the same folder you can see landing.controller.js in which I've added JSON path, as jsut path: 'data.json'

**Comment by bodymovin** [comment]
the json path is probably relative to your index.html, not to the .js file
your templateUrl path is pointing to 'app/user' and that path is not there.
Try doing the same with the json path moving it to the client folder.

**Comment by Khachatour** [comment]
Oh, thanks mate, it was a stupid mistake :) 
Can I continue with that and try to make an open source wrapper for Anuglar 1.x users ? Do you approve ?

**Comment by bodymovin** [comment]
yes of course :+1: 
thanks

**Comment by Khachatour** [comment]
Great!! :))

**Comment by adeopura4** [comment]
Hi - were you able to create an open source AngularJs 1.x plugin for bodymovin
