### ISSUE TITLE
Flickering on frame-by-frame animation

### ISSUE THREAD

**Issue by dotcomartist** [bodymovin/bodymovin#501]
I'm experiencing an issue with the opacity of a frame-by-frame animation I created. In this animation the flag unfurls and flaps 4 or 5 times, then recedes. I'm repeating multiple states of the flag on the same layer. In order to do this, I had to set the opacity on a keyframe from 0% to 100% and back to 0% with no empty frames between. It looks fine when played within After Effects, but when I render it with bodymovin, the opacity does some strange things. The flag looks translucent and there is some hideous flickering. Any ideas?
http://meredithworks.com/allrecipes/ar-logo/flag/

**Comment by bodymovin** [comment]
try doing
anim.setSubframe(false);
after
anim = bodymovin.loadAnimation(animData);

**Comment by dotcomartist** [comment]
Thanks! That worked!


Jeff Cummings
Senior Designer
Meredith Digital
p:      206.436.7424  m: 206.713.5870
w:      meredith.com<http://meredith.com>  e: jeff-cummings@meredith.com<mailto:jeff-cummings@allrecipes.com>
[http://dish.allrecipes.com/wp-content/uploads/2017/02/MeredithDigital_2016_logo-96x22.png]
[http://dish.allrecipes.com/wp-content/uploads/2017/02/facebook-icon.png]<https://www.facebook.com/meredithcorporation/>  [http://dish.allrecipes.com/wp-content/uploads/2017/02/twitter-icon.png] <https://twitter.com/MeredithCorp>   [http://dish.allrecipes.com/wp-content/uploads/2017/02/linkedin-icon.png] <https://www.linkedin.com/company/meredith>

________________________________

**Comment by bodymovin** [comment]
:)
