### ISSUE TITLE
Gradient fill dosen't work

### ISSUE THREAD

**Issue by PeterKim87** [bodymovin/bodymovin#502]
Hi, I just made a simple shape layer with gradient fill for test.

But it doesn't work properly. It just showed black & white gradient.

I tried to look in json file, i guess the color information is wrong..
~~~ "g":{"p":2,"k":{"a":0,"k":[0,1,1,1,1,0,0,0]}},  ~~~

I've got other json file which is showing gradient to compare with mine.
It has..
~~~ "g":{"p":3,"k":{"a":0,"k":[0,1,0.541,0,0.5,1,0.747,0,1,1,0.953,0]}}, ~~~

What's wrong with mine?

Can you help me?

I'm using AE CC2017(14.2.0.198), bodymovin 4.7.1
Thanks.

**Comment by bodymovin** [comment]
hi
try saving the .aep before exporting.
Gradient data is fetched from the .aep file itself.

**Comment by PeterKim87** [comment]
@bodymovin First, thank you for your answer. But it doesn't work for me. I already tried that way before(I searched same issues first, but nothing help to me)

Could you check my After Effect Project? It is not special indeed...

[lottie_2017.zip](https://github.com/bodymovin/bodymovin/files/1100788/lottie_2017.zip)

I attached json file which is exported by lottie_2017.aep

Thanks

**Comment by bodymovin** [comment]
do you have the .aep as well?

**Comment by PeterKim87** [comment]
Oh, I meant I attatched both json file and .aep file. :)

Please check the file I attached.

**Comment by bodymovin** [comment]
I only see the json file there

**Comment by PeterKim87** [comment]
[lottie_2017.zip](https://github.com/bodymovin/bodymovin/files/1100991/lottie_2017.zip)

I attach again! Thanks :)

**Comment by DaanDirk** [comment]
Works for me:
http://www.daandirk.com/bm-test-data/

**Comment by PeterKim87** [comment]
@DaanDirk Which version of bodymovin are you using?

I'm the lastest version(4.7.1) in AE CC 2017(14.2.0.198).

**Comment by DaanDirk** [comment]
Just went to the latest build and player. Still works.
You can check the version at the start of the json.
And I always append a bodymovin version to my players.

**Comment by DaanDirk** [comment]
I had the same problem a while ago, but that was with radial gradients. 
Ah, radial gradient inside a shapegroup goes black and white.

**Comment by PeterKim87** [comment]
It doesn't still work.. Even in bodymovin preview.
I look in json file, I guess color informations are different from AE(there are only black & white).

Should I set any settings before use this??

**Comment by bodymovin** [comment]
It works for me here too.
Are you using AE in english?

**Comment by PeterKim87** [comment]
I guess, yes. Because every menu shows in English.
I installed Adobe MASTER COLLECTION and some program(i.g. Media Encoder) show in Korean(I don't know why...)

Can it make any problems?

**Comment by bodymovin** [comment]
I've opened the .aep with a notepad and the gradient data seems correct, so I don't think that is the problem.
Could your .aep be in a folder with special user permissions?
What OS are you using?

**Comment by PeterKim87** [comment]
Windows 7 Professional K

I don't think there need any permissions. But let me check again about folder.

**Comment by PeterKim87** [comment]
.aep is in Desktop and .json is also in Desktop.

@bodymovin you told me the gradient data seems correct, but i don't think so..
because the data is <~~~ "k":[0,1,1,1,1,0,0,0] ~~~> that means black and white.

**Comment by PeterKim87** [comment]
Plus, I've got a .aep which is exported gradient well. And when I export it, there has same problem with gradient. 

So I guess problem is my settings or something else about my environment.

**Comment by luvpet** [comment]
Hi, did you figure out which setting occurs that issue? Cuz I'm struggling with the exact same problem with you. Every linear gradient filled shapes I made in AE turn into black & white gradient, no matter what color I used. (Since I know effects are not supported yet, so I didn't use any tint effect)

**Comment by bodymovin** [comment]
@luvpet hi, try saving the .aep before exporting

**Comment by okapii** [comment]
@bodymovin I am experiencing the very same issue with gradients. Is this really considered resolved as the bugreport is closed?

**Comment by bodymovin** [comment]
@okapii hi, have you saved the project before exporting?

**Comment by okapii** [comment]
@bodymovin Yeh, I read up here and did that but sadly to no avail.

I started messing with the json-file out of desperation yesterday. I managed to get *some* color slapped onto the gradients but since the colors seem to be defined in a non standard way I could not get the desired result. Neither could I find any documentation on this online. Any chance that you could give some info on that? Having a fallback plan available would be appreciated since lotsa people seem to encounter issues with gradients.

**Comment by bodymovin** [comment]
@okapii can you share the .aep?

**Comment by okapii** [comment]
It's a commercial project but I just isolated the relevant part.
[Here](https://github.com/airbnb/lottie-web/files/3955342/191212_lottie_gradien_issue.zip) is a package containing the .json-file, the generated demo.html and lastly .aep file.

**Comment by bodymovin** [comment]
I just exported it and it worked fine on my side.
I guess the problem is that your OS or AE is in german.
I've seen issues before with gradients when the system is in another language because gradient data is retrieved from the .aep file itself.
Can you try renaming the gradient property "Verlaufsfüllung 1" to something without special characters and see if it works?

**Comment by okapii** [comment]
Sadly that part is not coming from a renameable parameter in AE (see screenshot). But I manually edited the json-data yesterday hoping that removing all German umlauts would resolve the issue which it sadly did not. I searched and replaced all ä, ö, ü and ß characters to ensure that this is not causing any trouble. Messing with `"a": 0, "k": [1, 1, 1, 0, 1, 1, 1, 1], "ix": 9` lead to a colored gradient but as I have no idea how this works, I did not manage to get the desired colors.

<img width="921" alt="Bildschirmfoto 2019-12-12 um 12 17 20" src="https://user-images.githubusercontent.com/4265181/70708124-0f198380-1cda-11ea-8b26-764e13955b95.png">

**Comment by bodymovin** [comment]
Have you tried renaming the "Verlaufsfüllung" property?
Gradients are retrieved navigating all the properties tree.
Also, after renaming, remember to save the project before exporting.

**Comment by okapii** [comment]
Yeah, that part sadly can't be renamed in After Effects. It's a property named that by AE which users cannot change.

**Comment by bodymovin** [comment]
@okapii that's strange, I just tried to rename it and it worked. I'llego try again when I get home from work.
What version of AE are you using?

**Comment by okapii** [comment]
I am using AE Version 17.0.0 (Build 557)
I just made sure that I am not missing anything and asked two colleagues but one indeed can't rename this. Just to be sure: we are talking about this property, correct?

![ae_screenshot](https://user-images.githubusercontent.com/4265181/70720141-90c9db00-1cf3-11ea-99c1-9778036c1623.png)

**Comment by bodymovin** [comment]
yes, correct

**Comment by okapii** [comment]
Update: I changed my AfterEffects application language to en_EN, opened and saved the file again to then render it. Still black and white gradients. Interestingly changing the language did not change the gradient label from the German "Verlaufsfüllung" to its English translation.

**Comment by bodymovin** [comment]
I checked and I was able to rename that property. 
Now that you changed the language can you try two things?
- export the animation one more time
- or try renaming that property again

**Comment by bodymovin** [comment]
By the way, to rename it you need to click on it and hit Enter in your keyboard.

**Comment by okapii** [comment]
Very sorry, I was not aware that enter is used for renaming. I renamed it and the export works as expected.
