### ISSUE TITLE
CS Support

### ISSUE THREAD

**Issue by Timoti** [bodymovin/bodymovin#504]
Tremendously enthused about the potential for bodymovin but reluctant to pay an Adobe tax for the rest or my natural life (I'd rather contribute to bodymovin frankly), and all of my other adobe needs are well-met in legacy CS apps.  And the _relatively_ simple subset of AE that can be exported via BM suggests that for web folks, CC versions don't actually offer anything that CS doesn't

SO my questions, and I do have them… Am I right that bodymovin doesn't support CS versions of AE? Is there anything fundamentally holding back such support?

**Comment by bodymovin** [comment]
The reason why bodymovin only works with CC is because of the CEP panel support.
Older versions of AE only work with native panels.

**Comment by Timoti** [comment]
Ah - as I suspected - Thanks!
