### ISSUE TITLE
exported son file not working with Xcode project

### ISSUE THREAD

**Issue by tarekjam** [bodymovin/bodymovin#505]
Hi 👋,
I have a problem after exporting form after effect with bodymovin that it is not working with my project.
but when I try the demo son file it is working fine.
any suggestions 
Thanks in advance

**Comment by bodymovin** [comment]
Hi, can you share a link where I can see what is going on?

**Comment by tarekjam** [comment]
Hi Hernan,
Actually I just tried to export simple shape with json and it worked fine
but when I try to do this with with large compose with couple images "png" it seems not responding in Xcode .
what could be the issue, Thanks in advance

**Comment by bodymovin** [comment]
hi, you should share it directly with the lottie team. They'll have a better understanding of what is going on.
https://github.com/airbnb/lottie-ios

**Comment by tarekjam** [comment]
Thanks a lot for your fast respond
