### ISSUE TITLE
How to reverse an animation?

### ISSUE THREAD

**Issue by dotcomartist** [bodymovin/bodymovin#506]
I've been attempting to reverse a fairly complex animation so that multiple shapes morph into other shapes, then morphs back into the original shapes. I tried creating an composition and then reversing the timeline on that composition, but bodymovin doesn't seem to like that. It looks fine in After Effect though. Anyone know of an easy solution to this?

Example: http://meredithworks.com/allrecipes/ar-logo/morph/

**Comment by bodymovin** [comment]
can you use time remapping for this?

**Comment by dotcomartist** [comment]
I'll give that a shot!


Thanks!


Jeff Cummings
Senior Designer
Meredith Digital
p:      206.436.7424  m: 206.713.5870
w:      meredith.com<http://meredith.com>  e: jeff-cummings@meredith.com<mailto:jeff-cummings@allrecipes.com>
[http://dish.allrecipes.com/wp-content/uploads/2017/02/MeredithDigital_2016_logo-96x22.png]
[http://dish.allrecipes.com/wp-content/uploads/2017/02/facebook-icon.png]<https://www.facebook.com/meredithcorporation/>  [http://dish.allrecipes.com/wp-content/uploads/2017/02/twitter-icon.png] <https://twitter.com/MeredithCorp>   [http://dish.allrecipes.com/wp-content/uploads/2017/02/linkedin-icon.png] <https://www.linkedin.com/company/meredith>

________________________________

**Comment by dotcomartist** [comment]
I tried using time remapping and I just get a white screen where the remapped layers appear.


Jeff Cummings
Senior Designer
Meredith Digital
p:      206.436.7424  m: 206.713.5870
w:      meredith.com<http://meredith.com>  e: jeff-cummings@meredith.com<mailto:jeff-cummings@allrecipes.com>
[http://dish.allrecipes.com/wp-content/uploads/2017/02/MeredithDigital_2016_logo-96x22.png]
[http://dish.allrecipes.com/wp-content/uploads/2017/02/facebook-icon.png]<https://www.facebook.com/meredithcorporation/>  [http://dish.allrecipes.com/wp-content/uploads/2017/02/twitter-icon.png] <https://twitter.com/MeredithCorp>   [http://dish.allrecipes.com/wp-content/uploads/2017/02/linkedin-icon.png] <https://www.linkedin.com/company/meredith>

________________________________

**Comment by bodymovin** [comment]
can you share a link with the issue?
