### ISSUE TITLE
Some animations work locally but not on web

### ISSUE THREAD

**Issue by derfmilar** [bodymovin/bodymovin#507]
Title is self explanatory. I've added animations on my local environment that work perfectly, but when I push those out to a live URL, some animations are not playing at all.

At this URL - http://guidedtours.devmoore.com/
> Care Team > Section 3 / Section 4
> Patient > Section 5

Thank you very much for any help you can give.

**Comment by bodymovin** [comment]
http://guidedtours.devmoore.com/bodymovin/p01s03/data.json
http://guidedtours.devmoore.com/bodymovin/p01s04/01/data.json
seem to be missing

**Comment by derfmilar** [comment]
Strange! The file was definitely present. It looks like the file didn't have the proper "read" permissions, for whatever reason. After adjusting that it seems to work fine.

Thanks!
