### ISSUE TITLE
Running into Error: <g> attribute transform: Expected number, "matrix(NaN,NaN,NaN,NaN

### ISSUE THREAD

**Issue by rileybracken** [bodymovin/bodymovin#508]
According to this #324 it is because of a version mismatch. We have it exported from v4.7.0 and our package version is 4.7.0.

What could we be doing wrong?

**Comment by bodymovin** [comment]
can you share a link where it is failing?

**Comment by rileybracken** [comment]
Sure, here you go:
https://uplevelsecurity-fewmoswmvk.now.sh

**Comment by bodymovin** [comment]
It doesn't seem to be a version issue.
Can you share the .aep so I can check it out?

**Comment by rileybracken** [comment]
Yeah here you go:
http://belly.is/38A4BB/4f2tyaPb

**Comment by bodymovin** [comment]
Hi, the expression on the Scale property of the NULL CONTROL is not supported by the plugin.
I need to look further into it to check why it doesn't work.

**Comment by steveooo9** [comment]
@bodymovin Yeah. It's also not working here.. Exactly the same issue..

**Comment by bodymovin** [comment]
Will be fixed on next release.
