### ISSUE TITLE
variable in shape layer expression with Math.pow Math.sqrt

### ISSUE THREAD

**Issue by DaanDirk** [bodymovin/bodymovin#509]
Hi,
Just found bodymovin can't do a Math.pow() or Math.sqrt() with a variable inside a shape layer.
e.g. on a rectangle size:
> w = thisLayer("Contents")("Rectangle 1")("Contents")("Rectangle Path 1")("Size")[0];
> h = Math.pow(w,2);
> [w,h]
> 

But replace it with a value and it is fine.
> w = 100;
> h = Math.pow(w,2);
> [w,h]
> 

On the transform properties of the layer it does work.
Is that intentional?

**Comment by bodymovin** [comment]
Fixed, I'll upload it on the next release.

**Comment by DaanDirk** [comment]
Thanks!
