### ISSUE TITLE
can't refresh

### ISSUE THREAD

**Issue by loopHere** [bodymovin/bodymovin#51]
report "Unable to execute script at line 314. p is undefined"

I reinstalled twice, but still not working , don't where was wrong

**Comment by bodymovin** [comment]
@loopHere does that error show when you hit Render?

**Comment by loopHere** [comment]
when i hit the Refresh~

**Comment by bodymovin** [comment]
@loopHere what OS and AE version are you using?

**Comment by loopHere** [comment]
mac OSX 10.10.5 & AE 13.5

**Comment by bodymovin** [comment]
@loopHere is it with a particular project or with any?
can you send me the .ae?

**Comment by loopHere** [comment]
Just a simple test .aep for Bodymovin

[test1.aep.zip](https://github.com/bodymovin/bodymovin/files/79850/test1.aep.zip)

**Comment by bodymovin** [comment]
@loopHere It's really strange. Even more because no file I can think of from the extension has more than 300 lines.
Can you send me a screenshot with the error?

**Comment by loopHere** [comment]
Here it is ~ Does it  working on your AE?
![screen shot 2016-01-07 at 14 42 35](https://cloud.githubusercontent.com/assets/14327009/12164009/0718f95c-b54d-11e5-8827-b9d583fc573a.png)
