### ISSUE TITLE
Black Keylines around Exported assets

### ISSUE THREAD

**Issue by tokenGinger** [bodymovin/bodymovin#511]
Hey, Loving the product!

Ive come into an issue regarding the exported image assets. Every one has a thin black keyline stroke around that isnt visible before the export. All my assets come from an AI file and the comp is built to the size my AI files are meant for, so not stretching or pixelation is done my end. Or so i think...

Heres an image of the original comp versus the exported preview.
![screenshot 2017-06-28 12 20 41](https://user-images.githubusercontent.com/29752547/27634709-4713445c-5bfc-11e7-87fa-8fdc68922b34.png)

**Comment by bodymovin** [comment]
Hi, AE exports pngs with that black stroke around them. I'm working on a solution but it's not ready yet.
If you need them as pngs, you should replace the images folder with the assets exported from AI directly.
Nevertheless, if your assets are .ai layers, you should convert them to shapes in AE so they get exported as vectors and not raster images. Right click on the layer and select Create Shapes from Vector Layers

**Comment by tokenGinger** [comment]
Cool. thanks
Not sure why i missed that. 
Thanks again.
