### ISSUE TITLE
Template renders, but does not play back with any renderer

### ISSUE THREAD

**Issue by sbalko** [bodymovin/bodymovin#512]
I tried to get a basic template (https://motionarray.com/after-effects-templates/color-wall) to work, but cannot get it to play back using any of the renderers. Any idea why that is?

**Comment by bodymovin** [comment]
Hi, those template are usually based on rasterized effects which are not supported by the plugin with the exception of only a few.
Having said that, if you want to share the .aep I can take a look at this specific case.
