### ISSUE TITLE
Inverting colors and alpha background questions

### ISSUE THREAD

**Issue by inessashillo** [bodymovin/bodymovin#514]
Hi, it's me again! :) I tried another animation, and again it's super simple, but I've got problems.

The animation is a cat head which looks up when menu above is open. The example is in demo
[cat-menu_demo.mp4.zip](https://github.com/bodymovin/bodymovin/files/1111745/cat-menu_demo.mp4.zip)

So I need two animations one where the head looks up, and other — looks down. And I did it fine, and the player shows me all correct https://tppr.me/FoR9F, but when I open in it html demo the colors are inverted https://tppr.me/YfYGg

So, the first question, why so? How can I fix it.

And the second one, how can I make my background transparent? 

At the archive are .aep file (cat is in pre-comp) and exported files with demos.
[cat-menu-issues.zip](https://github.com/bodymovin/bodymovin/files/1111761/cat-menu-issues.zip)

Thank you!

**Comment by bodymovin** [comment]
Hi, the demo.html has hardcoded a white background. But if you implement it on your own context, you'll see it is actually transparent and will take whatever you put behind as the background.

**Comment by inessashillo** [comment]
Hi! We tried to put it on owr context but here what is happen http://joxi.ru/nAyQjXKtXgPZeA we took the json file from the zip above, what we did wrong?

**Comment by bodymovin** [comment]
can you share a working link?

**Comment by inessashillo** [comment]
bucha.html.nimaxdev.ru here, hover on green rectangle

**Comment by bodymovin** [comment]
your svg has a background color:
.cat-menu svg {
    background: #00f;
    vertical-align: top;
}
from here
http://bucha.html.nimaxdev.ru/template_styles.css

**Comment by inessashillo** [comment]
Well, here is the thing: we are aiming to make cat's head black on transparent background http://joxi.ru/L21lYjot6RK0Om, but when export from bodymovin we get the opposite http://joxi.ru/4AkQxOqtMozXPm and so we put blue backgrond under the cat's layer so you can see.

**Comment by inessashillo** [comment]
We still don't get why are we having the inverted colors on the cat's head and the transparent background, while on bodymovin player it looks fine.

You told us to put it in our context and it would be fine then, so we did, and still it's like it showed on html demo, not in player — inverted.

And thank you for your responses, btw, we really want to figure out how to work with your plugin, it's a lot of cool stuff ahead!

**Comment by bodymovin** [comment]
Ok, now I understand what is going on.
On your composition "cat", on the layer "head Outlines" > "Contents" > "Group 1"
you need to delete layers "Path 2" and "Merge Paths 1"
Sorry that I missed the issue.
Bodymovin doesn't support Merge Paths and those two layers are not necessary.

**Comment by inessashillo** [comment]
Yeah, thank you again! it works!
