### ISSUE TITLE
Export not working correctly with some AE Effects 😭

### ISSUE THREAD

**Issue by cedricbals** [bodymovin/bodymovin#515]
Hey ,

I created a loading animation today, thinking that I could use bodymovin to export it to json and use it in our cross platform applications. 
Guess it got a little too complex  🏃 💨 😅

I ran into problems converting the CC scatterize and glow effect.
While reading through the open and closed issues, I realized that the effect might just not been included to the plugin.

I still kinda hope that you have a chance to look into my problem and might give me an advice or a workaround to get this bad ass up and running ^^ 

Thanks!

![screenshot 2017-06-30 00 34 43](https://user-images.githubusercontent.com/10400753/27713442-0a577b6a-5d2c-11e7-828a-0af9f283809a.png)
<img width="963" alt="screenshot 2017-06-30 00 34 54" src="https://user-images.githubusercontent.com/10400753/27713441-0a54f098-5d2c-11e7-9e28-67f8a7b167af.png">

[appointer_co_loading.zip](https://github.com/bodymovin/bodymovin/files/1113683/appointer_co_loading.zip)

**Comment by amleon2007** [comment]
I'm having a somewhat similar similar issue. The compositions I have in ae are not rendering correctly in the bodymovin preview mode, nor in the json files. I also had to use an older version of the bodymovin extension as the latest version would not even load in the latest after effects.

Does anyone have a similar issue to mine or cedricbals? Any fixes or guidance anyone can provide?

Thank you ~

**Comment by therealsalih** [comment]
@cedricbals neither CC scaterize nor glow is supported by bodymovin. Check the wiki for supported features and effects
https://github.com/bodymovin/bodymovin/wiki/Effects
