### ISSUE TITLE
Unable to execute script at line 21. null is not an object 

### ISSUE THREAD

**Issue by IAIAE** [bodymovin/bodymovin#517]
**Tell us about your environment**

* **After Effects Version: CC 2017    version: 14.0.0.207**
* **bodymovin    version: 4.8.0**

**cannot export. is there feature in this AE that bodymovin donnot support?**

the ae file is here.

[center.aep.zip](https://github.com/bodymovin/bodymovin/files/1114704/center.aep.zip)

**Comment by bodymovin** [comment]
try saving the project before exporting.

**Comment by IAIAE** [comment]
it works!! thanks very much!!!
