### ISSUE TITLE
Text Not showing

### ISSUE THREAD

**Issue by jeetusurajwani** [bodymovin/bodymovin#518]
Hello,

I have created animation in after effect. Color of layers are appearing different then animation we have in after effect when we are using exported json in android native app. And text is also not appearing there. I am enclosing after effect project too. Please help me with this.
[onthego.zip](https://github.com/bodymovin/bodymovin/files/1116206/onthego.zip)

**Comment by bodymovin** [comment]
Hi, text is not yet supported in Lottie android but it's coming.
You should contact them directly for this issue.
https://github.com/airbnb/lottie-android
