### ISSUE TITLE
canvas not render and no error reported

### ISSUE THREAD

**Issue by IAIAE** [bodymovin/bodymovin#519]
**AE: 2017 cc version: 14.0**
**bodymovin: 4.8.0**

**i export the data.json file. and click the demo.html. it's ok to render with svg renderer.**

** but when i change the renderer to 'canvas'. the canvas element render nothing. and there isn't any console.error reported.  i check the `anim.currentFrame`, it changes normally.  **

**the data.json is here:**

[data.json.zip](https://github.com/bodymovin/bodymovin/files/1117830/data.json.zip)

**hope your help~~~   :)**

**Comment by bodymovin** [comment]
Hi, the fill effect is only supported with the svg renderer
