### ISSUE TITLE
Error when loading an animation

### ISSUE THREAD

**Issue by Tolmark12** [bodymovin/bodymovin#52]
` Cannot read property 's' of undefined`

When I use chrome to try to see where that's being thrown, I think it might be getting thrown in the matrixManagerFunction... but it's hard to tell because the lib is compressed. 

Any idea where to start poking around?

Here's the animation src : http://aristotle.gopagoda.io/episodes/episode2/animations/firewall_burn_bad_upper.json

**Comment by bodymovin** [comment]
@Tolmark12 I see the animation fine. Are you using the latest player?
Can you post a link to see the error?

**Comment by Tolmark12** [comment]
Just updated to be sure, but still getting that error. Let me push it up to a live url..

**Comment by Tolmark12** [comment]
Nevermind, it was an issue of not having the latest lib, whew! I updated the lib via bower just now, but forgot that gulp didn't automatically update bower libs. Thanks for the ultra quick response on a Friday night.

**Comment by bodymovin** [comment]
@Tolmark12 no problem!
