### ISSUE TITLE
GZIP

### ISSUE THREAD

**Issue by simonassili** [bodymovin/bodymovin#520]
How do you decompress GZIP'ed player?
Couldn't find a way to use gzipped player version, I can't manage to include it.
Any help?
would be cool if this would be on bodymovin github instructions, since it's very hard to google it :(

**Comment by bodymovin** [comment]
Hi, the gzipped player needs the content-encoding header from the server.
If you're using it locally, simply use the uncompressed version.
Where are you trying it?
