### ISSUE TITLE
Can't subtract paths/masks (iOS Lottie)

### ISSUE THREAD

**Issue by martyprague** [bodymovin/bodymovin#521]
Hi, I can't find a way how to cut out two animated holes in a shape. I have tried masks and paths with different settings but without success. It works perfectly on windows and android but not on iOS.

AE project: [Bodymovin_test.zip](https://github.com/bodymovin/bodymovin/files/1120629/Bodymovin_test.zip)

Thanks for help

**Comment by bodymovin** [comment]
Hi, I'd suggest that you post this issue directly at the Lottie iOS repo
https://github.com/airbnb/lottie-ios
