### ISSUE TITLE
Gradient fill not working on iOS

### ISSUE THREAD

**Issue by Hiroxox** [bodymovin/bodymovin#522]
Hi, I'm having an issue getting shape with gradient fills not working on iOS , but it showing fine on Android or html.

![image](https://user-images.githubusercontent.com/29878573/27813529-18d91678-60a9-11e7-8a55-de83e24cf19f.png)

is the gradient fill not supported on iOS？

here is my file>>>
[Gradient test.zip](https://github.com/bodymovin/bodymovin/files/1120913/Gradient.test.zip)

**Comment by bodymovin** [comment]
Hi, as far as I know, gradients are not yet supported in the iOS player.  
https://github.com/airbnb/lottie-ios
