### ISSUE TITLE
Problem with exporting hand with IK from DUIK

### ISSUE THREAD

**Issue by alexdanila2017** [bodymovin/bodymovin#523]
I have created a hand in AI from 3 pieces. Arm, forearm and hand. I applied DUIK IK on it and animated some keyframes. Exported a demo with the Bodymovin and the export just looks like my assets stacked on one another.

Google Chrome 
After Effects Version: 2017.2 Release  14.2.0.198

**What did you do? Please explain the steps you took before you encountered the problem.**
New Composition, Added 3 vector assets. arm, forearm, hand. Autorigged the hand using DUIK feature autorig for hands.  Animated position keyframe on new layer created by DUIK. exported with as demo with Bodymovin

**What did you expect to happen?**
I was supposed to get the animation in js format, but i only get in the browser the assets i used all stacked up.

**Please provide a download link to the After Effects file that demonstrates the problem.**

[hand anim DUIK test.zip](https://github.com/bodymovin/bodymovin/files/1122479/hand.anim.DUIK.test.zip)

[Bodymovin export.zip](https://github.com/bodymovin/bodymovin/files/1122496/Bodymovin.export.zip)

**Comment by bodymovin** [comment]
Hi, I'll check it when I get home, but have you selected to include guided layers on export?
I think Duik uses guided layers.

**Comment by alexdanila2017** [comment]
That mostly solved the problem! Thanks so much for the fast reply!

**Comment by alexdanila2017** [comment]
Back again. 
Managed to export the animation. I made the composition using an .ai file and all my layers are vector. 
The shapes in AE look sharp. 
After the export they look raster and each asset has a dark pixelated border, plus the animation seems to be framing in the export.

I read around and found that i have to convert the vector layers to AE shapes. I did that. The result in the exports are block of colors as large as the composition size.

I have attached the demo for both exports.

[export with ai files.zip](https://github.com/bodymovin/bodymovin/files/1127394/export.with.ai.files.zip)

[export with converted to shapes.zip](https://github.com/bodymovin/bodymovin/files/1127390/export.with.converted.to.shapes.zip)
![export output](https://user-images.githubusercontent.com/29895932/27905115-a093d3e2-6247-11e7-8449-61704b10fc96.png)

What do you advise?

**Comment by bodymovin** [comment]
Hi, unfortunately when converting ai layers to shapes, AE adds some unnecessary extra path with a merge path on each group and bodymovin doesn't support merge paths.
So you need to remove them manually, and everything will work fine.
Expand each layer, open it's content and check every group.
Let me know if you need further help.

**Comment by Alfinamn** [comment]
Hi, I also have the same problem. I made an animation using duik. when I export to json, the whole body does not run just the legs. what's the solution? Hope you can help. thank you
[TEST KARAKTER.zip](https://github.com/airbnb/lottie-web/files/2767065/TEST.KARAKTER.zip)
