### ISSUE TITLE
Error with repeater

### ISSUE THREAD

**Issue by redpandatronicsuk** [bodymovin/bodymovin#524]
I was following a tutorial to make AE fireworks with shapes only (http://www.premiumbeat.com/blog/after-effects-video-tutorial-fireworks/).

When exporting the animation with bodymovin it looks wrong. With some trial and error I found that the error is because of the repeater. When disabling the repeater, the animation looks the same in AE and the exported bodymovin file. The repeater is needed though for this animation to work.

In the attached aep file you can see the error and that disabling the repeaters gets rid of the error, but of course, also the repetition.

[RepeaterError.aep.zip](https://github.com/bodymovin/bodymovin/files/1122745/RepeaterError.aep.zip)

**Comment by bodymovin** [comment]
Repeaters support is almost ready.
I'll probably upload a version this weekend.

**Comment by redpandatronicsuk** [comment]
It is working now with version 4.9.0 🎉
