### ISSUE TITLE
Missing Elements on any Android Browser & React Native via Lottie

### ISSUE THREAD

**Issue by austinkettner** [bodymovin/bodymovin#526]
### Environment where problem occurs
React and Android/Edge Browser

* **Browser and Browser Version:**
Android (Any Browser). React Native via Lottie (On Device Only)
* **After Effects Version:**
After Effect CC 2015

**What did you do? Please explain the steps you took before you encountered the problem.**
Exported fully working Bodymovin Animations as shown here: https://bodymovin-nchan0154.c9users.io/ (Specifically 4th row, center, is the 'Systems' Animations)

**What did you expect to happen?**
These animations to work as they do on desktop, within Android and React Native.

**What actually happened? Please include as much _relevant_ detail as possible.**
On Android Devices in Browser and on all React Native tests (via Lottie), parts are missing despite using all supported properties. You can see the 'Systems' Animation in my above link, but upon viewing this in a Android Browser or in React Native via Lottie, the Van is missing. This actually occurs throughout a few of the animations with varying objects, but I am specifying Systems as the issue here is probably the same throughout all.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/u9x7d608yl7mg4m/systems.aep?dl=0

**Comment by gpeal** [comment]
@austinkettner Can you file these issues on lottie-android and lottie-react-native?

**Comment by austinkettner** [comment]
@gpeal I can, but I see this within non-lottie scenarios as well, such as any Android Browser (no Lottie, just React), so I believe the issue isn't directly related to Lottie.

**Comment by bodymovin** [comment]
@austinkettner I just tried that link on Chrome in an Android tablet, and animations looked fine.
Bad performance, but still fine.
On what device are you trying it?

**Comment by gpeal** [comment]
Seems life on Lottie Android
![systems](https://user-images.githubusercontent.com/1307745/27876621-a1ed63f6-616c-11e7-87b0-f9126b795735.gif)

**Comment by austinkettner** [comment]
We are experiencing issues on Galaxy Tab 4 10.1, and Nexus 5, specifically, both running latest Android (7.x). This is able to be reproduced on device and in Browserstack. As a note as well, everything is perfectly fine in Lottie player online too, no issues shown there.

With regards to performance, yea having all of them in a grid definitely bogs it down! Luckily we are only showing about 2 per page in the usage scenarios we have planned!

I am going to double back and get more detailed reproduction steps, as we experienced issues on a Google Pixel too. Let me know if you see or don't see issues in the above. It's been a long few days debugging these issues before we posted, so I just want to make sure I don't relay any 'non-working scenarios' that actually do work!

**Comment by gpeal** [comment]
@austinkettner we haven't been able to reproduce any of these. Can you post a video?

This is the json I exported of the systems animation.
[Systems.json.zip](https://github.com/bodymovin/bodymovin/files/1125656/Systems.json.zip)

**Comment by austinkettner** [comment]
Hey @gpeal and @bodymovin, here is the update I promised.

Seems the issue doesn't occur with the pure HTML Exports/etc. This is my mistake and I apologize for the incorrect introduction above. Instead we are running into issues with these in pure React.

Here is the React Site: https://clusio-website-nchan0154.c9users.io/ We can specifically focus on the homepage, 'For Systems', which has the following issues...

- Nexus 5x: No Van Appears via Chrome on Android
- Google Pixel: No Van Appears via Chrome on Android (Video: https://www.dropbox.com/s/gc3vgyr7v3sfkjl/systems-android-display-bug.mp4?dl=0

We notice differences where in an emulator these do appear fine for both of the above devices, but on-device they do not work, which makes this extremely hard to debug/trace. The React site has no modifications going on outside of React (15.6.1) > Bodymovin > Display on Page

**Comment by dwillmc** [comment]
[bug.mov.zip](https://github.com/bodymovin/bodymovin/files/1126836/bug.mov.zip)

Hey I'm part of the team with @austinkettner 
First part of video shows @gpeal 's export and second part shows @austinkettner's AEP export in CC 2015.

**Comment by gpeal** [comment]
@dwillmc Ah, your video is using React Native. Make sure you're using the latest version. I'm also going to be working on that repo a bit over the next week or so to so make sure to stay up to date.

@bodymovin I tried their site on my phone and the ambulance isn't visible for me either on my S8.

**Comment by bodymovin** [comment]
I'm trying it on a Nexus and it works fine. I'll try to get an S8. What OS version do you have?  
I guess it's related to using an alpha inverted mask. I really recommend that you precomp the ambulance and use a regular mask to achieve the same effect since you don't really need the alpha layer of the mask.
It's going to be much more performant and probably will solve the issue.

**Comment by austinkettner** [comment]
Thanks @gpeal and @bodymovin 

Going to test precomping the ambulance (+using a standard mask) and will report back!
