### ISSUE TITLE
Hi my AE file animation is not working when i convert in jshon. actually my dotes animation is working fine but when i connect these dots with line my hole animation is balnked 

### ISSUE THREAD

**Issue by rudra077** [bodymovin/bodymovin#528]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by rudra077** [comment]
[rudra1.aep.zip](https://github.com/bodymovin/bodymovin/files/1127729/rudra1.aep.zip)
Hi my AE file animation is not working when i convert in jshon. actually my dotes animation is working fine but when i connect these dots with line my hole animation is balnked

**Comment by rudra077** [comment]
i am using latest version of AE
i want to make a animation of connecting dotes when i give dotes to animation its working but when i used to beam effect to connecting these dotes with lines its not working.

**Comment by bodymovin** [comment]
Hi, the beam effect is not supported by the plugin, sorry :/
