### ISSUE TITLE
Effect bug

### ISSUE THREAD

**Issue by lgBatista** [bodymovin/bodymovin#529]
Hi there, 

I'm a front-end developer and see in bodymovin a great way to work animations through my codes. I've installed the plugin and created a simple animation to test the plugin. But I found a issue, look at the result on after effects:

![ae](https://user-images.githubusercontent.com/5192114/27919454-18d3bed0-6248-11e7-8d28-5402f1049bd6.gif)

See that I'he a simple elements with position and tint proprieties and a adjustment layer with 2 effects (that give this jelly effect). Now look at the HTML rendered 

![site](https://user-images.githubusercontent.com/5192114/27919550-5627f17a-6248-11e7-85fb-aec44de04466.gif)

The position and color are correct, but the effects applied on the adjustment layer are missing, making the jelly effect disappear. Pherhaps I dont configurated the script correctly or maybe this is a really bug.

It was tested using AE CC 2017 and Firefox 54.0.1

**Comment by bodymovin** [comment]
Hi, unfortunately not many effects are supported.
https://github.com/bodymovin/bodymovin/wiki/Effects
And Adjustment layers are not supported either.
sorry :/

**Comment by lgBatista** [comment]
oohh  I see, there's a plan to include theese ? Bodymovin is such amazing tool, that kind of tool that it's a game changing, you know? I know that SVG has limitations and the plugin was great already, but maybe adding more supported effects can put bodymovin on spotlight. 

You could consider make a page dedicate with detailed functions, events and all others details, github page are good but not great to see tha kind of informations. But its only my opinion ofcourse

Thanks man ... keep the good work
