### ISSUE TITLE
animation.destroy() clean up

### ISSUE THREAD

**Issue by Tolmark12** [bodymovin/bodymovin#53]
I've noticed running `animation.destroy()` leaves a lot behind in memory. For instance, consider the following:

|                               | Memory Used |
|------------------------------:|-------------|
| Before Animation is Loaded    | 66mb        |
| After Animation is Loaded     | 123mb       |
| After animation is Destroyed* | 96.5mb      |
_* I force garbage collection to make sure all items are cleaned up_

I took a heap snapshot (note that heap snapshots are a bit dense especially if you don't know what you're looking for). I think the largest thing I'm seeing in the heap snapshot is an `IImageElement()`, but I'm also seeing things like a very long `shapes` array.

Anywho, we're building a massive project with hundreds of animations, and the memory overhead is really adding up. I am totally available to help troubleshoot and work to fix it, but I'd need some help knowing where to start in the code. 

Thanks, this project rocks!

**Comment by bodymovin** [comment]
@Tolmark12 Thanks, I'll take a look at it. So you're using the svg renderer and you have png images animating?

**Comment by Tolmark12** [comment]
Yeah, some of the time. The vector assets were sometimes so complex, that replacing them with pngs was needed to speed things up.

**Comment by Tolmark12** [comment]
@bodymovin I just downloaded the new lib and ran a test, and as far as I can tell, it looks like items remain in RAM even after destroying an animation. See the following video for clarity : https://www.youtube.com/watch?v=5oUGoqLMczY

**Comment by Tolmark12** [comment]
Any data, or DOM elements that have a a variable with it's value assigned to that item (a pointer) won't be removed from RAM during garbage collection. Event handlers can be especially troublesome. ie: if you set an event handler on some object and even remove all pointers, but don't remove the event listener, the object won't be garbage collected

(Just tell me to shut up if you already know all this :-)

**Comment by bodymovin** [comment]
@Tolmark12 yes, every reference to dom elements should be removed when calling destroy. I'll keep looking into it.

**Comment by Tolmark12** [comment]
I think all the dom elements may be cleared, but maybe there is data elements still in memory?

**Comment by 1pocketaces1** [comment]
Hi I am still having this issue even though it apparently got fixed?

**Comment by 1pocketaces1** [comment]
So after more research and trials I found out that it is necessary to call the animation.destroy() inside the angular component onDestroy() for every animation used in the component. Doing this will work in cleaning up the heap, but if this is not done, then the memory is lost. Thanks for responding!
