### ISSUE TITLE
Support of Wiggle Path

### ISSUE THREAD

**Issue by AlbanCrepel** [bodymovin/bodymovin#530]
Hi,
First of all, thank you for this add-on, it's awesome !
Are you planning to support Wiggle Path in the future ? It would be great to be able to do complex animations with it ! (I tested bodymovin with an animation I've just made, and the render without wiggle path is terrible...)

**Comment by bodymovin** [comment]
Hi, I've done some attempts at supporting it but it's not ready yet.
I'll let you know if there's any progress on it.

**Comment by AlbanCrepel** [comment]
@bodymovin Alright, thank you for your answer !

**Comment by remorses** [comment]
Any update?

**Comment by bodymovin** [comment]
not yet, sorry

**Comment by bodymovin** [comment]
Not yet, wiggle path is not trivial at to implement all unfortunately.

**Comment by derbalint** [comment]
Hello Hernan!
Is there any update regarding the wiggle paths feature?
Would be awesome (:

**Comment by theo-grape** [comment]
> Not yet, wiggle path is not trivial at to implement all unfortunately.

Hello, :-) Do you have any suggestions for putting function instead of wiggle path?
