### ISSUE TITLE
I'm geting interesting results with zigzag, fonts and mask paths

### ISSUE THREAD

**Issue by semihsmg** [bodymovin/bodymovin#531]
First of all, thank you for this awesome project. I'm using bodymovin for android project with lottie. I've couple of issues that I couldn't solve...

Windows 8.1 Pro
Firefox 54.0.1
AE 2017.1 - Version 14.1.0.57

**What did you do? Please explain the steps you took before you encountered the problem.**
- Applied zigzag animation to sphere shape and rect shape and animated them
- Used mask path with Stroke effect for text
- Character offset with opacity for texts

**What did you expect to happen?**
- To be able to render with zigzag, character offset and mask path property

**What actually happened? Please include as much _relevant_ detail as possible.**
- After rendering with bodymovin; zigzags disappeared, fonts and mask path animations become interesting grass lookin shapes.

First one rendered from gifGun and second with bodymovin

**gifGun Render**
![comp 3_1](https://user-images.githubusercontent.com/23503571/27985230-27e13b92-63f0-11e7-965a-f261760c0f62.gif)

**bodymovin Render**
![comp 4](https://user-images.githubusercontent.com/23503571/27985500-68462568-63f4-11e7-8a6e-ad22be133936.gif)

**Comment by bodymovin** [comment]
Hi, zigzag is not supported yet.
The font issue seems related to using an older player. Can you confirm how it looks with the latest one?

**Comment by semihsmg** [comment]
I'm on it!

**Comment by bodymovin** [comment]
Can you share the .aep and .json files?

**Comment by semihsmg** [comment]
With the updated player I get this result.
![comp 4_1](https://user-images.githubusercontent.com/23503571/27985654-b12c3562-63f7-11e7-8b90-5c96b68cd83c.gif)


[Android_Anim_v4.zip](https://github.com/bodymovin/bodymovin/files/1132980/Android_Anim_v4.zip)

**Comment by Cavemancrayon** [comment]
Had the same issue with Zig Zag, I ended up just remaking the motion effect with raw paths.
