### ISSUE TITLE
RequestAnimationFrame not defined on Chrome 22- 23

### ISSUE THREAD

**Issue by lunaleaps** [bodymovin/bodymovin#532]
Hello! Thanks for this great library!

Ran into an issue where the `AnimationManager` threw an exception, this particular [line](https://github.com/bodymovin/bodymovin/blob/751aafcfeb637944003562e1e9f92d799317d5c4/player/js/animation/AnimationManager.js#L184).

Looks like `requestAnimationFrame` is not supported for Chrome versions 22-23 according to [caniuse](http://caniuse.com/#feat=requestanimationframe). Those versions do support a webkit prefixed version, `webkitRequestAnimationFrame`.

 Is it possible to get support for Chrome 22-23?

**Comment by bodymovin** [comment]
Hi, can you include a pollyfill yourself before loading the library?
