### ISSUE TITLE
Masking issue with luminance filter

### ISSUE THREAD

**Issue by n0wak** [bodymovin/bodymovin#533]
We have an animation exported by an animator ( I do not know AE ) that works fine across all browsers except IE 11 on Windows 8 (for some reason it's fine on Windows 10). Our logo has a solid blue background over white text that animates in as a mask on that text.

In IE 11 the text wouldn't show at all. Digging into the DOM I tracked the issue down to a filter using fematrix '0 0 0 1 0  0 0 0 1 0  0 0 0 1 0  0 0 0 0 1' set here https://github.com/bodymovin/bodymovin/blob/master/build/player/bodymovin.js#L4524

I'm not fully versed on feColorMatrix transformations but changing the last 0 to a 1 (supposedly alpha) rendered it. See the change:

![before](https://user-images.githubusercontent.com/754821/28029006-7bf4bd12-656c-11e7-9edd-1966b8244d0f.png)
![after](https://user-images.githubusercontent.com/754821/28029008-7d41f6a8-656c-11e7-9651-52e4d0f077a6.png)

I'm not sure if this has other implications but it fixed the issue without any adverse side effects. Is this a bug or is there an error in how the AE animation was created?

(I did notice I could replicate the masking issue if I switched from svg renderer to canvas)

**Comment by bodymovin** [comment]
I'm setting the alpha channel to 1 so it doesn't depend on the input alpha channel. Replacing the last 0 for a 1 would always set the alpha chanel to a higher value than 1. It shouldn't affect but I'm not sure how browsers will handle this.
Nevertheless do you need this to be a track matte mask? can you use a regular mask instead?
If it's the same, it would be much more performant.
