### ISSUE TITLE
Show wrong, how do i use it correctly?

### ISSUE THREAD

**Issue by wyfang** [bodymovin/bodymovin#534]
Before, I used png pictures to do animation, but not fluent. So, this time to use AI to draw and then use AE to make animation, export, they are all wrong, where is the way I made it wrong?

Youtebe：https://youtu.be/NMDJjhh2UkM

This is AEP&json:[aepandjson.zip](https://github.com/airbnb/lottie-android/files/1137964/aepandjson.zip)

**Comment by bodymovin** [comment]
Hi, bodymovin doesn't support Merge Paths.
I've tried to fix your animation but all layers are in chinese and I can't figure out how.
When converting AI layers to shapes, sometimes AE adds an unnecessary square path and a merge path property.
If you remove them it's probably going to work.
Let me know if I can help you further.

**Comment by wyfang** [comment]
@bodymovin WOW, So, I need delete Merge Paths? But I do not know how to distinguish what is the merge path.
