### ISSUE TITLE
Not supporting layer style and external plugin for text animation

### ISSUE THREAD

**Issue by pratheepchelladurai** [bodymovin/bodymovin#535]
The animation I did includes some layer animations and text animation. I have included text animation from external plugin which includes some math script. The rendered version when viewed in browser got stopped unexpectedly when the text animation starts. Anyways to fix it?

This is the math script generated by the external plugin for the Expression Selector:

delay = .1;
myDelay = delaytextIndex;
t = (time - inPoint) - myDelay;
if(t >= 0){
freq = 3;
amplitude = 250;
decay = 8.0;
s = amplitudeMath.cos(freqt2Math.PI)/Math.exp(decayt);
[s,s];
}else{
value
}

I have attached the json file also.

[Text animation bug.zip](https://github.com/bodymovin/bodymovin/files/1138652/Text.animation.bug.zip)

**Comment by bodymovin** [comment]
encrypted expressions are not supported.
