### ISSUE TITLE
Can't select a Comp to Export

### ISSUE THREAD

**Issue by fcatania** [bodymovin/bodymovin#536]
Hi,
I'm using Windows 10, Adobe After Effects CC 2015.
I created a simple composition, 2 seconds long, containing a Text Layer and two Shape Layers former Adobe Illustrator files.
As I read on the Wiki, both shapes and texts are supported.
I successfully installed the extension following your steps.
When I go to Window > Extensions > Bodymovin, the window show successfully but I can't select my composition to export. (see attached image)

Please help me, I don't know what I'm doing wrong.
![bodymovin-error](https://user-images.githubusercontent.com/19718601/28099330-3649911c-6692-11e7-900f-3b34ec9fb64c.JPG)

**Comment by bodymovin** [comment]
Did you try clicking on the refresh arrows?

**Comment by fcatania** [comment]
Yeah, I tried multiple times.

**Comment by bodymovin** [comment]
What steps did you use to install it?

**Comment by fcatania** [comment]
I downloaded it from here: http://aescripts.com/bodymovin/
I tried reinstalling it but I couldn't uninstall it so I think I didn't actually reinstall it.

**Comment by bodymovin** [comment]
how did you install it the first time?

**Comment by fcatania** [comment]
I don't remember, installed it some weeks ago.
If it isn't too much trouble, can I send you my .aep and you export a JSon file for me? It's only 2 seconds long and I just need it for one animation.

**Comment by bodymovin** [comment]
sure, but I won't be home to export it until tomorrow
I'd suggest that you try this zxpinstaller
http://aescripts.com/learn/zxp-installer/
it will help you uninstall the previous version

**Comment by fcatania** [comment]
Ok, I'll try that. Thanks for your help, if I can't make it work I will comment again tomorrow if that's okay to you.

**Comment by bodymovin** [comment]
sure, let me know how it goes

**Comment by fcatania** [comment]
Well, I can't make it work, but I'm certain it's a problem with my After Effects or my Windows and I don't have the time right now to reinstall everything, so I'll wait until tomorrow. Thanks a lot for everything and sorry for bothering.

**Comment by fcatania** [comment]
Hi Hernan, I don't mean to bother you, but I wanted to know if now you can export this short animation for me. Thanks.

**Comment by bodymovin** [comment]
Hi, can you share the animation? If you're attaching it to an email response, it doesn't work with github.

**Comment by fcatania** [comment]
Thanks in advance
[spicy-animation-prject.zip](https://github.com/bodymovin/bodymovin/files/1145810/spicy-animation-prject.zip)

**Comment by ChristineSG** [comment]
Hi I am also facing the same issue while testing the export of an aftereffects animation using bodymovin v5.5.7. Incidentally i also installed the bodymovin extension for telegram stickers, which could work perfectly and detect the comp, but not original extension. Not quite sure why? 
![Screenshot 2019-08-04 at 5 14 28 PM](https://user-images.githubusercontent.com/7472779/62421862-7ba4c600-b6db-11e9-9227-55f64a0f56e4.png)

**Comment by jimiswells** [comment]
Hello, 
I'm also having this issue, I've unistalled and reinstalled the .zxp, and still no luck......

Can anyone help?

**Comment by ChristineSG** [comment]
You can try uninstalling and installing AfterEffects - That's how I could get it to work: [https://github.com/airbnb/lottie-web/issues/1748](url)

**Comment by jjcontreras89** [comment]
Same issue here :(

**Comment by bodymovin** [comment]
@jjcontreras89 can you share some more info?

**Comment by thanhnha121** [comment]
If your comp that you wanted to export is the first of the list, I think this's a bug of Bodymovin extension. I did these steps and my problem solved temporarily (not the best solution). 
I created a new composition named AAA, so AE put this one (AAA) at the top of the list. 
Then I tried to refresh Bodymovin list (AAA was at the top of Bodymovin list too, and my comp went down to 2nd).
Select the comp that you wanted to export and it will work!

**Comment by joepuck** [comment]
I had the issue of Bodymovin not seeing my comps.  'thanhnha121' gave me the idea to pull my comp out of the pre-comp folder in the project window it was sitting in.  This solved my problem.  Bodymovin was then able to 'see' the comp for me to choose it to render
![project](https://user-images.githubusercontent.com/14179738/167219213-f94ef6bd-d77c-4e78-a7f4-0ec3e8eed171.JPG)
.
