### ISSUE TITLE
After effects Expressions not rendering properly.

### ISSUE THREAD

**Issue by Onlypar2** [bodymovin/bodymovin#538]
I have used Wiggle expression to make random movements in my simple animation. It looked fine in after effects, but when i exported it, the expression got aggressive and the expression "wiggle(1,5)" in after effects is acting something like "wiggle(50,100)" after it is rendered in bodymovin. Please help me on how to use expressions and get accurate renders.

All the shapes I used are built inside after effects only. nothing is from outside.

**Comment by bodymovin** [comment]
wiggle is not supported unfortunately, it works as a placeholder so the animation doesn't break.
It's difficult to simulate wiggle and it would never work exactly the same since I don't have AE's random seed.

**Comment by Onlypar2** [comment]
ok Thank you.

**Comment by danielbayley** [comment]
> wiggle is not supported unfortunately
It's difficult to simulate wiggle

@bodymovin See #709.

**Comment by NiftyGift** [comment]
You can convert the expression to keyframes, by selecting the transform property you assigned the expression to (e.g. Position) then clic to the menu Animation > Keyframe Assistant> Convert Expression to keyframe.

**Comment by Krulzor** [comment]
I did Convert Expression to keyframe but if its something larger lets say 1 minute have problems to show up due the big number of keyframes =S

**Comment by birdbrainsolutions** [comment]
> You can convert the expression to keyframes, by selecting the transform property you assigned the expression to (e.g. Position) then clic to the menu Animation > Keyframe Assistant> Convert Expression to keyframe.

Going to try this now, thanks!
