### ISSUE TITLE
Missing paths

### ISSUE THREAD

**Issue by lgBatista** [bodymovin/bodymovin#540]
Hi there, 

I'm making a simple animation with a line and some elements, on AE its all OK but when I renderize it on bodymovin only one line is missing ... 

![ae](https://user-images.githubusercontent.com/5192114/28135797-dd39dec4-671d-11e7-9a65-2b68bea42ec2.gif)

take a look at the splited line just before the words

![html](https://user-images.githubusercontent.com/5192114/28135820-f35aa5bc-671d-11e7-9573-4fc1d6053ba0.gif)

Look how on the second element that line are missing... both elements on screen are equals, just copy and paste ...

I looked on the generated code and see that bodymovin creates in <defs> tag some masks tags with IDs and link the graph with this, all seems OK to me

It only work with I making a new element and a new mask from scratch - with no ctrl+C  crtl+V. That is the default behaviour of the plugin ?

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by lgBatista** [comment]
for sure... hope it helps ^^ 

[squadrabkp.zip](https://github.com/bodymovin/bodymovin/files/1143174/squadrabkp.zip)

**Comment by bodymovin** [comment]
I've exported the composition named "infografico" and it seems to work fine. Is that the one that was failing?
Can you share a link so I can check what might be going on?

**Comment by lgBatista** [comment]
Oh sorry, I send you the wrong archive. That is the one that I fixed the behaviour by making all over again. 

Now its the right one 
[squadrabkp_bug.zip](https://github.com/bodymovin/bodymovin/files/1144988/squadrabkp_bug.zip)
