### ISSUE TITLE
Masking Issue With Trim Paths

### ISSUE THREAD

**Issue by bhamlefty** [bodymovin/bodymovin#541]
**Tell us about your environment**
Mac OSX
* **Browser and Browser Version:**
Chrome
* **After Effects Version:**
AE CC 2017 
**What did you do? Please explain the steps you took before you encountered the problem.**
Attached is an AE file for reference. I have a shape layer with an animated trim path. Below the trim path I have a mask in the shape of an S with its mode set to "Add". I am using the trim path to reveal the letter but when I view in my code editor the mask isn't applying correctly and I can only see the trim path line without the mask correctly choking the edges. Thank in advance for the help!

[MaskTrim.aep.zip](https://github.com/bodymovin/bodymovin/files/1146602/MaskTrim.aep.zip)

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

The trim path is visible but the mask over the trim path isn't displaying. 

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, can you share a link? I see it fine here.

**Comment by bhamlefty** [comment]
Here is a video showing the problem. I exported the animation and everything looks right except the shape of the S. Its only displaying the trim path stroke and is not using the mask on the layer. 

[trimpath.zip](https://github.com/bodymovin/bodymovin/files/1153461/trimpath.zip)

**Comment by bodymovin** [comment]
What renderer are you using? svg, canvas or html?

**Comment by mstrazds** [comment]
Hey, firstly, amazing library..! Hands down brilliant and has worked flawlessly for hundreds of animation exports.

It's a logo with a trim path layer above to reveal the logo below.

We have come across what appears to be a similar issue as well with a particular export. I have attached the aep and a couple of screenshots, including how it looks in AE as well as the result. Any help would be much appreciated.

Export:
[logo_reveal.json.zip](https://github.com/bodymovin/bodymovin/files/1203894/logo_reveal.json.zip)

AEP: (AE CC 2017.1)
[Logo_reveal.aep.zip](https://github.com/bodymovin/bodymovin/files/1203893/Logo_reveal.aep.zip)

Screenshot AE:
![screen shot 2017-08-07 at 2 45 14 pm](https://user-images.githubusercontent.com/756378/29012754-4907effc-7b81-11e7-9dd0-e56205dcf5cd.png)

Result: (Chrome Version 60.0.3112.90 / OSX 10.12.4)
<img width="240" alt="screen shot 2017-08-07 at 3 01 35 pm" src="https://user-images.githubusercontent.com/756378/29012775-5f79311a-7b81-11e7-9e14-a5f71c4f35c7.png">

I tried to render in (SVG) in Firefox and there is no result at all. Let me know if you need anymore information.

**Comment by bodymovin** [comment]
So in the AE preview it works fine but not in Chrome right?
I tried your .aep and .json and they seem to work fine here both in Chrome and Firefox.
Can you share a link with the animation failing so I can take a look?

**Comment by elisathielemann** [comment]
Hey, I have the same problem :( Did my animation with Masks and in the bodymovin preview everything works fine. But when I put the .json in the lottie editor, the mask did not work anymore. I need to export as a svg file, because I need the logo animation for my mobile app. Do you have any idea how to fix? Here is the link in lottie: not working in any browser sadly :(

https://www.lottiefiles.com/share/2SpDDe

**Comment by kloskow** [comment]
Hi there, I think I might have the same issue. My .json file does not appear in Lottiefile editor nor standalone LottieUWP.sample. On the other hand everything looks totally in order when I run html via a browser. I use subtract masks to great the reveal effect. When mask layer removed from the comp. image shows up with no issues. 


[demo.zip](https://github.com/airbnb/lottie-web/files/1736793/demo.zip)

Please find the attached project files.

**Comment by dmateobuitrago** [comment]
Did anyone find a solution for this issue?
