### ISSUE TITLE
Complete failure on IE9 and IE10: 'Redeclaration of const property' 

### ISSUE THREAD

**Issue by eelke** [bodymovin/bodymovin#542]
The current player version (v4.9.0) fails to load on both IE9 and IE10. I tested this on multiple machines, virtual and real. This is before even trying to load a json file.

The error thrown is `SCRIPT5039: Redeclaration of const property`, referring to line 1 character 1.
The script here starts with `var window=..`, which should probably never be called in this way, as this is trying to redeclare a const var. 

See https://stackoverflow.com/a/17587242/588163 for more information.

**Comment by eelke** [comment]
This problem was probably introduced with https://github.com/bodymovin/bodymovin/commit/c666a401ac32995c19893830f251492dd6d26347

**Comment by bodymovin** [comment]
any solution for this in order to support server side rendering?

**Comment by spassvogel** [comment]
https://github.com/bodymovin/bodymovin/pull/637

This fixed it for us.
