### ISSUE TITLE
Clickable/Selectable SVG Elements not Clickable/Selectable in Firefox

### ISSUE THREAD

**Issue by mikematos84** [bodymovin/bodymovin#543]
**Tell us about your environment**
Windows 7

* **Browser and Browser Version:**
Mozilla Firefox 47.0.2 (32-bit)
* **After Effects Version:**
Not sure

**What did you do? Please explain the steps you took before you encountered the problem.**
I am trying to add 508 compliance / accessibility to a project. Within the exported bodymovin JSON we have given objects we want to interact with body an ID and a Class. 

**What did you expect to happen?**
Using the mouse to interact with those objects works as expect in all browsers but when it comes to being able to table through "clickable" elements it does not. 

**What actually happened? Please include as much _relevant_ detail as possible.**
It works as expected in IE9+ and Chrome but when I tested it in Firefox I am not able to tab to the elements even though they have a tabindex and are focusable.

**Please provide a download link to the After Effects file that demonstrates the problem.**
I do not have a link to the after affects file to provide.

**Comment by mikematos84** [comment]
I thought I was on the latest but it turns out I was not. I have since upgrade to 54.0.1 and it seems the problem has been remedied

**Comment by bodymovin** [comment]
Closing issue.
Let me know if you need anything else.
