### ISSUE TITLE
Sticky Hover Effect on Touch Screen Devices

### ISSUE THREAD

**Issue by sifford** [bodymovin/bodymovin#544]
Hello everyone! I made an animated svg with bodymovin and added event listeners to make it play on hover. Works great online, though I noticed that when I click the svg on my phone in safari, the animation continues to loop through the frames I specified. Does anyone know of a way to fix it where the svg will only animate while the user is touching on it or is there a way to have it animate for a second or so and then return to to its original static state? Here's the pen:

[https://codepen.io/tc4d/pen/EXRJVN](url)

I'm a nub at jquery, but I'm learning as I go.

**Comment by DaanDirk** [comment]
You want to use touch events for touch devices.
Add this to your code:
>container.addEventListener("touchstart", myScript1);
container.addEventListener("touchend", myScript2);

I don't have safari to check, but I think this should work.

**Comment by sifford** [comment]
Awesome! Your solution worked! and created a few minor issues. It now flaps when I hold my finger on it and goes back to original state when I let go, but some odd behavior happens. A tinted square appears over the goose while I touch and keep my finger on it and sometimes if I just tap the goose, it will get stuck on looping until I tap it again. I'm assuming this could just the behavior of touch screens. Here's a new pen with the touch events you suggested:

[https://codepen.io/tc4d/pen/gRJwYQ](url)

**Comment by DaanDirk** [comment]
That is probably a square from your browser or phone, which you normally wouldn't see because your finger is on top of it.
And sometimes the browser might not register the touchend. You could also use a different touch event.

**Comment by sifford** [comment]
Ah ok. Thanks for your help!!
