### ISSUE TITLE
using rendererSettings breaks animation

### ISSUE THREAD

**Issue by nirurin** [bodymovin/bodymovin#545]
I've been testing a basic html page that shows just the animation I have made, just to check that it works as a concept, before I then try and link/import the animations into my wordpress site. 

I have managed to get it to run on my website on a blank page fine, however the first problem I had was that it appears in the middle of the page, leaving a lot of white space above and below which did cause some issues. However I fixed this by using :
> rendererSettings: {preserveAspectRatio: 'xMinYMin meet'}
This works. 

However -
I have been trying to make it so that the animation only starts to play, when there is a mouseover event. I have figured this part out, and I managed to get it to work fine, but only when there is no rendererSettings in the variables. As soon as I add in the rendererSettings, and try and run the code, it just loads a blank page and chrome says "Uncaught SyntaxError: Unexpected identifier".

It seems that I can either have a mouseover event, or edit the aspect ratio, but not both. 
Here is the code that I used, that doesn't work for some reason. If I remove the rendererSettings lines, it works fine. If I leave those in, but remove the mouseover event, it works fine. 

```
<script>
animContainer = document.getElementById('bodymovin');
    
var params = {
    container: animContainer,
    renderer: 'svg',
    loop: true,
    autoplay: true,
    autoplay:false,
    autoloadSegments: false,
    rendererSettings: {
    preserveAspectRatio: 'xMinYMin meet'
  }
    path: 'data.json'// path to your data.json file you rendered from AE

};

var anim;

anim = bodymovin.loadAnimation(params);
animContainer.addEventListener("mouseover", myScript);

function myScript(){
    anim.play();
}
    
</script>
```

Any ideas? Here are the links to the pages (I have all 3 set up online - one for the Aspect ratio, one for the mouseHover, and one that shows my attempt at both using the above code. 
http://scrivlings.co.uk/js/logotestaspect.html
http://scrivlings.co.uk/js/logotestmouse.html
http://scrivlings.co.uk/js/logotestboth.html

**Comment by bodymovin** [comment]
On your 3rd example, you're missing a comma after the rendererSettings:
```
<script>
animContainer = document.getElementById('bodymovin');
    
var params = {
    container: animContainer,
    renderer: 'svg',
    loop: true,
    autoplay: true,
    autoplay:false,
    autoloadSegments: false,
    rendererSettings: {
    preserveAspectRatio: 'xMinYMin meet'
  },
    path: 'data.json'// path to your data.json file you rendered from AE

};

var anim;

anim = bodymovin.loadAnimation(params);
animContainer.addEventListener("mouseover", myScript);

function myScript(){
    anim.play();
}
    
</script>
```

Also, you're passing an animationData object that you don't seem to have. You should remove the line:
animationData: animationData

**Comment by nirurin** [comment]
Ahha, that does work now thankyou for the fast response! Unfortunately I have been trying to pass the animation to wordpress via iFrames (hence needing to put the animation to the top of the page in the seperate html). But there is still white space below the animation in the iFrame. 

I'm trying to find ways to force the iframe to only display the animation part of the page, but it's being difficult. Is there any way you can think of to output the render without any white space? 

Unfortunately wordpress doesn't really let me input the json directly, at least not without a massive rewrite of the code for the pages it seems. 

Thanks for the fix though, it works as it should now!

**Comment by bodymovin** [comment]
Can you load js files easily to your page?
If so, you can use the json data as a js object and load it an animationDaata instead of passing the path.

**Comment by nirurin** [comment]
I dont know... I can upload the files to the file system, but it's getting the code in the right place that would confuse me. My coding skills pretty much conk out after CSS, most of the js changes ive been making have been trial and error from other people's codepen pages. 

However I did get the iFrame working properly, just needed to set the height to 100% and it worked.

**Comment by bodymovin** [comment]
nice. Let me know if you need anything else.
I'm closing the issue.
