### ISSUE TITLE
Shape layers issue

### ISSUE THREAD

**Issue by re-player** [bodymovin/bodymovin#547]
Hi, I have an issue with rendering shape layers. Bug appears not only on complex shapes, but even on text converted to shapes (!).

Here, take a look please:
1) in after effects everything is ok: http://c2n.me/3MdXVut.png
2) here it is after rendering in bodymovin: http://c2n.me/3MdY8xR.png. i've pointed with arrows problem places + u can see what happened to the letters 

This problem can be solved?

I've attached ae-file in hud.zip + JSON-file in eagle.zip.

[eagle.zip](https://github.com/airbnb/lottie-android/files/1155581/eagle.zip)
[HUD.zip](https://github.com/airbnb/lottie-android/files/1155576/HUD.zip)

AE ver CC 2017, bodymovin 4.9

**Comment by re-player** [comment]
2 days past, still no answer. Just in case, my question is about shape issues. Not about animation, cause i know why it's not working. Need to understand what happening to shapes & how to fix it.

**Comment by DaanDirk** [comment]
Hey re-player,
There are merge paths in the shape you are using and you don't need them.
But when I tried it, it all renders fine.

**Comment by re-player** [comment]
This bug is not about merge path. Here is another example. No merge paths in here http://c2n.me/3MiwtsA.png, but still it's happening.

And what is mostly interesting, it happens not always. Sometimes it renders ok, but sometimes not.

**Comment by re-player** [comment]
Smth happening with shape layers. I guess not only me having this problem. 

I've attached my current ae-file for this scene http://c2n.me/3MiwtsA.png.
[MENU (7).zip](https://github.com/bodymovin/bodymovin/files/1162656/MENU.7.zip)

**Comment by DaanDirk** [comment]
Sorry, I can't reproduce it.
But here is the eagle: https://www.dropbox.com/s/p918icdo66a9ade/eaglelogo.json?dl=0
Maybe Hernan knows what it is.

**Comment by DaanDirk** [comment]
https://www.dropbox.com/s/fzwpdtv3v2z78j4/menu.json?dl=0

**Comment by re-player** [comment]
Hm, this is very interesting. Eagle ver which u gave have no issue at all.
What version of after effects u use?

**Comment by DaanDirk** [comment]
CC 2017, latest release, english version.
Maybe you are using a localized version?
How did you install bodymovin? I'm using ZXP installer by aescripts.

**Comment by re-player** [comment]
No localization, only true-original english ver) and also CC 2017 http://c2n.me/3MiyVPP.png
U have PC or mac? Maybe PC ver works a little differently...

**Comment by re-player** [comment]
"How did you install bodymovin? I'm using ZXP installer by aescripts."

i've did the same thing. but maybe smth went wrong... shapes renders very wrong. And as far as i can see problem is on my side

**Comment by DaanDirk** [comment]
I'm on PC, so that's the main difference. 
Let's hope Hernan can figure it out.
He's the king of bodymovin! 🕺!!

**Comment by re-player** [comment]
I'm using PC too) Thought maybe u are using mac, that's why all fine.

"Let's hope Hernan can figure it out.
He's the king of bodymovin!"

Ok) I really hope he could help me with that :)

**Comment by bodymovin** [comment]
Hi, sorry about the delay.
I've been trying to understand what might be going on, but when I export it here, everything seems to work fine.
Can you export a simpler animation so I can compare results?
for example, can you export the single letter "P" without any animation at all and send me the json file?

**Comment by re-player** [comment]
Sure, here u go. Here is only letter P.
[data.zip](https://github.com/bodymovin/bodymovin/files/1163021/data.zip)

**Comment by bodymovin** [comment]
sorry, can you share the .aep as well so I can export the same composition?

**Comment by re-player** [comment]
Yep. Here it is.
[HUD.zip](https://github.com/bodymovin/bodymovin/files/1163068/HUD.zip)

**Comment by bodymovin** [comment]
There are many differences on the json you sent me and the comp.
for example comp height is 90 px vs 1080px.
Is it possible that you changed things and didn't save the project before sending it over?

**Comment by re-player** [comment]
Maybe. But I guess size of the comp doesn't change anything at all) Cropped it & attached. Smth wrong with shapes render, in every composition i work with. Doesn't matter size or animation, still the same almost every time. I've mentioned it few posts above  http://c2n.me/3MiwtsA.png
[HUD.zip](https://github.com/bodymovin/bodymovin/files/1163459/HUD.zip)

**Comment by bodymovin** [comment]
I know but I'm trying to reduce to a minimum the differences because there is something strange going on.
Can you export the project you just sent me and send me the json file?

**Comment by bodymovin** [comment]
Nevermind, I found the issue. But I don't understand how this is happening. There are properties missing in your json file.
Can you think of anything in your setup that might be affecting the exported json?

**Comment by re-player** [comment]
I've just re-installed bodymovin. Ver 4.7.1. All works just great, no bugs with shapes.

But now having bug in repeater http://c2n.me/3MiXVed.png. I suppose need to install ver 4.9, where is full repeater support)

**Comment by re-player** [comment]
And i have a noob question) I've downloaded latest ver, but can't find .zxp file there http://c2n.me/3MiY8cN.png. Can u tell me where i can find it?

**Comment by bodymovin** [comment]
sure, on the build/extension folder

**Comment by re-player** [comment]
Thx)

**Comment by bodymovin** [comment]
np, let me know if after reinstall it works properly

**Comment by re-player** [comment]
Now repeater works great) And no shape bugs. I hope this problem has gone for good and won't appear again.

Anyway, ur plugin is just great. Don't know how we could export complex animations from ae to apps another way. U're doing really great job)

**Comment by bodymovin** [comment]
thanks :)

**Comment by re-player** [comment]
Hi, Hernan)

have another issue with shapes. pls, take a look http://c2n.me/3Mk55VZ.png
i've already deleted all merged pass but nothing changed.

ae + JSON right here.
[Gestures (converted).zip](https://github.com/bodymovin/bodymovin/files/1165511/Gestures.converted.zip)
[tap.zip](https://github.com/bodymovin/bodymovin/files/1165513/tap.zip)

**Comment by re-player** [comment]
And btw, sadly, but initial problem with that http://c2n.me/3MlbDtR.png still actual. It doesn't appear only when bodymovin just installed. But when i open ae again this issue comes to light.

I tried to fix it with resetting settings in ZXP installer and & helped couple of times. But now even that not helping(( Only re-install can fix it. But it's very uncomfortable way to deal with that problem :(

**Comment by re-player** [comment]
UPD: now even re-install not helping( still the same

**Comment by bodymovin** [comment]
is it happening only with that project or with any?

**Comment by re-player** [comment]
With any. Different ae-files, not the same. But the same bug all the time.

I'll try to check it on another version of CC 2017 tomorrow. I've already checked on CC 2014. No problem with shapes, but after i export animation via bodymovin animation blinks almost on every frame (eagle comp, haven't checked anything else). Anyway, need to make it work right on CC 2017.

I'll report u here about any news.

**Comment by bodymovin** [comment]
can you write me an email with the results so I can follow the issue offline?

**Comment by re-player** [comment]
Sure. Can u tell me ur email? And have u checked this http://c2n.me/3MnjJxO.png?

**Comment by bodymovin** [comment]
hernantorrisi[at]gmail.com
