### ISSUE TITLE
3D animations are not responsive, Error or by design? 

### ISSUE THREAD

**Issue by QKIII** [bodymovin/bodymovin#548]
**Tell us about your environment**
OS Sierra MBP 
* **Browser and Browser Version:**
Chrome 59.0.3071.115
* **After Effects Version:**
AE 14.1.0.57
**What did you do? Please explain the steps you took before you encountered the problem.**
I am testing out the functionality of BodyMoving as it relates to 3D layers. Realized all of the layers have to be 3D in order to render. But I found that once it is a 3D animation it is not responsive when changing the browser window
**What did you expect to happen?**
I expected the animation to be responsive to the size of the viewport like non-3D animations are
**What actually happened? Please include as much _relevant_ detail as possible.**
The animation is not responding to the size of the viewport unless I refresh the page at the new viewport size
**Please provide a download link to the After Effects file that demonstrates the problem.**
[BM2.zip](https://github.com/bodymovin/bodymovin/files/1156450/BM2.zip)

**Comment by QKIII** [comment]
The AE file and BodyMoving Demo are included in the Zip 👍  Thanks !

**Comment by bodymovin** [comment]
you need to explicitly call "resize" on the animation instance.
Since size could be affected not only by window resize, but by any other change in the DOM, it's not possible to do it based on a single event.

**Comment by QKIII** [comment]
Thanks so much Hernan!

Keep making awesome stuff! 

-Ivan
