### ISSUE TITLE
How to update my version?

### ISSUE THREAD

**Issue by shokrizorid** [bodymovin/bodymovin#55]
Hello, 

Thank you so much for this plugin, it's just awesome. 

Today I want to update the bodymovin 4.0.1 extension, but I would like to know how to do this.
Do I have to uninstall the old plugin manually?
Or I just need to install directly the new bodymovin extension manually?

Best

**Comment by bodymovin** [comment]
hi!
you shouldn't need to uninstall the old version.
just do the same steps you did before

**Comment by shokrizorid** [comment]
Thank you for your fast answer :)
Last questions,

I would like to know if the mask works now with bodymovin?
And where can I find the number version of bodymovin? Because when I use cmd with "ExManCmd.exe /list all" he said I have the v1.0.0 : /

**Comment by bodymovin** [comment]
you're right, I didn't update the version on the extension. I'll do it in the next release.
You can check the version on the js player.
What kind of masks are you using? 
masks should have already been working

**Comment by shokrizorid** [comment]
Ok for the version. 
For the masks I'm using the tool: 
Effect/generation/line. 

Maybe it's not the right mask system?

**Comment by bodymovin** [comment]
I see. Those masks are not supported
you can animate normal masks or use the trim path property for strokes.

**Comment by shokrizorid** [comment]
Yes, I have just seen this on your example Bodymovin_Github.aep

Thank you so much
Have a nice day!

Nerisson

**Comment by bodymovin** [comment]
thanks. you too

**Comment by vincent-bidaux** [comment]
Do we need to redownload and checkout again from aescript for each update? Or is there an easier repository.

**Comment by bodymovin** [comment]
@vincent-bidaux if you are using aescripts, I think you need to redownload each time

**Comment by vincent-bidaux** [comment]
Thanks. And sorry, I didn't realize the .zxp was part of the Lottie repo. So it's all good, I just have to watch the Lottie repo and I'll be aware of changes.
