### ISSUE TITLE
effect disappeared

### ISSUE THREAD

**Issue by vision1989** [bodymovin/bodymovin#550]
when i craeted an AE comp，use bodymovin export to json，some effects of the comp  disappeared，like Feather, half transparent etc.
what should i do？

**Windows 10**

**After Effects CC 2015.3**

comp effects:
![image](https://user-images.githubusercontent.com/24890619/28354241-bb6058cc-6c91-11e7-86e1-b4d07d84b2d2.png)
export effects:
![image](https://user-images.githubusercontent.com/24890619/28354566-f434535a-6c92-11e7-993c-e2fab722cf6d.png)

**Comment by bodymovin** [comment]
Hi, unfortunately, not many AE effects are supported.
here's a list of the currently supported ones
https://github.com/bodymovin/bodymovin/wiki/Effects

**Comment by vision1989** [comment]
Thanks for your reply. Bodymovin is a great product.  Hoping it can support more AE effects in the not far future.  Thanks again~
