### ISSUE TITLE
Swap png for SVG manually

### ISSUE THREAD

**Issue by mamjed** [bodymovin/bodymovin#551]
Is it possible to swap exported PNG files with SVG files. I didn't convert my AI layers to AE Shapes, and I want to use the generated JSON with SVG files I manually exported from AI for the Bodymovin export.

**Comment by bodymovin** [comment]
you'll need to search in the assets property of the json for the png paths and replace them with the svg path.
You can do it at runtime before loading the animation or editing the json file manually.
