### ISSUE TITLE
Drop shadow not working

### ISSUE THREAD

**Issue by es-lab** [bodymovin/bodymovin#553]
**Tell us about your environment**
mac os 10.12
bodymovin 4.7.0

**After Effects Version:**
cc 2017

**What did you do? Please explain the steps you took before you encountered the problem.**
- Converted AI layers into vector shapes.
- Added layer style drop shadow
- export

**What did you expect to happen?**
The animation should be with drop shadows.

**What actually happened? Please include as much _relevant_ detail as possible.**
There are no shadows

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/7sj0e0s6yf6gf8w/Phone%20Animation%20.aep?dl=0

**Comment by DaanDirk** [comment]
Try the perspective effect named: Drop Shadow
:-)
