### ISSUE TITLE
sourceText experssion, Render output problem

### ISSUE THREAD

**Issue by Romixery** [bodymovin/bodymovin#554]
Hi all
I have null object with slider control with value range of 0-100. And, assigned source text of a text object to this value. In AE all is OK :-). BUT when i render composition using bodymovin, the result is text is just place holder text.
The source text expression is:
`Math.round(thisComp.layer("Null 1").effect("Slider Control")("Slider"))+"%"`
What is my problem?

**Comment by DaanDirk** [comment]
You want to show a value between 0 and 100?

I believe SourceText expressions aren't supported yet. 
also see: https://github.com/bodymovin/bodymovin/issues/308

But you can convert the Source Text expression to keyframes and it will work with bodymovin.
Hope that helps!

**Comment by effektsvk** [comment]
I've made a script that solves this, it isn't the most flexible thing but at least it works: https://github.com/effektsvk/bodymovin-numbercount-aescript

**Comment by bodymovin** [comment]
@effektsvk thank looks nice!
I'll try to work on supporting scripts for text soon.

**Comment by bodymovin** [comment]
Expressions are now supported on text sources in version 4.13.0

**Comment by RhysyG** [comment]
@effektsvk Were you able to use expressions the normal way once expressions were supported? I can only seem to get it working locally (export demo) but when I upload it to the Lottie preview it doesn't work. It also doesn't work in proto.io.

**Comment by bodymovin** [comment]
@RhysyG that lottiefiles player is pretty old and might not work with newer compositions.
Have you tried exporting the animation and trying it yourself?

**Comment by RhysyG** [comment]
@bodymovin 

Hey!

Yeah I did export the animation and it works locally (from generated demo file) but doesn't work in Proto.io so I am trying to identify the problem. Maybe their player is old as well.

Cheers.

**Comment by effektsvk** [comment]
@RhysyG I didn't try it out yet, I'm not sure.
