### ISSUE TITLE
Use the Drop Shadow, why not Drop Shadow after the output?AE CC 2015 /bodymovin_4.9

### ISSUE THREAD

**Issue by chongzidzh** [bodymovin/bodymovin#556]
![wx20170728-144736](https://user-images.githubusercontent.com/30520014/28706242-f457acb4-73a5-11e7-927a-8369e4740ce4.jpg)

**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by chongzidzh** [comment]
supplement
[Drop shadow.json.zip](https://github.com/bodymovin/bodymovin/files/1182281/Drop.shadow.json.zip)

**Comment by bodymovin** [comment]
Hi, the layer styles drop shadow is not supported, try using the one from the effects panel

**Comment by chongzidzh** [comment]
Use the shadow in the effects panel, or not. why? Can you give specific effects?
[Test the shadow.json.zip](https://github.com/bodymovin/bodymovin/files/1244047/Test.the.shadow.json.zip)

**Comment by chongzidzh** [comment]
You can use AE to cut a map to see, which is a special shadow support lottie?

**Comment by chongzidzh** [comment]
Which shadow is supported？

**Comment by chongzidzh** [comment]
@bodymovin
