### ISSUE TITLE
Hover effect. SVG + Animation?

### ISSUE THREAD

**Issue by Sandok-voc** [bodymovin/bodymovin#558]
Hi there!
I try to do a hover effect directly with an animation from ae. I don´t know why, but it doesn´t work... (That what I have written). Could you help me?

`var animation = bodymovin.loadAnimation({

	container: document.getElementById("logo").addEventListener("mouseover", function(){ anim.play(); }),
	renderer: "svg",
	loop: true,
	autoplay: false,
    prerender: true,
	path: "json/logo.json"
})`

Could I a svg image (logo) in the html embed and render the animation (json data) as hover?

Thank you! :)

**Comment by bodymovin** [comment]
your animation instance is called "animation", have you tried doing animation.play() instead of anim.play() ?

**Comment by Sandok-voc** [comment]
Yes I did it, but with the same result... Maybe is it an animation´s problem?

**Comment by DaanDirk** [comment]
Does putting these separate work:
>var logo = document.getElementById("logo");
var animation = bodymovin.loadAnimation({
container: logo,
renderer: "svg",
loop: true,
autoplay: false,
prerender: true,
path: "json/logo.json"
});
logo.addEventListener("mouseover", function(){ anim.play(); });

**Comment by Sandok-voc** [comment]
Hey! It´s alive, thank you so much!
That´s what I wrote (maybe can it help someone ;)):

`var logo = document.getElementById("logo");
var animation = bodymovin.loadAnimation({
    container: logo,
    renderer: "svg",
    loop: true,
    autoplay: false,
    prerender: true,
    path: "json/logo.json"
});

logo.addEventListener("mouseenter", function () {
    animation.play();
});

logo.addEventListener("mouseleave", function () {
    animation.stop();
});`
