### ISSUE TITLE
Animation not showing in any web browser except for firefox

### ISSUE THREAD

**Issue by kevinman1234** [bodymovin/bodymovin#56]
Hi I just have one main question, i cant seem to get the animation to work in chrome, or safari. It works in firefox. All web browser are up to date. Im not sure if i messed up anything or if im missing anything. If anyone could please help it would be awesome.
[bodymovin 2.zip](https://github.com/bodymovin/bodymovin/files/112555/bodymovin.2.zip)

**Comment by bodymovin** [comment]
@kevinman1234 I see your animation fine in chrome.
I guess you're not serving the files through a web server.
Is that possible?

**Comment by kevinman1234** [comment]
Hi yes, im only viewing from desktop, no server. Is that the reason why it's not working?

**Comment by bodymovin** [comment]
@kevinman1234 yes, very likely

**Comment by kevinman1234** [comment]
Hi thank you there much it works now!!!
