### ISSUE TITLE
Time remapped objects are not easing properly

### ISSUE THREAD

**Issue by jakeleboeuf** [bodymovin/bodymovin#560]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome 59.0.3071.115 (Issue is present in "Preview" as well)
* **After Effects Version: 2017.2** (14.2.0.198)

**What did you do? Please explain the steps you took before you encountered the problem.**
I did not create the AE file- I simply downloaded it and ran it thru bodymovin.

**What did you expect to happen?**
Timing to match the rendered view.

**What actually happened? Please include as much _relevant_ detail as possible.**
It appears there is a timing issue with a time remapped composition. You can see the animations are not synced up.

After Effects / Chrome
![timing](https://user-images.githubusercontent.com/690573/28726474-61faba16-738f-11e7-835f-5e87e29a3292.gif)

**Please provide a download link to the After Effects file that demonstrates the problem.**
The file is [available at UI8](https://www.ui8.net/products/splash-loader-project) and can be downloaded directly [here.](https://www.ui8.net/account/download/54eb648e5bb1cc61493d9a39/560cd523f7d2d9ab1dccdc82)

**Comment by bodymovin** [comment]
What version of bodymovin are you using?
Do you have a link with tha behavior?
It seems to work fine in version 4.9.0

**Comment by jakeleboeuf** [comment]
Latest upgrade of Bodymovin fixes this!
