### ISSUE TITLE
Problems with 3D layers

### ISSUE THREAD

**Issue by azun1te** [bodymovin/bodymovin#561]
**Environment:**
Hello, I'm using win10, AE 2017.2 EN , and Chrome 60.0.3112.78

**What did you do? Please explain the steps you took before you encountered the problem.**
I'm having trouble making 3D layers to work. Firstly, I've converted a character animation from AI. layers to shape layers, then I've converted the expressions to keyframes and tried to export the project. Because the character was from a 3D project and had animated [orientation] property, the layers remained 3D.

**What did you expect to happen?**
I've expected the exported character to look just like in AE project because I've removed all the effects and expressions. Only shapes and keyframes left.

**What actually happened? Please include as much _relevant_ detail as possible.**
The character is rotating randomly in 3D space. 
I've tried to take only the head layers - make new composition, disable 3D layers and it worked normally, but I lost all the animation that was based on 3D orientation property.

Also I've noticed that 3D shapes that have stroke are not working properly. IE: ellipse's stroke gets cut off where the fill ends - http://imgur.com/a/MQXNZ

**Please provide a download link to the After Effects file that demonstrates the problem.**
AE project and exported animation files  - https://we.tl/xh87MMg2hq

Love the project so far!

**Comment by Goozoon** [comment]
I have the same cut off problems. What can be wrong, please?
Project: https://we.tl/t-gA09CoWs73
IMG: https://pasteboard.co/I6hXYPj.png
