### ISSUE TITLE
Ouroboros 2 Support - Beta

### ISSUE THREAD

**Issue by laygir** [bodymovin/bodymovin#563]
Hi, Mister!

I just saw the new update and Ouroboros beta support. I wanted to try it but couldn't figure it out. Any specific way of export or implementation required?

**Tell us about your environment**

* **Browser and Browser Version:**
Chrome Version 60.0.3112.78 
* **After Effects Version:**
AE CC 2017 14.2.1.34

**What did you do? Please explain the steps you took before you encountered the problem.**
Created a new comp, inserted new Ouroboros 2 layer. That's it. no animation.

**What did you expect to happen?**
Expected to see Ouroboros in the browser

**What actually happened? Please include as much _relevant_ detail as possible.**
Console message appeared.

**Please provide a download link to the After Effects file that demonstrates the problem.**

![screen shot 2017-07-31 at 18 28 47](https://user-images.githubusercontent.com/772730/28787839-1e50edb2-761e-11e7-9e67-16f0135fe706.png)

**Comment by bodymovin** [comment]
Make sure you select to include Hidden elements on the Bodymovin plugin panel.
Open the comp settings and check the Hidden option.

**Comment by laygir** [comment]
Okay, I tried that but still no success although the console message changed.

![screen shot 2017-08-01 at 13 58 06](https://user-images.githubusercontent.com/772730/28824388-ff069d9a-76c1-11e7-9e9d-8be2d6a05652.png)

Also if I try to use speed property of Ouroboros, it throws an exception like this;
![screen shot 2017-08-01 at 13 52 58](https://user-images.githubusercontent.com/772730/28824432-2cff9c1a-76c2-11e7-9fa1-1b37886cf531.png)

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by laygir** [comment]
Yes, sorry.

[Ouroboros2.aep.zip](https://github.com/bodymovin/bodymovin/files/1191814/Ouroboros2.aep.zip)

**Comment by bodymovin** [comment]
Hi, I've found the issue.
It's fixed on version 4.10.1 and uploaded.
Can you share the .aep where you get the other error?
Thanks!

**Comment by laygir** [comment]
Hi! Thanks!

So I have attached the other file. If I use speed, I receive that javascript exception. Please see speed comp inside the aep.

[Ouroboros_speed_trim.aep.zip](https://github.com/bodymovin/bodymovin/files/1204194/Ouroboros_speed_trim.aep.zip)

**Comment by bodymovin** [comment]
thanks! I've found the issue and fixed it.
It will be uploaded on the next version.

**Comment by azinash** [comment]
I can't seem to get Ouroboros to work on iOS / Android but works fine on web. Is this a known issue?

**Comment by bodymovin** [comment]
@azinash yes iOS and Android don't support expressions. You can try exporting them as keframes from the bodymovin settings
