### ISSUE TITLE
Weird Display Issue

### ISSUE THREAD

**Issue by KatieBlackmore** [bodymovin/bodymovin#565]
Hi There :)

So I'm really loving bodymovin cause the possibilities are just awesome :D. 
I am having a few issues with using it though and would really really love some help........ like seriously please help me :)

I would like a really cool animated background on my website and did this trial run. The problem is that when I link it in the animation is super super tiny until I delete the height value, then it fills the page with a margin ( even when it's specified as 0). I also have a problem that it cuts off the sides of my design and seems to stretch it horizontally as you can see by the super thick lines and the squashed oval around my heading.

I don't know if it's coding or if it's when I export the animation but I only use paths with a stroke and took out the part that used effects

 This is what the animation looks like....... ( removed the red lines)

![website](https://user-images.githubusercontent.com/30649460/28868144-ce6a019c-7778-11e7-9577-3bbd09020689.gif)

 This is what the website when I first link it......

![website-success_](https://user-images.githubusercontent.com/30649460/28868125-bf1187a6-7778-11e7-9997-14aafc33bbb8.gif)

here's where you can really see how it is stretched and how the sides cut off.......

![awwww nooo](https://user-images.githubusercontent.com/30649460/28868482-e024b6a6-7779-11e7-8082-fc2090c8e295.PNG)

here is my html.......
[website trial.zip](https://github.com/bodymovin/bodymovin/files/1193460/website.trial.zip)

**Comment by DaanDirk** [comment]
Hey @KatieBlackmore
Maybe you could try the svg renderer instead of the html one:
>       animType: 'svg',

And set the with and height of the div with id=bodymovin to reflect the aspect-ratio of your comp.
something like:
`<div style="width:100%;height:313%;background-color:#333;" id="bodymovin"></div>`

Your animation looks like 16:9 but the comp is 2560x8008px?
Is that long shape what you are looking for?

**Comment by KatieBlackmore** [comment]
Thanks. It worked :D
