### ISSUE TITLE
Feature Request: import json into AE

### ISSUE THREAD

**Issue by jakeleboeuf** [bodymovin/bodymovin#566]
Any chance importing a json file into after effects is in the future for this project? I have a `.json` file from [lottie](https://www.lottiefiles.com/255-menu-button-alt?page=5) that I need to kill some dead time before/after the animation starts/ends, and am not sure how to do that by looking at the json!

**Comment by bodymovin** [comment]
Not for now. Might come in the future but it's not a simple task.
If you want to change initial and end frames you can take a look at "ip" and "op" properties

**Comment by bodymovin** [comment]
duplicate of #304
