### ISSUE TITLE
Text and Shape issue

### ISSUE THREAD

**Issue by niravmistrydesign** [bodymovin/bodymovin#568]
![issue](https://user-images.githubusercontent.com/30691304/28920239-8c9694d2-786e-11e7-8e25-b0192a2873b1.jpg)
Hi,

I am using first-time bodymovin. I am working on one animation project for iOS app. I am facing problem in TEXT (converted in to shape) and Line+Color Filled Shape.

Here I am attaching file for better understanding. I will be thankful. 
Zip file included file with .json, .ae, screenshot from desktop and mobile device. 
[text_shape_issue.zip](https://github.com/bodymovin/bodymovin/files/1196997/text_shape_issue.zip)

**Comment by bodymovin** [comment]
Hi, I don't think text is yet supported in iOS.
You should post it directly on their github, they'll have more info than I do.
https://github.com/airbnb/lottie-ios

**Comment by niravmistrydesign** [comment]
Hello, Its fine if it not support text but why trimed shape not showing in output.
I saw they have sample animation with text, but its created with Path tool.

**Comment by henriqrossatto** [comment]
I'm having the same problem.

**Comment by bodymovin** [comment]
Hi, can you post this issue on the Lottie iOS repo so they can follow up on this?
I'm afraid I can't help much more with this issue

**Comment by therealsalih** [comment]
@niravmistrydesign @henriqrossatto This issue should be fixed in Lottie iOS 2.0 or above.
