### ISSUE TITLE
Creating vector paths from points

### ISSUE THREAD

**Issue by andrewmarmion** [bodymovin/bodymovin#569]
I am totally loving bodymovin, especially using it with Lottie. 

I am wondering if it is possible to create a the json file without using after effects, specifically I am creating points on an image on a mobile device and saving them in a format similar to what is in the attached file. What I would like to do is create a simple line animation on the fly based on user input, i.e. join the points in the given color. However, looking inside the file generated by after effects I am not 100% sure of what everything means. 

How would I go about converting the file below into something that I could use with Lottie? 

I've attached an aep showing what I would like to achieve

[test.json.zip](https://github.com/bodymovin/bodymovin/files/1198053/test.json.zip)
[paths.aep.zip](https://github.com/bodymovin/bodymovin/files/1198203/paths.aep.zip)

**Comment by andrewmarmion** [comment]
I've figured it out. Much easier than I thought it was going to be.

**Comment by bodymovin** [comment]
Nice, let me know if you need any help in the future.
