### ISSUE TITLE
Should 'fills' and 'strokes' generated via effect still work?

### ISSUE THREAD

**Issue by SmartArtsStudio** [bodymovin/bodymovin#57]
Are fills and strokes generated by 'fill' and 'stroke' Effects unsupported because "Only slider effects are supported at the moment"?
I get the following error thrown when processing a layer which contains  only a fill, but it was generated via 'fill effect':
"Unable to execute script at line 305. undefined is not an object" 

The composition consists only of animated fills and strokes, however not shape fills and strokes. Fills and strokes generated from mask paths copied on to fill and stroke effects.

I would have thought a fills and strokes were still just a fills and strokes?
I couldn't figure out where line 305 would fall (I assumed based on Initializer.jsx file parsing order line 305 would fall on line 13 of compsManager.jsx but doesn't make sense at first glance)

When I remove the layers containing effect generated fills, the data.json IS produced but when I load it in firefox without a server (which plays all the demo's just fine) the remaining animated strokes of the composition do not render... would this be the result of fills and strokes generated via fill and stroke 'effects'?

**Comment by bodymovin** [comment]
@SmartArtsStudio can you send me the .ae project so I can take a look?
filling as an effect is not supported, but it shouldn't break the export process.
my email is hernantorrisi@gmail.com

**Comment by SmartArtsStudio** [comment]
Will do, thankyou.
