### ISSUE TITLE
Switching from .pngs to vectors breaks animation

### ISSUE THREAD

**Issue by jrogozen** [bodymovin/bodymovin#570]
**Tell us about your environment**

* **Browser and Browser Version:** mac osx chrome 59
* **After Effects Version:** 14.2.1.34

**What did you do? Please explain the steps you took before you encountered the problem.**
used bodymovin to export an animation that used .pngs. this worked as expected. switched to vectors that were output inside data.json. using bodymovin svg renderer

**What did you expect to happen?**
the animation to play the same as with .pngs

**What actually happened? Please include as much _relevant_ detail as possible.**
animation doesn't play. inspecting the result html, it looks like the svg in html is transforming, but it is going very fast. slowing down the animation speed to .1 with anim.setSpeed(0.1) makes the animation slightly more visible, but still incorrect (seems like it is still moving too fast). 

looking at some of the previous posts here it seems like i might need to delete merge paths? i'm unsure of where to do this step. do i do it inside after effects or inside the data.json file that is exported? i tried deleting references to merge paths in the data.json but the result is the same.

thanks!

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by jrogozen** [comment]
hi,

here are the exported files

[bodymovin_test.zip](https://github.com/bodymovin/bodymovin/files/1201099/bodymovin_test.zip)

**Comment by bodymovin** [comment]
Hi, I've checked the project.
The layer "testbuildings_merged Outlines" has around 600 subshapes in groups.
And some of the groups have Merge Paths on them.
For what I could check, only some of them have it but you'd need to go through all of them to remove the Merge Paths 1 and Paths 2 groups in order for it to work.
Or you can use this tool that removes all those artboards
http://aescripts.com/explode-shape-layers/

**Comment by jrogozen** [comment]
Thanks a lot for your help! Appreciate it
