### ISSUE TITLE
Where can I find the expressions that are supported?

### ISSUE THREAD

**Issue by lianyuzhe** [bodymovin/bodymovin#572]
Where can I find the expressions that are supported?

**Comment by bodymovin** [comment]
This is not documented yet, sorry

**Comment by lianyuzhe** [comment]
Thanks, that is ok , but where can I find the source code of the bodymovin plugin?

**Comment by lianyuzhe** [comment]
Thanks, that is ok , but where can I find the source code of the bodymovin plugin?

**Comment by bodymovin** [comment]
https://github.com/bodymovin/bodymovin-extension

**Comment by lianyuzhe** [comment]
Thanks
