### ISSUE TITLE
Is it possible to change the text with javascript ? 

### ISSUE THREAD

**Issue by ZeRego** [bodymovin/bodymovin#573]
The animation I exported has some text that I would like to dynamically change on the browser.
Right now I have to export several times the same animation with all the text options.

I tried to change some values in the json but without success.
Is there a way, or are you thinking about implementing something for this to be possible ?

**Comment by bodymovin** [comment]
You should be able to do it provided you render all the needed characters in the AE textfield.
Then, if you set the text value in the json file before loading the animation, it should work fine.
Let me know if you need more assistance.

**Comment by bodymovin** [comment]
https://github.com/bodymovin/bodymovin/wiki/TextLayer.updateDocumentData
