### ISSUE TITLE
Is the JSON format specified anywhere?

### ISSUE THREAD

**Issue by jlongster** [bodymovin/bodymovin#575]
I can't find anywhere that explains the format of the JSON file. We would like to potential change it at runtime and I was wondering if it was explained anywhere. I'd like to see how all the shapes/layers/paths/etc are encoded into the current format. (I plan to peek at the source code of bodymovin which may help as well)

**Comment by bodymovin** [comment]
Did you check the json docs here?
https://github.com/bodymovin/bodymovin/tree/master/docs/json
it's not complete but it should help.

**Comment by jlongster** [comment]
I did not, thanks! It's something, if not full docs, at least. That helps!

**Comment by Mrcooder** [comment]
@bodymovin yes,the json docs includes the most of the json means, but some key-value means is excluded from the docs.

**Comment by bodymovin** [comment]
@Mrcooder yes, I need to update the doc with newer and missing properties

**Comment by Phrogz** [comment]
Please do update. The lack of mapping for some keys (like in `properties/valueKeyframed.json`) is troublesome. _(And thanks for a nice plugin!)_

**Comment by zhengs** [comment]
Hi @bodymovin , did you get a chance to update the doc?

**Comment by tigaliang** [comment]
Hi @jlongster , did you find any doc about the lottie json file?

**Comment by mbasaglia** [comment]
I would need a correct and complete specification of the file format as well, the json schema seems to differ from how actual files are generated

**Comment by behdad** [comment]
Just jumping on this, I've been looking for any documentation of the json format for a couple days as well and so far found nothing.

**Comment by mbasaglia** [comment]
I've been reverse-engineering the file format, I started from the json schema in here, then fixing things based on actual lottie files and adding looking at lottie-web and rlottie sources.

I've turned it into a Python framework which also generates the documentation for the lottie json in a human-readable format.

It isn't 100% complete yet but it already supports most of the format.

The documentation is here: https://mattia.basaglia.gitlab.io/tgs/group__Lottie.html#details

**Comment by Fr4nZ82** [comment]
> I've been reverse-engineering the file format, I started from the json schema in here, then fixing things based on actual lottie files and adding looking at lottie-web and rlottie sources.
> 
> I've turned it into a Python framework which also generates the documentation for the lottie json in a human-readable format.
> 
> It isn't 100% complete yet but it already supports most of the format.
> 
> The documentation is here: https://mattia.basaglia.gitlab.io/tgs/group__Lottie.html#details

link broken! Pls share

**Comment by mbasaglia** [comment]
Updated link: http://mattia.basaglia.gitlab.io/python-lottie/group__Lottie.html#lottie_json

**Comment by tigaliang** [comment]
@mbasaglia 404 for the above link.

**Comment by mbasaglia** [comment]
Ah yeah I had to move it again https://mattbas.gitlab.io/python-lottie/group__Lottie.html#lottie_json

**Comment by Baboonanza** [comment]
Found it again: [https://mattbas.gitlab.io/python-lottie/group__Lottie.html#details](https://mattbas.gitlab.io/python-lottie/group__Lottie.html#details)

**Comment by frmsaul** [comment]
Doesn't seem like we have official documentation of the format yet. This issue should stay open until such documentation exists.
