### ISSUE TITLE
Is there a way to set the preserveAspectRatio to none?

### ISSUE THREAD

**Issue by amanda--** [bodymovin/bodymovin#58]
I would like the svg to fill up the container div completely, without keeping the aspect ratio.

**Comment by bodymovin** [comment]
@amanda-- not yet. But you could do it manually after the animation is loaded if you're using the svg renderer.

**Comment by amanda--** [comment]
First of all; thank you for your fast reply!

We changed the attribute manually like you suggested.

It would be nice if this would be a setting. Maybe a nice feature for a future version?

Thanks anyways!

**Comment by bodymovin** [comment]
@amanda-- absolutely. will be there soon.

**Comment by amanda--** [comment]
@bodymovin 

Hi,

A new issue we've got:
We use the 'onEnterFrame' to manually change the preserveAspectRatio. This works when autoplay is set to true. When set to false it doesn't.

Is there another event we can use? Like when the svg is loaded?

Thank you again!

**Comment by bodymovin** [comment]
there is a new event coming. I'll upload it this weekend.
for now you can manage listening to the event "config_ready".
After that event is triggered, the svg element will be present after the thread is complete so you could do:
setTimeout(changeSvgProperty,0);
let me know if it's not clear.

**Comment by amanda--** [comment]
Thanks!

Good to know, we are not in a hurry, we'll check next week.

For now it works when setting autoplay to true and using a stop.

**Comment by bodymovin** [comment]
@amanda-- hi! I've uploaded the new event. It's called "DOMLoaded"

**Comment by amanda--** [comment]
@bodymovin Thank you!

Unfortunately I can't get it to work with the setAttribute preserveAspectRatio to none. 
When using DOMLoaded it just keeps the aspect ratio as it originally is.

**Comment by bodymovin** [comment]
@amanda--  that's strange. it's working on my side.
do you have a link I can take a look at?

**Comment by amanda--** [comment]
@bodymovin http://codepen.io/amandavannoordenne/pen/NxmdNe

- it works when you change DOMLoaded to onEnterFrame. But in my project that causes problems I can't reproduce on codepen.

**Comment by bodymovin** [comment]
@amanda-- You should use it like this:
anim.addEventListener('DOMLoaded',function(){});
I will for next release.

**Comment by amanda--** [comment]
Thank you!

It works on my codepen, but in our project it still doesn't, while I'm doing the same thing.
I'll go and try to figure out why...

**Comment by bodymovin** [comment]
@amanda-- make sure you have the latest player

**Comment by amanda--** [comment]
Yes I have. I think it's an issue in combination with React.

**Comment by bodymovin** [comment]
I see. Let me know if I can help you with anything.

**Comment by ZachSaucier** [comment]
+1 on this request. `DOMLoaded` seems to have been removed...?

Instead, I do this right before calling `anim.play()`

**Comment by bodymovin** [comment]
DOMLoaded was not removed. Is it not firing?

**Comment by Sandstedt** [comment]
I would also like a setting to change from `"preserveAspectRatio","xMidYMid meet"` to `"preserveAspectRatio","none"` instead of a event lissener. For now I used changed the source code in the player. Example: http://codepen.io/sandstedt/pen/vKWzWE and player: http://codepen.io/sandstedt/pen/ZOarxj

**Comment by bodymovin** [comment]
I will add the possibility to override the default value later today.

**Comment by Sandstedt** [comment]
Amazing! Please tell me if you want some help with testing, documenting or anything else.

**Comment by bodymovin** [comment]
I've included a rendererSettings object param where you can override the preserveAspectRatio param, like so:
`var animData = {
        container: document.getElementById('bodymovin'),
        renderer: 'canvas',
        loop: false,
        autoplay: true,
        path: 'data.json',
        rendererSettings:{
                preserveAspectRatio:'none'
        }
    };`

**Comment by Sandstedt** [comment]
Works great, thanks!

**Comment by amanda--** [comment]
@bodymovin Thank you! Finally got around to refactor my project to the lastest version and this works perfectly.
