### ISSUE TITLE
How do you loop a single segment and not all segments?

### ISSUE THREAD

**Issue by amirmishani** [bodymovin/bodymovin#581]
I have several icons that have an intro animation [0,20] where they get drawn in and a loop animation [21, 100] for when you hover over the icons. Setting loop to true will make all my segments loop which is not what I want, I only need one of the segments to loop. Anyway do this?

Here's an example of how I have my code setup:

```javascript
var data = {
          container: el,
          renderer: 'svg',
          loop: false,
          autoplay: false,
          path: 'data.json'
        };

var anim = bodymovin.loadAnimation(data);

anim.addEventListener('DOMLoaded', function(e) {
        anim.playSegments([0,20], true); // run intro animation
});

el.addEventListener('mouseover', function(e) {
        anim.playSegments([21,100], true); // run loop animation
});
```

**Comment by amirmishani** [comment]
I wish there was a way to simply pass a flag to playSegments or may be a new method like loopSegments but here's my workaround if anyone is interested:

I basically load the same animation into two elements that are placed on top of each other. The two DOM elements are toggled via CSS for default and hover modes. The only difference is that I manipulate the data object and change the loop to true for the hover effect.

**Comment by bodymovin** [comment]
You can do anim.playSegments([[0,20],[21,100]],true) and it will loop only the final segment.
You can also set directly the "loop" property to false/true on the animation instance.

**Comment by bodymovin** [comment]
To set a new segment you need to wait for the animation to be loaded, that's why the first invocation isn't working.
you can use `this.playButtonAnimator.addEventListener('DOMLoaded',()=>{})`
For the rest of the issue, can you post a working implementation?

**Comment by pratapbunga** [comment]
@bodymovin - I was hoping for a similar fix while playing the reverse onClick but seems like it directly jumps to the last segment in it and starts looping without playing the first segment. It happened only in reverse(direction: -1), but during forward it is working fine for me.
```
anim.playSegments([[96,129], [76, 96]], true);
anim.setDirection(-1);
```

**Comment by Air-Sidney** [comment]
element.animation.playSegments([0, 79], true);

function loop() {
console.log('Loop start');              
element.animation.playSegments([79, 639], true);
}
element.animation.addEventListener('complete', loop);

**Comment by ManuelGuerreroVana** [comment]
> You can do anim.playSegments([[0,20],[21,100]],true) and it will loop only the final segment. You can also set directly the "loop" property to false/true on the animation instance.

That does not work sir.
