### ISSUE TITLE
How do I reduce the volume of generated JSON files?

### ISSUE THREAD

**Issue by JayZangwill** [bodymovin/bodymovin#582]
The JSON file exported by AE is too large. Is there any way to reduce its size?
Because if you use this large volume of JSON files in the web project, it's too heavy.

**Comment by bodymovin** [comment]
Can you serve it gzipped? It reduces the size significantly.

**Comment by Tchidu** [comment]
Hi,
Recycling this post. I'd like to know what is the basis that determines the file size.
Right now I'm rendering a 500x500px composition containing just AE shapes to SVG.
I got a .json of 462kb. I'd lik to know  if this is the regular size or if I can reduce it.
When I render the composition, the 462kb json file is generated before the gzipped player.

Somebody told me that 462kb is too heavy to have on codes.
ps: I'm not on codes!

Thanks! Awesome project you guys have been done!

**Comment by bodymovin** [comment]
You should server the json file gzipped as well. It will reduce it's filesize considerably.
Regarding what determines the file size, is mainly:
- number of keyframes
- number of layers / shapes

**Comment by Tchidu** [comment]
Great To know. Thanks!
Just one more thing, how do I export the .JSON file also gzipped? I just have the option to select the player gzipped.

**Comment by bodymovin** [comment]
You can't in the plugin, you need to do it with a js module or directly in your server

**Comment by Tchidu** [comment]
Is it necessary a lot of coding knowledge to accomplish that?
I mean, I know few basics concepts about html, css... but nothing about
javascript.
But if it's something not too complicated i'm really into it to get small
data sizes!

Also, I'm having some issues with resources I use from After Effects and
would like to know if some of then in fact don't work within the Bodymovin.

For text, I'm using museo sans 700, and using text animation with
properties of position, opacity and skew. The timing is working perfectly,
but some letters are surpassing their space and going backspaced,
interlacing with previows letters. I'm also using rotation in the text
layer transformations. Is there something with the font file I'm using?
It's an .otf file

Another issue I'm having is animating stard and end point of gradient
strokes. They just don't work. Is it supported by Bodymovin?
The thing that bothers me that maybe I'm doing something wrong is that it
works on google chrome, but not in safari.

That's it for today hehe.
Please tell me if it's not ok to ask this questions in this topic about
.json size file.

Thanks!

**Comment by bodymovin** [comment]
I'm uploading a couple of text fixes by today, you should check with the next version tomorrow.
Regarding gzipping, it should be easy to do, and there's probably a servico online to do that free.
But do you know how to set your headers in the host you'll use?
