### ISSUE TITLE
hi~ Will 'data-name' invalid is how is it?

### ISSUE THREAD

**Issue by HUIL012** [bodymovin/bodymovin#583]
**Tell us about your environment**

* **Browser and Browser Version:Google Chrome60.0.3112.90**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, not sure I understand the issue.
Can you elaborate on it?

**Comment by HUIL012** [comment]
**Required** 
. a class called "bodymovin" . a "data-animation-path" attribute with relative path to the data.json 
**Optional** 
. a "data-anim-loop" attribute . a "data-name" attribute to specify a name to target play controls specifically 
------------------------------------------------------------------
Is there any example of this format?
"data-name" is not quite clear.
thanks!
