### ISSUE TITLE
Loading multiple animations from the same animationData object error

### ISSUE THREAD

**Issue by saferthanhouses** [bodymovin/bodymovin#584]
**Tell us about your environment**

* **Browser and Browser Version:**
Chrome 59.0

* **After Effects Version:**
Unknown AE Version

I'm not sure if you are aware of this but I thought I would raise it here as this stumped me for a while and maybe the documentation could make this a bit clearer:

I was trying to create multiple instances of the same animation on the same page. When using the 'path' property this works fine, but when using the 'animationData' property everything started breaking. It works when i point each instance to a copy of the object, but i was passing them all references to the same object.

Doesn't work:
```javascript

const container = document.querySelector('div.container');
let bodymovinData = {...}
for (let i = 0; i < 30; i++) {
            let div = document.createElement('div');

            div.id = `bodymovin-${i}`;
            Object.assign(div.style, {
                width: "50px",
                height: "50px",
            });

            container.appendChild(div);

            var animation = bodymovin.loadAnimation({
                container: document.getElementById(`bodymovin-${i}`),
                renderer: 'svg',
                loop: true,
                autoplay: true,
                animationData: bodymovinData,
            })
```

Works:
```javascript

const container = document.querySelector('div.container');

for (let i = 0; i < 30; i++) {
            let div = document.createElement('div');

            div.id = `bodymovin-${i}`;
            Object.assign(div.style, {
                width: "50px",
                height: "50px",
            });

            container.appendChild(div);

            let bodymovinData = {...}

            var animation = bodymovin.loadAnimation({
                container: document.getElementById(`bodymovin-${i}`),
                renderer: 'svg',
                loop: true,
                autoplay: true,
                animationData: bodymovinData,
            })
```

I'd be happy to make a pr for the documentation to make this clearer.

Cheers & thanks for all your great work.

**Comment by bodymovin** [comment]
Hi, you're right, the same animation data can't be used in more than one animation.
I'll make a note about clarifying that on the next update.
It's also on my pipeline to amend this.
thanks!
