### ISSUE TITLE
Resizing multiple animations on the same page

### ISSUE THREAD

**Issue by jancbeck** [bodymovin/bodymovin#587]
I have three animations that I'd like to resize when the window size changes. I use the code below:

 ```
   var anim = []; // collecting animation instances in this array
    /**
     *  Animations
     */
    $('.bodymovin').each(function(index, el) {
    	
		var params = {
			container: $(this)[0],
			renderer: 'canvas',
			loop: true,
			autoplay: false,
			autoloadSegments: true,
			path: $(this).data('path') 
		};

		anim[index] = bodymovin.loadAnimation(params);
		bodymovin.setQuality(1);
		anim[index].playSegments([[1,2],[$(this).data('segment-0'),$(this).data('segment-1')]],true);
	});

	$(window).resize( function(){
		$.each(anim, function(index, el) {
			console.log(el); // this outputs the correct animation instance
			el.resize.bind(el);
		});
	})
```

This will not resize any animation canvases even though I keep a separate instance of each animation in a global array and console.log outputs the correct animation instance. An earlier version was more similar to #106 but was only resizing the last element on the page.

**Comment by bodymovin** [comment]
on your iteration you're binding the resize method to the element but you're not actually invoking the function.
you should do
`el.resize.bind(el)();`
but it would be better if you do the binding outside the window.resize so you're not creating the binding function each time.
````javascript
var anim = []; // collecting animation instances in this array
   /**
    *  Animations
    */
   $('.bodymovin').each(function(index, el) {
   	
   	var params = {
   		container: $(this)[0],
   		renderer: 'canvas',
   		loop: true,
   		autoplay: false,
   		autoloadSegments: true,
   		path: $(this).data('path') 
   	};
   	anim[index] = bodymovin.loadAnimation(params);
   	bodymovin.setQuality(1);
   	anim[index].playSegments([[1,2],[$(this).data('segment-0'),$(this).data('segment-1')]],true);
        anim[index].resize.bind(anim[index]);
   });
   $(window).resize( function(){
   	$.each(anim, function(index, el) {
   		console.log(el); // this outputs the correct animation instance
   		el.resize();
   	});
   })
````

On an unrelated issue keep in mind that the playSegments needs the animation to be loaded in order for it to work.

**Comment by jancbeck** [comment]
Thank you for your quick answer. The edits you suggested now produce the following Uncaught TypeError when resizing the window:

> Cannot read property 'canvas' of undefined

**Comment by bodymovin** [comment]
can you share a link with the code implemented?

**Comment by jancbeck** [comment]
I have sent you the link via email as the site is not yet lanched
