### ISSUE TITLE
Png transparency issue

### ISSUE THREAD

**Issue by re-player** [bodymovin/bodymovin#590]
Hi,

I'm having an issue with png export. I've done tricky pattern for the button, it's about 500 circle shapes in that pattern) And obviously performance & fps were very low in the app.

So, i figured out saving pattern to png (instead of using shapes) might do the trick. And it did :) But when i do export, png looks like this: http://c2n.me/3N1nEwJ.png.

But it should be like that: http://c2n.me/3N1nOXl.png, that's shape-version of pattern. As u can see, only central part of pattern looks fine. In ae shape & png versions are completely the same, no difference at all.

Is there any way to solve this problem? I've attached png file i'm using & ae file.
[png issue - ae file.zip](https://github.com/bodymovin/bodymovin/files/1231902/png.issue.-.ae.file.zip)
![_00082](https://user-images.githubusercontent.com/30260196/29422041-9aa2eda2-837f-11e7-8146-f08a8d18bc67.png)

**Comment by bodymovin** [comment]
Can you replace the exported png file on the images folder with the png you use on your project?
AE sometimes doesn't handle correctly transparency of exported pngs

**Comment by re-player** [comment]
Hi, Hernan)

That's so obvious, how i couldn't figure it out by myself. Thx for so fast reply & ur help :)

p.s.: source png file is also exported from ae. i've just rendred still frame & used it instead of shape-pattern. smth happens after exporting via bodymovin, but anyway i can just replace file & all works fine)
