### ISSUE TITLE
Bodymovin animation not working on device

### ISSUE THREAD

**Issue by abhijittambe** [bodymovin/bodymovin#592]
I have created animation in after effects and redenred it with Bodymovin. Now when i give it to programmer and he call that same jason file in mobile. Animation is not working as it was in after effect.

Need help,

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by abhijittambe** [comment]
Actually i made few changes in the file. now animation is working but
earlier i tried using different compositions in to one file which was not
working on ios. My concern was can we use different compositions in to  one
file

**Comment by bodymovin** [comment]
Yes, you should be able to use precomps in your animation.
Closing for now, reopen if necessary
