### ISSUE TITLE
Can you give an option to export .svg animation file from bodymovin in future?

### ISSUE THREAD

**Issue by Onlypar2** [bodymovin/bodymovin#595]

**Comment by bodymovin** [comment]
What do you mean by .svg animation?
Like an svg strip?

**Comment by Onlypar2** [comment]
Yeah i mean any possibility to export a svg file from after effects?
please go through this link : https://css-tricks.com/guide-svg-animations-smil/
It would be greate if we get after effects animations in css code (svg also) just like animate cc is capable of exporting. It will revolutionize web animations in the entire industry. once please check it out.

**Comment by bodymovin** [comment]
Unfortunately all those options fall short.
- SMIL is not adopted by all browsers and even those that support it have a lot of issues.
- CSS can work for some animations, but it's very limited.
As far as I know, Animate CC exports frame by frame information of the animation, and that's something I'd rather not do. Although it has some advantages, it feels too cumbersome and difficult to interact with.
If this made sense at some point I would consider it but for now it's too much work for little gain.
For now the only way to support many of AE's features is to use Javascript.

**Comment by Onlypar2** [comment]
Yes, ofcourse what you said is absolutely true.
But since css is the interface design code, which loads before javascript, I have found that css animations load faster and occupy less space when compared to the speed at which json files are doing the job. 
also many experts warned me not to use json files in larger numbers.
what would you suggest if i had to make animated icons? is it better to do it in json format or svg?

**Comment by bodymovin** [comment]
Yes, if I could leverage CSS for animations I'd definitely do it.
It runs on a different thread and enables more optimizations by browsers.
But shape interpolation, filter animation, expressions, trim paths, repeaters, parametric shapes, motion paths are impossible to support with CSS.
When the WAAPI, which brings the best of the two worlds together, gets to a more mature state I'll definitely use it as the underlying engine of animations.

**Comment by Onlypar2** [comment]
ok ya got your point. But anyway its a great start to be frank.. will be waiting for much more ! Thank you.
