### ISSUE TITLE
Weird glitch with baked rubberhose comp

### ISSUE THREAD

**Issue by TomHoenderdos** [bodymovin/bodymovin#597]
**Tell us about your environment**
OSX

* **Browser and Browser Version:** 
Chrome 60.0.3112.101, Firefox 54.0.1, Safari 10.1.2

* **After Effects Version:** 2017 -  14.1.0.57

**What did you do? Please explain the steps you took before you encountered the problem.**
Rubberhosed a arm and then baked the expressions to keyframes and then ran bodymovin

**What did you expect to happen?**
The arm should not glitch

**What actually happened? Please include as much _relevant_ detail as possible.**
Arm glitches randomly... Everytime we reload the arm glitches somewhere else

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Arnold only.zip](https://github.com/bodymovin/bodymovin/files/1251878/Arnold.only.zip)
(demo.html is included)

**Comment by bodymovin** [comment]
try using
`anim.setSubframe(false)`
Since all the animation keyframes are baked, some intermediate position are probably breaking.
