### ISSUE TITLE
Invalid value for <path> - mask issue

### ISSUE THREAD

**Issue by afdavies** [bodymovin/bodymovin#6]
Hi there,

I'm using an inverted Add Mask in my comp, but when I load in the JSON, inspector's throwing this error: 

`Error: 
Invalid value for <path> attribute d="M0,0 hundefinedvundefinedhNaNvNaN M659.75,505.75 C634.483,505.75 614,526.233 614,551.5 C614,576.767 634.483,597.25 659.75,597.25 C685.017,597.25 705.5,576.767 705.5,551.5 C705.5,526.233 685.017,505.75 659.75,505.75"`

Without the mask it works like a charm (this is a fantastic piece of work, by the way), but I'd love to get this hammered out, since that mask's a key part of animation. 

Thanks!

**Comment by bodymovin** [comment]
Hi are you using the canvas renderer or the svg?
would you send me the .ae project or the exported json to my email?
hernantorrisi@gmail.com

**Comment by afdavies** [comment]
I'm using svg - I'll send the files in a moment. Thanks!
