### ISSUE TITLE
AE CS6 

### ISSUE THREAD

**Issue by deborabm** [bodymovin/bodymovin#60]
Hey,
I'm trying to install it in CS6, but its not working.
Is it compatible?

**Comment by bodymovin** [comment]
hi!
no, only CC2014 and up unfortunately

**Comment by graphiclaboratory** [comment]
toobad -;)

**Comment by tslater** [comment]
Would it be hard to support AE6? If I was given some tips, I might be able to try a PR.

**Comment by bodymovin** [comment]
@tslater The problem is that AE6 doesn't support CEP panels, so the whole UI would need to be done again
