### ISSUE TITLE
CDN doesn't point to the newest Bodymovin version

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [bodymovin/bodymovin#602]
Go to the CDN:
https://cdnjs.com/libraries/bodymovin

I went to the CDN above, to get the script tag for the latest version of Bodymovin, which at the time of this writing is 4.10.**3**

The CDN only has 4.10.**2**

**Comment by timdoes** [comment]
This is still the case

**Comment by bodymovin** [comment]
Yes, it was a version issue.
Fixed now with version 4.11.0

**Comment by monkeydri** [comment]
is there a CDN for newest 5.*.* versions ?
