### ISSUE TITLE
need information regarding renderer: 'pixi option

### ISSUE THREAD

**Issue by karthickvkumar** [bodymovin/bodymovin#614]
Hi @bodymovin,  I would like to know about the `renderer: 'pixi ` whether this will use the pixi js renderer technique or else it will create a pixi js canvas?

**Comment by karthickvkumar** [comment]
closing due to no response

**Comment by bodymovin** [comment]
Sorry for the delay.
I'm travelling and I'm having a hard time answering issues.
Will be responding next week.
the pixi renderer was an experiment and it was creating a pixi js canvas. But I never got as far as I wanted with it.

**Comment by karthickvkumar** [comment]
thank @bodymovin
