### ISSUE TITLE
RubberHose2 Preset Styles Not Exporting Correctly.

### ISSUE THREAD

**Issue by sifford** [bodymovin/bodymovin#618]
**Tell us about your environment**
1 main composition(hand and dog) with 1 pre-comp(dog animation) inside of it.

* **After Effects Version:**
AE CC 2017 v14.2.1
Bodymovin v4.10.2
Rubberhose2 v2.05

**What did you do? Please explain the steps you took before you encountered the problem.**
I'm trying to make a short animation of a dog that is ancy for a ball. The 4 legs are made of 4 rubber hoses with the Tapered Hose style. Everything looks fine, but the legs get split up into 3 lines when I export the comp with bodymovin. I have noticed this with the other pre-styled hose selections as well. The only one that exports fine is the Base Hose. I ensured that I had the latest versions of everything and that I had the guide and hidden options checked prior to exporting.

**What did you expect to happen?**
I expected the legs to look and behave normally as in the comp preview within After Effects/

**What actually happened? Please include as much _relevant_ detail as possible.**
Rubber Hose legs with tapered as well as other premade styles do not export correctly. I have no idea. Please see my comp I've attached. demo.html file is included so you can see what's happening.

[Desktop.zip](https://github.com/bodymovin/bodymovin/files/1291802/Desktop.zip)

Any help is greatly appreciated! Thanks!!

**Comment by bodymovin** [comment]
Hi, unfortunately tapered hoses are not supported by bodymovin.
The rubberhose site has more detailed information on what is supported.

**Comment by sifford** [comment]
Ok. Thank you!
