### ISSUE TITLE
What about using SMIL to export animations? 

### ISSUE THREAD

**Issue by Emasoft** [bodymovin/bodymovin#62]
Have you considered using SMIL for exporting SVG animations? It is much better for synchronization, and does not have the troubles of webanimations (still lacking support).

P.s.
Do not listen to those who say that SMIL was deprecated... It is not. It is just polyfilled by some browsers using webanimations.

**Comment by bodymovin** [comment]
@Emasoft My first version exported to SMIL and I was very pleased with the result.
All those rumors about deprecation made me put that renderer on hold.
Besides, right now the plugin supports AE expressions and some other features that don't translate to SMIL capabilities; so it would need an hybrid solution nonetheless.

**Comment by AndreaMonzini** [comment]
For now SMIL seems well supported !

https://caniuse.com/svg-smil

**Comment by Antiokh** [comment]
I vote for this! SVG-SMIL or SVG+CSS are requirements-independent solution.
