### ISSUE TITLE
Missing Color and rotation on paths

### ISSUE THREAD

**Issue by Smus** [bodymovin/bodymovin#623]
Hi

Our designer uses AE to exporter some moving objects. When I use the data.json fil in my html/js, the colors are black, and the rotation of all paths have been set to 0.

Is there somkind of setting we are forgetting to check for this to get exported aswell?
My JS looks like this:

```
var animData_MapMain = {
    container: document.getElementById('MapMain'),
    renderer: 'svg',
    loop: true,
    autoplay: true,
    path: 'json/MapMain/data.json'
};

var anim_MapMain = bodymovin.loadAnimation(animData_MapMain);;
window.onresize = anim_MapMain.resize.bind(anim_MapMain);
```

**Comment by bodymovin** [comment]
Not sure but sounds like you're using an old version of the player
Can you share a link so I can check?

**Comment by Smus** [comment]
aaahh yes, that helped alot!.. it must have been an old version I had.
