### ISSUE TITLE
Bodymovin shows wilder animation

### ISSUE THREAD

**Issue by ashussen** [bodymovin/bodymovin#626]
Hi, 

We have created some animation with Body Movin, all of them works great.
The problem we have now is, the Body Movin animation animate really wild compared to what it supposed to animate.

Original Animation:
![shaking](https://user-images.githubusercontent.com/5305258/30529211-7571b654-9c7e-11e7-919b-a48f1a9b2b77.gif)

Bodymovin Animation:
![shaking-fail](https://user-images.githubusercontent.com/5305258/30529217-86e2e282-9c7e-11e7-8c86-b7bb69176e96.gif)

You can test and play around here:
https://codepen.io/albertdp/project/editor/AmbRgM

Please let me know if you ever encounter the same issue.

**Comment by sowmyy** [comment]
Its working perfectly fine for me

**Comment by colinbrandt** [comment]
Looks good to me as well (Chrome, MacOS)

**Comment by ashussen** [comment]
@sowmyy @colinbrandt Thank you for your response.
We figured out that we used After Effect function to let it shake randomly `wiggle()` function.

This leads to unexpected movement in the bodymovin generated files.

Our solution is we modify how it behave manually. Instead of using `wiggle()` function, we move it slightly frame by frame.

**Comment by bodymovin** [comment]
Yes, unfortunately wiggle is difficult to reproduce and for now it's just a placeholder.
It doesn't work as expected indeed.
