### ISSUE TITLE
Rendering makes strange frames. 

### ISSUE THREAD

**Issue by luminousdot** [bodymovin/bodymovin#627]
* **Windows 10**

* **Chrome latest update**
* **After Effects latest update CC 2017:**

* **Render with bodymovin**

* **Render the thing**

* **Render is cutting the composition to some specific dimensions, that don't exsist in the files I'm using

**

**Please provide a download link to the After Effects file that demonstrates the problem.**
![screenshot_2](https://user-images.githubusercontent.com/4018312/30549554-5d5a9542-9c95-11e7-8e57-230f8e06a509.png)
![screenshot_3](https://user-images.githubusercontent.com/4018312/30549581-6995348e-9c95-11e7-9a1d-db4fddee37dd.png)

**Comment by bodymovin** [comment]
Are you masking strokes?
Browsers don't handle well masked strokes. You'll need to add a transparent shape with a fill that covers the whole surface of the stroke

**Comment by luminousdot** [comment]
No, not masking. I'm using trim paths to draw strokes from end to start.

**Comment by luminousdot** [comment]
When I start it all works fine, than somewhere during the work it starts croping the area of a stroke, and it wont go back to normal. I', forced to do it all over again, and I can't get it when does it start to behave like this, and if I'm doing something that triggers the crop.

**Comment by luminousdot** [comment]
Found it! If you add fill effect, it brakes the svg path. So instead, you need to edit the content fill/stroke. 
Yea! Thanks for helping out. Hope this will helpful to someone else in the future.

**Comment by bodymovin** [comment]
Right fill effect also does that.
Good catch.
