### ISSUE TITLE
Error with the version 4.0.7

### ISSUE THREAD

**Issue by shokrizorid** [bodymovin/bodymovin#63]
Hello,

I have exported an animation with bodymovin v4.0.7 but I have this error when the animation is loading:

TypeError: v[f].pt.k is undefined

Do you know why I have this? I attached my animation contact.json

Thank you

**Comment by bodymovin** [comment]
@shokrizorid hi! can you send me the .ae so I can check it?
Did it work with the previous version?

**Comment by shokrizorid** [comment]
Element are in french, but if you have any question please feel free to ask me.

**Comment by shokrizorid** [comment]
The file is in french, but if you have any question feel free to ask me !
http://infinit.io/_/3mR6FZR

**Comment by bodymovin** [comment]
no problem.
je parle francais :)

**Comment by shokrizorid** [comment]
Haha, super !

Concernant mon fichier ae, j'ai rencontré quelques soucis au niveau des compositions. Par exemple, je ne peux pas coller plusieurs compositions dans 1 seul... Du coup j'ai dû utiliser des masques.

Sinon, j'ai remarqué un truc étrange aussi, si tu colles côte à côte 2 compositions, bodymovin laisse à l'export 1 micro pixel entre les 2... Ce qui explique mes petits rafistolages de 1px.

**Comment by bodymovin** [comment]
@shokrizorid j'ai essayé exporter ton projet et ca marche bien.
As tu mis a jour le bodymovin.js player aussi?
Veux-tu m'envoyer un lien?

**Comment by AntoineW** [comment]
Voici l'erreur exact : 
`15:08:50,772 TypeError: t[a].ks.k is undefined
s() bodymovin.js:1
s() bodymovin.js:1
t() bodymovin.js:1
t() bodymovin.js:1
a() bodymovin.js:1
t() bodymovin.js:9
AnimationItem.prototype.waitForFontsLoaded</<() bodymovin.js:9
AnimationItem.prototype.configAnimation() bodymovin.js:9
AnimationItem.prototype.setParams/i.onreadystatechange() bodymovin.js:9
1 bodymovin.js:1:6488
`

L'animation est appelée comme ceci : 

`bodymovin.loadAnimation({
	container: layout.find('.section-contact .animation-container').get(0),
	renderer: 'svg',
	loop: false,
	autoplay: false,
	path: WRK.tpl_dir+'/anim/process-transition.json'
});`

Les animations exportées avec l'ancienne version du plugin AE fonctionnent bien, que ce soit avec le nouveau ou avec l'ancien player JS. Mais les nouvelles animations ne fonctionnent plus.

**Comment by bodymovin** [comment]
Je vais t'envoyer cet apres-midi un lien avec ton animation marchant avec le player 4.0.7.
Si tu as un lien ou ca ne marcha pas, passe-le moi s'il te plait.

**Comment by bodymovin** [comment]
@shokrizorid @AntoineW 
J'ai créé un lien avec votre animation:
http://codepen.io/airnan/details/NxVQWV/
Je n'ai pas vu l'erreur mais j'ai vu le pixel qui sépare les compositions.
J'ai corrigé une erreur que ne montrait pas bien le layer "Bloc rose central". Vous pouvez télécharcher le nouveau build.
Mais l'autre erreur du pixel doit etre un arrondissement que fait le browser.
Je vais rechercher un peu plus.

**Comment by shokrizorid** [comment]
Merci pour la correction :) Je fais comment pour le télécharger le fichier ?

Par contre est-ce que tu peux juste retirer l'animation de codepen stp ? Car c'est une animation qui provient d'un projet encore confidentiel ^^

**Comment by bodymovin** [comment]
@shokrizorid effacée. excusez moi.
vous pouvez le télécharger d'ici, github.

**Comment by AntoineW** [comment]
Voici un exemple qui reproduit l'erreur que nous avons : http://codepen.io/anon/pen/xZomzX

L'animation ne se joue pas et nous avons l'erreur JS "TypeError: e.k is undefined"

**Comment by bodymovin** [comment]
@shokrizorid cette animation est exportée avec la version 3.x et le player est version 4.x
elles ne sont pas compatibles. C'est pour cela que ca ne marche pas.
Vous devez faire l'installation de la derniere version du plugin et exporter les animations a nouveau.
désolé :/

**Comment by shokrizorid** [comment]
Comment ça se passe la mise à jour du plugin ? 
Car j'a utilisé la méthode "option 2" : 
_"Install the zxp manually following the instructions here: https://helpx.adobe.com/x-productkb/global/installingextensionsandaddons.html
Jump directly to "Install third-party extensions"_

**Comment by bodymovin** [comment]
meme methode avec le dernier fichier .zxp
as-tu essayé et ca n'a pas marché?

**Comment by shokrizorid** [comment]
Oui, j'ai pris le fichier .zxp de la version 4.0.9 dernièrement et lorsque je fait la commande /list all il m'affiche toujours la version 1.0.0.0.

Je vais retenter de suite avec la version 4.0.10.

**Comment by shokrizorid** [comment]
On a réussi au final à faire fonctionner notre export avec la dernière version.
Merci pour ton aide. Je t'enverrai l'url du projet une fois le tout terminé.

**Comment by bodymovin** [comment]
merci!
si vous avez besoin de quelque chose d'autre n'hesitez pas.
et excusez mon francais precaire :)
