### ISSUE TITLE
Ever increasing js heap

### ISSUE THREAD

**Issue by colinmeinke** [bodymovin/bodymovin#633]
Firstly, thanks for the fantastic library! I just wanted you to take a look at this recording of js heap size.

![](https://www.dropbox.com/s/1a9y10hzdeb7pvx/Screen%20Shot%202017-09-20%20at%2008.17.15.png?raw=true)

My understanding is probably wrong, but I would have expected on each garbage collection the js heap to be brought down to it's initial size. It is only the forced gc right at the end of the recording that does that. I just wondered what is happening here, why, and if it is expected?

Installed with npm and called like:

```js
bodymovin.loadAnimation({
  container: document.querySelector('.test'),
  renderer: 'svg',
  loop: true,
  autoplay: true,
  path: 'test.json'
})
```

It's a fairly basic animation, the `json` is 94kb (10kb gzipped).

**Comment by bodymovin** [comment]
As far as I know, garbage collector does some heuristics to decide when and what to collect.
As long as the memory usage does return to a base value when forcing the GC, there shouldn't be any memory leaks.
But memory is something I'm always paying attention to and complicated to manage, so I might be wrong.

**Comment by colinmeinke** [comment]
Here's another recording, this time with 5 separate similar animations running simultaneously - so way more happening.

![](https://www.dropbox.com/s/mkn64d5v21e9p7x/Screen%20Shot%202017-09-25%20at%2010.07.56.png?raw=true)

This one more regularly makes it down close to the initial size.
