### ISSUE TITLE
Gradient fill not supported for Android AVD xml?

### ISSUE THREAD

**Issue by colinbrandt** [bodymovin/bodymovin#635]
Bodymovin Version: 4.10.2
After Effects Version: 2017.2

I have a couple shapes that have gradient fills, and they look great in the html file, but are not showing up in Android Studio using the xml file (the shapes simply don't render). Other shapes without gradient fill look great in the xml file, and when I change the gradient fills to regular fills, the shapes do render.

I made sure to save the aep file before rendering out of AE each time.

Are shape layer gradient fills simply not supported when exporting to xml? Is it a matter of importing a certain resource in Android Studio in order to support gradients? If they're not supported, is there a supported method that could "cheat" a gradient effect?

Sorry if this has been covered somewhere, I tried searching and didn't come up with anything.

**Comment by bodymovin** [comment]
Hi, no, unfortunately I haven't looked into gradients for AVD yet.
It's a feature I need to work on.
Not even sure if they are supported in Android vectors.

**Comment by colinbrandt** [comment]
K, thank you for the response!
