### ISSUE TITLE
freezing frame some time 

### ISSUE THREAD

**Issue by thaershabo** [bodymovin/bodymovin#639]
https://drive.google.com/open?id=0BxaRQ7RkdWbqeU5DNHV5R3I2VlE

**windows 7 64 **
* ** Chrome Version 61.0.3163.100 (Official Build) (64-bit)**
* **after effect 13.5.0.347**

**What did you do? Please explain the steps you took before you encountered the problem.**
after rendering my compostion it was not working at the first time after some tweak i relaze that the effect should removed from shape object on after effect so i remove it and reneder it again know its work but the motion stop before it end (freez frame ) and you should refrech browser many time (may be 4 at least) to be played fully 
**What did you expect to happen?**
i think its a problem with server side when comunicate with json file because it work better in local host
'but not perfect' 
**What actually happened? Please include as much _relevant_ detail as possible.**
the consile appear this error how ever it work perfclte even if it appear so may be not the case:
VM137:2 Uncaught TypeError: comp(...).layer(...).effect is not a function
    at r.eval (eval at initiateExpression (bodymovin.js:15), <anonymous>:2:88)
    at r.execute [as getValue] (bodymovin.js:13)
    at GroupEffect.getValue (bodymovin.js:15)
    at IShapeElement.BaseElement.prepareFrame (bodymovin.js:7)
    at ICompElement.prepareFrame (bodymovin.js:9)
    at SVGRenderer.renderFrame (bodymovin.js:5)
    at AnimationItem.renderFrame (bodymovin.js:9)
    at AnimationItem.gotoFrame (bodymovin.js:9)
    at AnimationItem.setCurrentRawFrameValue (bodymovin.js:9)
    at AnimationItem.advanceTime (bodymovin.js:9)

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/open?id=0BxaRQ7RkdWbqeGdiVmtLX0Ywd0U

thank you a lot

**Comment by DaanDirk** [comment]
Can you try it without the text layers on?
The font you chose might not work for bodymovin.

Try converting the text to outlines (right click layer then <create shapes from text>).
That might help.

**Comment by thaershabo** [comment]
thank you mr DaanDirk i solve it from a while its just you can't applay effect on layer you can just animate shape i don't know if it problem in bodymovin or its Capabilities of this add-on 

you are my hero keep moving i will try to be like you
thank you
