### ISSUE TITLE
Incorrect Text Positioning in SVG Renderer

### ISSUE THREAD

**Issue by cpdt** [bodymovin/bodymovin#640]
**Tell us about your environment**

Running After Effects 2017.2 (v14.2.1.34) on Windows with Bodymovin v4.10.1. This issue has occured on both Firefox 57.0a1and Chrome 59.0.3071.109.

**What did you do? Please explain the steps you took before you encountered the problem.**

I have created an animation based on the title sequence from the TV show "Stranger Things". When exporting with Bodymovin and running in a browser, all motion works as expected, however the different pieces of text end up out of alignment.

**What did you expect to happen?**

![Expected Image](https://user-images.githubusercontent.com/16081865/30845238-d9457a82-a2d5-11e7-96b5-1288725afdf7.png)

Here's how part of the sequence appears in After Effects.

**What actually happened? Please include as much _relevant_ detail as possible.**

![Actual Image](https://user-images.githubusercontent.com/16081865/30845288-10f379ac-a2d6-11e7-9a65-d27ba44c8d13.png)

Here's how the image looks exported with Bodymovin and playing in Firefox (Chrome looks the same). Notice how the "TRANGE" and "THINGS" pieces of text are moved to the left.

The issue occurs whether or not the "Glyphs" option is enabled. Additionally, it appears to occur even when the text has no motion or text animation (used to make the letters fly into the screen). The two pieces of text do have different tracking than normal applied -- this may be related, I have been unable to test.

The issue occurs in the SVG renderer. I haven't been able to get either of the other renderers to work at all for this project to test them.

**Please provide a download link to the After Effects file that demonstrates the problem.**

[Stranger Things.zip](https://github.com/bodymovin/bodymovin/files/1332004/Stranger.Things.zip)

The above ZIP file contains the AEP project file and the font used. The issue should still occur without the font, but it's provided in case it does not.

**Comment by cpdt** [comment]
Just noticed that 4.11.0 has "text fixes" listed in the changelog - I'm not able to test if it fixes this issue currently, if it does feel free to close.

**Comment by bodymovin** [comment]
I just tried it and it isn't fixed. I have to see what I can do.
There is a problem with centered text and text tracking.
Can you use the text boxes left aligned instead?
It should fix your issue.

**Comment by cpdt** [comment]
Thanks for taking a look! Unfortunately the text in this is meant to change dynamically with user input, which means that I'll probably need centered text. Although I suppose there is the workaround of left-aligning the text and centering it with an expression, will have to try that.

I'll see if I can wrap my head around the text rendering code and get a fix working.

**Comment by bodymovin** [comment]
fixed and uploaded in version 4.11.1

**Comment by cpdt** [comment]
Can confirm this is fixed - thanks!
