### ISSUE TITLE
Rendering multiple AE animations with bitmaps

### ISSUE THREAD

**Issue by adamdanielczyk** [bodymovin/bodymovin#643]
AE: CC2017 v14.2.1.34
Bodymovin: v4.11.1

Rendering multiple AE animations with bitmaps (so that `/images` directory is created) causes the previously created bitmaps to be overwritten. 

Example:
I have 2 animations to be converted to JSON. First animation has 2 bitmaps, second animation has 1 bitmap.

Rendering first animation will create 2 bitmaps under `/images` directory:
- `img_0.png`
- `img_1.png`

Rendering second animation will overwrite previously created `img_0.png`.

Batch rendering will overwrite some of the bitmaps and as a result will incorrectly render in application via Lottie.

Shouldn't Bodymovin check for pre-existing bitmaps?

**Comment by bodymovin** [comment]
on the comp settings you can select Original Asset Names so they will be exported with their AE source names.
Let me know if that helps.

**Comment by adamdanielczyk** [comment]
Haven't noticed that setting before, thanks
