### ISSUE TITLE
Extra frames after rendering animation with 3D layers

### ISSUE THREAD

**Issue by xeroxoid** [bodymovin/bodymovin#648]
Hi, great tool first of all and thanks for the effort!

Experiencing some problems with 3d layers though.

**Tell us about your environment**
This happens in the player as well as in html (Chrome).

* **After Effects Version:**
2017.1 - 14.1.0.57

**What did you expect to happen?**
The rendered animation to look like the AE animation

**What actually happened? Please include as much _relevant_ detail as possible.**
There are frames that are not included in the original AE animation i.e. the complete flipping of the send text as well as some aliasing appears on vectors.

Problem represented:

Original (AE)
![Original](https://media.giphy.com/media/3ohhwoAAlDPLcRU5na/giphy.gif)

Rendered
![Rendered](https://media.giphy.com/media/l378kjHtN3NqIgzE4/giphy.gif)

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/4tmf50x0ct9cejz/send-animation.aep?dl=1

**Comment by xeroxoid** [comment]
Any chance somebody has looked into this issue? Can we mark it as a bug or is it something that is caused by our AE file?

**Comment by bodymovin** [comment]
Fixed on version 4.12.0
Works with the html renderer.

**Comment by xeroxoid** [comment]
Great!
