### ISSUE TITLE
Player controls

### ISSUE THREAD

**Issue by swolfish** [bodymovin/bodymovin#65]
On the start I want to show the last frame of animation and then after some time (trigger) animate it reverse, from last frame to the first. Can I do that?
It's problem to show last frame first. I tried a lot of scenarios, nothing worked.

**Comment by bodymovin** [comment]
@swolfish you can set autoplay to false on the animation params and then do:

anim.addEventListener('DOMLoaded',function(){
    anim.goToAndStop(anim.totalFrames,true);
    anim.setDirection(-1);
    anim.play();
});

**Comment by swolfish** [comment]
'DOMLoaded' helped.
Thank you. :)
