### ISSUE TITLE
CC Bender effect not working

### ISSUE THREAD

**Issue by cristian-d** [bodymovin/bodymovin#656]
Hi,
Is there a chance you could enable CC Bender effects?
Here's the link to an aep with it: https://drive.google.com/open?id=0Bwco1Jd1EttKcV9xQjhzSU1aRFE
The resulted bodymovin template doesn't have the wobbling effect, using version 4.11.1

**Comment by bodymovin** [comment]
Hi, unfortunately simulating those type of raster effects is really complicated using svg, or canvas.
