### ISSUE TITLE
Could not create outlines from selected characters.

### ISSUE THREAD

**Issue by andy-kelly** [bodymovin/bodymovin#66]
> After Effects warning: Could not create outlines from selected characters. ( 26 :: 0 )

When trying to render my composition I get this error part of the way through the process of converting the type to outlines. I then have to hit cancel on the bodymovin render and get the following error:

> Unable to execute script at line 78. null is not an object

I then have to hit cancel again to close bodymovin.

The typeface I'm using is Myriad Pro.

Any help would be greatly appreciated!

**Comment by bodymovin** [comment]
@andy-kelly I've seen this issue only with terminal fonts.
What font file do you have? .ttf or .otf installed?

**Comment by andy-kelly** [comment]
They're the standard .otf files that come installed on OSX. I haven't tried with any other typefaces yet!

**Comment by bodymovin** [comment]
@andy-kelly are you using any special characters or a basic character set?

**Comment by andy-kelly** [comment]
Just upper and lowercase characters, space, and period.

**Comment by bodymovin** [comment]
ok I'll have to try that font.

**Comment by andy-kelly** [comment]
Aha, I figured it out! I think I was using soft returns (shift and return) rather than hard returns. Once I turned them into hard returns it rendered!

**Comment by bodymovin** [comment]
@andy-kelly nice! I'll take it into account for next build.

**Comment by andy-kelly** [comment]
I'm now having a different issue where only the first 3 seconds of my comp play and only one element of the animation appears.

**Comment by bodymovin** [comment]
can you send me the .ae and the exported .json so I can take a look?

**Comment by andy-kelly** [comment]
Just sent you an email, thanks!

**Comment by bodymovin** [comment]
@andy-kelly unfortunately you are using some things that aren't supported yet by the plugin:
- There is a repeated expression using velocityAtTime, that is not yet in production, and that's what's breaking the animation. It's almost ready but not there yet.
- fill effect is not supported. You need to change shapes fill on the contents if you need to change the color.

**Comment by andy-kelly** [comment]
Thanks for your help. I was planning on creating a simpler version for HTML5 use anyway so I should be able to get by without the expression & fill effects.

Thanks again!

**Comment by IlyaMelnix** [comment]
Hi!

Having the same issue as @andy-kelly when tryiing to export a sequence. 
Unfortunately, replacing all returns by hard returns didn't help.

Here are some screenshots:
![2017-01-13_21-17-37](https://cloud.githubusercontent.com/assets/10106291/21940523/d67f49e6-d9d5-11e6-8c54-d068d0098af5.png)
![2017-01-13_21-18-24](https://cloud.githubusercontent.com/assets/10106291/21940524/d67fd9b0-d9d5-11e6-8ae1-1dad0a88b500.png)

Yours faithfully,
Awaiting Response,
Ilya

**Comment by bodymovin** [comment]
@IlyaMelnix Hi, could you share the project so I can take a look? (and the fonts if necessary)

**Comment by IlyaMelnix** [comment]
@bodymovin The project is on your email, thank you very much for the speed and willingness to help :)

**Comment by bodymovin** [comment]
@IlyaMelnix There is a non breaking space in your text layer at the end off the sentence after the final dot.
"Beauty Etcetera is a sales distribution engineering company that assists niche brands to establish and expand a viable business internationally or domestically in today’s haphazard market. "
If you remove that extra space, everything will work.
I will have a fix for this on the next version.

**Comment by IlyaMelnix** [comment]
@bodymovin Yes, it has helped, thanks a lot!
P.S. The plugin is very useful, great job!

**Comment by majidawan** [comment]
Hi, I am getting the same error. Using the latest version of bodymovin.

I tried hard returns and removed extra spaces and special characters with no luck. Please help.

thanks
Looking forward to your response.
Majid


![1](https://user-images.githubusercontent.com/17173619/31048609-b113a932-a5ee-11e7-915f-5f158e370b4b.png)

![2](https://user-images.githubusercontent.com/17173619/31048610-bbb4a206-a5ee-11e7-8aec-d8b8b85f081c.png)

**Comment by rcdbandit** [comment]
i'm facing a similar issue....could you plzz help me?

**Comment by bodymovin** [comment]
@rcdbandit what font are you using?

**Comment by rcdbandit** [comment]
roboto regular

**Comment by bodymovin** [comment]
@rcdbandit can you share the .aep?

**Comment by rcdbandit** [comment]
sure...i'll mail it

**Comment by rcdbandit** [comment]
i've mailed it

**Comment by bodymovin** [comment]
@rcdbandit it's a problem with tabs.
On your precomp "precomp1", the layer "0312" has tabs on the text.
Next release won't break when text has tabs, but I still need to figure out how to support them.
Meanwhile, can you use 4 textboxes instead?

**Comment by rcdbandit** [comment]
okay...thanks

**Comment by victoria-clover** [comment]
Hi, I'm having the same problem with fontawesome.

**Comment by bodymovin** [comment]
@victoria-clover can you share the .aep?

**Comment by victoria-clover** [comment]
@bodymovin I fixed this by creating a shape from the text.

**Comment by volkanalkilic** [comment]
Same here with this text;

DirectoryInfo d = new DirectoryInfo(@"C:\Users\volka\OneDrive\Belgeler\Allavsoft\Download");
FileInfo[] infos = d.GetFiles();
foreach (FileInfo f in infos)
{
	File.Move(f.FullName, f.FullName.Replace("azure-event-hubs-dotnet-developers-fundamentals-", ""));
}

**Comment by volkanalkilic** [comment]
Same here with this text;
DirectoryInfo d = new DirectoryInfo(@"C:\Downloads");
FileInfo[] infos = d.GetFiles();
foreach (FileInfo f in infos)
{
	File.Move(f.FullName, f.FullName.Replace("azure-event-hubs-dotnet-developers-fundamentals-", ""));
}

**Comment by bodymovin** [comment]
@volkanalkilic can you share the .aep and font if necessary?

**Comment by limmmx3** [comment]
![2021-06-22 18_01_02-Window](https://user-images.githubusercontent.com/73275965/122905526-e02aa600-d383-11eb-9a7f-d31aeb0f7e27.jpg)
Anyone can help me with this?

**Comment by limmmx3** [comment]
whenever I render my project in bodymovin it comes out like this

**Comment by bodymovin** [comment]
@limmmx3 unfortunately there are certain fonts that can't be converted to shapes by AE, so the process breaks. The only other option you can try if it works for your project, is to try exporting them as text instead of glyphs of the bodymovin settings panel.

**Comment by WeihangMeng** [comment]
I got the same problem of created failed. Will it be the problem of some foreign language path and name of pic layer? Is it necessary to keep all the layers' names and the path in English?

**Comment by WeihangMeng** [comment]
![image](https://user-images.githubusercontent.com/17758367/124110624-01ce1080-da9b-11eb-8b3b-a7aa7f56f07d.png)

**Comment by bodymovin** [comment]
@WeihangMeng AE can't convert some fonts to shapes, you can try on your own project, by right clicking a text layer and select convert to shapes.
