### ISSUE TITLE
SVG very slow in Safari

### ISSUE THREAD

**Issue by a2rpriest** [bodymovin/bodymovin#661]
I love Bodymovin! However, I have found that many times Safari becomes extremely slow while playing files with the renderer set to SVG. They work great in Chrome. But in Safari some frames play well, and others come to a halt only refreshing once every second or so. 

Any ideas why this is? 

Thanks for your help!

**Comment by bodymovin** [comment]
Hi, it depends on what svg features you're using.
can you share an .aep so I can take a look?

**Comment by a2rpriest** [comment]
Sure, here is the file. I'm guessing it has to do with the Alpha Mattes I'm using, and the amount of layers. Thanks for your help!
[PB 4.7 Ads Animation - GIT.aep.zip](https://github.com/bodymovin/bodymovin/files/1369505/PB.4.7.Ads.Animation.-.GIT.aep.zip)

**Comment by bodymovin** [comment]
yes, alpha mattes are performance killers.
Can you use a regular AE mask instead?

**Comment by a2rpriest** [comment]
Yes, I can. Just takes longer. I'll do that now and see how it works. Thanks!

**Comment by a2rpriest** [comment]
Yep, that was the problem. Bummer that doesn't work better. Oh well. Thanks for your help! Amazing work you're doing.

**Comment by bodymovin** [comment]
Yes, I hope browsers will improve their game when it comes to filters and masks in svg.
