### ISSUE TITLE
Issues with Gradients exporting

### ISSUE THREAD

**Issue by kerrylofton** [bodymovin/bodymovin#668]
I know this has been asked a million times but I am having trouble with gradient colors exporting. I made sure I was using gradient fill and not an effect. Made sure to save the project before exporting. Followed every advice I could find on this forum with no luck. I am working in the latest AE and version 4.11.1 of bodymovin. Please help. I am working on a much bigger projects with TONS of gradients and really need to figure out how to make gradients work.

I am attaching and AE file. The animations are simple because this is just a test project, the much bigger project is confidential but will be using the same things (ease and wizz expressions, etc). Any help is appreciated 

Project DOWNLOAD LINK
 http://dl.fc.media/content/Jobs/Series/2017/OpenHeart/Projects/HeartStory/Sequences/ExportTest.aep?dl=1

**Comment by kerrylofton** [comment]
Nevermind! Ease and wizz was the problem. Solved it by converting the expression to keyframes and it works!

**Comment by kerrylofton** [comment]
Would love for the developer to integrate ease and wizz in future versions

**Comment by bodymovin** [comment]
@kerrylofton ease and wizz should be working.
I'll check the .aep and get back to you

**Comment by bodymovin** [comment]
@kerrylofton are you using it with Bodymovin or Lottie?

**Comment by kerrylofton** [comment]
Using it with bodymovin. I've found that ease and wizz works but not with the gradient. If I put ease and wizz on the gradient layer it doesn't export the correct colors, gradient just comes out black and white

**Comment by bodymovin** [comment]
interesting, I'll check it out.
thanks!

**Comment by kerrylofton** [comment]
thank you! If you find to a way that it does work with ease and wizz let me know. The converting expression to keyframes works for getting it out but makes me very nervous about having to go back and make changes down the line with this big project I am working on.

**Comment by bodymovin** [comment]
@kerrylofton can you reupload the failing .aep so I can reproduce it?

**Comment by kerrylofton** [comment]
Sooooo, as I got to work this morning and tried out the failing comp, it now works with ease and wizz and the gradient! lol No idea why but I promise it wasn't yesterday haha either way, glad that it works now with ease and wizz because that makes the work on this big project ALOT easier. thank you so much for the help and for this great program! I will send you the final project when we're done so you can see how it all came out!

**Comment by bodymovin** [comment]
Nice!
If you run into this issue again please let me know and I will check it out.
