### ISSUE TITLE
Exported Json file does not seem to contain animation

### ISSUE THREAD

**Issue by Diego-F-Aguirre** [bodymovin/bodymovin#669]
**Tell us about your environment**
  Mac OS, High Sierra
* **Browser and Browser Version:**
* **After Effects Version:**
AE CC 2017 (trial version)
**What did you do? Please explain the steps you took before you encountered the problem.**
I did my first animation which exported out correctly and I have been able to use it in my Xcode project. Unfortunately the second animation exports but is blank. I check using the preview which loads the first animation fine but not the second. I also checked in Codepen and I have the same issue, the first animation loads correctly and the second is blank. 
**What did you expect to happen?**
I expected the second animation which is very similar to the first to export a json file with animation.
**What actually happened? Please include as much _relevant_ detail as possible.**
The file contains json but does not play animation. No animation is visible in the bodymovin preview
**Please provide a download link to the After Effects file that demonstrates the problem.**

https://www.dropbox.com/s/mqoy52pt4i3noqr/off.json?dl=0
https://www.dropbox.com/s/cm3ud7h8d975i2n/Clap_Off.aep?dl=0

**Comment by Diego-F-Aguirre** [comment]
Found a workaround... simply start a new AE project from scratch and re-import the assets and re-do the animation. Apparently creating a copy of my first animation and re-ording the animation for the second animation clip caused some kind of error. 

Everything is working though on my newly created animation.

**Comment by bodymovin** [comment]
Hmmm, I'll try to reproduce the issue to fix it
