### ISSUE TITLE
3D layers no rendering  / Pas de rendu avec un calque D 

### ISSUE THREAD

**Issue by Arthurtharaud** [bodymovin/bodymovin#67]
J'ai découvert cette incroyable plugin, il est vraiment génial.
Je voudrais savoir s'il est possible de faire un rendu (export) avec des calques 3D.
Je suis sur cc 2015 et j'essaie le plugin 4.0.10, l'export de calque en 3D ne marche pas. 
Y-a t-il une solution ? Merci

![00-test](https://cloud.githubusercontent.com/assets/17462110/13302987/fa3de438-db4c-11e5-8e18-0be1f6f54728.png)

**Comment by bodymovin** [comment]
peux-tu m'envoyer le fichier?
ca devrait marcher bien avec des layers 3d.

**Comment by Arthurtharaud** [comment]
Bonjour, 
Voici mon fichier test : https://www.dropbox.com/sh/99siz4cagwrmk01/AADxXMs75Bf3Gq4xmvNLVCyMa?dl=0

**Comment by bodymovin** [comment]
j'ai essayé avec ce fichier et tout marche bien. 
Mais je ne vois pas un layer qui s'appele "Calque de forme 1".
Est-ce le meme projet?

**Comment by Arthurtharaud** [comment]
Merci beaucoup, oui c'est le même projet, j'ai renommer les calques. 
Je vais essayer de réinstaller le plugin pour voir si ça marche. 
Je n'ai pas préciser que je suis sur windows 8.
Merci pour tout, c'est un très bon plugin.
