### ISSUE TITLE
Supported feature list

### ISSUE THREAD

**Issue by kissadam** [bodymovin/bodymovin#671]
Hey Bodymovin,

Can you provide a list of usable/supported AE features?

For example I had to experiment and test with the merged paths to find out why they didn't work.
I also had other smaller things that I realised after a couple of hours of research.

I would be mostly interested in really basic things like:
- color support
- transition support
- maybe AE plugin support
etc.

I really hope it's not a big request but it would be helpful for lots of users to know what not to do when animating.

Thank you!

Adam

**Comment by bodymovin** [comment]
Hi, the wiki pages have a list of supported features
https://github.com/bodymovin/bodymovin/wiki/Features
And here is a more complete list of all supported features
http://airbnb.io/lottie/supported-features.html
But merge paths are not really supported, I have to ask them to change that.

**Comment by kissadam** [comment]
thanks!
