### ISSUE TITLE
Wiggle working but jittery

### ISSUE THREAD

**Issue by wedza** [bodymovin/bodymovin#674]
Hello

First, a huge thank for all your work, what you've done is really awesome.

It's the first time I use bodymovin, so sorry if my question is dumb, but I consider this as a bug.

I created an animation with a couple of wiggles, which seems right in After effect. But when I render it with Bodymovin, the wiggle works but is completely jittery.

In after effect, my wiggle values are (1,3), but when I render it seems the wiggle is like (50,20). The correct values from After Effects are in the rendered file, but the wiggle is a lot too faster, [here's what it looks like in after effects, and after the rendering](https://gyazo.com/29222f68a55837f1fbc82891c4a0e09c).

I try to change my browser (chrome and firefox), change my AE version, lower the values of my wiggle manually in the HTML file, but I never get a similar result.

Here is [a link ](https://fromsmash.com/bodymovinisgreat)to the aep file and the result when rendering.

And again, huge thanks for all your work.

**Comment by bodymovin** [comment]
Hi, unfortunately wiggle is not easy to replicate and for now it works as a placeholder so the animation doesn't break.
You're not doing anything wroing on your side, it's just not well supported in the library yet.

**Comment by wedza** [comment]
That's ok, I understand that this feature is really hard to reproduce, I will do without

Good luck to continue the development, and hoping we have this feature in the future :)

**Comment by jorjani1** [comment]
u can make key frame from your wiggle
