### ISSUE TITLE
Warning: unreachable code after return statement in FontManager.js

### ISSUE THREAD

**Issue by Adam16** [bodymovin/bodymovin#677]
Double return statement in utils/FontManager.js function createHelper

`
return tCanvasHelper;
return tHelper;
`

https://github.com/bodymovin/bodymovin/blob/486b6fc8581927d23935fa72927a116c43ea4dcf/player/js/utils/FontManager.js#L98

**Comment by bodymovin** [comment]
thanks, fixed in next build 4.11.3
