### ISSUE TITLE
img.png resources not found

### ISSUE THREAD

**Issue by jorgehjr84** [bodymovin/bodymovin#680]
**Working on a mac with macOS High Sierra**

* **Browser and Browser Version:Chrome**
* **After Effects Version:V14.2.1.34**

**I followed the tutorial for exporting using bodymovin on youtube, as well as looked at the examples on Github. **

**I expected my animation to work in an html file **

**I was receiving an error in the console stating that it could not find my image files. I have included a screen shot with the error. (This is not the exact error, I know that path is wrongly formatted, but entered in an incorrect path to get a screen shot and show an example of the error I was receiving)  **
<img width="629" alt="screen shot 2017-10-17 at 10 38 57 pm" src="https://user-images.githubusercontent.com/12106376/31698544-0e024752-b38c-11e7-8b96-7a2c15dcc1a9.png">

**Fix: So obviously this was not an ideal fix, but a fix nonetheless. I added the image files that the browser was unable to locate in an img directory within my project. I then went into the data.json file and edited the assets array to point to these files. 
"assets":[
        {
            "id":"image_0",
            "w":50,
            "h":50,
            "u":"../img/",  <------
            "p":"img_0.png" <-----
        }
After adding the assets into the img directory, and adjusting the assets array in the data.json file, I no longer received the error and everything worked.
**

**Issue: I am assuming that the bodymovin.js source code is generating an incorrect path for these assets and hence when the browser would request the assets, we would get an error.  **

**Comment by bodymovin** [comment]
you can pass a property "assetsPath" to loadAnimation where you can define the absolute or relative path of your asses.

**Comment by jorgehjr84** [comment]
Good to know. I may have overlooked that property in your examples code if it’s there.
