### ISSUE TITLE
Bodymovin plugin not previewing or rendering

### ISSUE THREAD

**Issue by SachaHerszkorn** [bodymovin/bodymovin#686]
Hi,

I followed every steps to install the "Bodymovin package", including the player & the aae plugin ( i installed the plugin via Creative cloud store).

I have a problem with the plugin part. 
Everything is intalled and i did check the "Allow Scripts to Write Files and Access Network" option.
I just made a short animation to test it out, i'm just increasing progressively the size of a circle shape but when i try to preview it in body movin my circle is just static, that's the same when i render my data.json and play it in the browser.

To be sure that the problem was only with AAE i took the data.json from [this codepen](https://codepen.io/airnan/project/editor/ZeNONO) and it worked just fine.

So here is my file if you want to take a look ! 
[animation.aep.zip](https://github.com/bodymovin/bodymovin/files/1399079/animation.aep.zip)

_Using Adobe After Effects CC 15.0.0 (Build 180)_

**Comment by bodymovin** [comment]
Hi, I've tried exporting the animation and it seems to work fine.
Can you share a link where it fails?

**Comment by SachaHerszkorn** [comment]
The player is not failing it's the plugin itself.
Like i said i installed it with the creative cloud store on _adobe After Effects CC 15.0.0 (Build 180)_, but when i try to use the plugin, it does not preview the animation or it render something static ... Maybe it's because of my after effects version ?
This is the data.json i get when i try to export the animation  
[data.json.zip](https://github.com/bodymovin/bodymovin/files/1401896/data.json.zip)

**Comment by bodymovin** [comment]
Can you share the font? It might be related to that.

**Comment by SachaHerszkorn** [comment]
[Here it is !](https://www.dafont.com/stranger-back-in-the-night.font)

But i also tried without text and i'm having the same problem...

**Comment by bodymovin** [comment]
[data.zip](https://github.com/bodymovin/bodymovin/files/1405429/data.zip)
I just tried it and it seems to work fine.
I don't know what could be going on.

**Comment by SachaHerszkorn** [comment]
I think the plugin's bugging not the player, or maybe it's not working with my after effects version _After Effects CC 18 V15.0.0 (Build 180)_ ?

**Comment by bodymovin** [comment]
I have the same config.
It doesn't make much sense that it's not exporting animations.
Is your OS or AE in another language?

**Comment by SachaHerszkorn** [comment]
> Is your OS or AE in another language?

I'm on mac os maybe this is not the right version that is on the Creative cloud store ?

**Comment by SachaHerszkorn** [comment]
Okay it finally works !

I uninstalled the plugin version i downloaded on the Creative Cloud store, and used the aescripts version installed with zxp installer. You should check the creative cloud store version i guess !

**Comment by cedced** [comment]
Same issue.

**Comment by nishchaldarda** [comment]
hello
i have some issue when rendereing in JSON

[Sine wave (converted).zip](https://github.com/airbnb/lottie-web/files/3438189/Sine.wave.converted.zip)

**Comment by nishchaldarda** [comment]
its showing animation not loaded

**Comment by ienatom** [comment]
> I have the same config.
> It doesn't make much sense that it's not exporting animations.
> Is your OS or AE in another language?

I have the same issue and the app is on a different language than my OS (MacOS)

**Comment by AbelaXV** [comment]
same issue here, the after effect animation works but in bodymovin preview it don't display anything

**Comment by mounirtaki** [comment]
Edit > Preferences > Scripting & Expressions... > and check on "Allow Scripts to Write Files and Access Network" 

this will solve the problem
