### ISSUE TITLE
Remove intro from looping 

### ISSUE THREAD

**Issue by mariosmaselli** [bodymovin/bodymovin#689]
Hi! 

I was wondering if it's possible to remove the intro when looping. So it play's only once and then when loops instead of starting from 0 you go to a specific frame.

Example:
https://codepen.io/airnan/project/editor/ZeNONO

1. B animates in
2. Circles and lines animate from the B 
3. Circles and lines animate from the B 
4. Circles and lines animate from the B 
7. Etc...

Or given that you already have the "Full" animation I will separate the animation in two

1. Intro
2. Loop 

Play intro and when finishes, I start playing the loop

Thanks a lot!

**Comment by bodymovin** [comment]
you can use playSegments to do that, for example:
anim.playSegments([[0,45],[46,100]])
if loop is set to true, it will only loop the last segment

**Comment by mariosmaselli** [comment]
O great that sounds what I'm looking for!

But how do I know which segments do I have? what's the logic behind it?

Because I just tried this playSegments([[0,45],[46,100]]) and it plays the full thing and starts all over again.

Thanks

**Comment by bodymovin** [comment]
those are the frames you can get from After Effects

**Comment by mariosmaselli** [comment]
Ok still not sure why starts all over again. Only once...

So it plays... then restarts.. plays and starts the right looping

http://recordit.co/KS91lwJc4x

**Comment by mariosmaselli** [comment]
I changed to autoplay and it seems that is working now.. no double playing 

Thanks a looot!!!

**Comment by mariosmaselli** [comment]
Hey man! 

sorry me again 

Sooo I though that it was fixed but actually is not... the double playing is still own

[Chat.zip](https://github.com/bodymovin/bodymovin/files/1406140/Chat.zip)

**Comment by mariosmaselli** [comment]
Ok finally figured out.. sorry for all the mess :D 

It was not the autoplay true but adding true at the end of the play segments 

`anim.playSegments([[0,38],[39,473]], true)`

Thanks a lot!
