### ISSUE TITLE
No popup window appears on AE when clicks on Bodymovin

### ISSUE THREAD

**Issue by danem025** [bodymovin/bodymovin#69]
Hi,

I run AE on a IMAC Yosemite 10.10.5. AE CC 2015.
I ve been able to install the extension but when I click on it, nothing happens.

I would need help...

Thx

**Comment by bodymovin** [comment]
@danem025 hi! how did you install it?
manually or from the add-ons page?

**Comment by danem025** [comment]
I put the extension files on the Extension folder.
It appears on AE. just doesnt work
I guess is manually then

**Comment by bodymovin** [comment]
If you do it manually you need to set debug mode to true.
Someone made a video with instructions on how to do it. It's in spanish but you can follow them visually.
https://vimeo.com/144533677

**Comment by danem025** [comment]
Hi again,
Everything is working great...
I don't really understand what I did on the terminal but now my CSS3ps plugin doesn't work anymore.
Did it block the server connection to adobe ?
It's really a problem ? Is there a way back ?
