### ISSUE TITLE
Image folder does not export

### ISSUE THREAD

**Issue by dungnt95** [bodymovin/bodymovin#691]
I use an image in my AE project, but when I export using Bodymovin there is no image folder comes with the json file 

My AE is CC 2016 
My Bodymovin is 2.14.0 
Here is my project link: https://goo.gl/DHkYYm

I have seen an issue similar to this and you say it would have been fixed in the following update. However, I still encounter with the same problem so I create a new one. 

Thank you a lot for making such great plugin

**Comment by bodymovin** [comment]
I tried your animation and it exported fine.
Are you trying to export it to a folder with special permissions?
On the zip file you sent me, the images folder seems to be there.

**Comment by dungnt95** [comment]
Actually I included it manually, however, after several times of restart, the plugin seems to work perfectly now, thanks for your attention, keep up great work man!

**Comment by bodymovin** [comment]
Glad it works now
