### ISSUE TITLE
Decompile

### ISSUE THREAD

**Issue by agencia** [bodymovin/bodymovin#70]
Hi,

I have a webpage with an animation using bodymovin but I would like to decompile to use the imagery, is this possible? how can I reuse imagery? I cannot get any image from the animation

I got this webpage as legacy so the guy who did this is no longer available

I would appreciate any help, Regards

**Comment by bodymovin** [comment]
if it's rendered as svg you could pause the animation and get the svg data from chrome dev tools.
Would that work?
