### ISSUE TITLE
Doesn't work on Safari

### ISSUE THREAD

**Issue by ChrisHolland92** [bodymovin/bodymovin#707]
**Tell us about your environment**

* **Browser and Browser Version:**
Safari Version 10.1.1 (12603.2.4)
* **After Effects Version:**
CC 2018
**What did you do? Please explain the steps you took before you encountered the problem.**
Exported the file as a html demo
**What did you expect to happen?**
I expected it to play on Safari as well as it does on chrome
**What actually happened? Please include as much _relevant_ detail as possible.**
I exported the file into a html demo and played it on Safari, it jumps from keyframe to keyframe with very little motion in between. It works flawlessly when played on Chrome. This is the same for all of the other files we have tested. Is there a setting or something that I can change to make it work on safari as well as it does on Chrome?
**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Can you share the .aep so I can check it out?
Safari can have performance issues with some type of features.

**Comment by bodymovin** [comment]
glad it works!
