### ISSUE TITLE
Unable to execute script at line 27.Cannot convert to /c/Program%20Files/Adobe/Adobe%20Effects%CC%202015/Support%20Files/extension/jsx/esprima.jsx

### ISSUE THREAD

**Issue by thrillerist** [bodymovin/bodymovin#71]
Hi all, thanks for developing this plug-in
I put the extension folder on "c:/Program Files/Adobe/Adobe Effects CC 2015/Support Files"
While adding bobymovin panel in AE, I got this error.
something wrong here? 
![error](https://cloud.githubusercontent.com/assets/7190154/13417206/6c8c238c-dfa4-11e5-8951-083b718a2d7c.png)

**Comment by bodymovin** [comment]
hi.
you need to install the extension since it is not a script.
get the bodymovin.zxp file from the folder build/extension/
and then follow instructions here:
https://helpx.adobe.com/x-productkb/global/installingextensionsandaddons.html
skip to where it says:
"Install third-party extensions"

if you need more help let me know

**Comment by thrillerist** [comment]
thanks for replying.
I read the instruction and  install the extension through the Creative Cloud
but when I open the extension in AE, still got a error
![image](https://cloud.githubusercontent.com/assets/7190154/13421538/ef07c288-dfc9-11e5-868e-577657a35540.png)

then I selected a  layer and destination folder, then clicked render
but there's no output file, and no preview too.
![image](https://cloud.githubusercontent.com/assets/7190154/13421617/65bb850e-dfca-11e5-8afb-20b3905be576.png)

![image](https://cloud.githubusercontent.com/assets/7190154/13421594/41800606-dfca-11e5-8bbe-43f1f20b4335.png)

can you give me more advise? thx.

**Comment by bodymovin** [comment]
can you check if that file is present in that path?

**Comment by thrillerist** [comment]
yes, it is

**Comment by thrillerist** [comment]
yes, it is.

**Comment by bodymovin** [comment]
can you try replacing that file with this one and restarting after effects?

[esprima.zip](https://github.com/bodymovin/bodymovin/files/152704/esprima.zip)

**Comment by thrillerist** [comment]
Same mistake here. 
How to export the text animation, did you write a expression parser or something like that?

**Comment by bodymovin** [comment]
it's an open source javascript parser called esprima
I'm using it to parse expressions

**Comment by bodymovin** [comment]
I'm guessing it could be some character breaking the evaluation.
Do you have After Effects or your OS on a language different than english?

**Comment by song0119** [comment]
I faced the same problem. Changing the OS language to English(US) works for me. Thank you very much.

**Comment by bodymovin** [comment]
@song0119 good to know. I'll see if I can fix this.
thanks!

**Comment by bodymovin** [comment]
@thrillerist @song0119 finally fixed on the latest build.
