### ISSUE TITLE
Lock position of mask with alpha matte

### ISSUE THREAD

**Issue by shokrizorid** [bodymovin/bodymovin#72]
Hello :) 

I want to use a lock position of mask with alpha matte but when I see my render, I can see the form who I want to mask and the mask without alpha... Have you an idea?

Here is my file : 
http://infinit.io/_/k7pe95V

**Comment by bodymovin** [comment]
hi!
what renderer are you using?

**Comment by shokrizorid** [comment]
Hum, what is renderer?
I use this on the mask form to mask the ball:
http://infinit.io/_/38vKPvP

**Comment by bodymovin** [comment]
I mean, is it rendering on svg or canvas on your browser?

**Comment by shokrizorid** [comment]
Svg

**Comment by bodymovin** [comment]
hmm ok, I'll take a look

**Comment by shokrizorid** [comment]
Thank you

**Comment by bodymovin** [comment]
I see you're using the Stencil Apha mode.
Unfortunately it is not supported yet.

**Comment by shokrizorid** [comment]
Do you know another solution to do the same animation?

**Comment by shokrizorid** [comment]
I found a solution :) 
I duplicate the floor and I added a simple mask :)

**Comment by bodymovin** [comment]
nice!
