### ISSUE TITLE
Premultiplied alpha / black halo png

### ISSUE THREAD

**Issue by dionysiusmarquis** [bodymovin/bodymovin#73]
Hi,

i recently tried to use bodymovin for an animation consisting of multiple images imported via psd. The exported images got all the good old premultiplied alpha issue. I tracked it down to the `saveFrameToPng` function. Same issue: https://forums.adobe.com/thread/1347389?start=0&tstart=0

I don't know if this is fixable.

**Comment by bodymovin** [comment]
I had read about it but didn't come up with that problem myself.   
The issue with importing a render setup is that it is too invasive on the project.  
I'll look further into it.  
Meanwhile can't you replace the exported images with the layers exported from Photoshop?

**Comment by dionysiusmarquis** [comment]
Thank you! 
Yes, replacing the images would fix this.

**Comment by bigxixi** [comment]
my solution to the 'saveFrameToPng()'  is to render the image through renderQ:
https://github.com/bigxixi/SaveFrameAsPNG-Plus
@bodymovin hope that can inspire

**Comment by bodymovin** [comment]
@bigxixi Yes, I've tried doing this before, but it involves messing with the render queue and loading an external comp to the rendering composition.
I will see if I find a better flow.

**Comment by bigxixi** [comment]
@bodymovin I add some code to replace the 'saveFrameToPng()' function in the (../jsx/utils/sourceHelper.jsx), and it works fine for me, the plugin now export pngs through renderQ and get rid of the black borders in pngs with transparency.
[sourceHelper.jsx.zip](https://github.com/bodymovin/bodymovin/files/870685/sourceHelper.jsx.zip)

just replace the same file and try it out.
I am on macOS 10.11.6 with AE CC 2014.2
I havent test it on other machines,  I hope it could work fine on them.

**Comment by bodymovin** [comment]
@bigxixi This looks very promising!
I'll take a look at it in the weekend.
thanks!!
