### ISSUE TITLE
RequireJS AMD loading breaks requirejs

### ISSUE THREAD

**Issue by ibanezm** [bodymovin/bodymovin#74]
UMD wrapper currently seems to break next loaded module by requirejs.

Seems to be solved after removing nested _define_ (nested after built) in js/3rd_party/seedrandom.js

![bodymovin-requirejs-test](https://cloud.githubusercontent.com/assets/5395780/13970866/ed1c3fc6-f08b-11e5-8f27-322999715662.jpg)

In both cases the code is the same, but of asynchronous loading of modules, the next one after loading bodymovin seems broken.

[bodymovin-requirejs-test.tar.gz](https://github.com/bodymovin/bodymovin/files/185157/bodymovin-requirejs-test.tar.gz)

**Comment by bodymovin** [comment]
thanks for the heads up.
And for finding the fix. Would have taken me some time.

I've uploaded the fix. Let me know if everything works fine.

thanks!

**Comment by ibanezm** [comment]
Thanks to you for this awesome plugin!

Current version (v 4.1.6) seems to work like a charm :+1: 

thanks!
