### ISSUE TITLE
Show the whole image straight away, and play once

### ISSUE THREAD

**Issue by vk011** [bodymovin/bodymovin#75]
Is it possible to show the image straight away? I want to show it straight up and then play it once on hover.

**Comment by bodymovin** [comment]
@vk011 I'm not sure I understand the question. Do you mean show the first frame paused?

**Comment by vk011** [comment]
@bodymovin  Hello and first of all thank you for replying.

Well I guess in my case it would be last frame, basically I want to show the end of the animation straight away, and then replay the animation ONCE on hover.

This is how it's setup:

```
var animData = {
        wrapper: document.getElementById('bodymovin'),
        animType: 'html',
        loop: true,
        prerender: true,
        autoplay: false,
        path: url
      };
      
      var anim = bodymovin.loadAnimation(animData);

      anim.play();
```
I guess I should be using `goToAndStop` for the first issue, but it's not working for me, I tried something like : `anim.anim.goToAndStop(1500, true)` but the image doesn't appear, and I am not sure how many frames I have, I tried getting the value with `alert(anim.totalFrames);` but it returns `0`

**Comment by ZachSaucier** [comment]
If I understand you correctly, you could do `.goToAndStop()` for 1) and `.play()` for 2
