### ISSUE TITLE
crash on `this.v.i` is null

### ISSUE THREAD

**Issue by wonnage** [bodymovin/bodymovin#76]
I am getting an "Uncaught TypeError: Cannot read property 'i' of undefined". Looking through the source, i see the offending line is line 468. Looks like you were trying to debug this at one point too:

https://github.com/bodymovin/bodymovin/blob/71cd416fc3f7d74d946d7e079ee58daae61ce3df/player/js/utils/expressions/ExpressionManager.js#L451

**Comment by bodymovin** [comment]
@wonnage can you share with me the .ae project?
It might be a method in an expression that is not yet supported.
