### ISSUE TITLE
playSegments reverse direction

### ISSUE THREAD

**Issue by calvinhui** [bodymovin/bodymovin#77]
Hi, for playSegments, which allow to play from frame 24 to frame 600. 
anim.playSegments([24, 600], true);

But it doesn't seem to work if I want to play that segment in reverse direction.
anim.playSegments([600, 24], true);

Is the following the only way to work?
`anim.goToAndStop(600, true);`
`anim.setDirection(-1);`
`anim.play();`
`setTimeout(function(){`
`anim.pause();`
`}, 24000);`

Can you please tell me whats the best way to do the reverse direction in segment? Thanks in advance for any help you can provide, and great works on this library!

**Comment by bodymovin** [comment]
@calvinhui yes, to play in reverse you should do that. But there is no need to pause it in the end if loop is set to false. 
I didn't set automatically the direction to negative when the first value is larger than the second because I don't think it will work for multiple segments.

**Comment by calvinhui** [comment]
I need to pause it, because I want it to stop at the frame of 24 or other specific frame.

**Comment by ivanjeremic** [comment]
> 
> Is the following the only way to work?
> `anim.goToAndStop(600, true);`
> `anim.setDirection(-1);`
> `anim.play();`
> `setTimeout(function(){`
> `anim.pause();`
> `}, 24000);`
> 

The issue I have with this solution is that it is not really playing back it is jumping to 600, any idea why?
