### ISSUE TITLE
play animation on mouseover event

### ISSUE THREAD

**Issue by zp0303** [bodymovin/bodymovin#78]
Is it possible to start an animation paused, play on hover, then return to paused state after mouse over?

**Comment by bodymovin** [comment]
you can set autoplay to false and then play the animation instance when hovered.

**Comment by zp0303** [comment]
first, thank you for the response. 
I've added this to the style div and paused the autoplay, but all I get is a paused animation. What am I doing incorrectly?
#bodymovin:hover{
          animation-play-state: running;
        }

**Comment by zp0303** [comment]
var params = {
        container: document.getElementById('bodymovin'),
        renderer: 'svg',
        loop: true,
        autoplay: false,
        animationData: animationData

    };

    var anim;

    anim = bodymovin.loadAnimation(params);



should I add an .eventListener for the mouseover? if so, where?

**Comment by bodymovin** [comment]
yes, add an eventListener to the mouseover event on the container document.getElementById('bodymovin')
something like:
`document.getElementById('bodymovin').addEventListener('mouseover', function(){
anim.play();
}`

**Comment by chandru1822** [comment]
I want to stop animation after sometime.
