### ISSUE TITLE
Can i use bodymovin in Google AdSense

### ISSUE THREAD

**Issue by viptv** [bodymovin/bodymovin#79]
Does anyone know? Can I link bodymovin.js from an external server ?

**Comment by bodymovin** [comment]
I'm not sure how Google AdSense works.  
I can't help you on that, but I'll look into it.

**Comment by Sandstedt** [comment]
I think you can only use the ad distributors own CDN to be able to not count for the extra weight of external libraries. And non of the largest ad distributors have bodymovin on their CDN as far as I know. [See similar question about Greensock on Adform](http://creative.adform.com/support/adquestions/html5-banners/greensock-animation-library/)

But my experience with Google Adform at least, is that they don't have any tools to check external requests. So you could basically put a version of the bodymovin player (the light version is 28 Kb gzipped) on any CDN and link to it in you banner and that would be fine. But make shure to put it on on a secured CDN (https).

Also see this old issue about placing bodymovin on a CDN: #109

**Comment by bodymovin** [comment]
library is on cndjs now
https://cdnjs.com/libraries/bodymovin

**Comment by Sandstedt** [comment]
Awesome!
