### ISSUE TITLE
BodyMovin / call the graphic cards

### ISSUE THREAD

**Issue by shokrizorid** [bodymovin/bodymovin#80]
Hello,

I would like to know if bodymovin can call the graphic card to animate.
I ask you this, because the perf are so different between Chrome & Firefox. 

On Firefox, if we have 3 big animations, the browser is slow. 
I already cleaned each illustration to help the processor, but it's slow yet. 

Our website will be launch in 2-3 weeks max!
Can't wait to credits your awesome tool :)

**Comment by bodymovin** [comment]
hi
depending on the type of animation you can use the canvas renderer or the html one that should perform better.
if you want to send me the .ae project I can take a look and see if I can help
