### ISSUE TITLE
blend modes

### ISSUE THREAD

**Issue by toth-robert** [bodymovin/bodymovin#81]
hello,
firstly, thanks for this great plugin, I really like the fact that I can save svg from AE.
It's very nice plugin, thank you for creating it!
My question is that how can I use blend modes?
I have 3 circles and I need to blend each with multiply blend mode.
can you help me with this?

thanks a lot, and keep up the good work!
Robert

**Comment by bodymovin** [comment]
hi
unfortunately blendmodes are not easy to replicate from AE to svg.
It's something I've been trying to support but I haven't been succesful yet.

**Comment by Emasoft** [comment]
What problem do you find? Multiply blend mode is supported in SVG:
http://www.w3.org/TR/compositing-1/#blendingmultiply

**Comment by bodymovin** [comment]
yes, those are the possibilities I'm evaluating, but blendmodes on AE apply between layers and svg filters can't have two source layers AFAIK

**Comment by toth-robert** [comment]
anyway, this is not a big problem.
thanks for the plugin, I really love it!!!
