### ISSUE TITLE
Bridge with C4D ?

### ISSUE THREAD

**Issue by mairod** [bodymovin/bodymovin#82]
A little thought off topic

Here's my problem, I do both Motion Design and Web design in my work, and I had the occasion to use Bodymovin several times and really enjoy this plug. On the other hand I've looking for a way to **export/import vector animation from After Effect to C4D** with a Spline animation, or a .obj sequence, or something like that.

Here my thought : **Can you think that bodymovin may can export animation** into .obj sequence, or other data compatible with 34D through a Python script or a little plug-in that use JSON **data from Bodymovin  to C4D Spline** ? 

Thanks a lot for your time, and hope you can help me with this

**Comment by bodymovin** [comment]
I really don't know much about C4D, so I'm not sure how much work this would be.
I'm starting to build a three.js player for webGL and I guess they might have common primitives
