### ISSUE TITLE
Drop shadow support

### ISSUE THREAD

**Issue by jeroentradecast** [bodymovin/bodymovin#83]
I'd really love to have (basic, even without animation) support for drop shadows.
Although new to AE and Adobe scripting, I'd like to help with building the support for it; I'm currently fiddling around with the extension to check how it's actually working.

About the extension: if drop shadows are a layer style, like strokes, I guess I need to add a type and  function to export all drop shadow properties in [extension/jsx/utils/layerStylesHelper.jsx](https://github.com/bodymovin/bodymovin/blob/master/extension/jsx/utils/layerStylesHelper.jsx) or am I going to run into problems? 

Also wouldn't it also be a good idea to register bodymovin to bower? 

**Update.**
Got the dropshadow style export working. 
`"sy": [{
            "ty": 1,
            "nm": "Drop Shadow",
            "m": {
                "k": 4
            },
            "c": {
                "k": [255, 0, 0, 255]
            },
            "o": {
                "k": 70
            },
            "d": {
                "k": 5
            },
            "b": {
                "k": 5
            }
        }`

Now looking at the player.

**Comment by bodymovin** [comment]
If you don't need the drop shadow to animate, the fastest way would be to set an id on AE to the layer you want the drop shadow on and use css to style it.
Exporting drop shadow as a layer style makes absolute sense though and I'll consider adding it to the plugin.
The only thing that worries me about it is performance.

**Comment by jeroentradecast** [comment]
True, but that would require some manual post processing which is something I (in my usecase) don't really want. 
 
How are you currently setting up the stroke effect? I'm having trouble understanding if _StrokeEffectManager.js_is the module for adding it, or if it's interwoven in the rest.

**Comment by bodymovin** [comment]
I've removed stroke layer style support because it's a performance killer on svg. So don't use it as a reference.
drop shadow should be easier to implement, but will probably reside on the SVG base element.
I have to think about it

**Comment by bodymovin** [comment]
done
