### ISSUE TITLE
Unable to execute script at line 224. undefined is not an object

### ISSUE THREAD

**Issue by kaulandb** [bodymovin/bodymovin#84]
Hello,

This extension is awesome by the way. Going to save me a lot of time.
When trying to render this current test animation, I am receiving the following error. Any idea what is causing this?

Thanks
![render-error](https://cloud.githubusercontent.com/assets/19212857/15054844/183e8f82-12cf-11e6-8ad0-a784461301b8.png)
![layer-details](https://cloud.githubusercontent.com/assets/19212857/15054845/1beca5c4-12cf-11e6-835e-4ca30db99e47.png)

**Comment by bodymovin** [comment]
@kaulandb hi
I don't see anything strange there.
could you send me the .ae file so I can take a look?

**Comment by kaulandb** [comment]
@bodymovin just emailed you the file. Thanks for your help and quick response!

**Comment by yehengqi** [comment]
i got this problem too, may i ask why= =
[无标题项目.aep.zip](https://github.com/bodymovin/bodymovin/files/380859/aep.zip)
