### ISSUE TITLE
playSegment not playing in big animations

### ISSUE THREAD

**Issue by juancabrera** [bodymovin/bodymovin#87]
I have two `data.json` for two SVG animations, one is `70kb` and the other one is `121kb` (attached to this issue).

when I do `.playSegments([0, 230], true)` to the small one, works perfect, but is not working with the big one, it might be a bug with bigger animations ?

I have to say, that if it's `autoplay: true` the animation works great. It's just the `playSegments` that isn't working.

[animation-context.json.zip](https://github.com/bodymovin/bodymovin/files/257451/animation-context.json.zip)

**Comment by bodymovin** [comment]
Hi!
I've tried the animation and it works fine with playSegments.
Do you have a small code demo I can take a look?

**Comment by juancabrera** [comment]
@bodymovin yes, still can not get it working.

take a look to the attached file.

[bm-animation.zip](https://github.com/bodymovin/bodymovin/files/277850/bm-animation.zip)

**Comment by juancabrera** [comment]
actually I don't think isn't working because is a "big" animation, I have one bigger animation that is working fine.

**Comment by bodymovin** [comment]
Hi, I found out what is going on.
Your animation starts at frame 840 and ends at frame 1261
if you want to play your first 120 frames form that segment, you should do:
.playSegments([840, 960], true)

**Comment by juancabrera** [comment]
Ohhh, I see.

How could you know the exact frames of the application ?

Thank you so much!

**Comment by bodymovin** [comment]
if you check the exported data.json, there are 2 params "ip" and "op" that indicate the start and end of the segment of the composition that is being rendered.

**Comment by ZachSaucier** [comment]
@bodymovin A list explaining what each value in the JSON file would be useful. I know you've mentioned it before. Is there an issue for that already?

**Comment by casizzi** [comment]
@bodymovin even after locating the 'ip' & 'op' params i still cant get the playSegments functionality to work, my animation just plays the entire length of the animation when calling it, any tips?

![screen shot 2017-05-03 at 16 54 14](https://cloud.githubusercontent.com/assets/12881937/25666572/3290765a-3021-11e7-9dd9-85e855113d68.png)
