### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by brunolazzaro** [bodymovin/bodymovin#88]
I've noticed that with some animations there seems to be a memory leak.

In my case I had 5 animations looping and after 7-10 minutes FireFox was using 3.5gb of RAM, Chrome 1.5gb but the animations were really choppy (like 5fps). This was tested using *only* bodymovin.js and the animation data on a blank page (no other frameworks or JS involved). Changing renderers didn't help much.

Is there something in the animations that could be causing the leak? I've even seen a memory spike every time I called .play() on one of the animations.

With the animations on the demo folder I've had the issue but it seems to be a little bit less aggressive.

I wish I could provide you with the actual animation .JSON files but I can't. :(

**Comment by brunolazzaro** [comment]
I did try other renderers, with similar results (if not worse than the SVG renderer).

**Comment by bodymovin** [comment]
Have you tried calling the garbage collector manually and profile memory?
I've been reported this some other times but there was no leak in those cases.
Can you think of any special feature you're using on those cases?

**Comment by brunolazzaro** [comment]
I profiled memory and overall animations frames are slow with these animations (15 to 20fps). What special features would you consider to be heavy to animate and could be causing the issue?

**Comment by bodymovin** [comment]
are they slow from the first time they run or after several times they've played on the browser?
If they run slow from the start, the animation might be too heavy.
some features that are usually a performance problem are:
- very large solids
- multiple track mattes
- lots of specific masks
- using pngs instead of shapes

but it really depends on how the animation is done. Can you describe or share an animation for me to take a look?

**Comment by brunolazzaro** [comment]
Thanks for the info, will talk with the design team and see if they are doing any of those. If I find any more info that I can share I'll keep you posted.

**Comment by brunolazzaro** [comment]
I have a heap snapshot that is 1GB. The most items under retained size seem to belong to an array called segments.

<img width="1296" alt="screen shot 2016-05-17 at 2 04 58 pm" src="https://cloud.githubusercontent.com/assets/689386/15335547/6fa0b490-1c38-11e6-85e3-d60e17c241d8.png">
<img width="1299" alt="screen shot 2016-05-17 at 2 05 09 pm" src="https://cloud.githubusercontent.com/assets/689386/15335548/6fa16890-1c38-11e6-97fc-3cf9caa72203.png">

**Comment by bodymovin** [comment]
Are you using trim paths on your animations?

**Comment by brunolazzaro** [comment]
Yes. I asked the team to remove anything related to that (they told me they were using starshapes and those used lots of trim paths animations) and now I'm not seeing any memory escalation issues.

**Comment by bodymovin** [comment]
hm ok, I'll look into it. Thanks for all the research!

**Comment by bodymovin** [comment]
@brunolazzaro here is a demo with 35 stars all with trim paths applied
http://lab.nearpod.com/bodymovin/demo/star_shapes/
even after sevaral minutes animating, there is no leak.
Can you think of something different on your animation compared to this one?

**Comment by brunolazzaro** [comment]
They are using this: http://www.battleaxe.co/rubberhose/

"So what it does, it creates a starshape and trims a segment of it, and then uses some math to make it work like limbs. But it is a lot of math involved, so I bake everything, erase the trash, and I end up with like 4 or 5 channels of animation keyframes per starshape".

Hope this helps! For now I told them to avoid using RubberHorse to avoid issues.

**Comment by bodymovin** [comment]
The trim path memory "leak" has been fixed.
Rubberhose is probably coming soon.
