### ISSUE TITLE
add click listener to animation inside a canvas

### ISSUE THREAD

**Issue by nbashiri95** [bodymovin/bodymovin#89]
hi,
how can I add onclick listener to animations that I've loaded inside a canvas?
by the way impressive plugin!

**Comment by bodymovin** [comment]
do you want the whole canvas to be clickable, or elements on the canvas?
if it's the second, unfortunately in general, it's not possible.
You should use the svg renderer for that.

**Comment by nbashiri95** [comment]
thanks
so I guess I have to stick to this [https://github.com/bodymovin/bodymovin/issues/32](url)
