### ISSUE TITLE
Help with exporting svg

### ISSUE THREAD

**Issue by iwo111** [bodymovin/bodymovin#9]
Hello there. First of all, greatly appreciate your plugin, really helps. Thanks, keep up.  I tried using it, really works, although I had to draw manually, without shape blend modes. Here I have one project file
https://www.dropbox.com/s/e62wsfha1catxwq/shape_reveal.aep?dl=0
I cannot see what's the problem, but when I try to export, I get blank screen. Json file is generated. I'm bit confused, because at first, I didn't have constant vertices count through the animation so I manually added them thinking it may cause the problem. I ended up with nothing. Maybe someone can help. Any kind of help/explanation is greatly appreciated. Thanks in advance!

**Comment by bodymovin** [comment]
@iwo111 hi.
you issue is indeed related to the varying amount of vertices between keyframes. There are some frames with 8 and some with 9 on the layer outer box2 for example.
The plugin doesn't support this yet.
sorry :/

**Comment by iwo111** [comment]
Cool, I never expected your answer this fast. Thanks a lot. I assumed that it can be due the unconstant number of vertices, and did add vertices manually, and double checked that it's 8 of them all the time, but...
Nevermind, problem solved, I know now what is the problem and how to avoid it.
Thanks a lot!

**Comment by bodymovin** [comment]
no problem!
If I can help you with anything else, let me know
