### ISSUE TITLE
Feature request: Output JSON with dynamic ID definitions

### ISSUE THREAD

**Issue by nickion** [bodymovin/bodymovin#91]
First, great job with this. It's very exciting. I can see that the layer name can be used to produce an ID on a comp, but as ID's should be unique, if an element with the same definition is used in more than one place on a page and there is the need to reference them by ID, there is a problem. 

Could you consider a syntax where the json can also be produced with names that refer to an expression? For example, if `ln` is the property used for the ID, have comp name _#foo_ produce `"ln": "foo"` (as it does already) and _=idVar_ produce `"ln": idVar`. In this way, if a definition is inlined, the JS object could be created with variable ID's. 

An alternative and perhaps more flexible approach would be a notation to access names passed into the player. Have a comp name `?elemID` mean take the name for the ID from property `elemID` in an object containing ID's. So the `loadAnimation` configuration object might have a property `idNames` with a value such as `{ "elemID" : "elem1" }`, and the part of the SVG corresponding to the comp with name `?elemID` would then get ID `elem1`. 

Hope that makes sense :)

**Comment by bodymovin** [comment]
I need to read it again to make sure I understand what you're suggesting :)
But on the next release, you'll be able to use classes as well as ids to name your layers.
Could that solve some multiple elements using a unique selector?

**Comment by nickion** [comment]
Naming classes would be good. What I'm thinking though is the case where the same generated json is going to be instantiated multiple times on a page as separate SVG's, and where mouse detection is required on part of each instance (rather than the SVG element itself). If the ID of the relevant part of the SVG can be specified at the time of instantiation, e.g. with a placeholder substituted with the desired ID, then the relevant part of each SVG instance can have a unique ID for assicating setting up event handlers is easy. If the json is in a string then a string substitution before parsing the json could achieve this, but I was envisaging the json containing variable references for the ID's rather than hardcoded strings for the scenario where the json is inlined into code and now loaded as a string.
