### ISSUE TITLE
Button states with one animation file

### ISSUE THREAD

**Issue by hardy613** [bodymovin/bodymovin#92]
I have one animation data.json file that has 5 animation states:

- animate in
- hover
- blur
- click
- animate out

I load the file data file

```
var animData = {
            wrapper: btnAccept,
            animType: 'svg',
            loop: false,
            prerender: false,
            autoplay: false,
            autoloadSegments: true,
            path: application.baseUrl + 'animations/btn_Accept/all.json'
        };
```
then I am setting the segments 
```
anim.addEventListener('DOMLoaded', function () {
            anim.playSegments([[0, 24],[25, 48],[49, 72],[73, 96], [97, 120]], false);
        });
```

then on a hover event I am trying to only play the hover segment animation:

```
$(btnAccept).mouseenter(function () {
            anim.goToAndStop(25);
            anim.play();
        });
```

I am stuck on how to effectively handle button states without loading multiple separate animations.

**Comment by bodymovin** [comment]
hi!
You should play the segment directly on the mousenter event:
$(btnAccept).mouseenter(function () {
anim.playSegments([25,38],true);
});

**Comment by hardy613** [comment]
Thanks for the quick response!

```
       var btnAccept = document.getElementById('btn_AcceptMission');

        var animData = {
            wrapper: btnAccept,
            animType: 'svg',
            loop: false,
            prerender: false,
            autoplay: false,
            autoloadSegments: true,
            path: application.baseUrl + 'animations/btn_AcceptMission/all.json'
        };

        var anim = bodymovin.loadAnimation(animData);

        anim.addEventListener('DOMLoaded', function () {//animate in
            anim.playSegments([0, 24], true);
        });

        $(btnAccept).mouseenter(function () {// hover state
            anim.playSegments([25, 48], true);
        }).mouseleave(function () { // blur state
            anim.playSegments([49, 72], true);
        }).click(function () { // active state
            anim.playSegments([72, 96], true);
        });
```
is how i gather I should lay out the button state. Should I export the animation from AE as segments for this? Sorry to bother I am still learning this wicked plugin. 

Thanks for your time!

**Comment by bodymovin** [comment]
No you don't need to export as segment,  everything should work fine with a single exported composition.
Let me know how it goes.

**Comment by hardy613** [comment]
Hey

I got everything going fine with the animations, but it seems adding URL parameters mess with the animation layers; but without parameters it works fine.

**Comment by bodymovin** [comment]
what do you mean by url parameters?
can you post an example?

**Comment by hardy613** [comment]
Hey, 

Thanks for responding

If you visit http://staging.bsl.com/bodymovinTest/ and hover the button, then visit http://staging.bsl.com/bodymovinTest/? and hover you should notice what I mean.

Thanks again for your help.

Cheers.

**Comment by bodymovin** [comment]
I think it's related to the tag base you're setting on the head.
Since svgs use relative urls for masks, it might be breaking when it doesn't match.
Can you try removing that tag and see if it works?
I need to find a solution for this on my side.

**Comment by hardy613** [comment]
Good news, you're correct.

Looks like I'll have to .... drop the base (had too).

Thanks again for your time.

**Comment by bodymovin** [comment]
lol
glad it worked

**Comment by hardy613** [comment]
Hey, 

Thanks!

I also tested changing the target and none worked as expected, but I couldn't say for sure without testing.

I'll close this issue and create a new issue for the <base /> tag with proper title, and description so it's easy to find if users search.

Thanks again.
