### ISSUE TITLE
Combine JSON exports into one data object

### ISSUE THREAD

**Issue by ZachSaucier** [bodymovin/bodymovin#94]
In cases [like this example](http://codepen.io/airnan/pen/RazwzX), multiple animations are used and it's easiest to combine them into one dataset like the array that you put them into.

Is there a way to generate output from multiple comps in one specified (or set) dataset? Manually going through each generated JSON file is more work than I'd prefer.

**Comment by bodymovin** [comment]
Hi, not really.
But a simple console command to bundle all json files into a single javascript object shouldn't be too hard to do.

**Comment by karthickvkumar** [comment]
Hi @ZachSaucier  @bodymovin  would be helpful if you provide more informations regarding this console command

**Comment by emcniece** [comment]
Did some experimenting - tried deep merging the entirety of 2 files, this failed. Also tried concatenating layers from one file onto another, and this fails too. Seems like there's more to this than merging layers.
