### ISSUE TITLE
where can i find information on adding interactivity in the animation?

### ISSUE THREAD

**Issue by pyfave** [bodymovin/bodymovin#96]
my css is rusty..
any hint welcome on how we can add hovering , some reactivity ,

something easy to begin :-) ..

but i first wanted to say thanks.
it's beautiful work.

**Comment by bodymovin** [comment]
if you want to add a hover to the whole svg, you should treat it as any other svg file or DOM element.
what kind of effect are you looking for?

**Comment by pyfave** [comment]
i have no clear objective, but let's say i want one (moving )layer to be a
hyperlink, a call to some javascript.
is it possible?
ideally in a way that would permit me to modify the design, re render ,
and keep these links active while iterating .
i iterate a lot... :-)

perhaps with a hidden text layer , just on top of a precomp with some
[LINK] in it's name.

a kind of what flash does with symbols. or did.

is transparency maintained?
is it possible to put a video behind the svg?

i imagine a lot of possibilities,

simple interaction without big coding skills is great.

less programming means more bodymoving :-)




2016-06-08 1:56 GMT+02:00 hernan <notifications@github.com>:

**Comment by ZachSaucier** [comment]
There are tons of possibilities. If you're looking to get help with implementation, you should have a clear idea of what you're trying to accomplish, an attempt at it, and post on a site like StackOverflow, not on Github

**Comment by bodymovin** [comment]
If you name the layer in AE beginning with a "#", it will add an id to that layer so you can reference it with css of query it via javascript.
That might be a good start for what you're looking for.

**Comment by pyfave** [comment]
ok thanks a lot .
i tried to find this info in some doc but couldn't.
have a nice day !

problem solved for now .

2016-06-08 18:57 GMT+02:00 hernan <notifications@github.com>:
