### ISSUE TITLE
Error on startup of AE

### ISSUE THREAD

**Issue by jorisvanr** [bodymovin/bodymovin#97]
When I reopen my AE after a reboot I get the following error: "Unable to execute script at line 1. bm_compsManager is undefined. 

I reinstalled the plugin and it worked for a while, until I restarted after effects again. It seems to have started with installing this thing: https://www.npmjs.com/package/ae-to-json. I uninstalled everything that has to do with it but it still errors. 

The problem is that I cant close the window as it immediately opens again. 

I'm working with cc2014. cc2015 works fine!

**Comment by bodymovin** [comment]
That's strange.
I'll try to install that npm package and see if I can reproduce the error.

**Comment by jorisvanr** [comment]
Have you been able to reproduce the error? It also has the following error (on startup): 

Unable to execute script at line 0. After Effects error: Can not run a script while a modal dialog is waiting for response.

![screen shot 2016-06-14 at 09 12 02](https://cloud.githubusercontent.com/assets/16778969/16034116/2e4d4506-3210-11e6-98ad-9c2462ffe103.png)

**Comment by quietchap** [comment]
Also is happening on CC2015 and I have not installed the npm packaage.

**Comment by bodymovin** [comment]
@quietchap are you getting that same message regarding modal dialog?
what do you mean you haven't installed the npm package? Have you installed bodymovin some other way?

**Comment by quietchap** [comment]
Sorry, I only get the initial error and upon a restart it goes aways for a time. No modal dialog warning.

**Comment by bodymovin** [comment]
@quietchap do you have any other extension installed?

**Comment by quietchap** [comment]
Only the adobe defaults. Adobe Color Themes and Creative Cloud Authentication.

**Comment by atomicmedia** [comment]
Any fix for this? I have exactly the same issue. AE v 14.1.0.57 (CC2017), Mac OS Sierra v 10.12.3.
Still not working after I uninstalled all Adobe products, restarted and re-installed. I installed BodyMovin via github download and ZXP installer. Any ideas? I don't have any other plugins installed.

**Comment by bodymovin** [comment]
@atomicmedia I have been trying to reproduce this issue with no luck. If I find anything, I'll let you know.

**Comment by jhughes000** [comment]
Hey I get this error and have the same issue closing it every time I start up AE w/ bodymovin actively docked in my workspace. Essentially, if I use bodymovin and forget to close the panel before quitting AfterEffects, the next time I open AfterEffects, I always get this error. It's been happening since day one and I've been using Bodymovin for a few months now :( Hopefully there's a fix? Here's my specs:

AfterEffects CC 2014.2 
<img width="266" alt="screen shot 2017-06-21 at 9 12 56 am" src="https://user-images.githubusercontent.com/29603071/27385870-ffd75d20-5661-11e7-9f1a-fd57f3b0b913.png">

**Comment by bodymovin** [comment]
this should be finally fixed.

**Comment by rishabhjain9191** [comment]
@bodymovin can you please tell what was causing this behavior ?

**Comment by bodymovin** [comment]
@rishabhjain9191 it seemed to be related to other panels being open when executing the initial scripts.

**Comment by LanceClaytonMotionDesign** [comment]
@bodymovin Thanks for tip tip on the panels thing!! I have this same issue with BattleAxe's Overlord on Windows 10:

'Unable to execute script at line 1. overlord is undefined'

As you say, resetting the 'Workspace' arrangements (which closed/opended variations of panels) seemed to do the trick....at least for now. 

Would be good to reign in the actual cause.

It occurred for me once I updated Windows 10 to the April 2018 edition.
