### ISSUE TITLE
Gradient stroke fill

### ISSUE THREAD

**Issue by JackMoGraphics** [bodymovin/bodymovin#98]
Hello!

I have a comp composed of 36 shape layers that animate in using trim paths. Export directly from this comp works perfectly as SVG with bodymovin. 

However, i have this pre-comped with a alpha track matte image of a gradient. Couldn't get pre-comped gradients to work. 

So i tried combining all the shape lines into one using Explode shape layers plugin. 

Applying a gradient stroke fill and trying that way. However, bodymovin didn't pickup the gradient fill colour. 

I saw at the bottom of coming soon that stroke effect support was coming up and i didn't know if this fell under that?

Any help appreciated!

**Comment by JackPollitt** [comment]
[Helical_SVG.zip](https://github.com/bodymovin/bodymovin/files/308795/Helical_SVG.zip)


Here is an example.

**Comment by JackPollitt** [comment]
[Logo_SVG.zip](https://github.com/bodymovin/bodymovin/files/308797/Logo_SVG.zip)
Here is my logo i am trying to gradient.

**Comment by JackPollitt** [comment]
[Logo2_SVG.zip](https://github.com/bodymovin/bodymovin/files/308820/Logo2_SVG.zip)

**Comment by bodymovin** [comment]
Gradients are now supported.
And stroke effect is partially supported for now.
