### ISSUE TITLE
Animation Masks not clipping

### ISSUE THREAD

**Issue by hardy613** [bodymovin/bodymovin#99]
I have a button that uses an animation mask on http://example.com, and everything works fine; however, when I go to http://example.com/?foo=bar the animation mask does not mask clip. 

After discussing with @bodymovin the combination the < base /> tag and URL parameters (?foo=bar for example) causes an issue with the relative URL's used by the SVG clip mask. The quickest solution is to remove the < base /> tag altogether. (@see: https://github.com/bodymovin/bodymovin/issues/92#issuecomment-224791048)

**Comment by joeshock** [comment]
I've got this same issue.e I've tried removing the base tag for our application but it breaks too many things for it to be worth it. I've tried installing the angular-svg-base module but can't seem to get it working with that. I think it's the right thing to do though by installing his plugin to assist.

https://github.com/jeffbcross/angular-svg-base

Thoughts?

**Comment by no-wa-ke** [comment]
I'm facing with exact same issue here.
i was thinking something like:
```javascript
document.getElementById('something').setAttribute('marker-mid', 'url(' + location.href + '#arrow)');
```
might temporary fix the issue,(i haven't tried it yet)

**Comment by adamchenwei** [comment]
Yea I am having the same issue, its pretty seriously. In Safari 10 for ipad or iphone are NOT able to produce the masking correctly. So every element just all appear on the screen where masking is needed, they are not there. Its like dancing without cloth on ---- nothing to hide.

Would love to see a fix soon! @no-wa-ke where should I place this piece of code?

**Comment by adamchenwei** [comment]
Does it means the issue fixed? Can't see any reference to the commit
